### ISSUE TITLE
多个instance会导致浏览器崩溃

### ISSUE THREAD

**Issue by TingzhouJia** [zhw2590582/ArtPlayer#100]
### Expected behaviour
同时有多个video在同一页面不会崩溃
### Actual behaviour
多个art video在同一页面开启preload会导致浏览器崩溃

请问如何在preload为none的情况下不让art player进入loading状态，现在preload为none会一直loading(只能使用css覆盖掉原有的元素样式)，谢谢

### Environment

-   Browser:Chrome
-   Version: 87
-   Operating System: Mac OS
-   Version: 10.15

**Comment by zhw2590582** [comment]
假如设置了preload为none，artplayer的UI也是出不来的，假如页面存在多个video而导致性能下降，你应该是让用户点击后再实例化artplayer就也可以了，不用页面加载时就全部实例化

**Comment by TingzhouJia** [comment]
好的，非常感谢
