### ISSUE TITLE
When you start the video programatically the video:play method is not triggered

### ISSUE THREAD

**Issue by dantart** [zhw2590582/ArtPlayer#107]
I don't know if this is a bug or I must accomplish it in other way.

When I want to play the video through Javascript I use this:

art_object.player.play = true;

But this does not trigger the "video:play" event.

The "video:play" event is just triggered when I press the PLAY button in the player (or if it's pauses, anyplace in the player as usual to resume the video)

My question... after setting the .on('video:play'... method ... how can I play the video externally and trigger that method ?

**Comment by zhw2590582** [comment]
You can try adding options: `muted: true`

**Comment by dantart** [comment]
I thiink I didnt explain myself :-(
I don't want the video to start automatically when loaded.
I want to initialize the video , not autoplay it, and when something happens in my page, start it.
So I start the video programmatically.

The only problem is that when I do this in the only way I have found (art_object.player.play = true;), the code I have in the "on video:play method" snippet is not executed.

That is only executed if the user plays pressing the artplayer play button or if the video is autoplayed since the beginning as you wrote in your code.

**Comment by zhw2590582** [comment]
The `ready` event ensure that the video can play: 

```js
var art = new Artplayer({
    container: '.artplayer-app',
    url: 'https://artplayer.org/assets/sample/video.mp4',
    muted: true,
});

art.on('ready', function (args) {
    setTimeout(() => {
       art.play = true;
    }, 5000);
});
```

**Comment by dantart** [comment]
Yes ... I'm creating the events INSIDE the ready 👍 
My code is this:

```
arts[0].on('ready', () => {

                           arts[0].on('video:play', function (args) {
                                console.log("play!!!");
                            });

        });
```

Then when I do  (whenever I want, 2 minutes after the page is loaded :-) 
 ```  art_object.player.play = true; ``` 
  that console.log is not executed.

**Comment by zhw2590582** [comment]
In fact, I don't quite understand your expression, but I wrote a demo, you can have a look，it can TRIGGER the method "video:play"：[demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20muted%3A%20true%2C%0A%7D)%3B%0A%0Aart.on(%27video%3Aplay%27%2C%20()%20%3D%3E%20%7B%0A%09console.info(%22--------------play!---------------%22)%3B%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20setTimeout(()%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20art.play%20%3D%20true%3B%0A%20%20%20%20%7D%2C%202000)%3B%0A%7D)%3B)

**Comment by dantart** [comment]
Ok, I start again in the simplest method to ask.

Can you write a code, in which you initialize the Artvideo, and then, you have an external BUTTON element, and when you click on it, the artvideo plays?

**Comment by zhw2590582** [comment]
This is simple: [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20muted%3A%20true%2C%0A%7D)%3B%0A%0Aart.on(%27video%3Aplay%27%2C%20()%20%3D%3E%20%7B%0A%09console.info(%22--------------play!---------------%22)%3B%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20const%20%24btn%20%3D%20document.createElement(%27button%27)%3B%0A%20%20%20%20%24btn.textContent%20%3D%20%27Click%20Me%20To%20Play!%27%3B%0A%20%20%20%20const%20%24wrap%20%3D%20document.querySelector(%27.video-wrap%27)%3B%0A%20%20%20%20%24wrap.appendChild(%24btn)%3B%0A%20%20%20%20%24btn.onclick%20%3D%20()%20%3D%3E%20(art.play%20%3D%20true)%3B%0A%7D)%3B)

**Comment by dantart** [comment]
In the demo you need yo start the video pressing on the video. The feature requested is if it's possible to start video from another element like a button

**Comment by zhw2590582** [comment]
Yes, you see, on the right side of the video, there's a button
