### ISSUE TITLE
Not find any event to see the updated time of art player

### ISSUE THREAD

**Issue by salmanAhmad143** [zhw2590582/ArtPlayer#112]
Hey @zhw2590582 ,
Please suggest me i need an event that call every sec when the time of player has been changing but i didn't see any event like this. Please tell me what i need to do in this scenario. 

Thanks,

**Comment by zhw2590582** [comment]
https://artplayer.org/document/#/events
https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Media_events

This is the native event of video, so I add the prefix `video:` to distinguish it

```js
art.on('video:timeupdate', function (event) {
    console.log(art.currentTime);
});
```
