### ISSUE TITLE
speed to 0.25

### ISSUE THREAD

**Issue by Grukz** [zhw2590582/ArtPlayer#115]
Hello, can you add to ArtPlayer a new speed value of 0.25 also? that's useful in some cases when a video is fast byself. Thanks.

**Comment by zhw2590582** [comment]
I think 0.25 is not a common speed, or you can modify the source code yourself, and then package it yourself, If you have any questions during this process, please contact me.

https://github.com/zhw2590582/ArtPlayer/blob/97dbdf16a5a8bb0c7c647554b87f92f1a43eccc3/packages/artplayer/src/player/playbackRateMix.js#L17
