### ISSUE TITLE
Google Cloud Storage

### ISSUE THREAD

**Issue by munimation** [zhw2590582/ArtPlayer#118]
I have link from google cloud storage, but not play

Is this link : https://storage.googleapis.com/hippomu/37984/1/37984_2.mp4

my link can run in video.js but not run in artplayer.js why?

**Comment by zhw2590582** [comment]
My test is no problem

<img width="1363" alt="屏幕快照 2021-05-02 上午9 41 26" src="https://user-images.githubusercontent.com/5907357/116799288-9e6f4300-ab2a-11eb-8c6e-1f31d6da299d.png">

**Comment by munimation** [comment]
Not working please help
![Screenshot_2021-05-02-11-32-22-59](https://user-images.githubusercontent.com/74494691/116802086-3163a980-ab3a-11eb-8494-22ffbbdaadbb.png)

**Comment by munimation** [comment]
This is work, thanks for helping me :)
Your awesome
