### ISSUE TITLE
Iframe black screen

### ISSUE THREAD

**Issue by munimation** [zhw2590582/ArtPlayer#119]
how to fix iframe black screen?

**Comment by munimation** [comment]
failed to read the 'localstorage' property from 'window' access is denied for this document.

This text show in console

**Comment by zhw2590582** [comment]
You try to install the latest version:`@3.5.28`

**Comment by munimation** [comment]
This last version, i am install the last version on @3.5.28

**Comment by zhw2590582** [comment]
yes，this problem has been fixed in @3.5.28

**Comment by munimation** [comment]
![Screenshot_2021-05-07-09-50-18-88](https://user-images.githubusercontent.com/74494691/117391318-e4a51780-af19-11eb-92b8-1864d8228481.png)
the promblem not fix

**Comment by zhw2590582** [comment]
Because this demo is not using the latest version, I will update this demo later

**Comment by zhw2590582** [comment]
![屏幕快照 2021-05-07 上午11 37 07](https://user-images.githubusercontent.com/5907357/117394351-94818180-af28-11eb-8ebe-4d5772152bc1.png)

**Comment by munimation** [comment]
Yeay its work, thanks very much
