### ISSUE TITLE
.m3u8 change quality resume time

### ISSUE THREAD

**Issue by munimation** [zhw2590582/ArtPlayer#120]
I have 2 video link .m3u8

180p
https://vuclip-eip2.akamaized.net/8b1a692f5d8f38901692bf913b8be53d/vp63207_V20210323042603/hlsc_e2931_2.m3u8

and 240p
https://vuclip-eip2.akamaized.net/8b1a692f5d8f38901692bf913b8be53d/vp63207_V20210323042603/hlsc_e2931_3.m3u8

I change quality from 180p (example: i run video 10.00 minutes) to 240p but time back to 00.00, not resume to 10.00 minutes

**Comment by zhw2590582** [comment]
A simple demo here: [demo link](https://artplayer.org/?libs=https%3A%2F%2Fcdn.bootcss.com%2Fhls.js%2F0.10.1%2Fhls.js&code=var%20hls%20%3D%20null%3B%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fvuclip-eip2.akamaized.net%2F8b1a692f5d8f38901692bf913b8be53d%2Fvp63207_V20210323042603%2Fhlsc_e2931_2.m3u8%27%2C%0A%20%20%20%20customType%3A%20%7B%0A%20%20%20%20%20%20%20%20m3u8%3A%20function%20(video%2C%20url)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20hls%20%3D%20new%20Hls()%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20hls.loadSource(url)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20hls.attachMedia(video)%3B%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D%2C%0A%20%20%20%20controls%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20position%3A%20%27right%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%27180p%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20selector%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20%27180p%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20url%3A%20%27https%3A%2F%2Fvuclip-eip2.akamaized.net%2F8b1a692f5d8f38901692bf913b8be53d%2Fvp63207_V20210323042603%2Fhlsc_e2931_2.m3u8%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20%27240p%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20url%3A%20%27https%3A%2F%2Fvuclip-eip2.akamaized.net%2F8b1a692f5d8f38901692bf913b8be53d%2Fvp63207_V20210323042603%2Fhlsc_e2931_3.m3u8%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20onSelect%3A%20function%20(item)%20%7B%0A%09%09%09%09art.switchQuality(item.url%2C%20item.name)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%5D%2C%0A%7D)%3B)

**Comment by munimation** [comment]
This link same .m3u8 not resume
https://lh3.googleusercontent.com/lr/AFBm1_YUnNQRZhaSP2qYnDzwYry1nkUO7MSpGB5xr4tgGj1151SCzNb1x28Kg3iNPMMobojY6QPtsWWvpmHh-8A1HljIP4Tb8zX6jOl0zACbXPaTYhBlH7dPTDtc0U1I8Cg2zHapsd2tzryoGiL4P0q7h875DHRlWR8KTLmXUgj-leI8Zf0w6r7wfk9OzGBEs-R80LJyOZDYOfF8DcOITsr_u8m96KXxTbXlMmggvCj795L6I6NldX-ua7jmtNTk-WtNRfYoX7x8G_KMrLtscOzj7H3ECQxxtZdWc55uqNekIKEILcss-VS8APJdsrGuZsiQhEfWmSDSd3u1NkZbRvFAvlpMPFh_ENofqkxpynwS25MGorkUD-wfGf3TFg8FbEUDKZieGnp4tu32Qfx864VtkIr_mdv5Lpr_61OMRgCoV1sNW54s-lfuBKwDJ99K3Om-6VQoYy_woZtCx80MhV3j-KA-mE0_E-vkPdQUwzMBvENe9W1fhI1N6qAEk_kVlDsX5mBjkN_wZTpPtw0abRnl3ggEmbR5sI3hF64WJ8PijXTupdvA_EJA76nLsspbQwPhTtxLcRwdx09XnYgtwfoKydAvUwv9hnSREW22InxzWaIVPZ3vj_0uC3wXRF9oio4rZ4gEI-KLyzAGti81G3si8uQfFBwXWU4e2u6R2QskA0wfdo3XJOwceOPRY1f5pX3KC-3lS5fFbODXfenTdn9uOZTFXDkt7kzRRg9K5Z03qV5wBJ_7o3yf8gFLxQ1seFzwt1AKhch26WfVsgNmAqfEviZUb8GW46FLMwVYfg=dv
