### ISSUE TITLE
Hls mode poster not show

### ISSUE THREAD

**Issue by dragonmoe** [zhw2590582/ArtPlayer#123]
Please check demo, i remove hls mode poster show but i add hls mode poster not show

[Demo](https://hippomu-em.blogspot.com/2021/04/37430-1.html?video=player) 

Screenshot poster not show in hls mode
![Screenshot_2021-05-10-15-06-03-93](https://user-images.githubusercontent.com/74494691/117626632-84280b80-b1a1-11eb-9085-628bd71c20f7.png)

**Comment by zhw2590582** [comment]
This seems to be the cause of HLS: https://github.com/video-dev/hls.js/issues/925

**Comment by munimation** [comment]
sorry iam not fin solution :(

**Comment by zhw2590582** [comment]
You can try to install the latest version: `@3.5.29`

**Comment by munimation** [comment]
Thanks, its Fix, this code i use

customType: {m3u8: function (video, url) {if (hls) hls.destroy();hls = new Hls( {autoStartLoad: true});hls.loadSource(url);hls.attachMedia(video);
video.addEventListener(&#39;play&#39;,function() {hls.startLoad();});},},
