### ISSUE TITLE
Create gif Uncaught TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by Angelk90** [zhw2590582/ArtPlayer#125]
### Expected behaviour
I was expecting to create a gif.

### Actual behaviour
The gif is not created.

### Steps to reproduce
Click on the Create GIF button, the following message appears in the console:
`Uncaught TypeError: Cannot read property 'style' of null
`

### Environment

-   Browser: Google Chrome
-   Version: 90.0.4430.93
-   Operating System: macOs Catalina
-   Version: 10.15.7

### Console errors (if any)
`Uncaught TypeError: Cannot read property 'style' of null
`

**Comment by zhw2590582** [comment]
Thank you very much, it has been fixed
