### ISSUE TITLE
Can we change the video time format?

### ISSUE THREAD

**Issue by salmanAhmad143** [zhw2590582/ArtPlayer#130]
@zhw2590582 I am working on a project where i have requirement to show the video time in mm:ss:milisec. So please tell me can we change the video time format in minute : second : milli-second. Please see below screen shot-

[https://www.awesomescreenshot.com/image/8501649](url)

Thanks,

**Comment by zhw2590582** [comment]
https://github.com/zhw2590582/ArtPlayer/blob/5d9de9eea9c63654e0c30701739984fc97e96150/packages/artplayer/src/utils/format.js#L5

**Comment by salmanAhmad143** [comment]
@zhw2590582 Thanks for your quick reply as usual. My question is how do i show the updated time on video?

Look right now video player showing the video time in **Minute : Second** at the bottom of video near play icon right. But my requirement is to change this and show the time in **Minute : Second : Mili Second**. How could i do this using art player?

**Comment by zhw2590582** [comment]
You only need to modify the method, and then package it again: `npm run build`
```js
export function secondToTime(second) {
    const add0 = (num) => (num < 10 ? `0${num}` : String(num));
    const hour = Math.floor(second / 3600);
    const min = Math.floor((second - hour * 3600) / 60);
    const sec = Math.floor(second - hour * 3600 - min * 60);
    const mili = Math.floor((second - Math.floor(second)) * 1000);
    return (hour > 0 ? [hour, min, sec, mili] : [min, sec, mili]).map(add0).join(':');
}
```

**Comment by salmanAhmad143** [comment]
Thanks @zhw2590582 It help me a lot. One more thing i want to know that is their a way to hide all the context menu from player that are coming on right click?

**Comment by zhw2590582** [comment]
Just delete this line of code
https://github.com/zhw2590582/ArtPlayer/blob/5d9de9eea9c63654e0c30701739984fc97e96150/packages/artplayer/src/index.js#L49

**Comment by salmanAhmad143** [comment]
@zhw2590582 Thanks but i don't want to make any change in the original module file. Is there any other way to do this?

**Comment by zhw2590582** [comment]
You can add css styles externally
```css
.art-contextmenus {
    display: none !important;
}
```

**Comment by salmanAhmad143** [comment]
Ahhh @zhw2590582 this was the awesome. Thanks mate (y)
