### ISSUE TITLE
How to seek or buffer video before play.

### ISSUE THREAD

**Issue by mba8487143** [zhw2590582/ArtPlayer#135]
Hi I want to buffer 30 sec before start playing video. 
Means before start the video video should be buffered about 30 second

**Comment by zhw2590582** [comment]
Usually you just need to set the value of `preload` to `auto`: [Demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20moreVideoAttr%3A%20%7B%0A%20%20%20%20%20%20%20%20preload%3A%20%27auto%27%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B%0A)

**Comment by mba8487143** [comment]
Is there is any way to load video faster, any configuration ?
Actually I want to perform a submission after 30 sec playing video.

**Comment by zhw2590582** [comment]
This is hard to do, but there is a way to load the entire video at once

```js
fetch("https://artplayer.org/assets/sample/video.mp4")
  .then((res) => res.blob())
  .then((blob) => {
    new Artplayer({
      container: ".artplayer-app",
      url: URL.createObjectURL(blob),
    });
  });
```
