### ISSUE TITLE
Generate thumbnails according to a specific time range

### ISSUE THREAD

**Issue by WingsleyLui** [zhw2590582/ArtPlayer#137]
Hi, thank you for the neat work!

For the thumbnail-tool, it works well for generating the thumbnails for the whole video. I wonder if it is possible to generate thumbnails for a specific time range of a video, e.g., from 36s~100s in a 8min long video? It is powerful for video editing (enables users to preview a clip).

Looking forward to your reply. A lot of thanks!

**Comment by zhw2590582** [comment]
Of course, this is a good idea, I will add this feature later

**Comment by Angelk90** [comment]
@WingsleyLui , @zhw2590582 :  

In reference to this question, this is the result I get in the player:
<img width="805" alt="Schermata 2021-06-08 alle 16 15 59" src="https://user-images.githubusercontent.com/20476002/121201638-f65d4000-c874-11eb-8f2e-7e76f0ddf40b.png">

This is what gets downloaded:
![video](https://user-images.githubusercontent.com/20476002/121201755-0d039700-c875-11eb-86a8-65669ba9b27c.png)

As you can see part of the thumbnails are not displayed, is there a reason?
P.s.
It would be possible to make sure that the that if desired not to show the writing:
"From: htto://, Number: 60, Width: 160, Height: 90, Column: 10"

**Comment by zhw2590582** [comment]
Thumbnail and poster are not related, poster does not need to show all, the poster of this demo is just for reference, Has no practical meaning.
