### ISSUE TITLE
Please make documentation in more detailed.

### ISSUE THREAD

**Issue by salmanAhmad143** [zhw2590582/ArtPlayer#139]
Hi @zhw2590582 

I want to use the Fast Forward and Fast Backward option of Art player. But i am not sure what number i have to mention in Forward and Backward property.  Please suggest.

> 

forward | Number | Video fast forward
-- | -- | --

> 

backward | Number | Video fast backward
-- | -- | --

If you can add an example for each of the property in documentation then it would be more easier for us.

Thanks,

**Comment by zhw2590582** [comment]
Just pass a time difference value.


```js
art.forward = 1;
// Equal to art.seek = art.currentTime + 1;

art.backward = 1;
// Equal to art.seek = art.currentTime - 1;
```
