### ISSUE TITLE
关于播放速度

### ISSUE THREAD

**Issue by shuai93** [zhw2590582/ArtPlayer#140]
目前代码证明确 指定速率的列表为
const rateList = [0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0];

请问该值可以扩充么？

**Comment by zhw2590582** [comment]
可以，但需要修改三处代码：

https://github.com/zhw2590582/ArtPlayer/blob/97dbdf16a5a8bb0c7c647554b87f92f1a43eccc3/packages/artplayer/src/setting/playbackRate.js#L17

https://github.com/zhw2590582/ArtPlayer/blob/97dbdf16a5a8bb0c7c647554b87f92f1a43eccc3/packages/artplayer/src/contextmenu/playbackRate.js#L9

https://github.com/zhw2590582/ArtPlayer/blob/97dbdf16a5a8bb0c7c647554b87f92f1a43eccc3/packages/artplayer/src/player/playbackRateMix.js#L17

**Comment by shuai93** [comment]
跟我修改的一样 谢谢。
