### ISSUE TITLE
Alternatively use <canvas> instead of <video> tags for creating custom player

### ISSUE THREAD

**Issue by gorinje** [zhw2590582/ArtPlayer#142]
Hi, thanks for this great work!

ArtPlayer seems to heavily rely on video tags to display video, although is it possible to use canvas in order to use custom video players using the customType configuration? This would allow the videoplayer to have a ready made display layer.

**Comment by zhw2590582** [comment]
It is difficult to use canvas instead of video, at least I have never encountered a player that uses canvas to play mp4 video
