### ISSUE TITLE
Cut Video

### ISSUE THREAD

**Issue by hippomu-media** [zhw2590582/ArtPlayer#146]
can i trim the video? For example, my video is 5:00, I want to start at 1:00 and end at 4:00, so the video is only 3 minutes long, but the original video is 5 minutes long.

**Comment by zhw2590582** [comment]
Yes, Similar to the function of video clip loop: [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%09art.loop%20%3D%20%5B1%20*%2060%2C%204%20*%2060%5D%3B%0A%7D)%3B)

**Comment by hippomu-media** [comment]
wow Thanks, great work
