### ISSUE TITLE
How subtitleOffset work on ready?

### ISSUE THREAD

**Issue by hippomu-media** [zhw2590582/ArtPlayer#149]
```
art.on('ready', () => {
	art.option.subtitleOffset = 5;
});
```

**Comment by zhw2590582** [comment]
But the maximum offset is from -5 to +5: [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09subtitleOffset%3A%20true%2C%0A%20%20%20%20subtitle%3A%20%7B%0A%20%20%20%20%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.srt%27%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%09art.plugins.subtitleOffset.offset(5)%0A%7D)%3B)

**Comment by hippomu-media** [comment]
thank you, this really helped me
