### ISSUE TITLE
Separate demo page from main repo

### ISSUE THREAD

**Issue by mochaaP** [zhw2590582/ArtPlayer#154]
<https://github.com/zhw2590582/ArtPlayer/pull/152/commits/6d09f9f2850d9540afb20b08f3a5d72cc455e473> 同理。

Demo page 会在 repo 中引入不必要的编译后的 bloat。仅留下必要文档，或让 demo page 默认从 CDN 引入本库。

**Comment by zhw2590582** [comment]
Demo page引入的js是开发过程中实时输出用的，并不是生产上的，所以在开发过程中需要运行两条命令：`npm run dev` 和 `npm start`

**Comment by zhw2590582** [comment]
实例里有很多getter，是因为前期没有规划好，下个大版本更新时会把一些常用的getter改为方法
