### ISSUE TITLE
download button

### ISSUE THREAD

**Issue by hippomu-media** [zhw2590582/ArtPlayer#155]
Please make it download button like this
![IMG_20210804_150638](https://user-images.githubusercontent.com/74494691/128145695-e4b94600-9680-497a-bb09-099f1a3bccbf.jpg)
Thanks

**Comment by zhw2590582** [comment]
This is easy to do: [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20controls%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20position%3A%20%27right%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%27Subtitle%2001%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20selector%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20%27%3Cspan%20style%3D%22color%3Ared%22%3E1080p%3C%2Fspan%3E%20%3Cspan%3E1.4GB%3C%2Fspan%3E%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo-1080p.mp4%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20%27%3Cspan%20style%3D%22color%3Agreen%22%3E720%3C%2Fspan%3E%20%3Cspan%3E702MB%3C%2Fspan%3E%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo-720.mp4%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20onSelect%3A%20function%20(item)%20%7B%0A%09%09%09%09console.log(item)%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%5D%2C%0A%7D)%3B)
