### ISSUE TITLE
Supporting BlobURL

### ISSUE THREAD

**Issue by EhsanFox** [zhw2590582/ArtPlayer#162]
hey, I'm downloading my clip from another server, and I want to play it, but when I turn it to blob URL, it won't work, so I was wondering if you could add this feature.

**Comment by zhw2590582** [comment]
Do you mean like this?

```js
fetch('https://artplayer.org/assets/sample/video.mp4')
  .then(res => res.blob())
  .then(blob => {
    var art = new Artplayer({
        container: '.artplayer-app',
        url: URL.createObjectURL(blob),
    })
})
```

**Comment by EhsanFox** [comment]
yeah, i didn't know it was possible...

**Comment by EhsanFox** [comment]
i probably had an error with my code, thanks you anyway.
