### ISSUE TITLE
如何监听按钮的触发事件

### ISSUE THREAD

**Issue by yuluozhiyi** [zhw2590582/ArtPlayer#180]
![VF%_HBQSW`~R}YFU@U%QC I](https://user-images.githubusercontent.com/40261363/141451703-bef8d4cc-1f32-4c11-a5b5-c73f1541c2ff.png)
如图,我想控制左上角上边的那个提示,那几个插件允许显示,那几个不允许显示,且修改提示的内容.怎么去控制显示以及修改内容.

**Comment by yuluozhiyi** [comment]
我在文档中没有找到方法去监听这些点击事件的实例,不知怎么去写

**Comment by zhw2590582** [comment]
这是一个小bug，你可以先把这个提示删掉，我后面再优化它
https://github.com/zhw2590582/ArtPlayer/blob/6abd7f3ae2ef31658d2a79fd6a392e06584cbaad/packages/artplayer/src/player/flipMix.js#L28

**Comment by zhw2590582** [comment]
在最新版本已经修复
