### ISSUE TITLE
Cannot run no ssl in domain

### ISSUE THREAD

**Issue by flixmu** [zhw2590582/ArtPlayer#181]
[No ssl video link](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27http%3A%2F%2Fflixmu.ezyro.com%2Fd%2F1K6XQvphtLe8pU2D6szTMGqdoXc-jRH-W%2Fdownload%27%2C%0A%20%20%20%20title%3A%20%27One%20More%20Time%20One%20More%20Chance%27%2C%0A%20%20%20%20poster%3A%20%27%2Fassets%2Fsample%2Fposter.jpg%27%2C%0A%20%20%20%20volume%3A%200.5%2C%0A%20%20%20%20isLive%3A%20false%2C%0A%20%20%20%20muted%3A%20false%2C%0A%20%20%20%20autoplay%3A%20false%2C%0A%20%20%20%20pip%3A%20true%2C%0A%20%20%20%20autoSize%3A%20true%2C%0A%20%20%20%20autoMini%3A%20true%2C%0A%20%20%20%20screenshot%3A%20true%2C%0A%20%20%20%20setting%3A%20true%2C%0A%20%20%20%20loop%3A%20true%2C%0A%20%20%20%20flip%3A%20true%2C%0A%20%20%20%20rotate%3A%20true%2C%0A%20%20%20%20playbackRate%3A%20true%2C%0A%20%20%20%20aspectRatio%3A%20true%2C%0A%20%20%20%20fullscreen%3A%20true%2C%0A%20%20%20%20fullscreenWeb%3A%20true%2C%0A%20%20%20%20subtitleOffset%3A%20true%2C%0A%20%20%20%20miniProgressBar%3A%20true%2C%0A%20%20%20%20localVideo%3A%20true%2C%0A%20%20%20%20localSubtitle%3A%20true%2C%0A%20%20%20%20networkMonitor%3A%20false%2C%0A%20%20%20%20mutex%3A%20true%2C%0A%20%20%20%20light%3A%20true%2C%0A%20%20%20%20backdrop%3A%20true%2C%0A%20%20%20%20log%3A%20true%2C%0A%20%20%20%20theme%3A%20%27%23ffad00%27%2C%0A%20%20%20%20lang%3A%20navigator.language.toLowerCase()%2C%0A%20%20%20%20%0A%20%20%20%20contextmenu%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%27Custom%20menu%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20click%3A%20function%20(contextmenu)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.info(%27You%20clicked%20on%20the%20custom%20menu%27)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20contextmenu.show%20%3D%20false%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%5D%2C%0A%20%20%20%20layers%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%60%3Cimg%20style%3D%22width%3A%20100px%22%20src%3D%22%2Fassets%2Fsample%2Flayer.png%22%3E%60%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20click%3A%20function%20()%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.info(%27You%20clicked%20on%20the%20custom%20layer%27)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20style%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20position%3A%20%27absolute%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20top%3A%20%2720px%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20right%3A%20%2720px%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20opacity%3A%20%27.9%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%5D%2C%0A%20%20%20%20quality%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20default%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20%27SD%20480P%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20%27HD%20720P%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%5D%2C%0A%20%20%20%20thumbnails%3A%20%7B%0A%20%20%20%20%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fthumbnails.png%27%2C%0A%20%20%20%20%20%20%20%20number%3A%20100%2C%0A%20%20%20%20%20%20%20%20width%3A%20160%2C%0A%20%20%20%20%20%20%20%20height%3A%2090%2C%0A%20%20%20%20%20%20%20%20column%3A%2010%2C%0A%20%20%20%20%7D%2C%0A%20%20%20%20subtitle%3A%20%7B%0A%20%20%20%20%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.srt%27%2C%0A%20%20%20%20%20%20%20%20style%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20color%3A%20%27%2303A9F4%27%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20encoding%3A%20%27utf-8%27%2C%0A%20%20%20%20%20%20%20%20bilingual%3A%20true%2C%0A%20%20%20%20%7D%2C%0A%20%20%20%20highlight%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20time%3A%2060%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20text%3A%20%27One%20more%20chance%27%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20time%3A%20120%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20text%3A%20%27%E8%B0%81%E3%81%A7%E3%82%82%E3%81%84%E3%81%84%E3%81%AF%E3%81%9A%E3%81%AA%E3%81%AE%E3%81%AB%27%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20time%3A%20180%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20text%3A%20%27%E5%A4%8F%E3%81%AE%E6%83%B3%E3%81%84%E5%87%BA%E3%81%8C%E3%81%BE%E3%82%8F%E3%82%8B%27%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20time%3A%20240%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20text%3A%20%27%E3%81%93%E3%82%93%E3%81%AA%E3%81%A8%E3%81%93%E3%81%AB%E3%81%82%E3%82%8B%E3%81%AF%E3%81%9A%E3%82%82%E3%81%AA%E3%81%84%E3%81%AE%E3%81%AB%27%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20time%3A%20300%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20text%3A%20%27%E7%BB%88%E3%82%8F%E3%82%8A%27%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%5D%2C%0A%20%20%20%20controls%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20position%3A%20%27right%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%27Control%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20click%3A%20function%20()%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.info(%27You%20clicked%20on%20the%20custom%20control%27)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%5D%2C%0A%20%20%20%20icons%3A%20%7B%0A%20%20%20%20%20%20%20%20loading%3A%20%27%3Cimg%20src%3D%22%2Fassets%2Fimg%2Fploading.gif%22%3E%27%2C%0A%20%20%20%20%20%20%20%20state%3A%20%27%3Cimg%20src%3D%22%2Fassets%2Fimg%2Fstate.png%22%3E%27%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B)

[With ssl video link](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fflixmu.ezyro.com%2Fd%2F1K6XQvphtLe8pU2D6szTMGqdoXc-jRH-W%2Fdownload%27%2C%0A%20%20%20%20title%3A%20%27One%20More%20Time%20One%20More%20Chance%27%2C%0A%20%20%20%20poster%3A%20%27%2Fassets%2Fsample%2Fposter.jpg%27%2C%0A%20%20%20%20volume%3A%200.5%2C%0A%20%20%20%20isLive%3A%20false%2C%0A%20%20%20%20muted%3A%20false%2C%0A%20%20%20%20autoplay%3A%20false%2C%0A%20%20%20%20pip%3A%20true%2C%0A%20%20%20%20autoSize%3A%20true%2C%0A%20%20%20%20autoMini%3A%20true%2C%0A%20%20%20%20screenshot%3A%20true%2C%0A%20%20%20%20setting%3A%20true%2C%0A%20%20%20%20loop%3A%20true%2C%0A%20%20%20%20flip%3A%20true%2C%0A%20%20%20%20rotate%3A%20true%2C%0A%20%20%20%20playbackRate%3A%20true%2C%0A%20%20%20%20aspectRatio%3A%20true%2C%0A%20%20%20%20fullscreen%3A%20true%2C%0A%20%20%20%20fullscreenWeb%3A%20true%2C%0A%20%20%20%20subtitleOffset%3A%20true%2C%0A%20%20%20%20miniProgressBar%3A%20true%2C%0A%20%20%20%20localVideo%3A%20true%2C%0A%20%20%20%20localSubtitle%3A%20true%2C%0A%20%20%20%20networkMonitor%3A%20false%2C%0A%20%20%20%20mutex%3A%20true%2C%0A%20%20%20%20light%3A%20true%2C%0A%20%20%20%20backdrop%3A%20true%2C%0A%20%20%20%20log%3A%20true%2C%0A%20%20%20%20theme%3A%20%27%23ffad00%27%2C%0A%20%20%20%20lang%3A%20navigator.language.toLowerCase()%2C%0A%20%20%20%20%0A%20%20%20%20contextmenu%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%27Custom%20menu%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20click%3A%20function%20(contextmenu)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.info(%27You%20clicked%20on%20the%20custom%20menu%27)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20contextmenu.show%20%3D%20false%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%5D%2C%0A%20%20%20%20layers%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%60%3Cimg%20style%3D%22width%3A%20100px%22%20src%3D%22%2Fassets%2Fsample%2Flayer.png%22%3E%60%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20click%3A%20function%20()%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.info(%27You%20clicked%20on%20the%20custom%20layer%27)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20style%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20position%3A%20%27absolute%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20top%3A%20%2720px%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20right%3A%20%2720px%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20opacity%3A%20%27.9%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%5D%2C%0A%20%20%20%20quality%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20default%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20%27SD%20480P%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20%27HD%20720P%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%5D%2C%0A%20%20%20%20thumbnails%3A%20%7B%0A%20%20%20%20%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fthumbnails.png%27%2C%0A%20%20%20%20%20%20%20%20number%3A%20100%2C%0A%20%20%20%20%20%20%20%20width%3A%20160%2C%0A%20%20%20%20%20%20%20%20height%3A%2090%2C%0A%20%20%20%20%20%20%20%20column%3A%2010%2C%0A%20%20%20%20%7D%2C%0A%20%20%20%20subtitle%3A%20%7B%0A%20%20%20%20%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.srt%27%2C%0A%20%20%20%20%20%20%20%20style%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20color%3A%20%27%2303A9F4%27%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20encoding%3A%20%27utf-8%27%2C%0A%20%20%20%20%20%20%20%20bilingual%3A%20true%2C%0A%20%20%20%20%7D%2C%0A%20%20%20%20highlight%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20time%3A%2060%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20text%3A%20%27One%20more%20chance%27%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20time%3A%20120%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20text%3A%20%27%E8%B0%81%E3%81%A7%E3%82%82%E3%81%84%E3%81%84%E3%81%AF%E3%81%9A%E3%81%AA%E3%81%AE%E3%81%AB%27%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20time%3A%20180%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20text%3A%20%27%E5%A4%8F%E3%81%AE%E6%83%B3%E3%81%84%E5%87%BA%E3%81%8C%E3%81%BE%E3%82%8F%E3%82%8B%27%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20time%3A%20240%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20text%3A%20%27%E3%81%93%E3%82%93%E3%81%AA%E3%81%A8%E3%81%93%E3%81%AB%E3%81%82%E3%82%8B%E3%81%AF%E3%81%9A%E3%82%82%E3%81%AA%E3%81%84%E3%81%AE%E3%81%AB%27%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20time%3A%20300%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20text%3A%20%27%E7%BB%88%E3%82%8F%E3%82%8A%27%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%5D%2C%0A%20%20%20%20controls%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20position%3A%20%27right%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%27Control%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20click%3A%20function%20()%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.info(%27You%20clicked%20on%20the%20custom%20control%27)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%5D%2C%0A%20%20%20%20icons%3A%20%7B%0A%20%20%20%20%20%20%20%20loading%3A%20%27%3Cimg%20src%3D%22%2Fassets%2Fimg%2Fploading.gif%22%3E%27%2C%0A%20%20%20%20%20%20%20%20state%3A%20%27%3Cimg%20src%3D%22%2Fassets%2Fimg%2Fstate.png%22%3E%27%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B)

**Comment by zhw2590582** [comment]
Of course, the demo page uses https, so you can't access the http URL
