### ISSUE TITLE
Subtitle not show

### ISSUE THREAD

**Issue by flixmu** [zhw2590582/ArtPlayer#183]
Failed to fetch

[Link](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20subtitle%3A%20%7B%0A%20%20%20%20%20%20%20%20url%3A%20%27https%3A%2F%2Fdl.flixmu.com%2Frepository%2FSubtitle%2FT%2FThe%2520Fruit%2520of%2520Evolution%3A%2520Before%2520I%2520Knew%2520It%2C%2520My%2520Life%2520Had%2520It%2520Made%2FSeason%25201%2F1%2F%255bEnglish%255d.srt%27%2C%0A%20%20%20%20%20%20%20%20encoding%3A%20%27utf-8%27%2C%0A%20%20%20%20%20%20%20%20bilingual%3A%20true%2C%0A%20%20%20%20%20%20%20%20style%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20color%3A%20%27%2303A9F4%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%27font-size%27%3A%20%2730px%27%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B)

**Comment by zhw2590582** [comment]
Yes, there is a cross-domain problem with your subtitle address

**Comment by flixmu** [comment]
How to fix?

**Comment by zhw2590582** [comment]
You can download the subtitle file to your local directory, or put the subtitle file on a non-cross-domain server
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by zhw2590582** [comment]
You can download the subtitle file to your local directory, or put the subtitle file on a non-cross-domain server
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by flixmu** [comment]
Thanks.

**Comment by flixmu** [comment]
Please help me! I use this link not work for subtitle
1. https://flixmu.com/ftp/index.php?p=subtitle&dl=English.srt

But this link work
2. https://flixmu.com/public/upload/subtitle/English.srt

Please help me use firts link

**Comment by zhw2590582** [comment]
Like this?
https://flixmu.com/ftp/index.php?p=subtitle&dl=https://flixmu.com/public/upload/subtitle/English.srt

**Comment by flixmu** [comment]
> Like this? https://flixmu.com/ftp/index.php?p=subtitle&dl=https://flixmu.com/public/upload/subtitle/English.srt

Cannot download file not found

**Comment by zhw2590582** [comment]
I can not open the player url: https://flixmu.com/ftp/index.php?p=subtitle&dl=English.srt

**Comment by flixmu** [comment]
> I can not open the player url, need login: https://flixmu.com/ftp/index.php?p=subtitle&dl=English.srt

Try again with this link with no login

https://flixmu.com/dl/index.php?p=upload%2Fsubtitle&dl=English.srt

**Comment by zhw2590582** [comment]
https://flixmu.com/dl/index.php?p=upload%2Fsubtitle&dl=English.srt
This link is download the srt file, not a player page

**Comment by flixmu** [comment]
Thanks the link is fix.
