### ISSUE TITLE
Help me please, subtitle not show

### ISSUE THREAD

**Issue by flixmu** [zhw2590582/ArtPlayer#185]
https://flixmu.com/serie/the-fruit-of-evolution-before-i-knew-it-my-life-had-it-made-1/1-season/1-episode

This link to player

**Comment by flixmu** [comment]
Subtitle show if i put in github pages, but not show if i put on my website storage

Here subtitle url from my storage:
https://flixmu-sub.herokuapp.com/subtitle/s/the-fruit-of-evolution-before-i-knew-it-my-life-had-it-made-1/1-season/1-episode/Simplified%20Chinese.srt

And here subtitle from github:
https://flixmu.github.io/subtitle/s/the-fruit-of-evolution-before-i-knew-it-my-life-had-it-made-1/1-season/1-episode/Simplified%20Chinese.srt

**Comment by zhw2590582** [comment]
You can open your chrome console through F12, then paste the following code to run, and see if you can access your subtitle file:

```js
fetch('https://flixmu-sub.herokuapp.com/subtitle/s/the-fruit-of-evolution-before-i-knew-it-my-life-had-it-made-1/1-season/1-episode/Simplified%20Chinese.srt').then(res => res.text()).then(console.log)
```

```js
fetch('https://flixmu.github.io/subtitle/s/the-fruit-of-evolution-before-i-knew-it-my-life-had-it-made-1/1-season/1-episode/Simplified%20Chinese.srt').then(res => res.text()).then(console.log)
```

**Comment by flixmu** [comment]
Done, thanks for help
