### ISSUE TITLE
Auto pause when duration update m3u8

### ISSUE THREAD

**Issue by flixmu** [zhw2590582/ArtPlayer#187]
https://flixmu.github.io/tv-channel/mnctv-visionplus/

Hi this link for player m3u8 type, but the player auto pause when duration video update, this video live from tv channel.

**Comment by flixmu** [comment]
I think its not player problem, the problem in my connection to slow. but what if if the video is paused it will play automatically?

**Comment by zhw2590582** [comment]
I didn't understand what you mean, you want to not let the video pause automatically when you update m3u8, right?
