### ISSUE TITLE
Is it possible to show Title of the video on hover and/or when the video is paused?

### ISSUE THREAD

**Issue by evidencefrank** [zhw2590582/ArtPlayer#188]
Thank you very much for this wonderful video player. I just discovered it right now and I have been playing around with the artplayer-vue package. 

I was wondering if it is possible to show/display the Title of the video on hover and/or when the video is paused? I tried looking into the documentation but could not find that setting.

So can it be achieved by modifying an option or it's something that we would have to implement using css?

**Comment by zhw2590582** [comment]
This is very simple: [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20autoSize%3A%20true%2C%0A%20%20%20%20layers%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20%27title%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%27%3Cspan%3EOne%20More%20Time%20One%20More%20Chance%3C%2Fspan%3E%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20style%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20position%3A%20%27absolute%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20top%3A%20%2715px%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20right%3A%20%2715px%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%5D%2C%0A%7D)%3B%0A%0Avar%20%24title%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%09%24title%20%3D%20art.template.query(%27.art-layer-title%27)%3B%0A%7D)%3B%0A%0Aart.on(%27pause%27%2C%20()%20%3D%3E%20%7B%0A%09%24title.style.display%20%3D%20%27block%27%3B%0A%7D)%3B%0A%0Aart.on(%27play%27%2C%20()%20%3D%3E%20%7B%0A%09%24title.style.display%20%3D%20%27none%27%3B%0A%7D)%3B%0A%0Aart.on(%27hover%27%2C%20(state)%20%3D%3E%20%7B%0A%20%20%20%24title.style.display%20%3D%20state%20%7C%7C%20!art.playing%20%3F%20%27block%27%20%3A%20%27none%27%3B%0A%7D)%3B)

**Comment by evidencefrank** [comment]
That was exactly what I was looking for! Thanks a lot :)

**Comment by evidence-sharenet** [comment]
Hi @zhw2590582. I have been trying to create a video playlist using vueJs. So one of the things I would like to do is change the Layer text (video title) when new video starts playing as shown below. Is it possible to do that with this player? I have been getting getting an error whenever  I try to rewrite the layers option.

<img width="838" alt="Screenshot 2021-12-08 at 21 23 15" src="https://user-images.githubusercontent.com/92296834/145271717-332fffae-c799-42a2-a083-ee9cbeb6eeba.png">

**Comment by zhw2590582** [comment]
Yes, this is demo link: [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09autoSize%3A%20true%2C%0A%09layers%3A%20%5B%0A%09%09%7B%0A%09%09%09name%3A%20%27title%27%2C%0A%09%09%09html%3A%20%27One%20More%20Time%20One%20More%20Chance%27%2C%0A%09%09%09style%3A%20%7B%0A%09%09%09%09position%3A%20%27absolute%27%2C%0A%09%09%09%09top%3A%20%2715px%27%2C%0A%09%09%09%09right%3A%20%2715px%27%2C%0A%09%09%09%7D%2C%0A%09%09%7D%2C%0A%09%5D%2C%0A%7D)%3B%0A%0Aart.on(%27pause%27%2C%20()%20%3D%3E%20%7B%0A%09art.layers.title.style.display%20%3D%20%27block%27%3B%0A%7D)%3B%0A%0Aart.on(%27play%27%2C%20()%20%3D%3E%20%7B%0A%09art.layers.title.style.display%20%3D%20%27none%27%3B%0A%7D)%3B%0A%0Aart.on(%27hover%27%2C%20(state)%20%3D%3E%20%7B%0A%09art.layers.title.style.display%20%3D%20state%20%7C%7C%20!art.playing%20%3F%20%27block%27%20%3A%20%27none%27%3B%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%09setTimeout(()%20%3D%3E%20%7B%0A%09%09art.layers.title.innerText%20%3D%20%27This%20is%20new%20title%27%3B%0A%09%7D%2C%203000)%3B%0A%7D)%3B%0A%0A)

你能直接访问到图层的dom元素，你想做任何dom操作都可以

```js
var dom = art.layers['your-layer-name'];
dom.innerText = 'This is new title';
```

**Comment by evidence-sharenet** [comment]
Thank you @zhw2590582.

**Comment by evidence-sharenet** [comment]
Hi @zhw2590582.

Is there a way to show the title (layer text) on the video component on initial page load if we have these following settings?
```
const playerOptions = {
    container: '.artplayer-app',
    url: 'https://artplayer.org/assets/sample/video.mp4',
    moreVideoAttr: {
      // crossOrigin: 'anonymous',
      preload: 'none'
      playsInline: true,
    },
}
```

if the preload value is "none" the title (layer text) does not show on page load. It will only show when you click to play the video. I want the title to behave the same way as if the preload value is set to 'metadata'. Is it possible?

**Comment by evidence-sharenet** [comment]
Is it possible to manually trigger the `loadedmetadata` event?

**Comment by evidence-sharenet** [comment]
@zhw2590582 you're a life saver :). Thanks...
