### ISSUE TITLE
Full screen hotkey

### ISSUE THREAD

**Issue by tokorode** [zhw2590582/ArtPlayer#194]
Can you set F and double click as fullscreen hotkey?

**Comment by zhw2590582** [comment]
Yes, you can see the code here: [demo](https://artplayer.org/?libs=&code=var%20container%20%3D%20document.querySelector(%27.artplayer-app%27)%3B%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20container%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%7D)%3B%0A%0A%2F%2F%2070%20is%20key%20code%20of%20%27F%27%20key%0Aart.hotkey.add(70%2C%20()%20%3D%3E%20%7B%0A%09art.fullscreen%20%3D%20!art.fullscreen%3B%0A%7D)%3B%0A%0Acontainer.ondblclick%20%3D%20function()%20%7B%0A%09art.fullscreen%20%3D%20!art.fullscreen%3B%0A%7D%3B)
