### ISSUE TITLE
Auto Horizontal Videos for Mobile Devices

### ISSUE THREAD

**Issue by tokorode** [zhw2590582/ArtPlayer#196]
When the video is full screen on mobile (or we turn screen horizontal), it will automatically rotate horizontally. (like YouTube)

![image](https://i.ibb.co/9TZXR9W/Horizontal-versus-vertical-1024x536.webp)

**Comment by zhw2590582** [comment]
This idea is very good, but currently only Android system can do this in mobile browsers, ios system does not support this js forced screen rotation function, I will find a better way

**Comment by zhw2590582** [comment]
Auto-rotate on mobile devices has been implemented in version 4.3.9
