### ISSUE TITLE
Some styles for a better look

### ISSUE THREAD

**Issue by desvu** [zhw2590582/ArtPlayer#205]
.art-settings button,
.art-settings input[type="radio"] {
    cursor: pointer;
}

.art-settings input[type="file"]::-ms-browse {
    cursor: pointer;
}

.art-settings input[type="file"]::-webkit-file-upload-button {
    cursor: pointer;
}

.art-settings input[type="file"]::file-selector-button {
    cursor: pointer;
}

.art-control-time {
    cursor: default;
}

**Comment by zhw2590582** [comment]
Thank you for your suggestion, I will add these css in the next version
