### ISSUE TITLE
Add icon in quality selector and subtitle selector

### ISSUE THREAD

**Issue by flixmu** [zhw2590582/ArtPlayer#208]
Please add icon in subtitle selector and quality selector

**Comment by zhw2590582** [comment]
You can set the appropriate icon by yourself:
 
```js
var art = new Artplayer({
    container: '.artplayer-app',
    url: '/assets/sample/video.mp4',
    controls: [
        {
            position: 'right',
            html: 'Custom Icon',
            selector: [
                {
                    default: true,
                    html: '<i class="some-font-icon"></i>Custom Icon01',
                },
                {
                    html: '<img src="some-image-icon.png" />Custom Icon02',
                },
            ],
            onSelect: function (item, $dom) {
                console.info(item, $dom);
                return 'You click ' + $dom.innerText;
            },
        },
    ],
});
```

**Comment by flixmu** [comment]
> You can set the appropriate icon by yourself:
> 
> ```js
> var art = new Artplayer({
>     container: '.artplayer-app',
>     url: '/assets/sample/video.mp4',
>     controls: [
>         {
>             position: 'right',
>             html: 'Custom Icon',
>             selector: [
>                 {
>                     default: true,
>                     html: '<i class="some-font-icon"></i>Custom Icon 01',
>                 },
>                 {
>                     html: '<img src="some-image-icon.png" />Custom Icon 02',
>                 },
>             ],
>             onSelect: function (item, $dom) {
>                 console.info(item, $dom);
>                 return 'You click ' + $dom.innerText;
>             },
>         },
>     ],
> });
> ```

Thnks
