### ISSUE TITLE
The video slider doesn’t work properly on mobile devices

### ISSUE THREAD

**Issue by Dester-Alken** [zhw2590582/ArtPlayer#212]
### Expected behaviour
I expected it to move when dragging using finger in mobile video but for some reason it works on desktop but not on mobile

### Actual behaviour
Does nothing when dragged

### Steps to reproduce
Using and mobile device this can be reproduced

### Environment

-   Browser: Chrome
-   Version: Version 97.0.4692.71 (Official Build) (x86_64)
-   Operating System: macOS, Android
-   Version: Monterey 12.1, Android 11

### Console errors (if any)
None

### Link to where the bug is happening
Its a local development environment

Improvement - I also noticed that you used divs rather than actual slider which makes customising a little difficult.

**Comment by zhw2590582** [comment]
Thank you for the reminder, I already know where the problem is, I will fix it in the next minor update, thank you

**Comment by zhw2590582** [comment]
I fixed this in version `@4.2.3`, actually the slider is too small on mobile devices to be easy to swipe, you can swipe directly on the video to achieve the same effect
