### ISSUE TITLE
artplayer在手机上进度条不好控制

### ISSUE THREAD

**Issue by muzidudu** [zhw2590582/ArtPlayer#213]
进度条高度太少了,点击半天没效果,特别是控制栏右边的位置,容易误触,网页全屏,全屏按钮

**Comment by zhw2590582** [comment]
当前还没有为移动设备单独设置样式，我会在下个版本优化这个样式问题的，多谢反馈
其实在移动端不用拖动进度条，直接在视频上拖动就也能快进快退的

**Comment by muzidudu** [comment]
视频上滑动短时间的可以 ,如果视频比较长的话,就一言难尽了 :D

**Comment by zhw2590582** [comment]
在`4.2.6`版本之后，在移动设备上拖动视频时，会以视频的总时长作为参考进行快进快退，就算视频比较长的话也不会造成困难了
