### ISSUE TITLE
感谢作者提供这么好的播放器

### ISSUE THREAD

**Issue by oyjcmyn** [zhw2590582/ArtPlayer#215]
我想提个建议，播放器设置方面的布局可以参考一下youtube上的播放器功能布局，把许多的一些功能集合到一个设置图标中，这样能给整个播放条一个比较宽的空间，不然在移动设备上，如果开启多个功能时，一行都装不下了

**Comment by zhw2590582** [comment]
有道理，但这个改动有点打，需要考虑一下

**Comment by oyjcmyn** [comment]
嗯 确实改动大，需要时间和精力。以后给我来赞助一些。
目前这个播放器功能都非常实用和强大，唯一缺点就是觉得播放器的设置界面有些low。

**Comment by zhw2590582** [comment]
下个版本会对设置面板进行优化，现在可以在demo看到测试效果了
