### ISSUE TITLE
首先感谢作者，然后因为是第一次使用，想请教几个问题，简单回答即可

### ISSUE THREAD

**Issue by MoConWu** [zhw2590582/ArtPlayer#217]
问题1：请问该项目是否支持Vue3

问题2：请问该播放器支持的视频格式与H5默认的支持格式是否相同，或比默认支持的格式更多？

问题3：若该播放器支持的格式有限，那么某些默认不支持的格式，是否可以支持类似ffmpeg解码进行实时播放的功能？

谢谢作者有空回答！

**Comment by zhw2590582** [comment]
支持Vue3，文档上面有Vue的demo
播放器默认不带有其它解码器，所以默认只支持mp3、webm和ogg三种视频格式
实时播放和播放器无关的，一般依赖第三方的解码库，在服务器端使用ffmpeg转码，播放器再接入像hls.js和flv.js这种软解码的库才行

MoConWu ***@***.***> 于2022年1月24日周一 18:12写道：

**Comment by MoConWu** [comment]
收到，谢谢您的回答！
