### ISSUE TITLE
再次请教作者几个问题哈

### ISSUE THREAD

**Issue by MoConWu** [zhw2590582/ArtPlayer#218]
我发现作者大大还做了FlvPlayer

问1：除了支持的格式不一样，FlvPlayer与ArtPlayer的区别是什么？

问2：FlvPlayer是否只支持flv格式的视频？

问3：能否将两个播放器做整合，使其支持的格式更多？

感谢作者抽空回答！

**Comment by zhw2590582** [comment]
FlvPlayer主要为了能在手机上播放flv视频，假如你想找集合多种解码器的播放器，你可以试试这种https://github.com/bytedance/xgplayer
