### ISSUE TITLE
应该有个播放速度功能

### ISSUE THREAD

**Issue by how4ever** [zhw2590582/ArtPlayer#22]
看主流播放器都有0.5,0.75,1,1.25.1.5,2倍速播放的功能, 不知道这个实现起来难度如何. 如果倍速播放的话,字幕和弹幕是否还能很好适配也是个问题.

**Comment by zhw2590582** [comment]
@how4ever 鼠标右键菜单就有，字幕本身是适配的，弹幕的话需要改进一下。

**Comment by how4ever** [comment]
> @how4ever 鼠标右键菜单就有，字幕本身是适配的，弹幕的话需要改进一下。

右键不够人性化,因为在pad, phone和tv等非PC设备上用右键都不方便, 该功能不如放在设置那个按钮里.

**Comment by zhw2590582** [comment]
@how4ever 确实是的，但目前播放器还没很好的适配移动端，后期会提供更多的选项的。

**Comment by how4ever** [comment]
> @how4ever 确实是的，但目前播放器还没很好的适配移动端，后期会提供更多的选项的。

恩, 希望能做的越来越好.

**Comment by oyjcmyn** [comment]
个人建议，设置按钮中的操作，可以参考一下youtube的中设置布局。
