### ISSUE TITLE
Play Audio Streams

### ISSUE THREAD

**Issue by LastxTemplar** [zhw2590582/ArtPlayer#221]
I haven't this in the docs, but is it possible to play audio streams with this player? like live radio stations?

Thank you!

**Comment by zhw2590582** [comment]
ArtPlayer just beautifies the UI of the native video dom element. If the native video can play the audio stream, then ArtPlayer will be able to. But ArtPlayer can't play real-time audio stream directly, maybe you need additional library like hls.js or use websocket

**Comment by LastxTemplar** [comment]
Got it. Thank you very much for the fast response. Since ArtPlayer only works with the `video` tag then I probably need to find a different player for my audio sources :)
