### ISSUE TITLE
Changing the source

### ISSUE THREAD

**Issue by LastxTemplar** [zhw2590582/ArtPlayer#223]
What would be the best way to change the source of the player in Vue?

I have a list of sources and I want to be able to change the video source by clicking on the items in the list. What would be the best way to achieve this?

Thank you!

**Comment by LastxTemplar** [comment]
I tried destroying the player and then instantiating it again, but then I found the there is this method on the instance `https://artplayer.org/document/propertie#switchurl` so everything works now :)

The issue though is that right now my source is an HLS video so I instantiate the player with this:
```
customType: {
  m3u8: (video, url) => {
    const hls = new Hls()
    hls.loadSource(url)
    hls.attachMedia(video)
  }
}
```

But what if the new video src is a Dash source? I would need to change the custom type option right? how would I do that?

Thanks again :)

**Comment by zhw2590582** [comment]
This is very simple, just remember to destroy the previous source when you switch url: [demo](https://artplayer.org/?libs=https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fhls.js%401.1.1%2Fdist%2Fhls.min.js%0Ahttps%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fdashjs%404.1.0%2Fdist%2Fdash.all.debug.min.js&code=let%20hls%20%3D%20null%3B%0Alet%20dash%20%3D%20null%3B%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20autoplay%3A%20true%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Ftest-streams.mux.dev%2Fx36xhzz%2Fx36xhzz.m3u8%27%2C%0A%20%20%20%20customType%3A%20%7B%0A%20%20%20%20%20%20%20%20m3u8%3A%20function%20(video%2C%20url)%20%7B%0A%09%09%09if%20(hls)%20%7B%0A%09%09%09%09hls.destroy()%3B%0A%09%09%09%09hls%20%3D%20null%3B%0A%09%09%09%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20hls%20%3D%20new%20Hls()%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20hls.loadSource(url)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20hls.attachMedia(video)%3B%0A%20%20%20%20%20%20%20%20%7D%2C%0A%09%09mpd%3A%20function%20(video%2C%20url)%20%7B%0A%09%09%09if%20(dash)%20%7B%0A%09%09%09%09dash.destroy()%3B%0A%09%09%09%09dash%20%3D%20null%3B%0A%09%09%09%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20dash%20%3D%20dashjs.MediaPlayer().create()%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20dash.initialize(video%2C%20url%2C%20true)%3B%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%09setTimeout(()%20%3D%3E%20%7B%0A%09%09art.switchUrl(%27https%3A%2F%2Fdash.akamaized.net%2Fenvivio%2FEnvivioDash3%2Fmanifest.mpd%27)%0A%09%7D%2C%203000)%3B%0A%7D))

**Comment by LastxTemplar** [comment]
Thank you very much! :)
