### ISSUE TITLE
how do i run MPEG-DASH in your video player?

### ISSUE THREAD

**Issue by xpcchx** [zhw2590582/ArtPlayer#227]
how do i make the video player play mpd files?

https: // cdn .test .com/playManifest/Id/0-123456789/Ids/360,480,720,1080/format/mpegdash/https/playlist.mpd

ids = quality

**Comment by zhw2590582** [comment]
You can see this: https://artplayer.org/document/libraries#dashjs

**Comment by xpcchx** [comment]
> You can see this: https://artplayer.org/document/libraries#dashjs

thank you 🥰🥰🥰
