### ISSUE TITLE
关于视频字幕问题

### ISSUE THREAD

**Issue by igoguojia** [zhw2590582/ArtPlayer#228]
是不支持srt格式的字幕吗？播放时会乱码

![](https://camo.githubusercontent.com/b199eda02aec7b4fa4ca1c79a257ef9805395be89e4370954a1ffdbb2b76c74b/68747470733a2f2f702e736461312e6465762f352f65373664656261326635663766376164343631633230386337316530653230342f515125453625383825414125453525394225424532303232303231383139343734302e706e67)
![image](https://user-images.githubusercontent.com/71238172/154853822-bd18af16-bc97-489a-ab64-479cc0c5da08.png)

**Comment by zhw2590582** [comment]
https://artplayer.org/document/zh-cn/options#subtitle
因为你这个不是utf-8编码的文件，你可以保存为utf-8编码，或者找到你这个文件原本的编码是多少再填到encoding里

**Comment by igoguojia** [comment]
> 
我更改之后也是这样。
![image](https://user-images.githubusercontent.com/71238172/154892157-c2732b65-4101-45af-95cd-926fcbf7bdc7.png)

**Comment by igoguojia** [comment]
> https://artplayer.org/document/zh-cn/options#subtitle 因为你这个不是utf-8编码的文件，你可以保存为utf-8编码，或者找到你这个文件原本的编码是多少再填到encoding里

十分抱歉！但是现在莫名其妙的好了，不过之前确实是utf-8编码，或许是我的错误操作。打扰了
![image](https://user-images.githubusercontent.com/71238172/154892294-d9df988c-10f3-44f9-be8a-463cdd469be2.png)
