### ISSUE TITLE
Multiple images on thumbnails.

### ISSUE THREAD

**Issue by ErenKrt** [zhw2590582/ArtPlayer#234]
Hello, I just discovered your project and I really like it. But I couldn't find how to use multiple images in thumbnail.

My expectation like this;
```
thumbnails: {
  url: ['/assets/sample/thumbnails.png','/assets/sample/thumbnails-2.png','/assets/sample/thumbnails-3.png'],
  number: 100, // number per image
  column: 10, // column per image
},
```

**Comment by zhw2590582** [comment]
Multiple images are not supported, I suggest you first merge multiple images first.

**Comment by ErenKrt** [comment]
Thanks for quick response. Im using external sources for thumbnails. How can i merge ?

**Comment by zhw2590582** [comment]
Like this: https://github.com/lukechilds/merge-images

**Comment by ErenKrt** [comment]
Thank you. I will try. Do you plan to add this feature in the future?

**Comment by zhw2590582** [comment]
In general, thumbnails is a picture. If it is a multi-picture, the front end will have many requests, which is not very practical.

**Comment by ErenKrt** [comment]
Yes but you already have isloaded system. When user hover progress will image load and cached. After that shows image from cache. If you're busy, I can try to do and send a pull request.

**Comment by zhw2590582** [comment]
I understand what you mean, I think this could be a player plugin, let me figure out how to do it

**Comment by ErenKrt** [comment]
Okey thank you for help. I need this urgently. Can you give an estimated time? If you can't, I can make it as a plugin and share it with you. I will be happy to help you

**Comment by zhw2590582** [comment]
There is only one problem at present, how to cache the images

**Comment by zhw2590582** [comment]
You can check this: [demo](https://artplayer.org/?libs=&code=var%20base%20%3D%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fsample%2Fthumbnails%2F%2Fthumbnail_%27%3B%0Avar%20urls%20%3D%20Array(60).fill().map((_%2C%20i)%20%3D%3E%20%60%24%7Bbase%7D%24%7Bi%20%2B%201%7D.jpg%60)%3B%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09plugins%3A%20%5B%0A%09%09artplayerPluginThumbnails(%7B%0A%09%09%09urls%3A%20urls%2C%0A%09%09%09width%3A%20160%2C%0A%09%09%09height%3A%2090%2C%0A%09%09%7D)%0A%09%5D%0A%7D)%3B%0A%0Afunction%20artplayerPluginThumbnails(option)%20%7B%0A%09return%20(art)%20%3D%3E%20%7B%0A%09%09art.controls.add(%7B%0A%09%09%09name%3A%20%27thumbnails%27%2C%0A%09%09%09position%3A%20%27top%27%2C%0A%09%09%09index%3A%2020%2C%0A%09%09%09mounted%3A%20(%24control)%20%3D%3E%20%7B%0A%09%09%09%09const%20%7B%0A%09%09%09%09%09template%3A%20%7B%20%24progress%20%7D%2C%0A%09%09%09%09%09events%3A%20%7B%20proxy%20%7D%2C%0A%09%09%09%09%09constructor%3A%20%7B%20utils%3A%20%7B%20setStyle%2C%20clamp%20%7D%20%7D%0A%09%09%09%09%7D%20%3D%20art%3B%0A%0A%09%09%09%09const%20cache%20%3D%20%5B%5D%3B%0A%09%09%09%09const%20%7B%20urls%2C%20width%2C%20height%20%7D%20%3D%20option%3B%0A%09%09%09%09setStyle(%24control%2C%20%27display%27%2C%20%22none%22)%3B%0A%09%09%09%09setStyle(%24control%2C%20%27height%27%2C%20%60%24%7Bheight%7Dpx%60)%3B%0A%09%09%09%09setStyle(%24control%2C%20%27width%27%2C%20%60%24%7Bwidth%7Dpx%60)%3B%0A%09%09%09%09setStyle(%24control%2C%20%27backgroundSize%27%2C%20%22contain%22)%3B%0A%0A%09%09%09%09proxy(%24progress%2C%20%27mousemove%27%2C%20(event)%20%3D%3E%20%7B%0A%09%09%09%09%09setStyle(%24control%2C%20%27display%27%2C%20%27block%27)%3B%0A%09%09%09%09%09const%20%7B%20left%3A%20progressLeft%2C%20width%3A%20progressWidth%20%7D%20%3D%20%24progress.getBoundingClientRect()%3B%0A%09%09%09%09%09const%20eventLeft%20%3D%20clamp(event.pageX%20-%20progressLeft%2C%200%2C%20progressWidth)%3B%0A%09%09%09%09%09const%20perWidth%20%3D%20progressWidth%20%2F%20urls.length%3B%0A%09%09%09%09%09const%20index%20%3D%20clamp(Math.ceil(eventLeft%20%2F%20perWidth)%20-%201%2C%200%2C%20urls.length%20-%201)%3B%0A%0A%09%09%09%09%09if%20(cache%5Bindex%5D)%20%7B%0A%09%09%09%09%09%09if%20(cache%5Bindex%5D.startsWith(%22blob%3A%22))%20%7B%0A%09%09%09%09%09%09%09setStyle(%24control%2C%20%27backgroundImage%27%2C%20%60url(%24%7Bcache%5Bindex%5D%7D)%60)%3B%0A%09%09%09%09%09%09%7D%0A%09%09%09%09%09%7D%20else%20%7B%0A%09%09%09%09%09%09cache%5Bindex%5D%20%3D%20%22loading%22%3B%0A%09%09%09%09%09%09fetch(urls%5Bindex%5D)%0A%09%09%09%09%09%09%09.then(function%20(response)%20%7B%0A%09%09%09%09%09%09%09%09return%20response.blob()%3B%0A%09%09%09%09%09%09%09%7D).then(blob%20%3D%3E%20%7B%0A%09%09%09%09%09%09%09%09cache%5Bindex%5D%20%3D%20URL.createObjectURL(blob)%3B%0A%09%09%09%09%09%09%09%09setStyle(%24control%2C%20%27backgroundImage%27%2C%20%60url(%24%7Bcache%5Bindex%5D%7D)%60)%3B%0A%09%09%09%09%09%09%09%7D)%0A%09%09%09%09%09%7D%0A%0A%09%09%09%09%09if%20(eventLeft%20%3C%3D%20width%20%2F%202)%20%7B%0A%09%09%09%09%09%09setStyle(%24control%2C%20%27left%27%2C%200)%3B%0A%09%09%09%09%09%7D%20else%20if%20(eventLeft%20%3E%20progressWidth%20-%20width%20%2F%202)%20%7B%0A%09%09%09%09%09%09setStyle(%24control%2C%20%27left%27%2C%20%60%24%7BprogressWidth%20-%20width%7Dpx%60)%3B%0A%09%09%09%09%09%7D%20else%20%7B%0A%09%09%09%09%09%09setStyle(%24control%2C%20%27left%27%2C%20%60%24%7BeventLeft%20-%20width%20%2F%202%7Dpx%60)%3B%0A%09%09%09%09%09%7D%0A%09%09%09%09%7D)%3B%0A%0A%09%09%09%09proxy(%24progress%2C%20%27mouseout%27%2C%20()%20%3D%3E%20%7B%0A%09%09%09%09%09setStyle(%24control%2C%20%27display%27%2C%20%27none%27)%3B%0A%09%09%09%09%7D)%3B%0A%09%09%09%7D%2C%0A%09%09%7D)%0A%0A%09%09return%20%7B%0A%09%09%09name%3A%20%27artplayerPluginThumbnails%27%0A%09%09%7D%0A%09%7D%0A%7D)

Thank you very much for the PR, but this is not a common feature, so I don't want to break the previous parameters, so I make this feature into a non-invasive plug-in, not as part of the artplayer core code, thank you again.

**Comment by ErenKrt** [comment]
Thanks you for all support.
