### ISSUE TITLE
Issue with type:'flv'

### ISSUE THREAD

**Issue by qqyuanxinqq** [zhw2590582/ArtPlayer#238]
First, thanks for building this nice tool!
I have some problems on playing *.flv videos. It always failed to connect the source, and then shows "Video Load Failed".  
I have the same problem even using the online demo. (https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.flv%27%2C%0A%20%20%20%20type%3A%20%27flv%27%2C%0A%7D)%3B%0A)

**Comment by zhw2590582** [comment]
You need to import flv.js
https://github.com/Bilibili/flv.js
https://artplayer.org/document/libraries#flvjs
