### ISSUE TITLE
Ass subtitle effect rendering?

### ISSUE THREAD

**Issue by qqyuanxinqq** [zhw2590582/ArtPlayer#239]
Current subtitle only reads the text contents in the *.ass subtitle file. Can the ASS subtitle effect also be rendered? I think the coloring, moving, positioning effects will be very similar to what gets implemented in danmuku.

**Comment by zhw2590582** [comment]
Rendering ass files is a complex issue, and it is difficult for web players to support this
But it is also possible to achieve this: https://github.com/weizhenye/ASS

**Comment by zhw2590582** [comment]
I wrote a plugin function `artplayerPluginAss`: [Demo](https://artplayer.org/?libs=%2Fassets%2Fjs%2FJavascriptSubtitlesOctopus%2Fsubtitles-octopus.js&code=%2F%2F%20https%3A%2F%2Fgithub.com%2Flibass%2FJavascriptSubtitlesOctopus%0A%0Avar%20baseUrl%20%3D%20%22%2Fassets%2Fjs%2FJavascriptSubtitlesOctopus%22%3B%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09plugins%3A%20%5B%0A%09%09artplayerPluginAss(%7B%0A%09%09%09%2F%2F%20debug%3A%20true%2C%0A%09%09%09%2F%2F%20fonts%3A%20%5B%60%24%7BbaseUrl%7D%2FArial.ttf%60%2C%20%60%24%7BbaseUrl%7D%2FTimesNewRoman.ttf%60%5D%2C%0A%09%09%09subUrl%3A%20%60%24%7BbaseUrl%7D%2Ftest.ass%60%2C%0A%09%09%09workerUrl%3A%20%60%24%7BbaseUrl%7D%2Fsubtitles-octopus-worker.js%60%2C%0A%09%09%7D)%0A%09%5D%0A%7D)%3B%0A%0Afunction%20artplayerPluginAss(options)%20%7B%0A%09return%20art%20%3D%3E%20%7B%0A%09%09const%20instance%20%3D%20new%20SubtitlesOctopus(%7B%0A%09%09%09...options%2C%0A%09%09%09video%3A%20art.template.%24video%0A%09%09%7D)%3B%0A%0A%09%09instance.canvasParent.style.zIndex%20%3D%2020%3B%0A%09%09art.on(%27destroy%27%2C%20()%20%3D%3E%20instance.dispose())%3B%0A%0A%09%09return%20%7B%0A%09%09%09name%3A%20%22artplayerPluginAss%22%2C%0A%09%09%09instance%3A%20instance%0A%09%09%7D%0A%09%7D%0A%7D)

You just need to copy the following directories into your project: https://github.com/zhw2590582/ArtPlayer/tree/master/docs/assets/js/JavascriptSubtitlesOctopus

**Comment by qqyuanxinqq** [comment]
Thanks! The plugin works well.
Everything works except... I found that all Chinese characters cannot display...
Although I know this is not relevant to this project, I am wondering if you have any idea on what's going on?

**Comment by zhw2590582** [comment]
You need to load the font files by yourself, but the Chinese font files are too large: [Demo](https://artplayer.org/?libs=%2Fassets%2Fjs%2FJavascriptSubtitlesOctopus%2Fsubtitles-octopus.js&code=%2F%2F%20https%3A%2F%2Fgithub.com%2Flibass%2FJavascriptSubtitlesOctopus%0A%0Avar%20baseUrl%20%3D%20%22%2Fassets%2Fjs%2FJavascriptSubtitlesOctopus%22%3B%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09plugins%3A%20%5B%0A%09%09artplayerPluginAss(%7B%0A%09%09%09%2F%2F%20debug%3A%20true%2C%0A%09%09%09fonts%3A%20%5B%60%24%7BbaseUrl%7D%2FSourceHanSansCN-Medium.otf%60%5D%2C%0A%09%09%09subUrl%3A%20%60%24%7BbaseUrl%7D%2Ftest2.ass%60%2C%0A%09%09%09workerUrl%3A%20%60%24%7BbaseUrl%7D%2Fsubtitles-octopus-worker.js%60%2C%0A%09%09%7D)%0A%09%5D%0A%7D)%3B%0A%0Afunction%20artplayerPluginAss(options)%20%7B%0A%09return%20art%20%3D%3E%20%7B%0A%09%09const%20instance%20%3D%20new%20SubtitlesOctopus(%7B%0A%09%09%09...options%2C%0A%09%09%09video%3A%20art.template.%24video%0A%09%09%7D)%3B%0A%0A%09%09instance.canvasParent.style.zIndex%20%3D%2020%3B%0A%09%09art.on(%27destroy%27%2C%20()%20%3D%3E%20instance.dispose())%3B%0A%0A%09%09return%20%7B%0A%09%09%09name%3A%20%22artplayerPluginAss%22%2C%0A%09%09%09instance%3A%20instance%0A%09%09%7D%0A%09%7D%0A%7D)
