### ISSUE TITLE
如何只关闭移动端下触摸暂停？

### ISSUE THREAD

**Issue by rwshui** [zhw2590582/ArtPlayer#243]
移动端下有时候容易误触屏幕 导致播放暂停了，如何只单单关闭移动端下的触屏暂停？

**Comment by zhw2590582** [comment]
不能在外面关闭，只能修改一下源码，然后再自己打包一下：

https://github.com/zhw2590582/ArtPlayer/blob/b284381534f8d51568a1097be1f1099482b6d136/packages/artplayer/src/player/eventInit.js#L17

```js
import { isMobile } from './utils';

proxy($video, 'click', () => {
    if (!isMobile) {
        art.toggle();
    }
});
```

**Comment by cqsn558** [comment]
在手机全屏时不但容易误点暂停，有时也可能误点进度条。感觉可以参考muiplayer这个js播放器，在使用了他的手机版插件后，全屏时会在控制栏左上方出现一个带锁样式的图标。未点击时是一个开锁的图标，点击一次这个锁就变为已锁的图标，并且隐藏控制栏，再点一次这个锁，锁就变为开锁样式，并且可以显示出控制栏，这个功能确实不错。
![QQ截图20220316194946](https://user-images.githubusercontent.com/39335744/158585066-0271bc15-268c-4327-a520-d622800aef00.png)

**Comment by rwshui** [comment]
> 



> 不能在外面关闭，只能修改一下源码，然后再自己打包一下：
> 
> https://github.com/zhw2590582/ArtPlayer/blob/b284381534f8d51568a1097be1f1099482b6d136/packages/artplayer/src/player/eventInit.js#L17
> 
> ```js
> import { isMobile } from './utils';
> 
> proxy($video, 'click', () => {
>     if (!isMobile) {
>         art.toggle();
>     }
> });
> ```



> 不能在外面关闭，只能修改一下源码，然后再自己打包一下：
> 
> https://github.com/zhw2590582/ArtPlayer/blob/b284381534f8d51568a1097be1f1099482b6d136/packages/artplayer/src/player/eventInit.js#L17
> 
> ```js
> import { isMobile } from './utils';
> 
> proxy($video, 'click', () => {
>     if (!isMobile) {
>         art.toggle();
>     }
> });
> ```

很详细，测试过OK，感谢回复！

**Comment by rwshui** [comment]
> 不能在外面关闭，只能修改一下源码，然后再自己打包一下：
> 
> https://github.com/zhw2590582/ArtPlayer/blob/b284381534f8d51568a1097be1f1099482b6d136/packages/artplayer/src/player/eventInit.js#L17
> 
> ```js
> import { isMobile } from './utils';
> 
> proxy($video, 'click', () => {
>     if (!isMobile) {
>         art.toggle();
>     }
> });
> ```

测试了下OK,很详细，感谢回复！

**Comment by zhw2590582** [comment]
这个加锁功能不错，我后期加入这个

**Comment by zhw2590582** [comment]
提示信息和控制音量这个可以优化，但屏幕亮度是app级别才能实现的

**Comment by cqsn558** [comment]
能上下控制音量也不错，这样手机端与电脑端快捷方式就基本一样了，左右控制进度，上下控制音量。

**Comment by zhw2590582** [comment]
加锁功能已经添加
但音量控制 iOS 设备下是不可用的，这就需要为安卓设备单独设置，为了统一性暂时不添加音量控制
