### ISSUE TITLE
Re-render component remains the div wrapper

### ISSUE THREAD

**Issue by wpplumber** [zhw2590582/ArtPlayer#248]
Thank you for this usefull **Lib** which has a clear **Docs** and **live** player.

After Re-render component using `:key` it remains the wrapper! I tried to use `art.on('destroy', ...` but it gives error.

QQ chat isn't in English! do you have a discord channel?

![image](https://user-images.githubusercontent.com/52907282/160278880-a5c1c740-c54c-483b-8e3a-cde0e1a491d0.png)

**Comment by zhw2590582** [comment]
I don't quite understand what you mean, can you give me some code, or an online demo?

**Comment by wpplumber** [comment]
I couldn't replicate the issue in the sandbox [Artplayer Vue Example](https://codesandbox.io/s/artplayer-vue-demo-forked-0nsn8t?file=/src/App.vue) but locally I have the following code, after a click on an item the videoID get updated and `:key` too which Re-render the component.

After **Re-render** with new _videoID_ the art-player creates other div within the container (div wrapper see the **1st** post screenshot)! only on my local not your live **demo**.

```
<template>
    <Artplayer  @get-instance="getInstance" :option="option" :style="style" />
</template>

<script>
// TypeScript disabled on this component since we need to set
// some custom attributes on the instance which aren't recognized by TypeScript.

import { useStore } from 'src/store/store';
import { defineComponent, computed } from 'vue';
import Artplayer from "artplayer/examples/vue/Artplayer.vue";
```

**Comment by wpplumber** [comment]
I made a fix by using 'destroy' event.
