### ISSUE TITLE
希望能加入弹幕防重叠的功能

### ISSUE THREAD

**Issue by AS042971** [zhw2590582/ArtPlayer#252]
现在的实现逻辑似乎会渲染所有的弹幕。
当弹幕字体过大或可用空间过小时，这样做会导致弹幕之间发生重叠，使观感降低。
希望能增加弹幕防重叠功能，在这种情况下随机丢弃一部分弹幕，优化观感。

**Comment by zhw2590582** [comment]
好建议，目前弹幕插件的功能还是轻量级的，我后面再优化一下
