### ISSUE TITLE
Hls.js Quality Control API Integration with ArtPlayer

### ISSUE THREAD

**Issue by anuzis** [zhw2590582/ArtPlayer#253]
Can ArtPlayer let users select video quality with the Hls.js streaming integration using a single source playlist file?

ArtPlayer quality setting appear to depend on separate URLs for each quality level:
- https://artplayer.org/document/options#quality

Hls.js quality settings adjust from a single source:
- https://github.com/video-dev/hls.js/blob/master/docs/API.md#quality-switch-control-api

This [example code](https://artplayer.org/?libs=https%3A%2F%2Fcdn.bootcss.com%2Fhls.js%2F0.10.1%2Fhls.js&code=var%20hls%20%3D%20null%3B%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fvuclip-eip2.akamaized.net%2F8b1a692f5d8f38901692bf913b8be53d%2Fvp63207_V20210323042603%2Fhlsc_e2931_2.m3u8%27%2C%0A%20%20%20%20customType%3A%20%7B%0A%20%20%20%20%20%20%20%20m3u8%3A%20function%20(video%2C%20url)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%09if%20(hls)%20hls.destroy()%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20hls%20%3D%20new%20Hls()%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20hls.loadSource(url)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20hls.attachMedia(video)%3B%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D%2C%0A%20%20%20%20controls%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20position%3A%20%27right%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%27180p%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20selector%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20%27180p%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20url%3A%20%27https%3A%2F%2Fvuclip-eip2.akamaized.net%2F8b1a692f5d8f38901692bf913b8be53d%2Fvp63207_V20210323042603%2Fhlsc_e2931_2.m3u8%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20%27240p%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20url%3A%20%27https%3A%2F%2Fvuclip-eip2.akamaized.net%2F8b1a692f5d8f38901692bf913b8be53d%2Fvp63207_V20210323042603%2Fhlsc_e2931_3.m3u8%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20onSelect%3A%20function%20(item)%20%7B%0A%09%09%09%09art.switchQuality(item.url%2C%20item.name)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%5D%2C%0A%7D)%3B) has ArtPlayer using Hls.js to adjust video quality, but seems to require separate URLs for each quality level  ( hlsc_e2931_2.m3u8,  hlsc_e2931_3.m3u8, etc. )

Is it possible for ArtPlayer to adjust Hls quality without multiple source playlists?

Thanks for the great software!

**Comment by zhw2590582** [comment]
I don't know much about the interface of hls.js, I just read its documentation and wrote the following example, you can refer to it: [Demo](https://artplayer.org/?libs=https%3A%2F%2Fcdn.bootcss.com%2Fhls.js%2F0.10.1%2Fhls.js&code=var%20hls%20%3D%20null%3B%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27https%3A%2F%2Ftest-streams.mux.dev%2Fx36xhzz%2Fx36xhzz.m3u8%27%2C%0A%09customType%3A%20%7B%0A%09%09m3u8%3A%20function%20(video%2C%20url)%20%7B%0A%09%09%09if%20(hls)%20hls.destroy()%3B%0A%09%09%09hls%20%3D%20new%20Hls()%3B%0A%09%09%09hls.loadSource(url)%3B%0A%09%09%09hls.attachMedia(video)%3B%0A%09%09%7D%2C%0A%09%7D%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%09art.controls.add(%7B%0A%09%09name%3A%20%27hls_levels%27%2C%0A%09%09position%3A%20%27right%27%2C%0A%09%09html%3A%20%27360P%27%2C%0A%09%09selector%3A%20hls.levels.map((item)%20%3D%3E%20%7B%0A%09%09%09return%20%7B%0A%09%09%09%09html%3A%20item.width%20%2B%20%27P%27%2C%0A%09%09%09%09level%3A%200%0A%09%09%09%7D%0A%09%09%7D)%2C%0A%09%09onSelect(item)%20%7B%0A%09%09%09hls.nextLevel%20%3D%20item.level%3B%0A%09%09%09return%20item.html%3B%0A%09%09%7D%2C%0A%09%09mounted()%20%7B%0A%09%09%09%2F%2F%20https%3A%2F%2Fgithub.com%2Fvideo-dev%2Fhls.js%2Fblob%2Fmaster%2Fdocs%2FAPI.md%23runtime-events%0A%09%09%09%2F%2F%20listen%20for%20events%2C%20change%20the%20html%20value%0A%09%09%09const%20%24value%20%3D%20art.query(%27.art-control-hls_levels%20.art-selector-value%27)%3B%0A%09%09%09%2F%2F%20%24value.innerHTML%20%3D%20%27360P%27%3B%0A%0A%09%09%09const%20initCurrentLevel%20%3D%20hls.levels%5Bhls.currentLevel%5D%3B%0A%09%09%09if%20(initCurrentLevel)%20%7B%0A%09%09%09%09%24value.innerHTML%20%3D%20initCurrentLevel.width%20%2B%20%27P%27%3B%0A%09%09%09%7D%0A%0A%09%09%09hls.once(Hls.Events.LEVEL_SWITCHING%2C%20(level)%20%3D%3E%20%7B%0A%09%09%09%09console.log(%27LEVEL_SWITCHING%27%2C%20level)%3B%0A%09%09%09%7D)%3B%0A%0A%09%09%09hls.once(Hls.Events.LEVEL_SWITCHED%2C%20(level)%20%3D%3E%20%7B%0A%09%09%09%09console.log(%27LEVEL_SWITCHED%27%2C%20level)%3B%0A%09%09%09%7D)%3B%0A%0A%09%09%09hls.once(Hls.Events.LEVEL_LOADING%2C%20(level)%20%3D%3E%20%7B%0A%09%09%09%09console.log(%27LEVEL_LOADING%27%2C%20level)%3B%0A%09%09%09%7D)%3B%0A%0A%09%09%09hls.once(Hls.Events.LEVEL_LOADED%2C%20(level)%20%3D%3E%20%7B%0A%09%09%09%09console.log(%27LEVEL_LOADED%27%2C%20level)%3B%0A%09%09%09%7D)%3B%0A%0A%09%09%09hls.once(Hls.Events.LEVEL_UPDATED%2C%20(level)%20%3D%3E%20%7B%0A%09%09%09%09console.log(%27LEVEL_UPDATED%27%2C%20level)%3B%0A%09%09%09%7D)%3B%0A%0A%09%09%09hls.once(Hls.Events.LEVELS_UPDATED%2C%20(level)%20%3D%3E%20%7B%0A%09%09%09%09console.log(%27LEVELS_UPDATED%27%2C%20level)%3B%0A%09%09%09%7D)%3B%0A%09%09%7D%0A%09%7D)%0A%7D))

**Comment by anuzis** [comment]
Thank you, confirming the demo code works well!

**Comment by wpplumber** [comment]
@zhw2590582 is there a possibility to add this custom control as menu item of settings? I tested to push it on `ready` but still on Map object not refreshed on the screen!

**Comment by zhw2590582** [comment]
> @zhw2590582 is there a possibility to add this custom control as menu item of settings? I tested to push it on `ready` but still on Map object not refreshed on the screen!

I am not very understanding what you mean, can you give me a look at your code, or you write a Demo？

**Comment by wpplumber** [comment]
```
        art.on('ready', () => {
          art.playbackRate = props.speed;

console.log('art object')
console.dir(art)
art.setting.option.push(
  {
		tooltip: 'right',
		html: 'Select Quality',
    width: 200,
    icon: '<img width="22" height="22" src="https://artplayer.org/assets/img/indicator.svg">',
		selector: hls.value.levels.map((item, index) => {
			return {
				html: item.height + 'P',
				level: item.level || index
			}
		}),
		onSelect(item) {
			console.log(hls.value, hls.value.levels, item);
			hls.value.nextLevel = item.level;
			return item.html;
		},
		mounted() {
			const $value = art.query('.art-control-hls_levels .art-selector-value');

			function updateHtml() {
				const currentLevel = hls.value.levels[hls.value.currentLevel];
				if (currentLevel) {
					$value.innerHTML = currentLevel.height + 'P';
				}
			}

			hls.value.once(Hls.Events.LEVEL_SWITCHING, (level) => {
				console.log('LEVEL_SWITCHING', level);
				updateHtml();
			});

			hls.value.once(Hls.Events.LEVEL_SWITCHED, (level) => {
				console.log('LEVEL_SWITCHED', level);
				updateHtml();
			});

			hls.value.once(Hls.Events.LEVEL_LOADING, (level) => {
				console.log('LEVEL_LOADING', level);
				updateHtml();
			});

			hls.value.once(Hls.Events.LEVEL_LOADED, (level) => {
				console.log('LEVEL_LOADED', level);
				updateHtml();
			});

			hls.value.once(Hls.Events.LEVEL_UPDATED, (level) => {
				console.log('LEVEL_UPDATED', level);
				updateHtml();
			});

			hls.value.once(Hls.Events.LEVELS_UPDATED, (level) => {
				console.log('LEVELS_UPDATED', level);
				updateHtml();
			});
		}
	}
)

})
```

**Comment by zhw2590582** [comment]
@wpplumber This is a bug, currently it is not possible to create a setting panel asynchronously, I need to update the code, I will write a demo for you after I fix it

**Comment by wpplumber** [comment]
Thank you Harvey Zack

**Comment by zhw2590582** [comment]
@wpplumber You need to install the latest version `4.3.8` using npm: [demo](https://artplayer.org/?libs=https%3A%2F%2Fcdn.bootcss.com%2Fhls.js%2F0.10.1%2Fhls.js&code=var%20hls%20%3D%20null%3B%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27https%3A%2F%2Ftest-streams.mux.dev%2Fx36xhzz%2Fx36xhzz.m3u8%27%2C%0A%09autoSize%3A%20true%2C%0A%09setting%3A%20true%2C%0A%09flip%3A%20true%2C%0A%09playbackRate%3A%20true%2C%0A%09aspectRatio%3A%20true%2C%0A%09customType%3A%20%7B%0A%09%09m3u8%3A%20function%20(video%2C%20url)%20%7B%0A%09%09%09if%20(hls)%20hls.destroy()%3B%0A%09%09%09hls%20%3D%20new%20Hls()%3B%0A%09%09%09hls.loadSource(url)%3B%0A%09%09%09hls.attachMedia(video)%3B%0A%09%09%7D%2C%0A%09%7D%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%09art.setting.add(%7B%0A%09%09width%3A%20200%2C%0A%09%09html%3A%20%27Quality%27%2C%0A%09%09tooltip%3A%20%27360P%27%2C%0A%09%09selector%3A%20hls.levels.map((item%2C%20index)%20%3D%3E%20%7B%0A%09%09%09return%20%7B%0A%09%09%09%09html%3A%20item.height%20%2B%20%27P%27%2C%0A%09%09%09%09level%3A%20item.level%20%7C%7C%20index%0A%09%09%09%7D%0A%09%09%7D)%2C%0A%09%09onSelect%3A%20function%20(item)%20%7B%0A%09%09%09hls.nextLevel%20%3D%20item.level%3B%0A%09%09%09return%20item.html%3B%0A%09%09%7D%2C%0A%09%09mounted(_%2C%20item)%20%7B%0A%09%09%09function%20updateHtml()%20%7B%0A%09%09%09%09const%20currentLevel%20%3D%20hls.levels%5Bhls.currentLevel%5D%3B%0A%09%09%09%09if%20(currentLevel)%20%7B%0A%09%09%09%09%09item.tooltip%20%3D%20currentLevel.height%20%2B%20%27P%27%3B%0A%09%09%09%09%7D%0A%09%09%09%7D%0A%0A%09%09%09hls.on(Hls.Events.LEVEL_SWITCHING%2C%20(res)%20%3D%3E%20%7B%0A%09%09%09%09art.notice.show%20%3D%20%22LEVEL_SWITCHING%22%3B%0A%09%09%09%09console.info(%27LEVEL_SWITCHING%20--%3E%27%2C%20res)%3B%0A%09%09%09%09updateHtml()%3B%0A%09%09%09%7D)%3B%0A%0A%09%09%09hls.on(Hls.Events.LEVEL_SWITCHED%2C%20(res)%20%3D%3E%20%7B%0A%09%09%09%09art.notice.show%20%3D%20%22LEVEL_SWITCHED%22%3B%0A%09%09%09%09console.info(%27LEVEL_SWITCHED%20--%3E%27%2C%20res)%3B%0A%09%09%09%09updateHtml()%3B%0A%09%09%09%7D)%3B%0A%0A%09%09%09hls.on(Hls.Events.LEVEL_LOADING%2C%20(res)%20%3D%3E%20%7B%0A%09%09%09%09art.notice.show%20%3D%20%22LEVEL_LOADING%22%3B%0A%09%09%09%09console.info(%27LEVEL_LOADING%20--%3E%27%2C%20res)%3B%0A%09%09%09%09updateHtml()%3B%0A%09%09%09%7D)%3B%0A%0A%09%09%09hls.on(Hls.Events.LEVEL_LOADED%2C%20(res)%20%3D%3E%20%7B%0A%09%09%09%09art.notice.show%20%3D%20%22LEVEL_LOADED%22%3B%0A%09%09%09%09console.info(%27LEVEL_LOADED%20--%3E%27%2C%20res)%3B%0A%09%09%09%09updateHtml()%3B%0A%09%09%09%7D)%3B%0A%0A%09%09%09hls.on(Hls.Events.LEVEL_UPDATED%2C%20(res)%20%3D%3E%20%7B%0A%09%09%09%09art.notice.show%20%3D%20%22LEVEL_UPDATED%22%3B%0A%09%09%09%09console.info(%27LEVEL_UPDATED%20--%3E%27%2C%20res)%3B%0A%09%09%09%09updateHtml()%3B%0A%09%09%09%7D)%3B%0A%0A%09%09%09hls.on(Hls.Events.LEVELS_UPDATED%2C%20(res)%20%3D%3E%20%7B%0A%09%09%09%09art.notice.show%20%3D%20%22LEVELS_UPDATED%22%3B%0A%09%09%09%09console.info(%27LEVELS_UPDATED%20--%3E%27%2C%20res)%3B%0A%09%09%09%09updateHtml()%3B%0A%09%09%09%7D)%3B%0A%09%09%7D%0A%09%7D)%0A%7D)%3B)
