### ISSUE TITLE
弹幕插件参数范围设置不合理

### ISSUE THREAD

**Issue by AS042971** [zhw2590582/ArtPlayer#254]
1. 弹幕的上下边距被设置为最多100像素。
https://github.com/zhw2590582/ArtPlayer/blob/54882b4e25e12019f4eb6b7407529f104f63ca1f/packages/artplayer-plugin-danmuku/src/danmuku.js#L83-L84
然而，这样的限制在很多情况下均无法满足要求。例如，对于1080像素高度的屏幕全屏播放时，若希望实现半屏弹幕的效果，下边距至少需要500像素。
建议将最大值限制为视频高度。同时，在视频resize事件发生时，建议自动根据视频的高度变化调整这两个参数的值。
进一步地，建议支持百分比输入。当检测到百分比格式文本时，程序可根据当前视频高度自动计算。
比如希望类似 `margin: [0, "50%"]` 的设置就可以实现半屏弹幕的功能。

2. 字体大小被设置为12-30像素
https://github.com/zhw2590582/ArtPlayer/blob/54882b4e25e12019f4eb6b7407529f104f63ca1f/packages/artplayer-plugin-danmuku/src/danmuku.js#L86
然而实际很可能需要更大的弹幕(30~50像素，尤其是在全屏情况下)，希望能调整这里的限制。

**Comment by zhw2590582** [comment]
可以加入后期优化计划

**Comment by zhw2590582** [comment]
在`4.3.12`中已实现
