### ISSUE TITLE
Question: How to delete a layer from layers list?

### ISSUE THREAD

**Issue by namtx** [zhw2590582/ArtPlayer#255]
I have a usecase that, after showing the layer 10 seconds, I want to automatically remove (or hide) that layer.
Is that API supported?

**Comment by zhw2590582** [comment]
This is not difficult to do: [demo](https://artplayer.org/?libs=&code=var%20img%20%3D%20%27%2Fassets%2Fsample%2Flayer.png%27%3B%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09layers%3A%20%5B%0A%09%09%7B%0A%09%09%09name%3A%20%27poster%27%2C%0A%09%09%09html%3A%20%60%3Cimg%20style%3D%22width%3A%20100px%22%20src%3D%22%24%7Bimg%7D%22%3E%60%2C%0A%09%09%09style%3A%20%7B%0A%09%09%09%09position%3A%20%27absolute%27%2C%0A%09%09%09%09top%3A%20%2720px%27%2C%0A%09%09%09%09right%3A%20%2720px%27%2C%0A%09%09%09%09opacity%3A%20%27.9%27%2C%0A%09%09%09%7D%2C%0A%09%09%09mounted(poster)%20%7B%0A%09%09%09%09setTimeout(()%20%3D%3E%20%7B%0A%09%09%09%09%09poster.style.display%20%3D%20%27none%27%3B%0A%09%09%09%09%7D%2C%2010000)%0A%09%09%09%7D%2C%0A%09%09%7D%2C%0A%09%5D%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%09setTimeout(()%20%3D%3E%20%7B%0A%09%09%2F%2F%20or%20like%20this%0A%09%09%2F%2F%20art.layers.poster.style.display%20%3D%20%27none%27%3B%0A%09%7D%2C%2010000)%0A%7D))

**Comment by namtx** [comment]
Amazing! thanks for your hard work.
