### ISSUE TITLE
可以实现在移动设备全屏情况下对字幕的支持吗？

### ISSUE THREAD

**Issue by oyjcmyn** [zhw2590582/ArtPlayer#259]
如，要IOS设备下，当全屏时，还可以显示字幕和切换字幕。
如下图：使用的是video.js 播放器，全屏情况下可以显示和选择字幕。
![WechatIMG45](https://user-images.githubusercontent.com/24839942/164424076-9f3489f9-9ee5-458f-b4bf-496f34fa9adf.jpeg)

目前IOS设备，和大多数安卓设备中浏览器都支持。个别国内浏览器不太支持（如QQ浏览器）

**Comment by zhw2590582** [comment]
这个有意思，我研究一下

**Comment by oyjcmyn** [comment]
http://gg.gg/ynzzd 这个地址

**Comment by JLdev0** [comment]
I am also having this issue, subtitles don't appear in mobile videos when in fullscreen. Is there an ETA on this?

**Comment by NADESHIKON** [comment]
@zhw2590582 iOS好像可以自动显示<track>里面的字幕 但是Artplayer貌似把track的kind设置成了metadata导致iOS全屏不显示字幕?

**Comment by NADESHIKON** [comment]
> @zhw2590582 iOS好像可以自动显示里面的字幕 但是Artplayer貌似把track的kind设置成了metadata导致iOS全屏不显示字幕?

因为Artplayer貌似是把字幕用emit提取出来放到另外一个div实时显示 但是如果iOS进入了全屏之后就只会显示<video>的部分了

**Comment by zhw2590582** [comment]
@JLdev0 When I started writing, I didn't know that IOS had this multi-subtitle switching function. It would be a bit complicated to adjust it. I will see how to do it later.

@NADESHIKON 开始写的时候，不知道IOS有这个多字幕切换功能，调整的话会有点复杂，我后面看看怎么弄

**Comment by NADESHIKON** [comment]
> @JLdev0 When I started writing, I didn't know that IOS had this multi-subtitle switching function. It would be a bit complicated to adjust it. I will see how to do it later.
> 
> @NADESHIKON 开始写的时候，不知道IOS有这个多字幕切换功能，调整的话会有点复杂，我后面看看怎么弄

好的 或者也可以像videojs一样弄一个伪全屏
https://videojs.com/guides/options/#preferfullwindow

**Comment by zhw2590582** [comment]
@NADESHIKON 这是网页全屏吧：https://artplayer.org/document/zh-cn/propertie#fullscreenweb

**Comment by NADESHIKON** [comment]
> @NADESHIKON 这是网页全屏吧：https://artplayer.org/document/zh-cn/propertie#fullscreenweb

但是fullscreenWeb会让iOS全屏的时候接管 而videojs的这个选项不会

**Comment by NADESHIKON** [comment]
> > @NADESHIKON 这是网页全屏吧：https://artplayer.org/document/zh-cn/propertie#fullscreenweb
> 
> 但是fullscreenWeb会让iOS全屏的时候接管 而videojs的这个选项不会

这种伪全屏也有一个好处就是可以显示弹幕

**Comment by zhw2590582** [comment]
@NADESHIKON 我看了下videojs的源码，这个选项的意思是，是否在不支持系统级别的视频全屏时，降级使用网页全屏
这其实和`fullscreenweb`差不多，只是我这边没有这个降级，而是区分了`fullscreen`和`fullscreenweb`，还是说你希望添加这个降级功能？

**Comment by NADESHIKON** [comment]
> @NADESHIKON 我看了下videojs的源码，这个选项的意思是，是否在不支持系统级别的视频全屏时，降级使用网页全屏 这其实和`fullscreenweb`差不多，只是我这边没有这个降级，而是区分了`fullscreen`和`fullscreenweb`，还是说你希望添加这个降级功能？

抱歉是我弄混了。。 我不知道为什么iPad不会显示fullscreenWeb的icon

**Comment by NADESHIKON** [comment]
> @NADESHIKON 我看了下videojs的源码，这个选项的意思是，是否在不支持系统级别的视频全屏时，降级使用网页全屏 这其实和`fullscreenweb`差不多，只是我这边没有这个降级，而是区分了`fullscreen`和`fullscreenweb`，还是说你希望添加这个降级功能？

那请问是否可以做到让desktop开fullscreen的时候是全屏而mobile则是fullscreenWeb的behavior

**Comment by zhw2590582** [comment]
@NADESHIKON 你可以在写配置的时候用`Artplayer.utils.isMobile`判断一下: [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20fullscreen%3A%20!Artplayer.utils.isMobile%2C%0A%20%20%20%20fullscreenWeb%3A%20Artplayer.utils.isMobile%2C%0A%7D)%3B)

**Comment by zhw2590582** [comment]
在`4.5.5`版本里添加了`IOS`全屏下的字幕支持，但目前只支持单个字幕选择
