### ISSUE TITLE
全屏时可以隐藏底部控制栏吗?

### ISSUE THREAD

**Issue by how4ever** [zhw2590582/ArtPlayer#26]
现在点全屏时, 控制栏还是会在底部一直显示. 
有没有什么属性设置, 可以在全屏时自动隐藏控制栏,
鼠标移动时再显示出来, 等几秒后再自动隐藏, 就和其他播放器的全屏时控制那样.

**Comment by zhw2590582** [comment]
@how4ever 其实全屏时已经是会自动隐藏控制栏的，前提条件是播放中，你试试即全屏又播放中。
