### ISSUE TITLE
Subtitles sentences are randomly lost

### ISSUE THREAD

**Issue by Howard20181** [zhw2590582/ArtPlayer#275]
### Expected behaviour
Subtitles display normally
### Actual behaviour
Subtitles not fully displayed, sometimes missing a few sentences
### Steps to reproduce
<details>

```
var art = new Artplayer({
            container: '.artplayer-app',
            url: '/video/rickroll/video.mp4',
            title: 'Never Gonna Give You Up',
            isLive: false,
            muted: true,
            autoplay: true,
            pip: true,
            autoSize: false,
            autoMini: true,
            screenshot: true,
            setting: true,
            loop: true,
            flip: true,
            playbackRate: true,
            aspectRatio: true,
            fullscreen: true,
            fullscreenWeb: true,
            subtitleOffset: false,
            miniProgressBar: true,
            mutex: true,
            backdrop: true,
            playsInline: true,
            autoPlayback: true,
            lang: navigator.language.toLowerCase(),
            whitelist: ['*'],
            moreVideoAttr: {
                crossOrigin: 'anonymous',
            },
            quality: [{
                    default: true,
                    html: 'SD 480P',
                    url: '/video/rickroll/video-480p.mp4',
                },
                {
                    html: 'HD 720P',
                    url: '/video/rickroll/video-720p.mp4',
                },
                {
                    html: 'UHD 1080P',
                    url: '/video/rickroll/video.mp4',
                },
            ],
            subtitle: {
                url: '/video/rickroll/subtitle.srt',
                type: 'srt',
                encoding: 'utf-8',
            },
        });
```

</details>

### Environment

-   Browser: Microsoft Edge
-   Version: 100.0.1185.50
-   Operating System: Windows 11 22000.613
-   Version: 22000.613

### Console errors (if any)
null
### Link to where the bug is happening
[subtitle.zip](https://github.com/zhw2590582/ArtPlayer/files/8596513/subtitle.zip)

<details>
<summary>video</summary>

https://user-images.githubusercontent.com/40033067/166099560-b4b0728e-fdaf-42f0-a511-ebb74cc9e620.mp4

</details>

**Comment by Howard20181** [comment]
![image](https://user-images.githubusercontent.com/40033067/166099804-a0cc2571-e3cc-4ecb-b033-a78c2ca948b4.png)

It appears that statements with a subtitle time milliseconds greater than 3 bits are discarded

**Comment by zhw2590582** [comment]
It seems that the srt subtitle parsing is a bit of a compatibility problem, I will fix it in the next version, thank you for your feedback

**Comment by Howard20181** [comment]
中文

实际上
并不确定srt是否支持超过3位毫秒的精度
这个字幕是从哔哩哔哩下载转换的
可能是在一句内前后毫秒数位数相同就可以？
就是不应该混合3位和6位

**Comment by zhw2590582** [comment]
我刚刚已经修复了，但还没发到npm，你可以直接下载下面这个文件测试一下。
https://github.com/zhw2590582/ArtPlayer/blob/master/packages/artplayer/dist/artplayer.js

**Comment by Howard20181** [comment]
我发现xysubfilter超过3位就坏了
所以不确定这是不是一个bug

![image](https://user-images.githubusercontent.com/40033067/166101411-e31376ad-6672-4506-bf8a-df6815f9a271.png)

**Comment by zhw2590582** [comment]
也不算bug，只是不规范，我刚是把超过3位的毫秒直接删掉了

**Comment by Howard20181** [comment]
> 我刚刚已经修复了，但还没发到npm，你可以直接下载下面这个文件测试一下。 https://github.com/zhw2590582/ArtPlayer/blob/master/packages/artplayer/dist/artplayer.js

测试没问题
