### ISSUE TITLE
播放的文件中途切换分辨率就无法播放了

### ISSUE THREAD

**Issue by KNaiFen** [zhw2590582/ArtPlayer#276]
有些视频前半截是竖屏后半截是横屏，然后artplayer放到后半截就报错了

**Comment by zhw2590582** [comment]
artplayer只是在原生的video标签里，加了几个美化UI的div，播放器本身不涉及到任何解码功能的，播放不了大概率是浏览器不支持你这个视频

**Comment by KNaiFen** [comment]
好的，了解




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Harvey ***@***.***&gt;; 
发送时间: 2022年4月30日(星期六) 晚上8:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhw2590582/ArtPlayer] 播放的文件中途切换分辨率就无法播放了 (Issue #276)





 
artplayer只是在原生的video标签里，加了几个美化UI的div，播放器本身不涉及到任何解码功能的，播放不了大概率是浏览器不支持你这个视频
