### ISSUE TITLE
Is it support with Vue 3 SSR ?

### ISSUE THREAD

**Issue by sikeat7** [zhw2590582/ArtPlayer#277]
Hi! I have implementation ArtPlayer with Nuxt3 SSR but it not working. Does it support vue 3 ssr yet ? Thank you.

**Comment by zhw2590582** [comment]
I'm not very familiar with Nuxt3, I wrote a simple example, you can refer to it
[https://github.com/zhw2590582/artplayer-nuxt3](https://github.com/zhw2590582/artplayer-nuxt3)

**Comment by sikeat7** [comment]
> I'm not very familiar with Nuxt3, I wrote a simple example, you can refer to it https://github.com/zhw2590582/artplayer-nuxt3

Thank you It's working but my Hls video has subtitles, qualities and audio combined but it's not shown. Does it support this feature ? Appreciated.

**Comment by zhw2590582** [comment]
Yes, you can take a look at this: https://github.com/zhw2590582/ArtPlayer/issues/253
