### ISSUE TITLE
调整弹幕大小后行距未发生变化

### ISSUE THREAD

**Issue by AS042971** [zhw2590582/ArtPlayer#278]
使用了`v4.3.13`的主程序和弹幕插件。
当尝试通过 `art.plugins.artplayerPluginDanmuku.config({ fontSize: size });` 指令调整弹幕大小时，弹幕字体大小的确会按照设定值变化，但弹幕之间的行间距却保持不变。
这导致了从大字号变到小字号时，弹幕间会产生较大的间隔；反之弹幕边缘又会重叠在一起，影响观感。

目前测试通过切换全屏可以使弹幕的行间距恢复正常。希望能在设置弹幕字体大小后自动执行类似的刷新操作。

**Comment by zhw2590582** [comment]
目前弹幕插件的功能还没做到各种场合的防重叠，你获取可以找第三方的成熟的弹幕插件来结合到播放器上先，我后续有时间再更新

**Comment by AS042971** [comment]
经测试已解决
(但好像又出现重叠在一行的情况了)

**Comment by zhw2590582** [comment]
有没有demo可以看看
