### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by AlkenD** [zhw2590582/ArtPlayer#281]
I was planning to go ahead and start using the ArtPlayer with next.js with ts and it just wouldn't work can you try to add typescript support cause without that i am not able to use it in my project. Btw thank you for building such an amazing video player.

**Comment by zhw2590582** [comment]
Did you mean this ?
https://github.com/zhw2590582/ArtPlayer/blob/master/packages/artplayer/types/artplayer.d.ts

**Comment by AlkenD** [comment]
> Did you mean this ? https://github.com/zhw2590582/ArtPlayer/blob/master/packages/artplayer/types/artplayer.d.ts

Can you create a demo if possible with next.js and ts

**Comment by zhw2590582** [comment]
Yes, I chose an official typescript template: 

https://nextjs.org/learn/basics/create-nextjs-app/setup
`npx create-next-app test use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/typescript-final"`

https://github.com/zhw2590582/artplayer-nextjs-ts

**Comment by AlkenD** [comment]
i am using the base template 
`npx create-next-app@latest --ts`

https://nextjs.org/docs/basic-features/typescript

and its throwing me this error 

ArtPlayerError: Cannot mount multiple instances on the same dom element

**Comment by zhw2590582** [comment]
You update the `artplayer` to `4.3.17`.

Then change the `ArtPlayer.tsx` file:
```tsx
import { useEffect, useRef } from "react";
import Artplayer from "artplayer";

export default function ({ option, getInstance, ...rest }: any) {
  const artRef = useRef();

  useEffect(() => {
    const art = new Artplayer({
      ...option,
      container: artRef.current,
    });

    if (getInstance && typeof getInstance === "function") {
      getInstance(art);
    }

    return () => {
      if (art && art.destroy) {
        art.destroy(false);
      }
    };
  }, []);

  return <div ref={artRef} {...rest}></div>;
}
```

**Comment by AlkenD** [comment]
Thank you

**Comment by TinsFox** [comment]
> Yes, I chose an official typescript template:
> 
> https://nextjs.org/learn/basics/create-nextjs-app/setup `npx create-next-app artplayer-nextjs-ts use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/typescript-final"`
> 
> https://github.com/zhw2590582/artplayer-nextjs-ts

hey, zhw.  This [repository](https://github.com/zhw2590582/artplayer-nextjs-ts) was deleted, can you restore it? Or I want to know how getInstance is written. thank you for your help

**Comment by TinsFox** [comment]
> > Yes, I chose an official typescript template:
> > https://nextjs.org/learn/basics/create-nextjs-app/setup `npx create-next-app artplayer-nextjs-ts use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/typescript-final"`
> > https://github.com/zhw2590582/artplayer-nextjs-ts
> 
> hey, zhw. This [repository](https://github.com/zhw2590582/artplayer-nextjs-ts) was deleted, can you restore it? Or I want to know how getInstance is written. thank you for your help

I get the code in doc. Thanks for your project
