### ISSUE TITLE
New languages (pl, cs)

### ISSUE THREAD

**Issue by Daxxxis** [zhw2590582/ArtPlayer#282]
Hi. I would like to add two languages (pl and cs), but I don't know exactly where to do this. Could I have additional info about this?

**Comment by zhw2590582** [comment]
Here are two ways to add your favorite language

1. Add outside the Artplayer, so there is no need to modify the source code of the Artplayer.
You just need to translate the json fields below into your language --> [Checkout the demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09lang%3A%20%27pl%27%2C%0A%7D)%3B%0A%0Aart.i18n.update(%7B%0A%09%27pl%27%3A%20%7B%0A%09%09%22Play%22%3A%20%22bawi%C4%87%20si%C4%99%22%2C%0A%09%09%22Pause%22%3A%20%22pauza%22%2C%0A%09%09%2F%2F%20...%0A%09%7D%2C%0A%09%27cs%27%3A%20%7B%0A%09%09%2F%2F%0A%09%7D%2C%0A%7D)%3B)
https://github.com/zhw2590582/ArtPlayer/blob/master/packages/artplayer/src/i18n/zh-cn.json

2. You can translate the json file, name it `pl.json`, and put it in the following directory
https://github.com/zhw2590582/ArtPlayer/tree/master/packages/artplayer/src/i18n
Then modify the following file
https://github.com/zhw2590582/ArtPlayer/blob/master/packages/artplayer/src/i18n/index.js

```js
import pl from './pl.json';
import cs from './cs.json';

this.languages = {
   pl: pl,
   cs: cs
};
```
