### ISSUE TITLE
Custom button in the controls won't update state on toggle.

### ISSUE THREAD

**Issue by AlkenD** [zhw2590582/ArtPlayer#284]
### Expected behaviour

I'm currently working to revamping the ui and adding playlist functionality to the player.

https://imgur.com/a/IVkxOjh 

and i couldn't get a proper grip oh how do i add another menu instead of the settings menu to allow this ui idea hence i'm creating a completely independent component and then toggling the visibility on click

Here is a simple function

  const [show, setShow] = React.useState(false);
  const handleShow = () => setShow(!show);

it works if i use a normal button outside the player by showing or hiding the playlist component

### Actual behaviour

But instead it always returns true therefore not updating the state

### Steps to reproduce

    controls: [
      {
        tooltip: 'Playlist',
        position: 'right',
        html: 'icon,
        click: function (_, event) {
          handleShow(event)
        },
      },
  ],

### Environment

-   Browser: Brave
-   Version: [Version 1.38.109 Chromium: 101.0.4951.41 (Official Build) (x86_64)](https://brave.com/latest/)
-   Operating System: macOS
-   Version: 12.3.1

### Console errors (if any)

none

### Link to where the bug is happening

local development

Note: If possible can you make the playlist a native feature in artplayer with next and prev functionality.

**Comment by zhw2590582** [comment]
Because artplayer is not a reaction player, when you click the control, the state `show` of the App component will change, and the Artplayer component will re-render too, then the player will be re-instantiated again `new Artplayer`

If you want the Artplayer component to render only once, you can use `React.memo`

```jsx
import { useEffect, useRef, memo } from "react";
import Artplayer from "artplayer";

export default memo(
  function ({ option, getInstance, ...rest }) {
    const artRef = useRef();

    useEffect(() => {
      const art = new Artplayer({
        ...option,
        container: artRef.current
      });

      if (getInstance && typeof getInstance === "function") {
        getInstance(art);
      }

      return () => {
        if (art && art.destroy) {
          art.destroy(false);
        }
      };
    }, [option, getInstance]);

    return <div ref={artRef} {...rest}></div>;
  },
  () => true
);
```

```jsx
import React, { useState } from "react";
import Artplayer from "./ArtPlayer";

function App() {
  const [show, setShow] = useState(false);

  const option = {
    url: "https://artplayer.org/assets/sample/video.mp4",
    controls: [
      {
        tooltip: "Playlist",
        position: "right",
        html: "icon",
        click: function () {
          setShow((state) => !state);
        }
      }
    ]
  };

  return (
    <div>
      <Artplayer
        option={option}
        style={{
          width: "600px",
          height: "400px",
          margin: "60px auto 0"
        }}
        getInstance={(art) => console.log(art)}
      />
    </div>
  );
}

export default App;
```
