### ISSUE TITLE
Unexpected token on vue nuxtjs

### ISSUE THREAD

**Issue by major-major-major** [zhw2590582/ArtPlayer#291]
Getting the following using nuxt 2.15.8, vue 2.6.12 using the vue example

`ERROR  in ./node_modules/artplayer/dist/artplayer.js                                                                                                    
Module parse failed: Unexpected token (7:67600)                                                                                                          
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders`

**Comment by zhw2590582** [comment]
Have you referenced the code below ? I test it's fine
https://github.com/zhw2590582/ArtPlayer/tree/master/packages/artplayer-template/nuxt.js

**Comment by major-major-major** [comment]
Changing the version resolved it. Thank you! :)
