### ISSUE TITLE
Multiple videos 

### ISSUE THREAD

**Issue by Jopchumba** [zhw2590582/ArtPlayer#293]
In the options you provide the url for video resource is it possible to have multiple videos url as an array and move to the next video.

**Comment by zhw2590582** [comment]
Like an automatic playlist: [demo](https://artplayer.org/?libs=&code=var%20index%20%3D%200%3B%0A%0Avar%20list%20%3D%20%5B%0A%09%27%2Fassets%2Fsample%2Fvideo.mp4%3Ft%3D1%27%2C%0A%09%27%2Fassets%2Fsample%2Fvideo.mp4%3Ft%3D2%27%2C%0A%09%27%2Fassets%2Fsample%2Fvideo.mp4%3Ft%3D3%27%2C%0A%5D%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20list%5Bindex%5D%2C%0A%7D)%3B%0A%0Afunction%20playNext()%20%7B%0A%09index%20%2B%3D%201%3B%0A%09var%20url%20%3D%20list%5Bindex%5D%0A%0A%09if%20(url)%20%7B%0A%09%09%2F%2F%20play%20next%0A%09%09art.switchUrl(url)%0A%09%7D%20else%20%7B%0A%09%09%2F%2F%20play%20first%0A%09%09index%20%3D%200%3B%0A%09%09art.switchUrl(list%5Bindex%5D)%0A%09%7D%0A%0A%09art.seek%20%3D%200%3B%0A%09art.play()%3B%0A%7D%0A%0Aart.on(%27video%3Aended%27%2C%20playNext))
