### ISSUE TITLE
[FR] Set subtitle font size according to player height

### ISSUE THREAD

**Issue by Howard20181** [zhw2590582/ArtPlayer#294]
字幕大小能不能设置一个高度而不是字体大小，比如这个高度是视频高度的10%（可更改）
需要一个接口在resize后重调整，全屏和非全屏的字幕大小需要调整

**Comment by zhw2590582** [comment]
可以监听 `resize` 事件再调整字体大小，你可以参考一下: [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09autoSize%3A%20true%2C%0A%09fullscreen%3A%20true%2C%0A%09fullscreenWeb%3A%20true%2C%0A%09subtitle%3A%20%7B%0A%09%09url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.srt%27%2C%0A%09%7D%2C%0A%7D)%3B%0A%0Afunction%20resizeFontSize()%20%7B%0A%09art.subtitle.style(%7B%0A%09%09fontSize%3A%20%60%24%7Bart.height%20*%200.05%7Dpx%60%2C%0A%09%7D)%0A%7D%0A%0Aart.on(%27ready%27%2C%20resizeFontSize)%3B%0Aart.on(%27resize%27%2C%20resizeFontSize)%3B)

**Comment by Howard20181** [comment]
ok
