### ISSUE TITLE
Instead of the controls appearing, the entire video is downloaded

### ISSUE THREAD

**Issue by Daxxxis** [zhw2590582/ArtPlayer#300]
When the page is loaded, artplayer downloads entire video instead of buffering it on the fly. Artplayer controls appear only after the complete download. When you try to play large files, it will take a few minutes for controls to apper

**Comment by zhw2590582** [comment]
Yes, I noticed this, I will fix it in the next version

**Comment by zhw2590582** [comment]
Fixed

**Comment by Daxxxis** [comment]
There seems to be an additional related issue. The controls appear immediately, but the entire video is downloaded anyway (the video length is 00:00 until all is downloaded). Sometimes a page refresh solves this

**Comment by zhw2590582** [comment]
The player will not actively download the entire video, and the player does not have this function. But you can set the preload attribute to try

```js
var art = new Artplayer({
    container: '.artplayer-app',
    url: '/assets/sample/video.mp4',
    moreVideoAttr: {
		preload: 'none', // auto, metadata, none
	}
});
```

**Comment by Daxxxis** [comment]
No, no, no. I mean, the player gets stuck like this until it downloads all of the video. Normal <video> tag works fine
![image](https://user-images.githubusercontent.com/60961958/169672784-e9b35ac1-9328-49ee-b9b7-f7a92aae8fc0.png)

**Comment by zhw2590582** [comment]
what is your url, let me check

**Comment by Daxxxis** [comment]
My page is hosted on https://miraculum.ml/

**Comment by zhw2590582** [comment]
I can't reproduce your problem on my site, everything looks normal: [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27https%3A%2F%2Fmiraculum-host.ml%2Fmiraculum%2Fs1%2Fpl%2F125.mp4%27%2C%0A%09moreVideoAttr%3A%20%7B%0A%09%09preload%3A%20%27auto%27%0A%09%7D%0A%7D)%3B%0A%0A%2F%2F%20const%20%24video%20%3D%20document.createElement(%27video%27)%3B%0A%2F%2F%20const%20%24app%20%3D%20document.querySelector(%27.artplayer-app%27)%3B%0A%2F%2F%20%24app.appendChild(%24video)%3B%0A%2F%2F%20%24video.src%20%3D%20%27https%3A%2F%2Fmiraculum-host.ml%2Fmiraculum%2Fs1%2Fpl%2F125.mp4%27%3B%0A%2F%2F%20%24video.preload%20%3D%20%27auto%27%3B%0A%2F%2F%20%24video.controls%20%3D%20true%3B%0A%2F%2F%20%24video.width%20%3D%20400%3B%0A%2F%2F%20%24video.height%20%3D%20300%3B)

https://user-images.githubusercontent.com/5907357/169673794-ed6e7ae4-d51e-4d1f-843f-bb5b974eb809.mov

**Comment by Daxxxis** [comment]
Same for me on your page
![msedge_5mzIzS7I9U](https://user-images.githubusercontent.com/60961958/169673873-76d09f50-3c56-415c-ac0d-a72383e78290.gif)

**Comment by zhw2590582** [comment]
Try opening this link: [demo](https://artplayer.org/?libs=&code=const%20%24video%20%3D%20document.createElement(%27video%27)%3B%0Aconst%20%24app%20%3D%20document.querySelector(%27.artplayer-app%27)%3B%0A%24app.appendChild(%24video)%3B%0A%24video.src%20%3D%20%27https%3A%2F%2Fmiraculum-host.ml%2Fmiraculum%2Fs1%2Fpl%2F125.mp4%27%3B%0A%24video.preload%20%3D%20%27auto%27%3B%0A%24video.controls%20%3D%20true%3B%0A%24video.width%20%3D%20400%3B%0A%24video.height%20%3D%20300%3B)

**Comment by Daxxxis** [comment]
Almost instantly
[image](https://user-images.githubusercontent.com/60961958/169674027-9d85268f-b2c2-4216-a450-739f9a2cf842.png)

**Comment by zhw2590582** [comment]
This is very strange, artplayer only beautifies the UI of the video tag, it will not interfere with the loading of the video

**Comment by Daxxxis** [comment]
Nah, artplayer looks very nice. I guess I will have to endure that strange behavior. Thanks for help
