### ISSUE TITLE
怎么设置自适应宽高

### ISSUE THREAD

**Issue by dage66788** [zhw2590582/ArtPlayer#301]
怎么设置自适应宽高

**Comment by zhw2590582** [comment]
在回调函数里调用`this.autoHeight = true`既可：[demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%7D%2C%20function%20()%20%7B%0A%09this.autoHeight%20%3D%20true%3B%0A%7D)%3B)
