### ISSUE TITLE
Is it possible to have a Mini Player when you scroll out of the browser viewport?

### ISSUE THREAD

**Issue by evidence-sharenet** [zhw2590582/ArtPlayer#302]
<img width="300"  alt="Screenshot 2022-05-25 at 16 02 34" src="https://user-images.githubusercontent.com/92296834/170281816-63a8758b-f469-4f3b-b1a1-e6930cdae51f.png">

Hi.  Is it possible to have a Mini Player when you scroll out of the browser viewport like this video player on investing.com?

I tried doing something as shown below but I doesn't seem to work for me. I'm using Vue.

```
var art = new Artplayer({
    container: '.artplayer-app',
    url: '/assets/sample/video.mp4',
    autoMini: true,
    mini = true;
});

```

**Comment by zhw2590582** [comment]
I tested it and there is no problem: [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20autoMini%3A%20true%2C%0A%7D)%3B%0A%0Adocument.querySelector(%27.part-right%27).style.height%20%3D%20%222000px%22%0Adocument.querySelector(%27.video-wrap%27).style.height%20%3D%20%22400px%22)

**Comment by zhw2590582** [comment]
I reproduced the problem you mentioned, it is a bug, I will fix it in the next version

**Comment by zhw2590582** [comment]
Please update to `4.4.3` version

**Comment by evidence-sharenet** [comment]
I just tested now and it is working brilliantly. Thanks !!...

**Comment by evidence-sharenet** [comment]
Hi @zhw2590582. Is there way to keep the mini player hidden after clicking the close button on the mini player? 

Right now the when you close the mini player and then scroll/move the mouse the mini player automatically pops up back again.

**Comment by zhw2590582** [comment]
@evidence-sharenet [demo](https://artplayer.org/?libs=&code=document.querySelector(%27.part-right%27).style.height%20%3D%20%225000px%22%3B%0Adocument.querySelector(%27.video-wrap%27).style.height%20%3D%20%22400px%22%3B%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09autoMini%3A%20true%2C%0A%7D)%3B%0A%0Aart.proxy(art.template.%24miniClose%2C%20%27click%27%2C%20()%20%3D%3E%20%7B%0A%09art.option.autoMini%20%3D%20false%0A%7D))
