### ISSUE TITLE
Help *.ass not work in my website

### ISSUE THREAD

**Issue by flixmu** [zhw2590582/ArtPlayer#306]
please help me *.ass not work in my website, i don't know where yhe problem.
This my website : https://flixmu.com/player.php

**Comment by zhw2590582** [comment]
I can't open your url, but you can send your ass subtitle file

**Comment by flixmu** [comment]
I use sub from you repo (test.ass)

This my code: https://raw.githubusercontent.com/flixmu/subtitle/main/index.html

**Comment by zhw2590582** [comment]
But I have no problem with the test: [demo](https://artplayer.org/?libs=%2Fassets%2Fjs%2FJavascriptSubtitlesOctopus%2Fsubtitles-octopus.js&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09title%3A%20%27%27%2C%0A%09poster%3A%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fsample%2Fposter.jpg%27%2C%0A%09autoSize%3A%20true%2C%0A%09loop%3A%20true%2C%0A%09mutex%3A%20true%2C%0A%09setting%3A%20true%2C%0A%09flip%3A%20true%2C%0A%09lock%3A%20true%2C%0A%09fastForward%3A%20true%2C%0A%09playbackRate%3A%20true%2C%0A%09aspectRatio%3A%20true%2C%0A%09theme%3A%20%27%23ff0057%27%2C%0A%09fullscreen%3A%20true%2C%0A%09fullscreenWeb%3A%20true%2C%0A%09miniProgressBar%3A%20true%2C%0A%09autoOrientation%3A%20true%2C%0A%09whitelist%3A%20%5B%27*%27%5D%2C%0A%09moreVideoAttr%3A%20%7B%0A%09%09%27x5-video-player-type%27%3A%20%27h5%27%2C%0A%09%09%27x5-video-player-fullscreen%27%3A%20false%2C%0A%09%09%27x5-video-orientation%27%3A%20%27portraint%27%2C%0A%09%09preload%3A%20%22metadata%22%0A%09%7D%2C%0A%09icons%3A%20%7B%0A%09%09loading%3A%20%27%3Cimg%20src%3D%22https%3A%2F%2Fartplayer.org%2Fassets%2Fimg%2Fploading.gif%22%3E%27%2C%0A%09%09state%3A%20%27%3Cimg%20width%3D%22150%22%20heigth%3D%22150%22%20src%3D%22https%3A%2F%2Fartplayer.org%2Fassets%2Fimg%2Fstate.svg%22%3E%27%2C%0A%09%09indicator%3A%20%27%3Cimg%20width%3D%2216%22%20heigth%3D%2216%22%20src%3D%22https%3A%2F%2Fartplayer.org%2Fassets%2Fimg%2Findicator.svg%22%3E%27%2C%0A%09%7D%2C%0A%0A%09settings%3A%20%5B%0A%09%09%7B%0A%09%09%09width%3A%20200%2C%0A%09%09%09html%3A%20%27Subtitles%27%2C%0A%09%09%09tooltip%3A%20%27%E5%8F%8C%E8%AF%AD%27%2C%0A%09%09%09icon%3A%20%27%3Cimg%20width%3D%2222%22%20heigth%3D%2222%22%20src%3D%22https%3A%2F%2Fartplayer.org%2Fassets%2Fimg%2Fsubtitle.svg%22%3E%27%2C%0A%09%09%09selector%3A%20%5B%0A%09%09%09%09%7B%0A%09%09%09%09%09html%3A%20%27Switch%27%2C%0A%09%09%09%09%09switch%3A%20true%2C%0A%09%09%09%09%09tooltip%3A%20%27Show%27%2C%0A%09%09%09%09%09onSwitch%3A%20function%20(item)%20%7B%0A%09%09%09%09%09%09item.tooltip%20%3D%20item.switch%20%3F%20%27Hide%27%20%3A%20%27Show%27%3B%0A%09%09%09%09%09%09art.subtitle.show%20%3D%20!item.switch%3B%0A%09%09%09%09%09%09return%20!item.switch%3B%0A%09%09%09%09%09%7D%2C%0A%09%09%09%09%7D%2C%0A%09%09%09%09%7B%0A%09%09%09%09%09default%3A%20true%2C%0A%09%09%09%09%09html%3A%20%27%E5%8F%8C%E8%AF%AD%27%2C%0A%09%09%09%09%09url%3A%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fjs%2FJavascriptSubtitlesOctopus%2Ftest.ass%27%0A%09%09%09%09%7D%2C%0A%09%09%09%09%7B%0A%09%09%09%09%09html%3A%20%27%E4%B8%AD%E6%96%87%27%2C%0A%09%09%09%09%09url%3A%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fjs%2FJavascriptSubtitlesOctopus%2Ftest.ass%27%0A%09%09%09%09%7D%2C%0A%09%09%09%09%7B%0A%09%09%09%09%09html%3A%20%27%E6%97%A5%E6%96%87%27%2C%0A%09%09%09%09%09url%3A%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fjs%2FJavascriptSubtitlesOctopus%2Ftest.ass%27%0A%09%09%09%09%7D%2C%0A%09%09%09%5D%2C%0A%09%09%09onSelect%3A%20function%20(item)%20%7B%0A%09%09%09%09art.subtitle.switch(item.url%2C%20%7B%0A%09%09%09%09%09name%3A%20item.html%0A%09%09%09%09%7D)%3B%0A%09%09%09%09return%20item.html%3B%0A%09%09%09%7D%2C%0A%09%09%7D%2C%0A%09%5D%2C%0A%09plugins%3A%20%5B%0A%09%09artplayerPluginAss(%7B%0A%09%09%09subUrl%3A%20%60https%3A%2F%2Fartplayer.org%2Fassets%2Fjs%2FJavascriptSubtitlesOctopus%2Ftest.ass%60%2C%0A%09%09%09workerUrl%3A%20%60https%3A%2F%2Fartplayer.org%2Fassets%2Fjs%2FJavascriptSubtitlesOctopus%2Fsubtitles-octopus-worker.js%60%2C%0A%09%09%7D)%0A%09%5D%2C%0A%7D)%3B%0A%0Afunction%20artplayerPluginAss(options)%20%7B%0A%09return%20art%20%3D%3E%20%7B%0A%09%09const%20instance%20%3D%20new%20SubtitlesOctopus(%7B%0A%09%09%09...options%2C%0A%09%09%09video%3A%20art.template.%24video%0A%09%09%7D)%3B%0A%0A%09%09instance.canvasParent.style.zIndex%20%3D%2020%3B%0A%09%09art.on(%27destroy%27%2C%20()%20%3D%3E%20instance.dispose())%3B%0A%0A%09%09return%20%7B%0A%09%09%09name%3A%20%22artplayerPluginAss%22%2C%0A%09%09%09instance%3A%20instance%0A%09%09%7D%0A%09%7D%0A%7D%0A)

**Comment by flixmu** [comment]
should I add the contents of this folder to my site?
/assets/js/JavascriptSubtitlesOctopus/subtitles-octopus.js

**Comment by flixmu** [comment]
And its posible make it sub selector with SubtitlesOctopus?

**Comment by zhw2590582** [comment]
I don't quite understand what you mean

**Comment by flixmu** [comment]
> 

can you use the subtitle selector with SubtitleOctopus?

**Comment by zhw2590582** [comment]
https://github.com/libass/JavascriptSubtitlesOctopus#changing-subtitles

```js
onSelect: function (item) {
    art.plugins.artplayerPluginAss.instance.setSubUrl(item.url);
    return item.html;
},
```

**Comment by flixmu** [comment]
> https://github.com/libass/JavascriptSubtitlesOctopus#changing-subtitles
> 
> ```js
> onSelect: function (item) {
>     art.plugins.artplayerPluginAss.instance.setSubUrl(item.url);
>     return item.html;
> },
> ```

Can you give me full demo on artplayer.org? Thanks

**Comment by zhw2590582** [comment]
[demo](https://artplayer.org/?libs=%2Fassets%2Fjs%2FJavascriptSubtitlesOctopus%2Fsubtitles-octopus.js&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09setting%3A%20true%2C%0A%09settings%3A%20%5B%0A%09%09%7B%0A%09%09%09width%3A%20200%2C%0A%09%09%09html%3A%20%27Subtitles%27%2C%0A%09%09%09tooltip%3A%20%27%E5%8F%8C%E8%AF%AD%27%2C%0A%09%09%09icon%3A%20%27%3Cimg%20width%3D%2222%22%20heigth%3D%2222%22%20src%3D%22https%3A%2F%2Fartplayer.org%2Fassets%2Fimg%2Fsubtitle.svg%22%3E%27%2C%0A%09%09%09selector%3A%20%5B%0A%09%09%09%09%7B%0A%09%09%09%09%09html%3A%20%27Switch%27%2C%0A%09%09%09%09%09switch%3A%20true%2C%0A%09%09%09%09%09tooltip%3A%20%27Show%27%2C%0A%09%09%09%09%09onSwitch%3A%20function%20(item)%20%7B%0A%09%09%09%09%09%09item.tooltip%20%3D%20item.switch%20%3F%20%27Hide%27%20%3A%20%27Show%27%3B%0A%09%09%09%09%09%09art.query(%27.libassjs-canvas-parent%27).style.display%20%3D%20item.switch%20%3F%20%27none%27%20%3A%20%27block%27%3B%0A%09%09%09%09%09%09return%20!item.switch%3B%0A%09%09%09%09%09%7D%2C%0A%09%09%09%09%7D%2C%0A%09%09%09%09%7B%0A%09%09%09%09%09default%3A%20true%2C%0A%09%09%09%09%09html%3A%20%27%E5%8F%8C%E8%AF%AD%27%2C%0A%09%09%09%09%09url%3A%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fjs%2FJavascriptSubtitlesOctopus%2Ftest.ass%27%0A%09%09%09%09%7D%2C%0A%09%09%09%09%7B%0A%09%09%09%09%09html%3A%20%27%E4%B8%AD%E6%96%87%27%2C%0A%09%09%09%09%09url%3A%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fjs%2FJavascriptSubtitlesOctopus%2Ftest.ass%27%0A%09%09%09%09%7D%2C%0A%09%09%09%09%7B%0A%09%09%09%09%09html%3A%20%27%E6%97%A5%E6%96%87%27%2C%0A%09%09%09%09%09url%3A%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fjs%2FJavascriptSubtitlesOctopus%2Ftest.ass%27%0A%09%09%09%09%7D%2C%0A%09%09%09%5D%2C%0A%09%09%09onSelect%3A%20function%20(item)%20%7B%0A%09%09%09%09art.plugins.artplayerPluginAss.instance.setSubUrl(item.url)%3B%0A%09%09%09%09return%20item.html%3B%0A%09%09%09%7D%2C%0A%09%09%7D%2C%0A%09%5D%2C%0A%09plugins%3A%20%5B%0A%09%09artplayerPluginAss(%7B%0A%09%09%09subUrl%3A%20%60https%3A%2F%2Fartplayer.org%2Fassets%2Fjs%2FJavascriptSubtitlesOctopus%2Ftest.ass%60%2C%0A%09%09%09workerUrl%3A%20%60https%3A%2F%2Fartplayer.org%2Fassets%2Fjs%2FJavascriptSubtitlesOctopus%2Fsubtitles-octopus-worker.js%60%2C%0A%09%09%7D)%0A%09%5D%2C%0A%7D)%3B%0A%0Afunction%20artplayerPluginAss(options)%20%7B%0A%09return%20art%20%3D%3E%20%7B%0A%09%09const%20instance%20%3D%20new%20SubtitlesOctopus(%7B%0A%09%09%09...options%2C%0A%09%09%09video%3A%20art.template.%24video%0A%09%09%7D)%3B%0A%0A%09%09instance.canvasParent.style.zIndex%20%3D%2020%3B%0A%09%09art.on(%27destroy%27%2C%20()%20%3D%3E%20instance.dispose())%3B%0A%0A%09%09return%20%7B%0A%09%09%09name%3A%20%22artplayerPluginAss%22%2C%0A%09%09%09instance%3A%20instance%0A%09%09%7D%0A%09%7D%0A%7D)

**Comment by flixmu** [comment]
I try with my subtitle `https://raw.githubusercontent.com/flixmu/embed/master/%5BMasanori%5D%20Yatogame-chan%20Kansatsu%20Nikki%20Yonsatsume%20-%2001.ass` and test.ass but not work, not change subtitle when i change

**Comment by zhw2590582** [comment]
[demo](https://artplayer.org/?libs=%2Fassets%2Fjs%2FJavascriptSubtitlesOctopus%2Fsubtitles-octopus.js&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09setting%3A%20true%2C%0A%09settings%3A%20%5B%0A%09%09%7B%0A%09%09%09width%3A%20200%2C%0A%09%09%09html%3A%20%27Subtitles%27%2C%0A%09%09%09tooltip%3A%20%27%E5%8F%8C%E8%AF%AD%27%2C%0A%09%09%09icon%3A%20%27%3Cimg%20width%3D%2222%22%20heigth%3D%2222%22%20src%3D%22https%3A%2F%2Fartplayer.org%2Fassets%2Fimg%2Fsubtitle.svg%22%3E%27%2C%0A%09%09%09selector%3A%20%5B%0A%09%09%09%09%7B%0A%09%09%09%09%09html%3A%20%27Switch%27%2C%0A%09%09%09%09%09switch%3A%20true%2C%0A%09%09%09%09%09tooltip%3A%20%27Show%27%2C%0A%09%09%09%09%09onSwitch%3A%20function%20(item)%20%7B%0A%09%09%09%09%09%09item.tooltip%20%3D%20item.switch%20%3F%20%27Hide%27%20%3A%20%27Show%27%3B%0A%09%09%09%09%09%09art.query(%27.libassjs-canvas-parent%27).style.display%20%3D%20item.switch%20%3F%20%27none%27%20%3A%20%27block%27%3B%0A%09%09%09%09%09%09return%20!item.switch%3B%0A%09%09%09%09%09%7D%2C%0A%09%09%09%09%7D%2C%0A%09%09%09%09%7B%0A%09%09%09%09%09html%3A%20%27Other%20Ass%27%2C%0A%09%09%09%09%09url%3A%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fjs%2FJavascriptSubtitlesOctopus%2Ftest.ass%27%0A%09%09%09%09%7D%2C%0A%09%09%09%5D%2C%0A%09%09%09onSelect%3A%20function%20(item)%20%7B%0A%09%09%09%09console.log(item.url)%3B%0A%09%09%09%09art.plugins.artplayerPluginAss.instance.setTrackByUrl(item.url)%3B%0A%09%09%09%09return%20item.html%3B%0A%09%09%09%7D%2C%0A%09%09%7D%2C%0A%09%5D%2C%0A%09plugins%3A%20%5B%0A%09%09artplayerPluginAss(%7B%0A%09%09%09subUrl%3A%20%60https%3A%2F%2Fraw.githubusercontent.com%2Fflixmu%2Fembed%2Fmaster%2F%255BMasanori%255D%2520Yatogame-chan%2520Kansatsu%2520Nikki%2520Yonsatsume%2520-%252001.ass%60%2C%0A%09%09%09workerUrl%3A%20%60https%3A%2F%2Fartplayer.org%2Fassets%2Fjs%2FJavascriptSubtitlesOctopus%2Fsubtitles-octopus-worker.js%60%2C%0A%09%09%7D)%0A%09%5D%2C%0A%7D)%3B%0A%0Afunction%20artplayerPluginAss(options)%20%7B%0A%09return%20art%20%3D%3E%20%7B%0A%09%09const%20instance%20%3D%20new%20SubtitlesOctopus(%7B%0A%09%09%09...options%2C%0A%09%09%09video%3A%20art.template.%24video%0A%09%09%7D)%3B%0A%0A%09%09instance.canvasParent.style.zIndex%20%3D%2020%3B%0A%09%09art.on(%27destroy%27%2C%20()%20%3D%3E%20instance.dispose())%3B%0A%0A%09%09return%20%7B%0A%09%09%09name%3A%20%22artplayerPluginAss%22%2C%0A%09%09%09instance%3A%20instance%0A%09%09%7D%0A%09%7D%0A%7D)

**Comment by flixmu** [comment]
Great Thanks its work :)
