### ISSUE TITLE
Subtitle *.ass Lag

### ISSUE THREAD

**Issue by flixmu** [zhw2590582/ArtPlayer#308]
Subtitle ass make streaming video lag
[Demo](https://artplayer.org/?libs=%2Fassets%2Fjs%2FJavascriptSubtitlesOctopus%2Fsubtitles-octopus.js&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09setting%3A%20true%2C%0A%09settings%3A%20%5B%0A%09%09%7B%0A%09%09%09width%3A%20200%2C%0A%09%09%09html%3A%20%27Subtitles%27%2C%0A%09%09%09tooltip%3A%20%27%E5%8F%8C%E8%AF%AD%27%2C%0A%09%09%09icon%3A%20%27%3Cimg%20width%3D%2222%22%20heigth%3D%2222%22%20src%3D%22https%3A%2F%2Fartplayer.org%2Fassets%2Fimg%2Fsubtitle.svg%22%3E%27%2C%0A%09%09%09selector%3A%20%5B%0A%09%09%09%09%7B%0A%09%09%09%09%09html%3A%20%27Switch%27%2C%0A%09%09%09%09%09switch%3A%20true%2C%0A%09%09%09%09%09tooltip%3A%20%27Show%27%2C%0A%09%09%09%09%09onSwitch%3A%20function%20(item)%20%7B%0A%09%09%09%09%09%09item.tooltip%20%3D%20item.switch%20%3F%20%27Hide%27%20%3A%20%27Show%27%3B%0A%09%09%09%09%09%09art.query(%27.libassjs-canvas-parent%27).style.display%20%3D%20item.switch%20%3F%20%27none%27%20%3A%20%27block%27%3B%0A%09%09%09%09%09%09return%20!item.switch%3B%0A%09%09%09%09%09%7D%2C%0A%09%09%09%09%7D%2C%0A%09%09%09%09%7B%0A%09%09%09%09%09html%3A%20%27Other%20Ass%27%2C%0A%09%09%09%09%09url%3A%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fjs%2FJavascriptSubtitlesOctopus%2Ftest.ass%27%0A%09%09%09%09%7D%2C%0A%09%09%09%5D%2C%0A%09%09%09onSelect%3A%20function%20(item)%20%7B%0A%09%09%09%09console.log(item.url)%3B%0A%09%09%09%09art.plugins.artplayerPluginAss.instance.setTrackByUrl(item.url)%3B%0A%09%09%09%09return%20item.html%3B%0A%09%09%09%7D%2C%0A%09%09%7D%2C%0A%09%5D%2C%0A%09plugins%3A%20%5B%0A%09%09artplayerPluginAss(%7B%0A%09%09%09subUrl%3A%20%60https%3A%2F%2Fraw.githubusercontent.com%2Fflixmu%2Fsubtitle%2Fmain%2Fanime%2FY%2FYatogame-chan%2520Kansatsu%2520Nikki%2FS4%2F%255BFLIXMU%255D%255BIND%255D%255BEP04%255DYatogame-chan%2520Kansatsu%2520Nikki%2520Yonsatsume.ass%60%2C%0A%09%09%09workerUrl%3A%20%60https%3A%2F%2Fartplayer.org%2Fassets%2Fjs%2FJavascriptSubtitlesOctopus%2Fsubtitles-octopus-worker.js%60%2C%0A%09%09%7D)%0A%09%5D%2C%0A%7D)%3B%0A%0Afunction%20artplayerPluginAss(options)%20%7B%0A%09return%20art%20%3D%3E%20%7B%0A%09%09const%20instance%20%3D%20new%20SubtitlesOctopus(%7B%0A%09%09%09...options%2C%0A%09%09%09video%3A%20art.template.%24video%0A%09%09%7D)%3B%0A%0A%09%09instance.canvasParent.style.zIndex%20%3D%2020%3B%0A%09%09art.on(%27destroy%27%2C%20()%20%3D%3E%20instance.dispose())%3B%0A%0A%09%09return%20%7B%0A%09%09%09name%3A%20%22artplayerPluginAss%22%2C%0A%09%09%09instance%3A%20instance%0A%09%09%7D%0A%09%7D%0A%7D)

**Comment by zhw2590582** [comment]
You should ask questions here: https://github.com/libass/JavascriptSubtitlesOctopus/issues

**Comment by flixmu** [comment]
Thanks
