### ISSUE TITLE
Remove url: and subUrl:

### ISSUE THREAD

**Issue by flixmu** [zhw2590582/ArtPlayer#309]
Can i remove `url:` and `subUrl:`? Only use subtitle selector and quality selector, if i try remove `url:` and `subUrl:` video and subtitle can't load

Demo: [Link](https://artplayer.org/?libs=&code=%20%20%20%20var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20%20%20%20%20%2F%2F%20remove%20url%3A%20%27https%3A%2F%2Fflixmu.com%2Fplayer%2Fstream%2F360%2FzV0ALfPVUQ60FVy%2F__001%27%2C%0A%20%20%20%20%20%20%20%20title%3A%20%27%5BSE04EP07%5D%5BJP%20DUB%5D%5BFLIXMU%5DYatogame-chan%20Kansatsu%20Nikki%27%2C%20%0A%20%20%20%20%20%20%20%20poster%3A%20%27https%3A%2F%2Fflixmu.com%2Fpublic%2Fupload%2Fplayer%2Fse04ep07-jp-dub-flixmu-yatogame-chan-kansatsu-nikki.webp%27%2C%0A%20%20%20%20%20%20%20%20autoSize%3A%20true%2C%0A%20%20%20%20%20%20%20%20mutex%3A%20true%2C%0A%20%20%20%20%20%20%20%20setting%3A%20true%2C%0A%20%20%20%20%20%20%20%20flip%3A%20true%2C%0A%20%20%20%20%20%20%20%20lock%3A%20true%2C%0A%20%20%20%20%20%20%20%20fastForward%3A%20true%2C%0A%20%20%20%20%20%20%20%20playbackRate%3A%20true%2C%0A%20%20%20%20%20%20%20%20aspectRatio%3A%20true%2C%0A%20%20%20%20%20%20%20%20theme%3A%20%27%23ff0057%27%2C%0A%20%20%20%20%20%20%20%20fullscreen%3A%20true%2C%0A%20%20%20%20%20%20%20%20fullscreenWeb%3A%20true%2C%0A%20%20%20%20%20%20%20%20miniProgressBar%3A%20true%2C%0A%20%20%20%20%20%20%20%20whitelist%3A%20%5B%27*%27%5D%2C%0A%20%20%20%20%20%20%20%20icons%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20loading%3A%20%27%3Cimg%20src%3D%22%2Fpublic%2Fassets%2Fartplayer%2Fimg%2Fploading.gif%22%3E%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20state%3A%20%27%3Cimg%20width%3D%22150%22%20heigth%3D%22150%22%20src%3D%22%2Fpublic%2Fassets%2Fartplayer%2Fimg%2Fstate.svg%22%3E%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20indicator%3A%20%27%3Cimg%20width%3D%2216%22%20heigth%3D%2216%22%20src%3D%22%2Fpublic%2Fassets%2Fartplayer%2Fimg%2Findicator.svg%22%3E%27%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20quality%3A%20%5B%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%27360%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20url%3A%20%27https%3A%2F%2Fflixmu.com%2Fplayer%2Fstream%2F360%2FzV0ALfPVUQ60FVy%2F__001%27%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%27720%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20url%3A%20%27https%3A%2F%2Fflixmu.com%2Fplayer%2Fstream%2F720%2FzV0ALfPVUQ60FVy%2F__001%27%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%271080%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20url%3A%20%27https%3A%2F%2Fflixmu.com%2Fplayer%2Fstream%2F1080%2FzV0ALfPVUQ60FVy%2F__001%27%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%09%0A%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20settings%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20width%3A%20200%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%27Subtitles%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20tooltip%3A%20%27Bilingual%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20icon%3A%20%27%3Cimg%20width%3D%2222%22%20heigth%3D%2222%22%20src%3D%22%2Fpublic%2Fassets%2Fartplayer%2Fimg%2Fsubtitle.svg%22%3E%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20selector%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%09%09%09%09%20%20%20%20%20%20%20%20html%3A%20%27Switch%27%2C%0A%09%09%09%09%20%20%20%20%20%20%20%20switch%3A%20true%2C%0A%09%09%09%09%20%20%20%20%20%20%20%20tooltip%3A%20%27Show%27%2C%0A%09%09%09%09%20%20%20%20%20%20%20%20onSwitch%3A%20function%20(item)%20%7B%0A%09%09%09%09%09%20%20%20%20%20%20%20%20item.tooltip%20%3D%20item.switch%20%3F%20%27Hide%27%20%3A%20%27Show%27%3B%0A%09%09%09%09%09%20%20%20%20%20%20%20%20art.query(%27.libassjs-canvas-parent%27).style.display%20%3D%20item.switch%20%3F%20%27none%27%20%3A%20%27block%27%3B%0A%09%09%09%09%09%20%20%20%20%20%20%20%20return%20!item.switch%3B%0A%09%09%09%20%20%20%20%20%20%20%20%09%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%2C%0A%09%09%20%20%20%20%20%20%20%20onSelect%3A%20function%20(item)%20%7B%0A%09%09%09%20%20%20%20%20%20%20%20console.log(item.url)%3B%0A%09%09%09%20%20%20%20%20%20%20%20art.plugins.artplayerPluginAss.instance.setTrackByUrl(item.url)%3B%0A%09%09%09%20%20%20%20%20%20%20%20return%20item.html%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20plugins%3A%20%5B%0A%09%20%20%20%20%20%20%20%20artplayerPluginAss(%7B%0A%09%09%20%20%20%20%20%20%20%20%2F%2F%20remove%20subUrl%3A%20%60https%3A%2F%2Fraw.githubusercontent.com%2Fflixmu%2Fsubtitle%2Fmain%2Fanime%2FY%2FYatogame-chan%2520Kansatsu%2520Nikki%2FS4%2F%255BFLIXMU%255D%255BIND%255D%255BEP07%255DYatogame-chan%2520Kansatsu%2520Nikki%2520Yonsatsume.ass%60%2C%0A%09%09%20%20%20%20%20%20%20%20workerUrl%3A%20%60%2Fpublic%2Fassets%2Fartplayer%2Fjs%2FJavascriptSubtitlesOctopus%2Fsubtitles-octopus-worker.js%60%2C%0A%09%09%20%20%20%20%20%20%20%20renderMode%3A%20%60lossy%60%2C%0A%09%09%20%20%20%20%20%20%20%20dropAllAnimations%3A%20%60true%60%2C%0A%09%20%20%20%20%20%20%20%20%7D)%0A%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20customType%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20m3u8%3A%20function%20(video%2C%20url)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20(Hls.isSupported())%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20const%20hls%20%3D%20new%20Hls()%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20hls.loadSource(url)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20hls.attachMedia(video)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20const%20canPlay%20%3D%20video.canPlayType(%27application%2Fvnd.apple.mpegurl%27)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20(canPlay%20%3D%3D%3D%20%27probably%27%20%7C%7C%20canPlay%20%3D%3D%20%27maybe%27)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20video.src%20%3D%20url%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20art.notice.show%20%3D%20%27Does%20not%20support%20playback%20of%20m3u8%27%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D)%3B)

        var art = new Artplayer({
            container: '.artplayer-app',
            // remove url: 'https://flixmu.com/player/stream/360/zV0ALfPVUQ60FVy/__001',
            title: '[SE04EP07][JP DUB][FLIXMU]Yatogame-chan Kansatsu Nikki', 
            poster: 'https://flixmu.com/public/upload/player/se04ep07-jp-dub-flixmu-yatogame-chan-kansatsu-nikki.webp',
            autoSize: true,
            mutex: true,
            setting: true,
            flip: true,
            lock: true,
            fastForward: true,
            playbackRate: true,
            aspectRatio: true,
            theme: '#ff0057',
            fullscreen: true,
            fullscreenWeb: true,
            miniProgressBar: true,
            whitelist: ['*'],
            icons: {
                loading: '<img src="/public/assets/artplayer/img/ploading.gif">',
                state: '<img width="150" heigth="150" src="/public/assets/artplayer/img/state.svg">',
                indicator: '<img width="16" heigth="16" src="/public/assets/artplayer/img/indicator.svg">',
            },
            quality: [

                        {
                html: '360',
                url: 'https://flixmu.com/player/stream/360/zV0ALfPVUQ60FVy/__001',
            },
                    {
                html: '720',
                url: 'https://flixmu.com/player/stream/720/zV0ALfPVUQ60FVy/__001',
            },
                    {
                html: '1080',
                url: 'https://flixmu.com/player/stream/1080/zV0ALfPVUQ60FVy/__001',
            },
        	
            ],
            settings: [
                {
                    width: 200,
                    html: 'Subtitles',
                    tooltip: 'Bilingual',
                    icon: '<img width="22" heigth="22" src="/public/assets/artplayer/img/subtitle.svg">',
                    selector: [
                        {
					        html: 'Switch',
					        switch: true,
					        tooltip: 'Show',
					        onSwitch: function (item) {
						        item.tooltip = item.switch ? 'Hide' : 'Show';
						        art.query('.libassjs-canvas-parent').style.display = item.switch ? 'none' : 'block';
						        return !item.switch;
				        	},
                        },

    
                    ],
			        onSelect: function (item) {
				        console.log(item.url);
				        art.plugins.artplayerPluginAss.instance.setTrackByUrl(item.url);
				        return item.html;
                    },
                },
            ],
            plugins: [
		        artplayerPluginAss({
			        // remove subUrl: `https://raw.githubusercontent.com/flixmu/subtitle/main/anime/Y/Yatogame-chan%20Kansatsu%20Nikki/S4/%5BFLIXMU%5D%5BIND%5D%5BEP07%5DYatogame-chan%20Kansatsu%20Nikki%20Yonsatsume.ass`,
			        workerUrl: `/public/assets/artplayer/js/JavascriptSubtitlesOctopus/subtitles-octopus-worker.js`,
			        renderMode: `lossy`,
			        dropAllAnimations: `true`,
		        })
	        ],
            customType: {
                m3u8: function (video, url) {
                    if (Hls.isSupported()) {
                        const hls = new Hls();
                        hls.loadSource(url);
                        hls.attachMedia(video);
                    } else {
                        const canPlay = video.canPlayType('application/vnd.apple.mpegurl');
                        if (canPlay === 'probably' || canPlay == 'maybe') {
                            video.src = url;
                        } else {
                            art.notice.show = 'Does not support playback of m3u8';
                        }
                    }
                },
            },
        });

**Comment by zhw2590582** [comment]
Once the url is removed, the player will not work, why would you do this

**Comment by flixmu** [comment]
Because i am get data video url from json, but my json only for jwplayer and i tried to do this in the art player

**Comment by zhw2590582** [comment]
Then you can instantiate the player after getting the json
