### ISSUE TITLE
Switch Url not working 

### ISSUE THREAD

**Issue by Timothy16** [zhw2590582/ArtPlayer#311]
i can't seems to get get the switch url working in my Nuxt 3 project
Here is my player.vue component 

<template>
    <div ref="artRef" ></div>
</template>

<script>
import Hls from 'hls.js';
import Artplayer from 'artplayer';
export default {
    data() {
        return {
            instance: null,
        };
    },
    props: {
        option: {
            type: Object,
            required: true,
        },
    },

    mounted() {
        this.instance = new Artplayer({
            ...this.option,
            container: this.$refs.artRef,
            autoplay: false,
            isLive: true,
            mutex: true,
            url: this.option.url,
            moreVideoAttr: {
                // 'webkit-playsinline': true,
                playsInline: true,
                preload: 'none'
            },
            customType: {
                m3u8: function (video, url) {
                    if (Hls.isSupported()) {
                        const hls = new Hls();
                        hls.loadSource(url);
                        hls.attachMedia(video);
                    } else {
                        const canPlay = video.canPlayType('application/vnd.apple.mpegurl');
                        if (canPlay === 'probably' || canPlay == 'maybe') {
                            video.src = url;
                        } else {
                            art.notice.show = 'Does not support playback of m3u8';
                        }
                    }
                },
            },
        });
        this.instance.on('ready', () => {
            console.log("on-switch", this.option.url)
            setTimeout(() => {
                        //  destroy the hls
                    if (this.instance.hls) {
                        this.instance.hls.destroy();
                        this.instance.hls = null;
                    }
                    this.instance.switchUrl(this.option.url)
                    console.log("on-switch", this.option.url)
            }, 3000);
        })
        this.$nextTick(() => {
            this.$emit('get-instance', this.instance);
        });
      
    },
    beforeUnmount() {
        if (this.instance && this.instance.destroy) {
            this.instance.destroy(false);
        }
    },
};
</script>

**Comment by zhw2590582** [comment]
Artplayer.vue
```js
<template>
    <div ref="artRef"></div>
</template>

<script>
import Artplayer from 'artplayer';

export default {
    data() {
        return {
            instance: null,
        };
    },
    props: {
        option: {
            type: Object,
            required: true,
        },
    },
    mounted() {
        this.instance = new Artplayer({
            ...this.option,
            container: this.$refs.artRef,
        });

        this.$nextTick(() => {
            this.$emit('get-instance', this.instance);
        });
    },
    beforeUnmount() {
        if (this.instance && this.instance.destroy) {
            this.instance.destroy(false);
        }
    },
};
</script>
```

app.vue
```js
<template>
    <Artplayer @get-instance="getInstance" :option="option" :style="style" />
</template>

<script>
import Hls from 'hls.js';
import Artplayer from './Artplayer.vue';

export default {
    data() {
        return {
            option: {
                url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8?t=0',
                autoplay: true,
                muted: true,
                autoSize: true,
                customType: {
                    m3u8: function (video, url, art) {
                        console.log('url', url);

                        if (art.hls) {
                            art.hls.destroy();
                            art.hls = null;
                        }

                        if (Hls.isSupported()) {
                            art.hls = new Hls();
                            art.hls.loadSource(url);
                            art.hls.attachMedia(video);
                        } else {
                            const canPlay = video.canPlayType('application/vnd.apple.mpegurl');
                            if (canPlay === 'probably' || canPlay == 'maybe') {
                                video.src = url;
                            } else {
                                art.notice.show = 'Does not support playback of m3u8';
                            }
                        }
                    },
                },
            },
            style: {
                width: '600px',
                height: '400px',
                margin: '60px auto 0',
            },
        };
    },
    components: {
        Artplayer,
    },
    methods: {
        getInstance(art) {
            art.on('ready', () => {
                setTimeout(() => {
                    art.url = 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8?t=1';
                    // art.switchUrl('https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8');
                }, 3000);
            });
        },
    },
};
</script>
```

**Comment by Timothy16** [comment]
This actually change url, but only change once

i have an object of url's, how do i make this change dynamically. since i will be switching and playing multiple url

**Comment by zhw2590582** [comment]
https://github.com/zhw2590582/ArtPlayer/issues/253
