### ISSUE TITLE
Progressbar hidden after scroll page

### ISSUE THREAD

**Issue by MasoudSobhi** [zhw2590582/ArtPlayer#313]
### Expected behaviour
After Scroll Progress Bar and indicator will hidden , please fix it
when inspect and debuged in browser  " var(--theme)  " is null and have no color
fixed this problem when introduced --theme in my css

### Environment

-   Browser: Chrome
-   Version: Latest
-   Operating System: Windows 11
-   Version:

**Comment by zhw2590582** [comment]
I don't quite understand what you mean, why do you want to set var(--theme) to null

**Comment by MasoudSobhi** [comment]
after scroll page var(--theme) seted color is null , 
please visit this page  https://ybapp.ir/Player/  and scroll page to down , 
progress and indicator is gone automatically after scroll , and not showable after scroll top

**Comment by zhw2590582** [comment]
I understand what you mean, it is a bug caused by autoMini, you can update to this version and try: artplayer@4.4.5

**Comment by MasoudSobhi** [comment]
thanks , where i can download artplayer.js version 4.4.5  js file?

**Comment by zhw2590582** [comment]
https://unpkg.com/artplayer@4.4.5/dist/artplayer.js
