### ISSUE TITLE
Add External Subtitle

### ISSUE THREAD

**Issue by MasoudSobhi** [zhw2590582/ArtPlayer#314]
Hi  And thanks for this player.
Please Add Option to Adding External Subtitle From another source such as File Import srt or vtt file from device . thanks

**Comment by zhw2590582** [comment]
You can see this: [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09controls%3A%20%5B%0A%09%09%7B%0A%09%09%09position%3A%20%27right%27%2C%0A%09%09%09html%3A%20%27%3Cinput%20type%3D%22file%22%3E%3C%2Finput%3E%27%2C%0A%09%09%09tooltip%3A%20%27Open%20Subtitle%27%2C%0A%09%09%09style%3A%20%7B%0A%09%09%09%09width%3A%20%27100px%27%0A%09%09%09%7D%2C%0A%09%09%09mounted(el)%20%7B%0A%09%09%09%09const%20%7B%20getExt%20%7D%20%3D%20Artplayer.utils%3B%0A%09%09%09%09const%20input%20%3D%20el.querySelector(%27input%27)%3B%0A%09%09%09%09input.onchange%20%3D%20event%20%3D%3E%20%7B%0A%09%09%09%09%09const%20file%20%3D%20event.target.files%5B0%5D%3B%0A%09%09%09%09%09const%20type%20%3D%20getExt(file.name)%3B%0A%09%09%09%09%09if%20(%5B%27ass%27%2C%20%27vtt%27%2C%20%27srt%27%5D.includes(type))%20%7B%0A%09%09%09%09%09%09const%20url%20%3D%20URL.createObjectURL(file)%3B%0A%09%09%09%09%09%09art.subtitle.switch(url%2C%20%7B%0A%09%09%09%09%09%09%09name%3A%20file.name%2C%0A%09%09%09%09%09%09%09type%3A%20type%2C%0A%09%09%09%09%09%09%7D)%3B%0A%09%09%09%09%09%7D%0A%09%09%09%09%7D%0A%09%09%09%7D%0A%09%09%7D%2C%0A%09%5D%2C%0A%7D)%3B)
