### ISSUE TITLE
Make layer inner video

### ISSUE THREAD

**Issue by flixmu** [zhw2590582/ArtPlayer#316]
Make layer inner video on corner if full screen

![Screenshot_2022-06-05-20-11-39-81](https://user-images.githubusercontent.com/84267010/172052126-b5a11394-a80f-41cc-87bf-67e91eb500bb.png)

**Comment by zhw2590582** [comment]
Or you can use the `autoOrientation` option:

```js
var art = new Artplayer({
    container: '.artplayer-app',
    url: '/assets/sample/video.mp4',
    autoOrientation: true,
});
```

**Comment by flixmu** [comment]
Thanks very much
