### ISSUE TITLE
Unable to install artplayer 

### ISSUE THREAD

**Issue by bugcoder** [zhw2590582/ArtPlayer#321]
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for artplayer-react

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-08T12_19_46_840Z-debug.log
root@ip-172-31-8-132:/var/www/xxxx/xxxx# npm run build

> fla@0.1.0 build /var/www/xxxx/xxxx
> env-cmd -f .env react-scripts build && rm -rf docs && mv build docs

sh: 1: env-cmd: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! fla@0.1.0 build: `env-cmd -f .env react-scripts build && rm -rf docs && mv build docs`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fla@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-08T12_20_06_376Z-debug.log

**Comment by bugcoder** [comment]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/artplayer-react/-/artplayer-react-3.3.2.tgz
npm ERR! 404
npm ERR! 404  'artplayer-react@3.3.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'fla'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-08T12_32_44_806Z-debug.log

**Comment by zhw2590582** [comment]
artplayer-react has been deprecated
You can use this https://artplayer.org/document/#use-in-reactjs-or-nextjs
