### ISSUE TITLE
Play a video in viewport

### ISSUE THREAD

**Issue by Timothy16** [zhw2590582/ArtPlayer#322]
I have multiple videos on my landing page, how do i play a video only when the video is on focus or viewport

**Comment by zhw2590582** [comment]
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div class="player01" style="width: 400px;height: 300px;margin-bottom: 1000px;"></div>
    <div class="player02" style="width: 400px;height: 300px;margin-bottom: 1000px;"></div>
    <script src="./compiled/artplayer.js"></script>
    <script>
        const player01 = new Artplayer({
            container: '.player01',
            url: './assets/sample/video.mp4',
            muted: true,
        })

        const player02 = new Artplayer({
            container: '.player02',
            url: './assets/sample/video.mp4',
            muted: true,
        })

        Artplayer.instances.forEach(player => {
            player.on('view', state => {
                if (state) {
                    if (!player.playing) {
                        player.play();
                    }
                } else {
                    if (player.playing) {
                        player.pause();
                    }
                }
            })
        });

        // window.addEventListener('scroll', () => {
        //     for (let index = 0; index < Artplayer.instances.length; index++) {
        //         const player = Artplayer.instances[index];
        //         const state = checkInViewport(player.template.$container);

        //         if (state) {
        //             if (!player.playing) {
        //                 player.play();
        //             }
        //         } else {
        //             if (player.playing) {
        //                 player.pause();
        //             }
        //         }
        //     }
        // });
    </script>
</body>

</html>
```

**Comment by Timothy16** [comment]
i'm trying to implement this on my nuxt js project but not functioning properly, the videos are not playing in viewport 

<template>
    <div ref="artRef" ></div>
</template>

<script>
import Hls from 'hls.js';
import Artplayer from 'artplayer';
export default {
    data() {
        return {
            instance: null,
        };
    },
    props: {
        option: {
            type: Object,
            required: true,
        },
    },

    mounted() {
        this.instance = new Artplayer({
            ...this.option,
            container: this.$refs.artRef,
            autoplay: false,
            isLive: true,
            mutex: true,
            url: this.option.url,
            moreVideoAttr: {
                // 'webkit-playsinline': true,
                playsInline: true,
                preload: 'none'
            },
            icons: {
                state: '',
            },
            customType: {
                m3u8: function (video, url) {
                    if (Hls.isSupported()) {
                        const hls = new Hls();
                        hls.loadSource(url);
                        hls.attachMedia(video);
                    } else {
                        const canPlay = video.canPlayType('application/vnd.apple.mpegurl');
                        if (canPlay === 'probably' || canPlay == 'maybe') {
                            video.src = url;
                        } else {
                            art.notice.show = 'Does not support playback of m3u8';
                        }
                    }
                },
            },
        });
        
         Artplayer.instances.forEach(player => {
            player.on('view', state => {
                if (state) {
                    if (!player.playing) {
                        player.play();
                    }
                } else {
                    if (player.playing) {
                        player.pause();
                    }
                }
            })
        });
       
        this.$nextTick(() => {
            this.$emit('get-instance', this.instance);
        });
      
    },
    beforeUnmount() {
        if (this.instance && this.instance.destroy) {
            this.instance.destroy(false);
        }
    },
};
</script>

**Comment by zhw2590582** [comment]
Actually, this is not an issue of artplayer, you need to listen to the scroll event of the window, and then determine which player is in the viewport

```js
window.addEventListener('scroll', () => {
  for (let index = 0; index < Artplayer.instances.length; index++) {
    const player = Artplayer.instances[index]
    const state = checkInViewport(player.template.$container)

    if (state) {
      if (!player.playing) {
        player.play()
      }
    } else {
      if (player.playing) {
        player.pause()
      }
    }
  }
})
```

**Comment by Timothy16** [comment]
Uncaught ReferenceError: checkInViewport is not defined

**Comment by zhw2590582** [comment]
You need to define this function yourself. You can google it
