### ISSUE TITLE
【使用疑问】artplayer 弹幕配置项能否配置输入框的显示？

### ISSUE THREAD

**Issue by GlodenBoy** [zhw2590582/ArtPlayer#324]
artplayer 弹幕配置项能否配置输入框的显示？在文档弹幕插件里没有发现有这个配置，

例如我只想显示一个弹幕开启和关闭的按钮，只能用用自定义按钮吗。

**Comment by zhw2590582** [comment]
建议用CSS把输入框隐藏掉

**Comment by GlodenBoy** [comment]
> 

好的，可以的话，还是建议出个开关配置做到更自定义化一些。
