### ISSUE TITLE
Typescript 下 的error

### ISSUE THREAD

**Issue by GlodenBoy** [zhw2590582/ArtPlayer#325]
在使用ts的弹幕插件时，按照文档配置   plugins: [ artplayerPluginDanmuku({ }) 会报第一个not find错，实际f12过去是有的。

按照webstorm自动引用 import artplayerPluginDanmuku from 'artplayer-plugin-danmuku'  解决。

第二个是
![image](https://user-images.githubusercontent.com/2329528/173273424-3ef1ab96-e01a-474d-aee4-dc6d72b54a7d.png)

![image](https://user-images.githubusercontent.com/2329528/173273453-8f47fa6a-4fcb-40ee-9ec1-f9c47138dc9e.png)

**Comment by zhw2590582** [comment]
忘记发布主程序了，你更新到artplayer@4.4.7
