### ISSUE TITLE
Script error PluginAss

### ISSUE THREAD

**Issue by flixmu** [zhw2590582/ArtPlayer#326]
please help me, error again in PluginAss

https://flixmu.github.io/subtitle/

**Comment by zhw2590582** [comment]
I don't understand, you can check the chrome console first, this is just a cross-domain issue, why don't you copy the JavascriptSubtitlesOctopus directory to your project?
![企业微信20220614-133943](https://user-images.githubusercontent.com/5907357/173501736-df902827-1548-4f9b-8b40-61c0823bd0e0.png)
