### ISSUE TITLE
Subtitle not showing every time

### ISSUE THREAD

**Issue by sampleGit202** [zhw2590582/ArtPlayer#327]
I am using artplayer in react project. Recently, i updated the artplayer from 3.3 to 4.4. The requirement is that i have a dynamic subtitle list below my video player and whenever i click on subtitle or video plays and seeks then subtitle get updated.

### Expected behaviour
Subtitle should show in video player each and every time.

### Actual behaviour
In the earlier version i was picking the subtitle url from art.template.$track. But now $track is not present every time in art.template. Due to which i am not able to show my subtitle in video player every time.

### Sample code

####Function where subtitle url is getting updated
```
            const $video = state.art.template.$video;
            const $track = state.art.template.$track; 
            const videoUrl = $video.src;
            const subtitleUrl = $track ? $track.src : ''; //This is where i am extracting url from track
            if (props.videoUrl !== videoUrl) {
                state.art.player.switchUrl(props.videoUrl); is changed into state.art.switchUrl(props.videoUrl); as switchUrl is now present at this path
                URL.revokeObjectURL(videoUrl);
            }
            if (props.subtitleUrl !== subtitleUrl) {
                state.art.subtitle.init(props.subtitleUrl); //showing error of should be object but getting a string
                state.art.subtitle=props.subtitleUrl; //Used this to resolve the issue.
                URL.revokeObjectURL(subtitleUrl);
            }
```
#### Render function: 
```
<Artplayer
             style={{
                   width: '100%',
                   height: '300px',
                 }}
             option={{
                   url: videoUrl,
                   loop: false,
                   lang: 'en',
                   autoSize: false,
                   fullscreenWeb: true,
                   icons: {
                        state: ''
                         },
                   subtitle: {
                         url: subtitleUrl,
                       },
                   moreVideoAttr: {
                         crossOrigin: 'anonymous',
                     },
               }}
               getInstance={(art) => {
                       console.log(art); 
                       // When i am printing the art object here i cannot find $track itself. While in the last version i was able to get it everytime.
                      this.setState({ art });
                 }}
         />
```

### I need answers for
1.) How can i get my subtitleUrl every time via art object?
2.) How can i check what are new changes in 4.4?

**Comment by zhw2590582** [comment]
Some simple code optimization suggestions：
1. get the video url: `art.url`
2. get the subtitle url: `art.subtitle.url`
3. change the video url: `art.switchUrl(newUrl)` or `art.url = newUrl`
4. change the subtitle url: `art.subtitle.url = newUrl`
5. You don't need to call `URL.revokeObjectURL`, it's already done in the core code

In the new version, the process of instance initialization has changed, you can do the following:
```js
getInstance={(art) => {
    art.on('ready', () => {
       this.setState({ art });
    })
}}
```

**Comment by sampleGit202** [comment]
@zhw2590582 Thanks alot for the suggestions.

Also, when i checked the art.subtitle object i am not able to get the url.

#### This is what i am seeing in the console: 
![image](https://user-images.githubusercontent.com/107407402/173744396-c202a741-7570-40f9-ab03-66b6c304239e.png)

Why this error?
Also, in getInstance before setState(art) when i console.log(art) subtitle object is still same as the above added screenshot. Any idea what might be the problem? Why i am not able to get subtitle url each and every time?

**Comment by zhw2590582** [comment]
You can't get the subtitle url before the player ready event fires.

However, because the asynchronous request is used when loading the subtitle url, the subtitle url cannot be obtained immediately after the ready event is fires.

Usually, you don't need to get the url of the subtitle, and you don't need to compare the url of the subtitle, you can directly switch the url of the subtitle

```js
var art = new Artplayer({
	container: '.artplayer-app',
	url: '/assets/sample/video.mp4',
	subtitle: {
		url: '/assets/sample/subtitle.srt',
	},
});

art.on('ready', () => {
        // the subtitle url is empty
	console.log(art.subtitle.url)
});

art.on('subtitleSwitch', (url) => {
	console.log(url)
});
```

**Comment by zhw2590582** [comment]
Because $track is not created until subtitles are initialized for the first time

https://github.com/zhw2590582/ArtPlayer/blob/422728844a89f53e0d1e18f8e19e02848972ae5e/packages/artplayer/src/subtitle.js#L71-L78
