### ISSUE TITLE
广告插件的一个建议

### ISSUE THREAD

**Issue by cqsn558** [zhw2590582/ArtPlayer#329]
这次用广告插件确实比以前的广告棒，有个小的建议，playDuration这个必看广告时长在设置时如果等于或大于totalDuration总时长时，应该不显示canBeClosed这个提示，就是不显示“X秒后可关闭广告”这个提示。
另外i18n这个多语言支持能否根据在播放器设置lang的值自动显示为设置的语言呢？比如lang设置的是zh-tw，广告插件中i18n也显示为繁体，这样就与主播放器语言统一了，没必要对i18n进行自定义内容，只根据播放器语言自动更改成其他语言就行了。

**Comment by zhw2590582** [comment]
可以的

**Comment by zhw2590582** [comment]
刚刚更新到`artplayer-plugin-ads@1.0.3`了，不过这个插件的`i18n`和`artplayer`的`i18n`不太一样，这个是会插值（秒数）的，所以不能套用原来的`i18n`，所以暂时先保持原样
