### ISSUE TITLE
Vite project gives javascript error

### ISSUE THREAD

**Issue by wpplumber** [zhw2590582/ArtPlayer#331]
### Expected behaviour
It was working before migration to `Vite`!
### Actual behaviour
Trying to navigate to other route gives the error
### Steps to reproduce
private project
### Environment
Mac OS
-   Browser:
-   Version:
-   Operating System:
-   Version: 

### Console errors (if any)
`vue-router.esm-bundler.js:3325 SyntaxError: The requested module '/app/node_modules/artplayer/dist/artplayer.js?v=d18516bc' does not provide an export named 'default' (at Artplayer.vue:6:8)`

**Comment by zhw2590582** [comment]
You can refer to this: https://github.com/zhw2590582/ArtPlayer/tree/master/packages/artplayer-template/vue3.js

**Comment by wpplumber** [comment]
I see it calling the control the same way!

`import Artplayer from ..;`

Is it a dependency missing? (`"@vitejs/plugin-vue"`)

**Comment by zhw2590582** [comment]
Can you post your code, otherwise I don't know how to find the error

**Comment by wpplumber** [comment]
Think of my code like your sample for vue 3 just the `import` doesn't work and raises the previous error.

**Comment by zhw2590582** [comment]
Can you give me more code details?

**Comment by wpplumber** [comment]
It is a private project @zhw2590582, I see it like ESM issue with Vite and the project is a Quasar migration to vite.. (in progress..)
