### ISSUE TITLE
Random ads

### ISSUE THREAD

**Issue by flixmu** [zhw2590582/ArtPlayer#340]
1. Put 5 or 10 video and random display ads.

2. Ads video or banner with setting custom put, example in opening video, middle video, and ending video. Or custom timer, example with 3 minutes after video play ads can show.

3. Thanks

**Comment by zhw2590582** [comment]
The current ad can only appear before the video: https://artplayer.org/document/en/Plugins/ads

**Comment by zhw2590582** [comment]
I see what you mean, but this one is a bit complicated and I don't plan to use this ad insertion method at the moment
