### ISSUE TITLE
Open External Subtitle in Player

### ISSUE THREAD

**Issue by MasoudSobhi** [zhw2590582/ArtPlayer#341]
Hi,
How i can add External Subtitle from Computer or url address in Player
please help me.

**Comment by zhw2590582** [comment]
Are you talking about this: https://artplayer.org/document/options#subtitle

**Comment by MasoudSobhi** [comment]
already you send me that player has open file dialog and select srt file from pc and loaded in player . but you deleted this file and is not accessible

please send me again. thanks

**Comment by zhw2590582** [comment]
This? https://github.com/zhw2590582/ArtPlayer/issues/314
