### ISSUE TITLE
x265 encoding not show video

### ISSUE THREAD

**Issue by MasoudSobhi** [zhw2590582/ArtPlayer#342]
Hi, 
x265 encoding video not show video just play only audio. 
link of video is here
https://4kkgjojskmvositejhkkjnclacnalsnavlikn.gdfsucx8kttyy021t4m4bnu7kr81rpera.cf/Serial%204/Control.Z/fasl.3/x265/Control.Z.S03E04.720p.NF.WEB-DL.x265.10Bit.PaHe.mkv

please check that in artplayer 

and send me why this file only play audio and not showing video.
thanks

**Comment by zhw2590582** [comment]
This is caused by the lack of the corresponding decoder in chrome, and the js player cannot solve this problem
