### ISSUE TITLE
Can't open setting on kiwi browser (android)

### ISSUE THREAD

**Issue by flixmu** [zhw2590582/ArtPlayer#343]
-   Browser: Kiwi Browser
-   Version: 94.0.4606.56
-   Operating System: Android
-   Version: Android 9

![Screenshot_2022-07-17-14-13-02-60](https://user-images.githubusercontent.com/84267010/179388127-063c4377-99d9-4fec-b9be-80f162941595.png)
![Screenshot_2022-07-17-14-15-06-67](https://user-images.githubusercontent.com/84267010/179388132-7de5ebfc-5bdf-41a7-b435-b16c71f134a0.png)

**Comment by zhw2590582** [comment]
You try to visit this address and see if it appears normal: https://artplayer.org/mobile.html

**Comment by zhw2590582** [comment]
I don't have an Android phone with me right now, you can click the vConsole button at the bottom to see if there is any error message

**Comment by zhw2590582** [comment]
I mean, after you click the setting button, check vConsole for any error messages

**Comment by zhw2590582** [comment]
Thanks for your feedback, I will fix this in the next version
