### ISSUE TITLE
disabled progressbar seeking

### ISSUE THREAD

**Issue by achekra** [zhw2590582/ArtPlayer#348]
Hi,
congrats for this amazing plugin, just i want to know if we can disable progress bar (prevent click and forward)

**Comment by zhw2590582** [comment]
I found similar question, you can try it

https://stackoverflow.com/questions/11903545/how-to-disable-seeking-with-html5-video-tag

[demo for disable seeking](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%09%2F%2F%20Hotkey%20is%20disabled%0A%09art.hotkey.keys%5B%2737%27%5D%20%3D%20%5B%5D%3B%0A%09art.hotkey.keys%5B%2739%27%5D%20%3D%20%5B%5D%3B%0A%0A%09%2F%2F%20Seeking%20is%20disabled%0A%09var%20video%20%3D%20art.template.%24video%3B%0A%09var%20supposedCurrentTime%20%3D%200%3B%0A%09art.on(%27video%3Atimeupdate%27%2C%20()%20%3D%3E%20%7B%0A%09%09if%20(!art.template.%24video.seeking)%20%7B%0A%09%09%09supposedCurrentTime%20%3D%20video.currentTime%3B%0A%09%09%7D%0A%09%7D)%3B%0A%0A%09art.on(%27video%3Aseeking%27%2C%20()%20%3D%3E%20%7B%0A%09%09var%20delta%20%3D%20video.currentTime%20-%20supposedCurrentTime%3B%0A%09%09if%20(Math.abs(delta)%20%3E%200.01)%20%7B%0A%09%09%09video.currentTime%20%3D%20supposedCurrentTime%3B%0A%09%09%7D%0A%09%7D)%0A%0A%09art.on(%27video%3Aended%27%2C%20()%20%3D%3E%20%7B%0A%09%09supposedCurrentTime%20%3D%200%3B%0A%09%7D)%0A%7D))

**Comment by achekra** [comment]
Hi, thanks for your answer.
i prefer if there is any way to hide progress bar button or disable click on it,

**Comment by zhw2590582** [comment]
this is very simple

```css
.art-progress {
    pointer-events: none !important;
}
```

**Comment by achekra** [comment]
Hi, thank you
