### ISSUE TITLE
[Nuxt] webpack error

### ISSUE THREAD

**Issue by HamoBoker** [zhw2590582/ArtPlayer#351]
Getting following error when running nuxt.

```console
in ./node_modules/artplayer/dist/artplayer.js

Module parse failed: Unexpected token (7:69488)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.

```

## versions
```json
"nuxt": "^2.15.8"
"artplayer": "^4.5.3",
```

**NOTE** | rolling back to artplayer@4.5.2 fixes the problem

**Comment by zhw2590582** [comment]
yes i know this, will fix it in next version

**Comment by HamoBoker** [comment]
Hi @zhw2590582

I got same error on nuxt@2 with artplayer@5.0.9

`Module parse failed: Unexpected token (7:147582) `

Thank you for the amazing work 💙

**Comment by zhw2590582** [comment]
try use this one: 

```js
import Artplayer from 'artplayer/dist/artplayer.legacy.js';
```

**Comment by HamoBoker** [comment]
Thank you, error has gone

**Comment by duanqimiao** [comment]
well-done
