### ISSUE TITLE
Save video progresse

### ISSUE THREAD

**Issue by achekra** [zhw2590582/ArtPlayer#356]
Hi, 
is there any function for saving and loading saved video progress

**Comment by zhw2590582** [comment]
Do you mean to get the video playback progress, and set the video playback progress?
https://artplayer.org/document/propertie#currenttime

**Comment by achekra** [comment]
Yes,
but I'm asking if there is any existing option to set true for saving / loading progress automatically in / from cookies or browser memory

**Comment by zhw2590582** [comment]
Do you mean this, automatic memory playback: https://artplayer.org/document/options#autoplayback

**Comment by achekra** [comment]
yes, can we jump automatically without message

**Comment by zhw2590582** [comment]
You can't

**Comment by achekra** [comment]
thank you for you time,
