### ISSUE TITLE
Chrome 104 之後，HLS.js 無法顯示字幕

### ISSUE THREAD

**Issue by amowu** [zhw2590582/ArtPlayer#359]
### Expected behaviour

`customType` 使用 hls.js 時，播放 `*.m3u8` 應該要能正常顯示 `subtitle.url` 字幕

### Actual behaviour

Chrome 104 之後，`*.m3u8` 無法顯示 `subtitle.url` 字幕，但是 `*.mp4` 可以正常顯示字幕

### Steps to reproduce

1. 使用官方 hls.js 範例＋字幕：

```js
var art = new Artplayer({
    url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    customType: {
        m3u8: function (video, url) {
            if (Hls.isSupported()) {
                const hls = new Hls();
                hls.loadSource(url);
                hls.attachMedia(video);
            } else {
                const canPlay = video.canPlayType('application/vnd.apple.mpegurl');
                if (canPlay === 'probably' || canPlay == 'maybe') {
                    video.src = url;
                } else {
                    art.notice.show = '不支持播放格式：m3u8';
                }
            }
        },
    },
    subtitle: {
        url: "https://artplayer.org/assets/sample/subtitle.srt",
        type: "srt",
        style: {
            color: "#fe9200",
            fontSize: "20px"
        },
        encoding: "utf-8"
    },
});
```

2. 播放影片，發現沒有字幕，但是 `url` 換成 `*.mp4`、或是 Chrome 版本降回 103，可以正常播放字幕

### Environment

-   Browser: Chrome
-   Version: 104
-   Operating System: macOS
-   Version: Monterey

### Link to where the bug is happening

https://codesandbox.io/s/sad-sanne-vqt7xo

**Comment by zhw2590582** [comment]
似乎不知道哪里出问题了，在 codesandbox 上确实不显示字幕，但我在官网上测试确实正常的：[demo](https://artplayer.org/?libs=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fhls.js%2F8.0.0-beta.3%2Fhls.min.js&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Ftest-streams.mux.dev%2Fx36xhzz%2Fx36xhzz.m3u8%27%2C%0A%20%20%20%20customType%3A%20%7B%0A%20%20%20%20%20%20%20%20m3u8%3A%20function%20(video%2C%20url)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(Hls.isSupported())%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20const%20hls%20%3D%20new%20Hls()%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20hls.loadSource(url)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20hls.attachMedia(video)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20const%20canPlay%20%3D%20video.canPlayType(%27application%2Fvnd.apple.mpegurl%27)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20(canPlay%20%3D%3D%3D%20%27probably%27%20%7C%7C%20canPlay%20%3D%3D%3D%20%27maybe%27)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20video.src%20%3D%20url%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20art.notice.show%20%3D%20%27%E4%B8%8D%E6%94%AF%E6%8C%81%E6%92%AD%E6%94%BE%E6%A0%BC%E5%BC%8F%EF%BC%9Am3u8%27%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D%2C%0A%20%20%20%20subtitle%3A%20%7B%0A%20%20%20%20%20%20%20%20url%3A%20%22https%3A%2F%2Fartplayer.org%2Fassets%2Fsample%2Fsubtitle.srt%22%2C%0A%20%20%20%20%20%20%20%20type%3A%20%22srt%22%2C%0A%20%20%20%20%20%20%20%20style%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20color%3A%20%22%23fe9200%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20fontSize%3A%20%2220px%22%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20encoding%3A%20%22utf-8%22%0A%20%20%20%20%7D%2C%0A%7D)%3B)

**Comment by amowu** [comment]
> 似乎不知道哪里出问题了，在 codesandbox 上确实不显示字幕，但我在官网上测试确实正常的：[demo](https://artplayer.org/?libs=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fhls.js%2F8.0.0-beta.3%2Fhls.min.js&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Ftest-streams.mux.dev%2Fx36xhzz%2Fx36xhzz.m3u8%27%2C%0A%20%20%20%20customType%3A%20%7B%0A%20%20%20%20%20%20%20%20m3u8%3A%20function%20(video%2C%20url)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(Hls.isSupported())%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20const%20hls%20%3D%20new%20Hls()%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20hls.loadSource(url)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20hls.attachMedia(video)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20const%20canPlay%20%3D%20video.canPlayType(%27application%2Fvnd.apple.mpegurl%27)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20(canPlay%20%3D%3D%3D%20%27probably%27%20%7C%7C%20canPlay%20%3D%3D%3D%20%27maybe%27)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20video.src%20%3D%20url%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20art.notice.show%20%3D%20%27%E4%B8%8D%E6%94%AF%E6%8C%81%E6%92%AD%E6%94%BE%E6%A0%BC%E5%BC%8F%EF%BC%9Am3u8%27%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D%2C%0A%20%20%20%20subtitle%3A%20%7B%0A%20%20%20%20%20%20%20%20url%3A%20%22https%3A%2F%2Fartplayer.org%2Fassets%2Fsample%2Fsubtitle.srt%22%2C%0A%20%20%20%20%20%20%20%20type%3A%20%22srt%22%2C%0A%20%20%20%20%20%20%20%20style%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20color%3A%20%22%23fe9200%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20fontSize%3A%20%2220px%22%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20encoding%3A%20%22utf-8%22%0A%20%20%20%20%7D%2C%0A%7D)%3B)

找到原因了，如果 hls.js 用 `8.0.0-beta.3` 可以成功顯示字幕，可是奇怪的是這個版本只有在 cdnjs 上有，npm 只到 `1.2.1-0.canary.8561`。

**Comment by amowu** [comment]
> > 似乎不知道哪里出问题了，在 codesandbox 上确实不显示字幕，但我在官网上测试确实正常的：[demo](https://artplayer.org/?libs=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fhls.js%2F8.0.0-beta.3%2Fhls.min.js&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Ftest-streams.mux.dev%2Fx36xhzz%2Fx36xhzz.m3u8%27%2C%0A%20%20%20%20customType%3A%20%7B%0A%20%20%20%20%20%20%20%20m3u8%3A%20function%20(video%2C%20url)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(Hls.isSupported())%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20const%20hls%20%3D%20new%20Hls()%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20hls.loadSource(url)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20hls.attachMedia(video)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20const%20canPlay%20%3D%20video.canPlayType(%27application%2Fvnd.apple.mpegurl%27)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20(canPlay%20%3D%3D%3D%20%27probably%27%20%7C%7C%20canPlay%20%3D%3D%3D%20%27maybe%27)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20video.src%20%3D%20url%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20art.notice.show%20%3D%20%27%E4%B8%8D%E6%94%AF%E6%8C%81%E6%92%AD%E6%94%BE%E6%A0%BC%E5%BC%8F%EF%BC%9Am3u8%27%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D%2C%0A%20%20%20%20subtitle%3A%20%7B%0A%20%20%20%20%20%20%20%20url%3A%20%22https%3A%2F%2Fartplayer.org%2Fassets%2Fsample%2Fsubtitle.srt%22%2C%0A%20%20%20%20%20%20%20%20type%3A%20%22srt%22%2C%0A%20%20%20%20%20%20%20%20style%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20color%3A%20%22%23fe9200%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20fontSize%3A%20%2220px%22%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20encoding%3A%20%22utf-8%22%0A%20%20%20%20%7D%2C%0A%7D)%3B)
> 
> 找到原因了，如果 hls.js 用 `8.0.0-beta.3` 可以成功顯示字幕，可是奇怪的是這個版本只有在 cdnjs 上有，npm 只到 `1.2.1-0.canary.8561`。

順便問一下 hls.js https://github.com/video-dev/hls.js/issues/4841

**Comment by amowu** [comment]
> > > 似乎不知道哪里出问题了，在 codesandbox 上确实不显示字幕，但我在官网上测试确实正常的：[demo](https://artplayer.org/?libs=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fhls.js%2F8.0.0-beta.3%2Fhls.min.js&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Ftest-streams.mux.dev%2Fx36xhzz%2Fx36xhzz.m3u8%27%2C%0A%20%20%20%20customType%3A%20%7B%0A%20%20%20%20%20%20%20%20m3u8%3A%20function%20(video%2C%20url)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(Hls.isSupported())%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20const%20hls%20%3D%20new%20Hls()%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20hls.loadSource(url)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20hls.attachMedia(video)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20const%20canPlay%20%3D%20video.canPlayType(%27application%2Fvnd.apple.mpegurl%27)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20(canPlay%20%3D%3D%3D%20%27probably%27%20%7C%7C%20canPlay%20%3D%3D%3D%20%27maybe%27)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20video.src%20%3D%20url%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20art.notice.show%20%3D%20%27%E4%B8%8D%E6%94%AF%E6%8C%81%E6%92%AD%E6%94%BE%E6%A0%BC%E5%BC%8F%EF%BC%9Am3u8%27%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D%2C%0A%20%20%20%20subtitle%3A%20%7B%0A%20%20%20%20%20%20%20%20url%3A%20%22https%3A%2F%2Fartplayer.org%2Fassets%2Fsample%2Fsubtitle.srt%22%2C%0A%20%20%20%20%20%20%20%20type%3A%20%22srt%22%2C%0A%20%20%20%20%20%20%20%20style%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20color%3A%20%22%23fe9200%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20fontSize%3A%20%2220px%22%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20encoding%3A%20%22utf-8%22%0A%20%20%20%20%7D%2C%0A%7D)%3B)
> > 
> > 
> > 找到原因了，如果 hls.js 用 `8.0.0-beta.3` 可以成功顯示字幕，可是奇怪的是這個版本只有在 cdnjs 上有，npm 只到 `1.2.1-0.canary.8561`。
> 
> 順便問一下 hls.js [video-dev/hls.js#4841](https://github.com/video-dev/hls.js/issues/4841)

目前測試下來，hls@0.14.7 是最後可以 work 的版本，再上去 1.0.0 之後都有這問題

**Comment by zhw2590582** [comment]
似乎只和hls.js的版本有关，播放器本身无法修复该问题
