### ISSUE TITLE
Thumbnail支持VTT格式 (Sprite)

### ISSUE THREAD

**Issue by NADESHIKON** [zhw2590582/ArtPlayer#360]
你好 请问可以做到让Artplayer支持类似于像这种的 https://preview.zorores.com/4b/4b1a02c7ffcad4f1ee11cd6f474548cb/thumbnails/sprite.vtt vtt格式的预览吗

**Comment by zhw2590582** [comment]
可以的，这可以作为一个插件，只是需要单独开发
