### ISSUE TITLE
I need episodes select menu

### ISSUE THREAD

**Issue by Youssef-Durgham** [zhw2590582/ArtPlayer#363]
I need the selection list of episodes of the series inside the video and when i click on one of the episodes it will work.

**Comment by Youssef-Durgham** [comment]
And please i need button for skip intro it will show when intro start and hide when intro end

**Comment by Youssef-Durgham** [comment]
<img width="960" alt="36BCF81B-07EE-49B6-8627-FB47C3EB6446" src="https://user-images.githubusercontent.com/73782996/185442485-49c4651a-5c0f-425c-8f44-b7b57249bbdd.png">

Like this for select list

**Comment by zhw2590582** [comment]
Do you need this? [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20controls%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20position%3A%20%27right%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%27video%2001%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20selector%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20default%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%27%3Cspan%20style%3D%22color%3Ared%22%3Evideo%2001%3C%2Fspan%3E%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%3Fid%3D1%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%27%3Cspan%20style%3D%22color%3Ayellow%22%3Evideo%2002%3C%2Fspan%3E%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%3Fid%3D2%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20onSelect%3A%20function%20(item%2C%20%24dom)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.info(item%2C%20%24dom)%3B%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20art.url%20%3D%20item.url%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20%27You%20click%20%27%20%2B%20item.html%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%5D%2C%0A%7D)%3B)

**Comment by Youssef-Durgham** [comment]
Yes thx
I have one problem when i add the player to react.js its needed to change position from relative to static to appear in page 
I tried to change it from css but nothing 
Any idea ?

**Comment by Youssef-Durgham** [comment]
Position for art-video or art-video-player I don’t remember because I’m out now 😅

**Comment by zhw2590582** [comment]
I think it's your style issue, but I don't know your specific situation

**Comment by Youssef-Durgham** [comment]
I have last question can i change css style for art-video or art-video-player ?

**Comment by zhw2590582** [comment]
Of course, as long as it is a higher style priority, the original style can be overwritten

**Comment by Youssef-Durgham** [comment]
By only adding styles in css file with the same class name ?

**Comment by zhw2590582** [comment]
Or you can try more, this is very basic css knowledge

```html
<div class="your-class-name"></div>
```

```js
const art = new Artplayer({
    container: '.your-class-name',
    url: '/assets/sample/video.mp4'
})
```

```css
.your-class-name .art-video {}

.your-class-name .art-video-player {}
```

**Comment by Youssef-Durgham** [comment]
Thx ❤️
