### ISSUE TITLE
Subtitle italic tags

### ISSUE THREAD

**Issue by 5H4D0WILA** [zhw2590582/ArtPlayer#366]
Currently, whenever there is an `<i>` tag inside the vtt for italic text, it gets turned into `&lt;i&gt;`, which means it will display the actual `<i>`  tag on the subtitle.
Is there an easy way to change that behaviour?
i am right now using the video:timeupdate event to dynamically replace `&lt;i&gt;` back to `<i>`  tags, but it isnt instant, and also doesnt seem like the right way

**Comment by zhw2590582** [comment]
Rendering the style of VTT or ASS subtitles is a complex problem, and this function is not considered at present

**Comment by zhw2590582** [comment]
But you can customize the output effect of subtitle: [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20subtitle%3A%20%7B%0A%20%20%20%20%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.srt%27%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B%0A%0Aart.on(%27subtitleUpdate%27%2C%20text%20%3D%3E%20%7B%0A%09art.template.%24subtitle.innerHTML%20%3D%20text%3B%0A%7D))

```js
var art = new Artplayer({
    container: '.artplayer-app',
    url: '/assets/sample/video.mp4',
    subtitle: {
        url: '/assets/sample/subtitle.srt',
    },
});

art.on('subtitleUpdate', text => {
    art.template.$subtitle.innerHTML = text;
})
```
