### ISSUE TITLE
Having list of videos with a right side preview made multiple videos audio to play all

### ISSUE THREAD

**Issue by wpplumber** [zhw2590582/ArtPlayer#367]
### Expected behaviour
Using a vue js project to allow users watch video clicked on the link from the list without refresh using SPA. (only one video to run)
### Actual behaviour
The bug it is showing one video but running audios from other videos.
### Environment

-   Browser: Chrome
-   Version: Version 104.0.5112.79 (Official Build) (x86_64)
-   Operating System: MacOS
-   Version:  ArtPlayer  4.3.8

**Comment by zhw2590582** [comment]
You seem to need a playlist, you can write the playlist outside the player, click the playlist and switch the video address: https://artplayer.org/document/propertie#switchurl

**Comment by wpplumber** [comment]
Thank you @zhw2590582

After using `:key` prop the issue moved to archive.
