### ISSUE TITLE
支持同时显示多个字幕

### ISSUE THREAD

**Issue by NADESHIKON** [zhw2590582/ArtPlayer#368]
有些时候多个字幕会有overlap的时间段, 比如
https://cc.zorores.com/7f/c1/7fc1657015c5ae073e9db2e51ad0f8a0/eng-2.vtt

![image](https://user-images.githubusercontent.com/20222292/186052787-70b20a33-ec9c-454f-839d-12b881f70bf0.png)

而Artplayer会只显示其中一个
![image](https://user-images.githubusercontent.com/20222292/186052953-ae0ca12a-9dbf-4367-a62c-971a95f32bec.png)

例如这里 
05:36.300 --> 05:38.780
I've written up a few humanities questions.

05:37.150 --> 05:41.930
Our special cakes must be 
reserved one week in advance.

理想情况下屏幕靠上的位置应该会显示 ``Our special cakes must be reserved one week in advance.`` 的字幕 而不是只显示一个

如果检测到overlap的时间段能否把overlap的字幕显示在屏幕靠上的位置 例如:
![image](https://user-images.githubusercontent.com/20222292/186053569-72687320-a4f5-4313-ab85-7abada259fae.png)

**Comment by zhw2590582** [comment]
其实播放器里的vtt字幕解析是原生video自带的功能，你这种情况比较定制化，实现起来会有点复杂

**Comment by dylanZk1** [comment]
这种建议转为ass，而且如果出现连续三个时间轴重叠，那就没地儿放了。而且建议作者针对ass转新的解析组件，例如ass.js
