### ISSUE TITLE
Select menu disappear when i m in full screen

### ISSUE THREAD

**Issue by Yusifdhrgam1999** [zhw2590582/ArtPlayer#369]
I have to problem here 🥲

1. I made a select menu using createportal and its fine and work but when i go to full screen or web full screen video the content of menu disappear any idea for fixing it ?
![2BA8D8AA-0E97-40F7-92CD-4A4DF7AA8DF4](https://user-images.githubusercontent.com/108579971/186164770-007d37d7-9985-44a9-9bce-8cff5d277075.jpeg)

2. And the another problem its not responsive for mobile device so I tried to use @media for screen device to change the width and height not work and i tried to use tailwindcss to make it responsive and even its not work the width and height is constantly not changed any idea ?

This is a simple of the code on codesandbox
https://codesandbox.io/s/cool-meninsky-ze7szz?file=/src/App.js

**Comment by zhw2590582** [comment]
You may need to add the Portal to the player(like a layer), not outside the player:
https://codesandbox.io/s/gallant-babbage-it2mpb?file=/src/App.js

**Comment by Yusifdhrgam1999** [comment]
Thx i will try it today.
And the another problem player is not responsive for mobile device so I tried to use https://github.com/media for screen device to change the width and height not work and i tried to use tailwindcss to make it responsive and even its not work the width and height is constantly not changed any idea ?

**Comment by Yusifdhrgam1999** [comment]
> You may need to add the Portal to the player(like a layer), not outside the player:
> https://codesandbox.io/s/gallant-babbage-it2mpb?file=/src/App.js

It’s same what i did it and i tried here with your code its same error when i go in fullwebscreen or full screen the content of menu in up-left disappear but when I’m not in full screen it appears without any problem check this code

https://codesandbox.io/s/cool-meninsky-ze7szz?file=/player.js

**Comment by zhw2590582** [comment]
Because the dropdown menu is mounted on the body element by default and is separated from the player, you can try adding the `container` option

## When used, portals the content part into the body.
https://www.radix-ui.com/docs/primitives/components/dropdown-menu#portal

Regarding the responsive problem, the size of the player depends on the container, but you set the container width and height to: `1599 x 500`, so it cannot be responsive
