### ISSUE TITLE
移动端浏览器全屏后，点击弹幕输入框键盘会弹出后自动隐藏

### ISSUE THREAD

**Issue by maxoyed** [zhw2590582/ArtPlayer#379]
### Expected behaviour
移动端浏览器全屏后，点击弹幕输入框键盘自动弹出
### Actual behaviour
移动端浏览器全屏后，点击弹幕输入框键盘自动弹出，然后马上就会自动隐藏，无法正常使用
### Steps to reproduce
移动端浏览器点击全屏，点击弹幕输入框
### Environment

-   Browser: Chrome
-   Version: 105.0.5195.79
-   Browser: 夸克浏览器
-   Version: 5.8.9.225(220907105903)
-   Operating System: Android
-   Version: 12

### Console errors (if any)
无报错
### Link to where the bug is happening
https://maxoyed.r6stv.com

**Comment by DRAWCORE** [comment]
同样的问题，Android 12 Chrome 105 以及系统自带的浏览器等都会出现点击输入框后输入法弹出后立即消失，这个问题我观察发现应该只是在弹幕输入框可用的宽度小于设定的`minWidth`值后输入框挂载到播放器的下方时才会出现这个问题，如果输入框在播放器内部就不会出现

**Comment by DRAWCORE** [comment]
这个问题在您给出的移动端演示界面也是存在的，您可以使用手机看一下
https://artplayer.org/mobile.html

**Comment by DRAWCORE** [comment]
> 大概知道哪里出问题了，因为开启自动旋屏，我是使用`css3`的`rotate`模拟的，并非真正旋屏，所以输入法并不知道，输入法会遮挡住输入框造成误触，这个不好解决

这个的话我发现即使不开启`autoOrientation`问题也是存在的，普通竖屏(非网页全屏也非全屏)的情况下，点击输入框也会立即退出，输入框可用宽度不够自动挂载在播放器下面的时候和输入框在播放器内部的时候都会出现这个问题

**Comment by zhw2590582** [comment]
似乎只出现在安卓手机上，但目前缺少测试的手机，不好找原因

**Comment by DRAWCORE** [comment]
哦哦，有安卓系统的模拟器比如genymotion，mac系统也可以安装，要是您方便的话可以安装试一下

**Comment by zhw2590582** [comment]
在 `artplayer-plugin-danmuku@4.4.11` 中已修复该问题
