### ISSUE TITLE
移动端新功能请求

### ISSUE THREAD

**Issue by DRAWCORE** [zhw2590582/ArtPlayer#381]
1. 当前移动端播放视频时，进度条不能点击或滑动，只能通过在屏幕上左滑右滑来调整时间，希望可以支持对进度条的点击以及滑动操作
2. 希望可以支持移动端单击屏幕后显示/隐藏控制窗体的功能，例如B站播放器那样

**Comment by zhw2590582** [comment]
1. 目前在移动端上，整个播放器都可以拖动时间的，所以也包含了进度条，但目前不支持进度条点击，因为可点击区域太小，这个有待优化
2. 没理解这个，意思是点击播放器以外的区域时，显示播放器的控制栏吗？

**Comment by DRAWCORE** [comment]
第2个我的意思是就像B站app的播放器那样，单击播放器内视频画面的话就可以显示/隐藏整个播放器的控制窗体，不然的话现在是用户没有操作了之后需要等个几秒钟才会自动隐藏整个播放器的控制窗体只显示视频画面

关于第一个的问题的话您说的进度条也可以拖动是不是实际上并没有作用在进度条上，还是按照整个播放器区域来响应的，因为我去拖动进度条的话发现进度条的那个指示器并不跟随我的手指，有时候是在手指后面一点，有时候是在手指前面一点，它有它自己的节奏，不是手指到哪它就到哪，这样的效果就是相当于我在播放器内其他位置进行滑动一样

**Comment by zhw2590582** [comment]
第一个问题，目前已经是这样的了，视频播放一段时间后会自动隐藏控制栏，点击播放器会显示控制栏
第二个问题，默认拖动是按 `0.5` 的比例来设置播放进度的，例如从左往右拖动整个播放器宽度，实际上视频会拖放50%的进度，但你可以通过 `Artplayer.TOUCH_MOVE_RATIO = 0.5` 来设置这个比例

**Comment by DRAWCORE** [comment]
哦哦，那第一个的话可不可以增加一个点击屏幕立即隐藏控制栏，不用等待那几秒

**Comment by zhw2590582** [comment]
这个行为习惯是PC端和移动端统一的，目前不打算改变，假如你觉得等待的时间太久的话，你可以修改等待的时间，单位毫秒：
`Artplayer.CONTROL_HIDE_TIME = 3000;`
