### ISSUE TITLE
Can't click and drag on progress bar

### ISSUE THREAD

**Issue by LordOfCinder2000** [zhw2590582/ArtPlayer#383]

**Comment by zhw2590582** [comment]
Did the video fail to load?

**Comment by LordOfCinder2000** [comment]
I mean, some other video players you just need to click anywhere on the progress bar and drag, to change the time of the video. But with ArtPlayer you have to click and drag the indicator to do that.

**Comment by zhw2590582** [comment]
https://artplayer.org

You can take a look at this official website, the progress bar can be clicked anywhere

**Comment by LordOfCinder2000** [comment]
Yes, but click and drag at the same time doesn't work

**Comment by zhw2590582** [comment]
I see, I will fix this in the next version

**Comment by zhw2590582** [comment]
Fixed it in `artplayer@4.5.7`
