### ISSUE TITLE
Passive Listeners

### ISSUE THREAD

**Issue by Lestadt** [zhw2590582/ArtPlayer#385]
Hello, I have recently started using ArtPlayer, it seemed quite light and I wanted to try it. The player works fine, although I don't know why it takes a while to appear in my theme's template (that's something I'll see later), the real reason for this message is that when doing a performance analysis in PageSpeed Insights and Lighthouse (both Google tools) points me to this error or suggestion:
Does not use passive listeners to improve scrolling performance
and makes me this recommendation to solve it:
Consider marking your touch and wheel event listeners as `passive` to improve your page's scroll performance.
It is the first time that this type of error appears to me, I wanted to try your player to improve the performance of my website but this advice or suggestion reduces my performance score, I would like to know if there is anything I can do or if you have any suggestions for my, thanks in advance, I attach a screenshot.
![artplayer bug -Captura](https://user-images.githubusercontent.com/52806949/192081128-56882561-094b-4704-9f3a-03ce8b335fe0.PNG)

**Comment by zhw2590582** [comment]
you may need to install this script: https://github.com/zzarcon/default-passive-events

**Comment by Lestadt** [comment]
Thank you for your quick reaction, the implementation of the script you suggested was quick and easy, there are no more warnings or suggestions, everything is solved.
