### ISSUE TITLE
container type error with typescript

### ISSUE THREAD

**Issue by leopku** [zhw2590582/ArtPlayer#391]
### Actual behaviour
Uncaught ArtPlayerError: option.container require 'string' or 'Element' type

### Steps to reproduce
1. Creating own ArtPlayer component or using `artplayer/examples/react/Artplayer` directly in `tsx` files
2. Erorr occured while player rendering

### Environment

-   Browser & Version: Edge 106.0 & Chromiun 92.0
-   Operating System: macOS 11.6.7 Big Sur 

### Console errors (if any)

```
Uncaught ArtPlayerError: option.container require 'string' or 'Element' type
    at a (artplayer.js:7)
    at u (artplayer.js:7)
    at n (artplayer.js:7)
    at artplayer.js:7
    at Array.forEach (<anonymous>)
    at artplayer.js:7
    at i (artplayer.js:7)
    at new te (artplayer.js:7)
    at Artplayer.js:8
    at commitHookEffectListMount (react-dom.development.js:23150)
```

**Comment by zhw2590582** [comment]
`artplayer/examples/react/Artplayer` This file is obsolete

I recommend that you copy this player component into your project yourself:

https://github.com/zhw2590582/ArtPlayer/tree/master/packages/artplayer-template/react.js

**Comment by leopku** [comment]
I copied code from `https://github.com/zhw2590582/ArtPlayer/blob/master/packages/artplayer-template/react.js/src/ArtPlayer.js` as `TestPlayer`, but same error.

```
import { useEffect, useRef } from 'react'
import Artplayer from 'artplayer'

export default function TestPlayer({ option, getInstance, ...rest }) {
  const artRef = useRef()

  useEffect(() => {
    const art = new Artplayer({
      ...option,
      container: artRef.current,
    })

    if (getInstance && typeof getInstance === 'function') {
      getInstance(art)
    }

    return () => {
      if (art && art.destroy) {
        art.destroy(false)
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  return <div ref={artRef} {...rest}></div>
}
```

**Comment by leopku** [comment]
Invoking of TestPlayer as below:

```js
<TestPlayer
            option={{ url: 'https://artplayer.org/assets/sample/video.mp4' }}
            getInstance={(art) => console.log(art)}
          />
```

**Comment by zhw2590582** [comment]
it's weird, It's the first time I've encountered this, Or can you provide me with a demo like in `codesandbox`:
https://codesandbox.io/s/adoring-wildflower-w0hu42?file=/src/App.js
