### ISSUE TITLE
Highlight end time

### ISSUE THREAD

**Issue by 5H4D0WILA** [zhw2590582/ArtPlayer#394]
Sorry for creating a new issue so quickly, but i would like to add an end time to the highlight feature
The reason for that is that i wanna show where the intro is in a video
Is there an easy solution for that?

**Comment by zhw2590582** [comment]
I don't quite understand what you mean, can you explain in more detail?

**Comment by 5H4D0WILA** [comment]
Yeah, so
I have two time numbers, in seconds, that are the timeframe where an anime has its opening
and i would like to display that timeframe on the progressbar
i have seen the highlight option of artplayer, but it seems there is no "end" field and the highlight thing is always one seconds long

**Comment by zhw2590582** [comment]
I wrote a simple plugin call `artplayerPluginHighlight` for you, you can see if it is what you want: [demo](https://artplayer.org/?libs=&code=function%20artplayerPluginHighlight(option)%20%7B%0A%09return%20(art)%20%3D%3E%20%7B%0A%09%09const%20%24highlight%20%3D%20art.query(%27.art-progress-highlight%27)%3B%0A%09%09const%20%7B%20append%2C%20createElement%2C%20setStyles%20%7D%20%3D%20art.constructor.utils%3B%0A%09%09art.on(%27video%3Aloadedmetadata%27%2C%20()%20%3D%3E%20%7B%0A%09%09%09for%20(let%20index%20%3D%200%3B%20index%20%3C%20option.length%3B%20index%2B%2B)%20%7B%0A%09%09%09%09const%20item%20%3D%20option%5Bindex%5D%3B%0A%09%09%09%09const%20left%20%3D%20item.start%20%2F%20art.duration%20*%20100%3B%0A%09%09%09%09const%20width%20%3D%20(item.end%20-%20item.start)%20%2F%20art.duration%20*%20100%3B%0A%09%09%09%09const%20%24item%20%3D%20createElement(%27span%27)%3B%0A%09%09%09%09%24item.dataset.text%20%3D%20item.text%3B%0A%09%09%09%09setStyles(%24item%2C%20%7B%0A%09%09%09%09%09left%3A%20left%20%2B%20%27%25%27%2C%0A%09%09%09%09%09width%3A%20width%20%2B%20%27%25%27%2C%0A%09%09%09%09%09background%3A%20%27%2300ff96%27%2C%0A%09%09%09%09%7D)%3B%0A%09%09%09%09append(%24highlight%2C%20%24item)%3B%0A%09%09%09%7D%0A%09%09%7D)%0A%09%7D%0A%7D%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09plugins%3A%20%5B%0A%09%09artplayerPluginHighlight(%5B%0A%09%09%09%7B%0A%09%09%09%09start%3A%2010%2C%0A%09%09%09%09end%3A%2020%2C%0A%09%09%09%09text%3A%20%27some%20text%2001%27%2C%0A%09%09%09%7D%2C%0A%09%09%09%7B%0A%09%09%09%09start%3A%2030%2C%0A%09%09%09%09end%3A%2040%2C%0A%09%09%09%09text%3A%20%27some%20text%2002%27%2C%0A%09%09%09%7D%2C%0A%09%09%5D)%0A%09%5D%0A%7D)%3B)

**Comment by 5H4D0WILA** [comment]
this is exactly what i needed, thank you soo much

**Comment by Tescan-group** [comment]
Hey there, sorry for re-opening this. This is a very useful plugin but upon checking the demo, it does not seem to work. Like I did start 10 and end 60 for example but the highlight does not expand at all no matter what the start and end is.

Could you help on this perhaps?

**Comment by Tescan-group** [comment]
Artplayer's own CSS is overwriting the span's width so adding !important for the div solves it as in the demo it does not work;

Replace this;
```
setStyles($item, {
	left: left + '%',
	width: width + '%',
	background: '#00ff96',
});
```

With this;
`$item.style.cssText = `left: ${left}%; width: ${width}%!important; background: #00ff96;`;`
