### ISSUE TITLE
Odd behaviour

### ISSUE THREAD

**Issue by ahmedalashhab** [zhw2590582/ArtPlayer#396]
Hey, 
so, I tried creating a settings menu, that is able to change the provider from where i fetch my anime data
but, when i do that, it either doesnt update the qualities, which i store inside an array, or it updates them, but the onclick functionality is broken.

**Comment by zhw2590582** [comment]
I don't quite understand what you mean, can you give me some code? or give me a demo?

**Comment by 5H4D0WILA** [comment]
https://github.com/5H4D0WILA/InuStreamWebsite/blob/main/pages/watch/%5Bid%5D/%5Bname%5D.vue

This is the code that causes the issue. Its not that pretty, so hopefully you can understand whats going on.
Also, the issue was caused on my project, i just asked my friend to ask about this, cuz i didnt want to create a third issue in 3 days .-.

**Comment by zhw2590582** [comment]
@5H4D0WILA The code is too long and I don't know where the error occurred

**Comment by 5H4D0WILA** [comment]
the error occurs in line 223, thats the provider switching part

**Comment by 5H4D0WILA** [comment]
essentially, users have the option to choose between two providers:
Gogoanime and Zoro
So i added a settings menu for the two options, and try to fetch the data using the newly selected provider
but, that causes the other settings menus to not update
https://www.inu.watch/watch/98659/classroom-of-the-elite-ep-1
this is my website to show you what currently happens
just switch to zoro, and try changing the quality/subtitles

**Comment by zhw2590582** [comment]
@5H4D0WILA 
![1](https://user-images.githubusercontent.com/5907357/194713211-8703fb5e-1cab-4289-8c34-2d74ee6e8739.png)
![2](https://user-images.githubusercontent.com/5907357/194713229-d86a31ae-241e-4d3b-9233-115e6a005ae4.png)

```js
// streamData is null caused the error
streamData = stream.value
```

**Comment by 5H4D0WILA** [comment]
i know that i can open a new issue
that error is caused by the api not having the newest key, its not the issue

**Comment by 5H4D0WILA** [comment]
but, in short, changing the qualities array i created should update the settings, correct?
