### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by MaybeQHL** [zhw2590582/ArtPlayer#398]
1. 屏幕可以点击显示或隐藏进度条
2. 进度条可以点击跳转进度

**Comment by zhw2590582** [comment]
1. 进度条目前是鼠标经过就显示，过一会就隐藏，目前大部分视频网站都是这个逻辑的
2. 进度条目前已经是可以点击跳转进度了

**Comment by MaybeQHL** [comment]
移动端环境

**Comment by MaybeQHL** [comment]
1. 感觉移动端单次触摸体验好点 类似B站的播放器。

**Comment by zhw2590582** [comment]
1. 这个实现起来很简单，可以自行监听页面点击事件，然后`art.controls.show = true`即可
2. 因为移动端的进度条高度比较小，不好触碰，而且网页的灵敏度和app的灵敏度肯定是没法比的

**Comment by MaybeQHL** [comment]
嗯嗯
