### ISSUE TITLE
弹幕输入框显示的一个小问题

### ISSUE THREAD

**Issue by DRAWCORE** [zhw2590582/ArtPlayer#401]
当在弹幕输入框可用宽度小于设置的`minWidth`时，输入框会被挂在播放器窗口下端，这时候就会出现由于输入框是透明色而看不见的问题，比如网页背景为白色，那么输入框在被挂在播放器窗口下端时，它的输入栏和最左边的设置弹幕颜色和模式的按钮就会看不见，只能看见最右边的发送按钮，demo在https://codepen.io/DRAWCORE/pen/xxjGXQy

**Comment by zhw2590582** [comment]
设置 `theme: "light"` 即可

**Comment by DRAWCORE** [comment]
好的好的谢谢，没注意到这个🤣
