### ISSUE TITLE
hls的ts片段没问题，但伪装成png的m3u8无法播放

### ISSUE THREAD

**Issue by Miku-frank** [zhw2590582/ArtPlayer#403]

**Comment by zhw2590582** [comment]
你是说m3u8的地址伪装成png的地址？

```js
var art = new Artplayer({
    container: '.artplayer-app',
    autoplay: true,
    url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.png',
    type: 'm3u8', // <--- 添加一个 type 选项即可
    customType: {
        m3u8: function (video, url) {
            if (Hls.isSupported()) {
                const hls = new Hls();
                hls.loadSource(url);
                hls.attachMedia(video);
            } else {
                const canPlay = video.canPlayType('application/vnd.apple.mpegurl');
                if (canPlay === 'probably' || canPlay === 'maybe') {
                    video.src = url;
                } else {
                    art.notice.show = '不支持播放格式：m3u8';
                }
            }
        },
    },
});
```

**Comment by Miku-frank** [comment]
不是，是m3u8的地址，但是里面的片段是ts伪装成png的
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:11
#EXTINF:10.135122,
https://ali-ec.static.yximgs.com/udata/pkg/ks-merchant/541150223-56963efc-409f-4e9b-9a88-cc8acf466171-1665462824610.png
#EXTINF:10.010000,
https://ali-ec.static.yximgs.com/udata/pkg/ks-merchant/541150223-d25477f8-48ba-4499-bd72-502ce99a4853-1665462847534.png
#EXTINF:10.010000,
https://ali-ec.static.yximgs.com/udata/pkg/ks-merchant/541150223-6d136861-1e20-4f13-a5c1-cd9b376c45b6-1665462830920.png
#EXTINF:10.010000
```

**Comment by zhw2590582** [comment]
有没有这个这个m3u8的地址，发我一个，我测试一下

**Comment by Miku-frank** [comment]
https://yun.ssdm.cc/SBDM/ShinobinoIttoki01.m3u8

**Comment by zhw2590582** [comment]
你可以去官网试试，能解析出 manifest ，但播放黑屏，Buffer stalled error
https://hls-js.netlify.app/demo

![01](https://user-images.githubusercontent.com/5907357/195243802-7197a0ca-df93-4bef-9cd3-dd1d8c45d8da.png)
![02](https://user-images.githubusercontent.com/5907357/195243822-51dd474b-1f76-4531-b055-90785a95d941.png)

**Comment by Miku-frank** [comment]
我下载了png片段，好像是头部那里改了几个字节，但在播放器里这个怎么解决的，我看到有的其他网站是能播放的，但不知道原理=-=

**Comment by zhw2590582** [comment]
其他网站是哪个网站，我去看看

**Comment by Miku-frank** [comment]
http://tool.liumingye.cn/m3u8/
https://www.m3u8play.com/

**Comment by zhw2590582** [comment]
https://fastly.jsdelivr.net/npm/hls.js@1.1.3/dist/hls.min.js

似乎是hls版本的兼容问题，你看看这个：[demo](https://artplayer.org/?libs=https%3A%2F%2Ffastly.jsdelivr.net%2Fnpm%2Fhls.js%401.1.3%2Fdist%2Fhls.min.js&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20autoplay%3A%20true%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fyun.ssdm.cc%2FSBDM%2FShinobinoIttoki01.m3u8%27%2C%0A%20%20%20%20customType%3A%20%7B%0A%20%20%20%20%20%20%20%20m3u8%3A%20function%20(video%2C%20url)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(Hls.isSupported())%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20const%20hls%20%3D%20new%20Hls()%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20hls.loadSource(url)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20hls.attachMedia(video)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20const%20canPlay%20%3D%20video.canPlayType(%27application%2Fvnd.apple.mpegurl%27)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20(canPlay%20%3D%3D%3D%20%27probably%27%20%7C%7C%20canPlay%20%3D%3D%3D%20%27maybe%27)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20video.src%20%3D%20url%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20art.notice.show%20%3D%20%27%E4%B8%8D%E6%94%AF%E6%8C%81%E6%92%AD%E6%94%BE%E6%A0%BC%E5%BC%8F%EF%BC%9Am3u8%27%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B)

**Comment by Miku-frank** [comment]
好像解决了，网站集成的播放器能播放被伪装png的m3u8了，谢谢大佬
