### ISSUE TITLE
希望播放器增加VR模式选项(LR, TM等)

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [zhw2590582/ArtPlayer#404]
我本地存了很多VR视频，大部分都是 左右180度的格式，少部分上下180度的，能否像 PotPlayer 一样 增加切换3D模式的选项？让没有VR设备的用户也可以正常查看视频

**Comment by zhw2590582** [comment]
我给你写了个插件叫 `artplayerPluginVideo360`，你可以看看: [demo](https://artplayer.org/?libs=https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fkaleidoscopejs%2Fdist%2Fkaleidoscope.min.js&code=function%20artplayerPluginVideo360(art)%20%7B%0A%09const%20container%20%3D%20document.createElement(%27div%27)%3B%0A%09container.classList.add(%27artplayer-plugin-video360%27)%3B%0A%09art.template.%24video.after(container)%3B%0A%0A%09container.style.cssText%20%3D%20%60%0A%09%09position%3A%20absolute%3B%0A%09%09left%3A%200%3B%0A%09%09top%3A%200%3B%0A%09%09right%3A%200%3B%0A%09%09bottom%3A%200%3B%0A%09%09width%3A%20100%25%3B%0A%09%09height%3A%20100%25%3B%0A%09%09z-index%3A%2011%3B%0A%09%60%3B%0A%0A%09%2F%2F%20https%3A%2F%2Fgithub.com%2Fthiagopnts%2Fkaleidoscope%0A%09const%20viewer%20%3D%20new%20Kaleidoscope.Video(%7B%0A%09%09muted%3A%20true%2C%0A%09%09autoplay%3A%20art.option.autoplay%2C%0A%09%09height%3A%20art.height%2C%0A%09%09width%3A%20art.width%2C%0A%09%09source%3A%20art.option.url%2C%0A%09%09loop%3A%20art.option.loop%2C%0A%09%09container%3A%20container%0A%09%7D)%3B%0A%0A%09art.proxy(container%2C%20%27click%27%2C%20()%20%3D%3E%20art.play())%3B%0A%0A%09art.on(%27ready%27%2C%20()%20%3D%3E%20viewer.render())%3B%0A%09art.on(%27play%27%2C%20()%20%3D%3E%20viewer.play())%3B%0A%09art.on(%27pause%27%2C%20()%20%3D%3E%20viewer.pause())%3B%0A%09art.on(%27destroy%27%2C%20()%20%3D%3E%20viewer.destroy())%3B%0A%0A%09art.on(%27resize%27%2C%20()%20%3D%3E%20viewer.setSize(%7B%0A%09%09height%3A%20art.height%2C%0A%09%09width%3A%20art.width%0A%09%7D))%0A%0A%09art.on(%27seek%27%2C%20()%20%3D%3E%20%7B%0A%09%09viewer.element.currentTime%20%3D%20art.currentTime%3B%0A%09%7D)%0A%0A%09return%20%7B%0A%09%09name%3A%20%27artplayerPluginVideo360%27%2C%0A%09%09viewer%2C%0A%09%7D%0A%7D%0A%0Aconst%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09poster%3A%20%27%2Fassets%2Fsample%2Fposter.jpg%27%2C%0A%09plugins%3A%20%5BartplayerPluginVideo360%5D%0A%7D)%3B)

具体的设置，你可以参考：https://github.com/thiagopnts/kaleidoscope#documentation
