### ISSUE TITLE
control bar hidden on mobile [only with react]

### ISSUE THREAD

**Issue by abdellani** [zhw2590582/ArtPlayer#416]
### Actual behaviour
* When I used my laptop, I didn't find any problem in any page.
* When I used my smartphone:
   *  If I access https://artplayer.org/  I can play the video.
   * If I run  `/ArtPlayer/packages/artplayer-template/react.js/`, The control bar is hidden
![314923240_498583982295544_2365824764940772689_n](https://user-images.githubusercontent.com/16113997/200390649-90870193-2f4b-40f5-801d-09ad4456c3ce.jpg)

I noticed the problem for the first time in my project, where users were reporting that can't play videos when they access using a smartphone. 
It seems to be related to the integration with react.js. (  because with vanilla js, I didn't notice the problem)

### Steps to reproduce
- run the project /ArtPlayer/packages/artplayer-template/react.js/
- access the project from a smartphone/iphone 

### Environment

-   Browser: chrome
-   Version: 107.0.5304.91
-   Operating System: ColorOS
-   Version: v12
I also tested on iPhone and Android.

**Comment by zhw2590582** [comment]
I think you forgot to add this option: `whitelist: ['*'],`

**Comment by abdellani** [comment]
Hi @zhw2590582 
Yes, this solved the problem.

Thank you
