### ISSUE TITLE
提供90度旋转(翻转)的选项

### ISSUE THREAD

**Issue by in-out** [zhw2590582/ArtPlayer#420]
翻转现在只有
垂直(180)
水平(270)
两种 
可否提供90度这个选项

![image](https://user-images.githubusercontent.com/3615775/201503428-f8586d15-5c14-4df9-a958-c197860be901.png)

**Comment by zhw2590582** [comment]
这个功能以前有过，后来发现用处不大就移除了，目前还不打算添加这个
