### ISSUE TITLE
Player on mobile view does't show video tag next elements

### ISSUE THREAD

**Issue by wpplumber** [zhw2590582/ArtPlayer#421]
### Expected behaviour

To show the player video tag with next elements

### Actual behaviour
Only `video` tag without next elements to control.
### Steps to reproduce
I'm using a VUEJS project but the issue seems related to rendering of plugin!

**Comment by zhw2590582** [comment]
https://github.com/zhw2590582/ArtPlayer/issues/416
I think you forgot to add this option: whitelist: ['*'],

**Comment by wpplumber** [comment]
It shows now using that option,  but showing a lock icon ?
![image](https://user-images.githubusercontent.com/52907282/201532040-db8a865c-ee8a-4685-a45e-745ada4d8652.png)

Thank you for this useful plugin.

**Comment by wpplumber** [comment]
I used the [lock](https://artplayer.org/document/options/#lock) option which fixed it.
