### ISSUE TITLE
群晖映射的WEBDAV里的视频播放时音频与视频不同步，音频慢一拍。快进一下又好了，播一会儿又慢了

### ISSUE THREAD

**Issue by yefenghu** [zhw2590582/ArtPlayer#422]
### Environment

-   Browser:
-   Version:
-   Operating System:
-   Version:

### Link to where the bug is happening
https://yefenghu.top:5244/%E5%BD%B1%E8%A7%86%E5%A4%A7%E5%8E%85/%E7%94%B5%E8%A7%86%E5%89%A7/q%E5%8D%BFr%E5%B8%B8.EP12.HD1080p.mp4

**Comment by zhw2590582** [comment]
假如用artplayer是这种情况的话，那么用原生的video肯定也会是这种情况，因为播放器本身就是对原生的video进行了包装美化，不做任何解码功能的，所以是这个视频源出现问题了
