### ISSUE TITLE
Chromecast

### ISSUE THREAD

**Issue by Bilnaa** [zhw2590582/ArtPlayer#425]
Hi I've been using your player for one of my project which is really good and really straightforward. I just wanna know if the implementation of Chromecast could be a thing or not ? Cheers.

**Comment by zhw2590582** [comment]
Not yet, thought I didn't have a Chromecast device with me yet, so I couldn't add Chromecast functionality

**Comment by Bilnaa** [comment]
So that's mean that you're gonna be working on it right ?

**Comment by zhw2590582** [comment]
Yes, as long as I have a Chromecast device
