### ISSUE TITLE
HEVC 编码问题

### ISSUE THREAD

**Issue by teaka-xss** [zhw2590582/ArtPlayer#426]
这是一个非常棒的播放器，最近遇到 HEVC 编码的MP4无法播放，我该如何添加此支持或者有什么第三方库推荐吗？

**Comment by teaka-xss** [comment]
市面上大部分的做法好像都是服务器解码，然后返回数据给前端。

**Comment by zhw2590582** [comment]
HEVC前端也可以做软解码，但是用canvas播放，很难与artplayer进行融合

**Comment by teaka-xss** [comment]
😄看了一下canvas的设计思路，那还是中间加多个转码服务器吧（就是懒。。。），感谢。
