### ISSUE TITLE
HLS支持问题

### ISSUE THREAD

**Issue by qian9008** [zhw2590582/ArtPlayer#427]
http://39.134.166.197:6610/000000001000/6000000001000029752/index.m3u8?channel-id=wasusyt&Contentid=6000000001000029752&livemode=1&stbId=3
 这个视频potplayer可以正常播放的

**Comment by zhw2590582** [comment]
我这边也打不开这个地址，说有跨域问题，你那边是不是也是报跨域的错误

**Comment by qian9008** [comment]
> 我这边也打不开这个地址，说有跨域问题，你那边是不是也是报跨域的错误
打不开，不知道什么错误。pc edge不用插件不支持hls .安卓却没问题。直接能打开。

**Comment by zhw2590582** [comment]
你可以打开chrome的控制台，就能看到是什么错误了。
跨域问题只存在于浏览器，安卓不是浏览器，所以没有这个问题。
