### ISSUE TITLE
Nuxt3 local url path for video not functioning

### ISSUE THREAD

**Issue by tsrift** [zhw2590582/ArtPlayer#430]
### Expected behaviour
Local video to play

### Actual behaviour
`url: "assets/sample/video.mp4"`
It's translating it in url path, not local path

### Environment

-   Browser: All
-   Version:
-   Operating System:
-   Version:

### Console errors (if any)
GET http://localhost:3000/assets/sample/video.mp4 404 (Page not found: /assets/sample/video.mp4)

### Link to where the bug is happening
https://codesandbox.io/s/thirsty-sunset-3lz7m?file=/src/App.vue

App.vue

```
<template>
  <Artplayer @get-instance="getInstance" :option="option" :style="style" />
</template>

<script>
import Artplayer from "artplayer/examples/vue/Artplayer";

export default {
  data() {
    return {
      option: {
        url: "https://artplayer.org/assets/sample/video.mp4",
      },
      style: {
        width: "600px",
        height: "400px",
        margin: "60px auto 0",
      },
    };
  },
  components: {
    Artplayer,
  },
  methods: {
    getInstance(art) {
      console.log(art);
    },
  },
};
</script>
```

**Comment by tsrift** [comment]
I will take your advice for consideration in the future.
But, as I said, the problem is that url for local path of mp4 is not working. Try it by yourself. It's not working.

`GET http://localhost:3000/public/sample/video.mp4 404 (Page not found: /public/sample/video.mp4)`

**Comment by zhw2590582** [comment]
https://nuxt.com/docs/getting-started/assets#public-directory

If the video is stored in: `/public/sample/video.mp4`

OK：
```js
const art = new Artplayer({
     url: '/sample/video.mp4'
})
```

Not OK：
```js
const art = new Artplayer({
     url: '/public/sample/video.mp4'
})
```
