### ISSUE TITLE
让 Artplayer 记住用户在重新加载页面时先前选择的视频质量，并且只运行 Artplayer 质量设置中的视频质量链接，而不必首先设置 Artplayer playable.video 的 url。

### ISSUE THREAD

**Issue by newbie9999a** [zhw2590582/ArtPlayer#434]
您好，感谢您创造了一个很棒的视频播放器，但是有一个问题让我很困扰，尽管我是第一次尝试这个播放器。
当您将设置中的视频质量设置为默认高清时，我默认使用 jwplayer 已经有一段时间了，然后在播放视频时，用户将能够根据他们的网络速度选择全高清或标清质量（所以当我使用 ArtPlayer 时，我选择全HD 或 SD，但在重新加载 artplayer 页面时，我不记得用户之前选择的质量）。

- 我想建议：
+ 请仅在 artplayer 质量设置部分播放视频或仅通过设置 url 播放视频，只有 2 个中的 1 个（为什么有完整的视频质量，但 artplayer 必须坚持在设置中设置 url 才能播放它，即使它是配置）设置中的多链接质量，我发现在 artplayer 设置中同时运行 url 或质量更复杂且不同步）。
而在 jwplayer 中，我可以运行 2 个中的 1 个（1 是配置视频链接以运行 url，2 是运行多链接视频质量，无需首先添加视频 url 来设置播放视频）。
例如：
1 是只运行设置 url：
var art = new Artplayer({
  网址：'#linkvideo'，
});
2是当你设置了多质量链接播放后，一开始不需要有新的视频url播放（完全不同步）。
var art = new Artplayer({
质量： [
         {
             html: '标清 480P',
             网址：'#linkvideo'，
         },
         {
默认值：真，
             html: '高清 720P',
             网址：'#linkvideo'，
         },
     ],
});
* 但artplayer不一定要这样运行：
var art = new Artplayer({
网址：'#linkvideo'，
质量： [
         {
             html: '标清 480P',
             网址：'#linkvideo'，
         },
         {
默认值：真，
             html: '高清 720P',
             网址：'#linkvideo'，
         },
     ],
});
+ 请让 Artplayer 记住用户先前在重新加载页面时选择的视频质量选项。

**Comment by zhw2590582** [comment]
你的主意很好，但你的主意对当前的代码改动比较大，我先给你写了一个小插件`artplayPluginQuality`，插件能记住你最后一次所选择的画质，你可以直接复制到你的项目里使用，看看能不能满足你的要求：[demo](https://artplayer.org/?libs=&code=function%20artplayPluginQuality(option)%20%7B%0A%09return%20art%20%3D%3E%20%7B%0A%09%09const%20storageQuality%20%3D%20art.storage.get(%27quality%27)%3B%0A%09%09art.controls.add(%7B%0A%09%09%09position%3A%20%27right%27%2C%0A%09%09%09html%3A%20storageQuality%20%7C%7C%20%27Quality%27%2C%0A%09%09%09selector%3A%20option%2C%0A%09%09%09onSelect%3A%20function%20(item)%20%7B%0A%09%09%09%09art.switchQuality(item.url%2C%20item.html)%3B%0A%09%09%09%09art.storage.set(%27quality%27%2C%20item.html)%3B%0A%09%09%09%09return%20item.html%0A%09%09%09%7D%2C%0A%09%09%7D)%3B%0A%09%09if%20(storageQuality)%20%7B%0A%09%09%09const%20quality%20%3D%20option.find(item%20%3D%3E%20item.html%20%3D%3D%3D%20storageQuality)%3B%0A%09%09%09if%20(quality)%20%7B%0A%09%09%09%09art.url%20%3D%20quality.url%3B%0A%09%09%09%7D%20else%20%7B%0A%09%09%09%09art.url%20%3D%20option%5B0%5D.url%3B%0A%09%09%09%7D%0A%09%09%7D%20else%20%7B%0A%09%09%09art.url%20%3D%20option%5B0%5D.url%3B%0A%09%09%7D%0A%09%7D%0A%7D%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09plugins%3A%20%5B%0A%09%09artplayPluginQuality(%5B%0A%09%09%09%7B%0A%09%09%09%09html%3A%20%27SD%20480P%27%2C%0A%09%09%09%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%3Fp%3D480%27%2C%0A%09%09%09%7D%2C%0A%09%09%09%7B%0A%09%09%09%09html%3A%20%27HD%20720P%27%2C%0A%09%09%09%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%3Fp%3D720%27%2C%0A%09%09%09%7D%2C%0A%09%09%5D)%0A%09%5D%0A%7D)%3B)

**Comment by newbie9999a** [comment]
> 你 你 ， ， ，`artplayPluginQuality`， ， ， ， ， 你 你 你 你 你 你 你 你 你 到 你 到 你 你 你 到 到使用，看看能不能满足你的要求: [demo](https://artplayer.org/?libs=&code=function%20artplayPluginQuality(option)%20%7B%0A%09return%20art%20%3D%3E%20%7B%0A%09%09const%20storageQuality%20%3D%20art.storage.get(%27quality%27)%3B%0A%09%09art.controls.add(%7B%0A%09%09%09position%3A%20%27right%27%2C%0A%09%09%09html%3A%20storageQuality%20%7C%7C%20%27Quality%27%2C%0A%09%09%09selector%3A%20option%2C%0A%09%09%09onSelect%3A%20function%20(item)%20%7B%0A%09%09%09%09art.switchQuality(item.url%2C%20item.html)%3B%0A%09%09%09%09art.storage.set(%27quality%27%2C%20item.html)%3B%0A%09%09%09%09return%20item.html%0A%09%09%09%7D%2C%0A%09%09%7D)%3B%0A%09%09if%20(storageQuality)%20%7B%0A%09%09%09const%20quality%20%3D%20option.find(item%20%3D%3E%20item.html%20%3D%3D%3D%20storageQuality)%3B%0A%09%09%09if%20(quality)%20%7B%0A%09%09%09%09art.url%20%3D%20quality.url%3B%0A%09%09%09%7D%20else%20%7B%0A%09%09%09%09art.url%20%3D%20option%5B0%5D.url%3B%0A%09%09%09%7D%0A%09%09%7D%20else%20%7B%0A%09%09%09art.url%20%3D%20option%5B0%5D.url%3B%0A%09%09%7D%0A%09%7D%0A%7D%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09plugins%3A%20%5B%0A%09%09artplayPluginQuality(%5B%0A%09%09%09%7B%0A%09%09%09%09html%3A%20%27SD%20480P%27%2C%0A%09%09%09%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%3Fp%3D480%27%2C%0A%09%09%09%7D%2C%0A%09%09%09%7B%0A%09%09%09%09html%3A%20%27HD%20720P%27%2C%0A%09%09%09%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%3Fp%3D720%27%2C%0A%09%09%09%7D%2C%0A%09%09%5D)%0A%09%5D%0A%7D)%3B)

非常感谢，它运行完美（但是，如果用户之前选择的质量菜单中它会亮起（ .active ），而不是像没有选择质量一样没有任何项目被点亮，那会更好).

* 你能不能让字幕sud ASS像每个角色的原始子文件一样分别显示颜色和字体，文本的显示位置（就像编码动漫情节时的子结果）。
很久以前有一个玩sub ASS的插件，显示角色自己的颜色，包括字体和sub位置，显示的效果（不是默认的sub 1颜色，很平淡，总是在底部）。就像你正在观看由软件编码的动漫剧集。
现在我不记得它的名字是什么了。

**Comment by zhw2590582** [comment]
No wonder your Chinese looks weird, you can communicate with me in English，Regarding the problem of ass subtitle rendering, you can take a look at this: https://github.com/zhw2590582/ArtPlayer/issues/239#issuecomment-1060243794

**Comment by newbie9999a** [comment]
> Thảo nào tiếng Trung của bạn trông lạ quá, bạn có thể giao tiếp với tôi bằng tiếng Anh，Về vấn đề kết xuất phụ đề mông, bạn có thể xem cái này: [#239 (bình luận)](https://github.com/zhw2590582/ArtPlayer/issues/239#issuecomment-1060243794)

My English is very bad, but perhaps translating into English would be more accurate.

The sub ass works perfectly, thank you but there is an issue that the video avatar doesn't show up if I name it the same as the original file:
Eg:
img/Jashin-chan Dropkick!! X-980x560.jpg
I checked that the artplayer doesn't output the image link on the div tag.
But if I set it like this, Artplayer will output the image link on the div tag.
for example:
img/Jashin-chan%20Dropkick%21%21%20X-980x560.jpg

* I tried on jwplayer with link img/Jashin-chan Dropkick!! X-980x560.jpg display is fine.

**Comment by zhw2590582** [comment]
I don't quite understand what you mean, can you provide me with a demo?

https://stackblitz.com

https://codesandbox.io

**Comment by newbie9999a** [comment]
![Untitled](https://user-images.githubusercontent.com/121395021/210176441-a8eaaedf-7de0-4364-806e-97be1307887f.jpg)
That means I'm having 2 problems:
Problem 1:
When I put the image link in the setup with space or characters, I see that artplayer does not insert the image link into the div.art-poster tag, so the poster image does not appear (but when I encode the image url, the new artplayer can insert the image link into the div tag. .art-poster) , even though video links with spacing or characters are still playable, titles with spaces or characters are still displayed fine.

Problem 2 as demo photo:
By default artplayer does not show the title when the player is loaded and when the video ends.
so I manually added the video title and a small title.
- I see in the setup there is a title but no subtitle (so how do I insert a small title into the artplayer's own setup)
