### ISSUE TITLE
移动端长按倍速播放时手指稍微有点抖动，都会改变进度条

### ISSUE THREAD

**Issue by 52beijixing** [zhw2590582/ArtPlayer#438]
在长按倍速播放的时候，手指稍微抖动，甚至有时自己都无法察觉的抖动，都会改变进度条。
在移动端，使用【ipad上的safari浏览器】或者【华为手机自带浏览器】都会产生这样的问题。

希望在长按倍速的时候可以禁止进度条的变化，或者滑动明显时才改变进度条。

我认为在长按倍速的时候禁止进度条的变化是最好的体验，希望您可以考虑！

**Comment by zhw2590582** [comment]
多谢建议，我会在下个版本中修复这个问题

**Comment by zhw2590582** [comment]
在最新版中已修复
