### ISSUE TITLE
Back to progress storage

### ISSUE THREAD

**Issue by Bilnaa** [zhw2590582/ArtPlayer#439]
Hi,

Just wanted to know if there was a way to save the url of the page instead of the video link for the Last Seen layer since the video link changes all the time but not the url. Sorry If it's something that you already talk about I can't seem to find good informations.

![image](https://user-images.githubusercontent.com/43651360/210241289-94033b83-755b-483c-8d00-339022b0547b.png)

Cheers, Nabil.

**Comment by zhw2590582** [comment]
Just pass in a unique id in the options:

```js
const art = new Artplayer({
    id: 'video-id'
})
```

**Comment by Bilnaa** [comment]
thx a lot
