### ISSUE TITLE
HLS Quality Plugin error and suggestions

### ISSUE THREAD

**Issue by DiST1122** [zhw2590582/ArtPlayer#440]
1. Normal playback is not possible when using HLS Quality Plugin on iPhone.
It has been confirmed that normal play is possible when the HLS Quality Plugin is removed.

2. When HLS quality is changed in Auto mode of HLS Quality Plugin, the text of Quality Icon at the bottom does not change.
HLS stream changed 720P to 1080P.
However, Artplayer's Icon is still displaying 720P.

3. Can you add an option that doesn't use the Context Menu?

Your project is very helpful to me.
Thank you for always.

### Environment
-   Browser: Safari
-   Version: Lastest
-   Operating System: IOS 16.2

**Comment by zhw2590582** [comment]
`artplayer-plugin-hls-quality` depends on `hls.js`, but `hls.js` is not supported in `ios`, so `artplayer-plugin-hls-quality` cannot be used in `ios`

**Comment by DiST1122** [comment]
> `artplayer-plugin-hls-quality` depends on `hls.js`, but `hls.js` is not supported in `ios`, so `artplayer-plugin-hls-quality` cannot be used in `ios`

Oh. I understood. Thank you for your reply.
Is there any way I can fix the problem in item 2?

**Comment by zhw2590582** [comment]
The second problem, I will try to fix it in the next version;

Third question:

```js
Artplayer.CONTEXTMENU = false;

var art = new Artplayer({
    container: '.artplayer-app',
    url: '/assets/sample/video.mp4',
});
```
