### ISSUE TITLE
Can i get help?

### ISSUE THREAD

**Issue by DiST1122** [zhw2590582/ArtPlayer#441]
I want to dynamically change the value of i18n .

For example : 'Play' : 'TEST PLAY'

Is there any way to do this?

As always thank you for your work.

**Comment by zhw2590582** [comment]
https://artplayer.org/document/advance#update

**Comment by DiST1122** [comment]
> https://artplayer.org/document/advance#update

Is using like this?

new Art...{
   lang: 'sample',
}

art.i18n.update({
	sample: {
		Language: 'Sample', 'Play': 'Sample Play',
	}
});


Thank you!

**Comment by zhw2590582** [comment]
Yes, but this can only modify i18n after instantiation, not before instantiation, I think this is a bug, I will fix this in the next version.
I'll let you know here when it's fixed

**Comment by DiST1122** [comment]
> Yes, but this can only modify i18n after instantiation, not before instantiation, I think this is a bug, I will fix this in the next version. I'll let you know here when it's fixed

Thank you :)
Artplayer is amazing solution to us.

**Comment by zhw2590582** [comment]
You installed the latest version: `4.6.1`

```js
var art = new Artplayer({
    container: '.artplayer-app',
    url: '/assets/sample/video.mp4',
    lang: 'your-lang',
    i18n: {
        'your-lang': {
            Play: 'Your Play'
        },
    },
});
```
https://github.com/zhw2590582/ArtPlayer/blob/master/packages/artplayer/types/i18n.d.ts
