### ISSUE TITLE
Send custom header or cookie with video url in artplayer?

### ISSUE THREAD

**Issue by Steve7394** [zhw2590582/ArtPlayer#444]
Hi
I have two questions:
1-Is there any option for art player to send some **custom header** like jwt token for url video?
2- is there any way to send **cookies** with the video url?

**Comment by zhw2590582** [comment]
1, The default http connection does not support custom request headers
2. The default http connection can carry cookies

**Comment by Steve7394** [comment]
Thanks for your answer
In angular app we define an interceptor and all http request intercept with that, and alll works except video url...
And still can not solve the problem...

**Comment by zhw2590582** [comment]
Or you can pass your parameters through url, such as token, and the backend will do special processing for this parameter

**Comment by Steve7394** [comment]
Actually the url is an api need authentication
And authentication token (jwt) should be sent by headers or cookies....

I think artplayer should have some feature to send custom header and send cookie for supporting url with authentication.
( like set  withCredential=true in moreVideoAttribute to send cookie but its not working)

**Comment by zhw2590582** [comment]
I think you have misunderstood the essence of artplayer, artplayer is `one video tab` + `some div tab` + `some style`.
Meaning, artplayer just beautifies the `video tab` with some divs and some style
If the `video tab` itself does not support custom request headers, artplayer cannot customize request headers too

**Comment by Steve7394** [comment]
thanks for your explanation
in sample user video url from assets
try to use from other  domain like
http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
it does not send any cookies

**Comment by zhw2590582** [comment]
Yes, cross-domain can be a bit tricky, but there are some useful references:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

https://stackoverflow.com/questions/1019370/are-cookies-sent-with-image-requests/69318616#69318616

**Comment by Steve7394** [comment]
This is a fair answer.
thanks a lot
