### ISSUE TITLE
thumbnails as vtt & playlist support

### ISSUE THREAD

**Issue by elsayed85** [zhw2590582/ArtPlayer#447]
what about supporting vtt thumb 
https://prev.2cdns.com/_m_preview/9e/9e29df132d9713aebdc211079ee01352/thumbnails/sprite.vtt

**Comment by zhw2590582** [comment]
thumbnails as vtt is currently not supported, but I can write you a plugin and I will let you know in this issue
Playlist support is currently not supported, because usually this is a highly customized list, I suggest that it will be easier to write your own

**Comment by elsayed85** [comment]
yes please

**Comment by zhw2590582** [comment]
I wrote a very simple plugin, but it has not been fully tested, you can try it

https://artplayer.org/?libs=./uncompiled/artplayer-plugin-vtt-thumbnail/index.js&example=vtt.thumbnail

https://github.com/zhw2590582/ArtPlayer/tree/master/packages/artplayer-plugin-vtt-thumbnail/dist
