### ISSUE TITLE
HLS ERROR 

### ISSUE THREAD

**Issue by flixmu** [zhw2590582/ArtPlayer#449]
![Screenshot_2023-01-15-20-55-57-77](https://user-images.githubusercontent.com/84267010/212545014-9031048d-ed70-419f-9106-ef69bbb6f842.png)

Note: the m3u8 link has an expiration date

[Link](https://pl.crunchyroll.com/evs3/c5faca62d5e7a2bc6a76749ed645958f/assets/f54089f8bc09b1e8becbce75457222e3_,3765265.mp4,3765266.mp4,3765264.mp4,3765262.mp4,3765263.mp4,3765261.mp4,.urlset/master.m3u8?Expires=1673959877&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMy9jNWZhY2E2MmQ1ZTdhMmJjNmE3Njc0OWVkNjQ1OTU4Zi9hc3NldHMvZjU0MDg5ZjhiYzA5YjFlOGJlY2JjZTc1NDU3MjIyZTNfLDM3NjUyNjUubXA0LDM3NjUyNjYubXA0LDM3NjUyNjQubXA0LDM3NjUyNjIubXA0LDM3NjUyNjMubXA0LDM3NjUyNjEubXA0LC51cmxzZXQvbWFzdGVyLm0zdTgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2NzM5NTk4Nzd9fX1dfQ__&Signature=aNb11SfUdciLVm35vmaFPwlCz6~BTTnVb1OQLkoH4uk3fidpDZPi3nqTl7ZtB9Ol2wInn2lqEI-tVw4ON0dtFlwecAJyqMbE2AJ6CHek431FBZEn~Q4OMIlRG0QMLIUW7tr7boXkYJFPLZSqMMGcO75VD~APu2dMghbwFI9Rff~qGqFbStgfoSOf4AAX~g1fSFpN6E4lF7UTQ7eFLpewlx8GLz5dqotEvPXqla2cee4~wjhuTrh1DMO5CCORYteqP86r~uIennLgVIjyzf9WC1IFGFZBrK4kOGBhUYQV9Xwooe8wGrU7Qjxkr-CgADPKps66GBM3BSRyS~9CWGwKnA__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA)

**Comment by zhw2590582** [comment]
Can you give me a `url` of `m3u8` that I can access?

**Comment by zhw2590582** [comment]
There seems to be a cross domain issue

![Snipaste_2023-01-16_10-58-34](https://user-images.githubusercontent.com/5907357/212589278-7186bc31-ed0e-4853-933a-192d7a016b0d.png)
