### ISSUE TITLE
[Not tree-shakable friendly] Artplayer is fully bundled to entry with SSG

### ISSUE THREAD

**Issue by Mister-Hope** [zhw2590582/ArtPlayer#450]
Thanks for the package first.

I am trying to build a component with artplayer, and I have SSG on my pages. The problem is that when I want to use `useSSR: true`, I need to import an html template, that's reasonable.

**However, placing these kind of resources as static member on `ArtPlayer` class is not resaonable**. Since modern web application are already targeting es module, and we would like to make everything tree-shakable, for me, I would like to import the static html template at entry and registing my component globally, then load ArtPlayer while the component is mounted. This benifit the loading speed.

To be clearer:

This is not what I want

```ts
// artplayer is bundled with this component as artplayer is referenced in dom.
import Artplayer from "artplayer";

export default defineComponent({
  setup: () => {
     onMounted(async () => {
      const player = new Artplayer(option());
    });
    return () => h('div', { innerHTML: ArtPlayer.html })
});
```

This is what I want:

```ts
// html template is named exported, so only the static string is bundled with component
import { html } from "artplayer";

export default defineComponent({
  setup: () => {
     // artplayer constructor is loaded when component is mounted.
     onMounted(async () => {
        // use dynamic import and magic comment to ensure artplayer is splitted into a chunk and only loads when component is mounted.
        import('artplayer').then(({ Artplayer } => {
         const player = new Artplayer(option());
       }):
    });
    return () => h('div', { innerHTML: ArtPlayer.html })
});
```

**Comment by Mister-Hope** [comment]
I read at some lines of code, and no offense, my suggestion is that maybe you can have a look at `VidPlayer`, to see how they decouple each features. Maybe you are familiar with classes and you can write and maintain easily with them, but users do need to suffer importing a whole package without haveing any choice.

**Comment by zhw2590582** [comment]
Your suggestion is good, but it's too much of a code change to implement at the moment.
However, the use of `useSSR` by the player does not have much optimization effect

**Comment by Mister-Hope** [comment]
Just the reason you provide this, I just want a placeholder of video before artplayer is loaded.

Currently I make a workaround by copying the html template manually. But I am looking forward to the package improvement.

**Comment by Mister-Hope** [comment]
Any update for this?

**Comment by zhw2590582** [comment]
There is no update for this tree-shakable, because if we want to use tree-shakable, the structure of the code will change too much
