### ISSUE TITLE
Subtitle Flickering Issue.

### ISSUE THREAD

**Issue by DiST1122** [zhw2590582/ArtPlayer#454]
Flickering may be seen on the screen when outputting subtitles on some devices.
I've seen what's happening when the subtitle's P tag disappears or appears.
Is there any solution I can try?

85-inch LCD TV is outputting in full screen using HTPC.
HTPC is outputting using the latest version of Chrome.

I'm not experiencing that problem with my personal PC.

Thank you!

**Comment by zhw2590582** [comment]
I don't have this kind of devices here, so it's hard to find the problem. Can you record a video for this issue?

**Comment by DiST1122** [comment]
> I don't have this kind of devices here, so it's hard to find the problem. Can you record a video for this issue?

Hi.

Found the problem.
Turning off chrome's hardware acceleration fixed the flickering issue.

Chrome's hardware acceleration on some display devices
It may cause flickering when displaying and hiding subtitles.
This seems to be a chrome problem, not an artplayer problem.

Thx :)
