### ISSUE TITLE
playbackRate 功能有点小问题

### ISSUE THREAD

**Issue by iuk-ink** [zhw2590582/ArtPlayer#455]
版本：4.6.1
手机端、电脑端都一样，设置面板 和 右键菜单 里设置了 倍数 后会现实相应 倍数 播放，但是一直显示 正常，不显示为相应 倍数

用的这个：https://unpkg.com/artplayer/dist/artplayer.js

var art = new Artplayer({
    container: '.artplayer-app',
    playbackRate: true,
    setting: true,
});

**Comment by zhw2590582** [comment]
已经发现这个问题，会在下个版本中修复的，多谢反馈
