### ISSUE TITLE
Tags showing in subtitles when using ArtPlayer

### ISSUE THREAD

**Issue by RazeViana** [zhw2590582/ArtPlayer#457]
### Expected behaviour
Show subtitles using the correct styling.
### Actual behaviour
Subtitles are displaying the tags without applying the style.
https://i.imgur.com/3MOL3aP.png
### Steps to reproduce
Here is [example](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20subtitle%3A%20%7B%0A%20%20%20%20%20%20%20%20url%3A%20%27https%3A%2F%2Fcc.zorores.com%2Ff1%2F53%2Ff153995a4a0a949f8dbb341ce60b7883%2Feng-2.vtt%27%2C%0A%20%20%20%20%20%20%20%20type%3A%20%27vtt%27%2C%0A%20%20%20%20%20%20%20%20encoding%3A%20%27utf-8%27%2C%0A%20%20%20%20%20%20%20%20style%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20color%3A%20%27%2303A9F4%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%27font-size%27%3A%20%2730px%27%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B)
### Environment

-   Browser:
-   Version:
-   Operating System:
-   Version:

**Comment by 756751uosmaqy** [comment]
thanks, l was about to ask about this too 
![1ar](https://user-images.githubusercontent.com/116700531/214763200-8fd71ad9-70a6-44ee-8549-4466b700faa3.jpg)

![1arfix](https://user-images.githubusercontent.com/116700531/214763325-85f0e8c2-b23e-457b-9ff6-d07cd4bff0eb.png)

**Comment by zhw2590582** [comment]
I just released `artplayer@4.6.2`, added `escape` in subtitle options, whether to escape html tags, the default is `true`, If you want to display html tags, set it to `false`:

```js
var art = new Artplayer({
    container: '.artplayer-app',
    url: '/assets/sample/video.mp4',
    subtitle: {
        url: '/assets/sample/subtitle.srt',
        escape: false,
    },
});
```

**Comment by RazeViana** [comment]
Hello, I updated the package to 4.6.2 and I tried to use the `escape: false` option but it is still not working for me. Here is my implementation:

```
             <Artplayer
                option={{
                    url: MediaURL?.status === 'available' ? MediaURL.value : '',
                    poster: PosterURL?.status === 'available' ? PosterURL.value : '',
                    type: VideoType,
                    theme: PlayerTheme,
                    subtitle: {
                        url: SubtitleURL?.status === 'available' ? SubtitleURL.value : '',
                        escape: false,
                        type: 'vtt',
                        encoding: 'utf-8',
                        style: {
                            color: SubtitleTheme,
                            'font-size': `${SubtitleFontSize}px`,
                            'font-family': 'Gg Sans',
                        },
                    },
                    fullscreen: true,
                    setting: false,
                    hotkey: true,
                }}
                getInstance={(art) => console.info(art)}
            />
```

**Comment by zhw2590582** [comment]
What is the url of your subtitles? i want to test it

**Comment by RazeViana** [comment]
It's the same as the one in this [example](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20subtitle%3A%20%7B%0A%20%20%20%20%20%20%20%20url%3A%20%27https%3A%2F%2Fcc.zorores.com%2Ff1%2F53%2Ff153995a4a0a949f8dbb341ce60b7883%2Feng-2.vtt%27%2C%0A%20%20%20%20%20%20%20%20type%3A%20%27vtt%27%2C%0A%20%20%20%20%20%20%20%20encoding%3A%20%27utf-8%27%2C%0A%20%20%20%20%20%20%20%20style%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20color%3A%20%27%2303A9F4%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%27font-size%27%3A%20%2730px%27%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B)

**Comment by zhw2590582** [comment]
I tested it, it's ok：[demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20subtitle%3A%20%7B%0A%20%20%20%20%20%20%20%20url%3A%20%27https%3A%2F%2Fcc.zorores.com%2Ff1%2F53%2Ff153995a4a0a949f8dbb341ce60b7883%2Feng-2.vtt%27%2C%0A%09%09escape%3A%20false%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B)

**Comment by RazeViana** [comment]
Ah! it works. I had to reinstall the ArtPlayer package. Thank you very much 👍
