### ISSUE TITLE
The subtitles doesn't apply HTML tag.

### ISSUE THREAD

**Issue by huy232** [zhw2590582/ArtPlayer#459]
### Expected behavior

The subtitle applies an HTML tag and displays correctly (WEBVTT format)

### Actual behavior

The subtitle doesn't apply an HTML tag and is displayed incorrectly (WEBVTT format)

### Steps to reproduce

Mount the example subtitles to any video (can be HLS support or purely mp4 is acceptable)
The subtitles example: `https://cc.zorores.com/e2/26/e2269e124e6ef28c0fda30e4636550c6/eng-2.vtt `

Can be mounted directly on the [Art Player home page](https://artplayer.org/)

When mounted, for example, the very first sentence of the subtitles:

```
00:03.980 --> 00:07.440
<b>The Dawn of the 
Age of Great
 Exploration</b>

```

The video player can't understand the tag symbol and render those tags along with the subtitle.

![image](https://user-images.githubusercontent.com/59156109/215391955-78e0e92e-4801-474f-bf20-1633107566b6.png)

Picture to demonstrate the problem.

**Comment by huy232** [comment]
> 

Yes, you just need to add:
```
					subtitle: {
						escape: false,
					}
```

if apply the HTML tag that is used inside the VTT.

**Comment by NinjaCoderDotCom** [comment]
Hi @huy232 
I followed your comment and added escape:false but HTML tags are not working properly.

**My WEBVTT**
```
WEBVTT

STYLE
::cue {
    background-color: white;
}

STYLE
::cue(blue) {
    color: blue;
}

STYLE
::cue(yellow) {
    background-color: yellow; 
}

STYLE
::cue(green) { 
    color: green; 
}

00:00:03.492 --> 00:00:05.227
Natasha: He <blue>used</blue> the stones again

00:00:05.796 --> 00:00:09.257
Bruce: Heeyyyy!! <yellow>We</yellow> will be going in 
short handed you know?

00:00:10.161 --> 00:00:10.963
He still got the <green>stones</green>, so!!

00:00:10.982 --> 00:00:11.896
Carol: So, let's get them

```
*My artplayer component*
```
subtitle: {
     url: url.vttUrl,
     type: 'vtt',
     escape: false
}
```
Do tell me if i am doing something wrong.

**Comment by zhw2590582** [comment]
@NinjaCoderDotCom Because <green> and <blue> are not standard dom tags, such as <div> and <span>

**Comment by NinjaCoderDotCom** [comment]
@zhw2590582 I know but does these kinda custom tags will not work with artplayer? Coz while creating .vtt file we can cretae these kinda custom tags as mentioned in the offical webvtt documentation ([Link](https://www.w3.org/TR/webvtt1/#styling)).What to do if I have to add color to any target word?

**Comment by zhw2590582** [comment]
@NinjaCoderDotCom The player does not support this vtt style rule
