### ISSUE TITLE
移动端双击切换视频的播放和暂停问题

### ISSUE THREAD

**Issue by Jerry12228** [zhw2590582/ArtPlayer#461]
### Expected behaviour
每连点2次切换一次播放和暂停
### Actual behaviour
如果一直连点, 从连点第三次开始, 每点击一次就会切换播放和暂停
### Steps to reproduce
一直连点
### Environment
在https://artplayer.org/mobile.html测试发现此问题
### Link to where the bug is happening
https://artplayer.org/mobile.html

**Comment by 756751uosmaqy** [comment]
subtitles automatically line when selected escape: false,

![1](https://user-images.githubusercontent.com/116700531/222648936-f6922558-6359-4e0e-adf3-b602e2ee77eb.png)



![2](https://user-images.githubusercontent.com/116700531/222649013-665ac9bc-f2ec-44a6-90f6-629bca5fa9a9.png)

can you fix it , thanks ^^
