### ISSUE TITLE
Subtitles don't display all when there are overlapping subtitles.

### ISSUE THREAD

**Issue by huy232** [zhw2590582/ArtPlayer#462]
### Expected behaviour

Subtitles can overlap each other and display all at the same time.

### Actual behaviour

Subtitles only display 1 part instead of 3 overlap parts leading to there are some scenes that don't have full subtitles, so the user can't understand what the film said.

For example:
```
02:29.290 --> 02:38.470
<b>Oni</b>

02:31.940 --> 02:32.940
Should I do this?

02:34.110 --> 02:36.590
Or maybe... this?
```

Only display the `"Oni"` subtitle part and doesn't display the 2 pieces below since the `"Oni"` part overlaps 2 subtitles below.

### Steps to reproduce
For example:
1. Mount this subtitle and skip to the part around ~2:30 where the subtitles appear the `"Oni"` text, this is where I notice it doesn't display correctly: [Subtitle URL sample](https://cc.zorores.com/80/39/803925bf4ef86043a3eaebb34f7343dc/eng-2.vtt)
2. Mount the video that has a video duration longer than 1:30 since the ArtPlayer's video sample is just only 1:30, so I choose _[Big Buck Bunny that I get from another Github](https://gist.github.com/jsturgis/3b19447b304616f18657)_, video sample: [Video URL sample](http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4)
3. Mount these 2 to the [ArtPlayer](https://artplayer.org/), and set the subtitle to `escape: false` so it can read the HTML tag, too.

**Comment by zhw2590582** [comment]
This is a feature of `vtt` subtitles and cannot be modified temporarily

**Comment by huy232** [comment]
> 

Thanks for your reply @zhw2590582 , is there really no trick or anything that I can do to make the subtitle work the way I want it to? 😃

**Comment by zhw2590582** [comment]
There is currently no better way than modifying the `vtt` file
