### ISSUE TITLE
M3U8 play

### ISSUE THREAD

**Issue by gyxoBka** [zhw2590582/ArtPlayer#463]
Hi, is there a way to don't start immediately video downloading after player mounted ? start it only user click on play button

**Comment by zhw2590582** [comment]
yes

```js
var art = new Artplayer({
    container: '.artplayer-app',
    url: '/assets/sample/video.mp4',
	moreVideoAttr: {
		preload: 'metadata'
	}
});
```

**Comment by gyxoBka** [comment]
@zhw2590582 i found a solution. In this case hls  stream isnt loading after page load.

[LINK](https://artplayer.org/?libs=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fhls.js%2F8.0.0-beta.3%2Fhls.min.js&code=function%20playM3u8(video%2C%20url%2C%20art)%20%7B%0A%20%20%20%20if%20(Hls.isSupported())%20%7B%0A%20%20%20%20%20%20%20%20const%20hls%20%3D%20new%20Hls()%3B%0A%20%20%20%20%20%20%20%20hls.loadSource(url)%3B%0A%20%20%20%20%20%20%20%20hls.attachMedia(video)%3B%0A%0A%20%20%20%20%20%20%20%20%2F%2F%20optional%0A%20%20%20%20%20%20%20%20art.hls%20%3D%20hls%3B%0A%20%20%20%20%20%20%20%20art.once(%27url%27%2C%20()%20%3D%3E%20hls.destroy())%3B%0A%20%20%20%20%20%20%20%20art.once(%27destroy%27%2C%20()%20%3D%3E%20hls.destroy())%3B%0A%20%20%20%20%7D%20else%20if%20(video.canPlayType(%27application%2Fvnd.apple.mpegurl%27))%20%7B%0A%20%20%20%20%20%20%20%20video.src%20%3D%20url%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20art.notice.show%20%3D%20%27Unsupported%20playback%20format%3A%20m3u8%27%3B%0A%20%20%20%20%7D%0A%7D%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20%2F%2F%20url%3A%20%27https%3A%2F%2Ftest-streams.mux.dev%2Fx36xhzz%2Fx36xhzz.m3u8%27%2C%0A%20%20%20%20type%3A%20%27m3u8%27%2C%0A%20%20%20%20customType%3A%20%7B%0A%20%20%20%20%20%20%20%20m3u8%3A%20playM3u8%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20console.info(art.hls)%3B%0A%7D)%3B%0A%0Aart.on(%27click%27%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20art.url%20%3D%20%27https%3A%2F%2Ftest-streams.mux.dev%2Fx36xhzz%2Fx36xhzz.m3u8%27%0A%7D)%3B)

But the spinner in the middle of frame is some annoying. Is there way to show Play icon in the middle ?
