### ISSUE TITLE
向控制条添加控件，能否增加"center"这个位置

### ISSUE THREAD

**Issue by Vanisper** [zhw2590582/ArtPlayer#464]
我在template.js中看到，是预留了一个中间的位置的
![Snipaste_2023-02-06_11-39-08](https://user-images.githubusercontent.com/55046983/216878727-5b68c8fd-8f99-4d95-bf04-1287dcfb26f3.png)
---
但是在ts类型中，以及在内部add方法中，没有对这个地方作导出
![Snipaste_2023-02-06_11-41-05](https://user-images.githubusercontent.com/55046983/216878913-b084a695-d3f5-4866-83d8-e106cedce128.png)

希望作者大大能更新一下

**Comment by Vanisper** [comment]
![Snipaste_2023-02-06_11-50-23](https://user-images.githubusercontent.com/55046983/216879865-730a6303-da39-4c1b-b6d7-f75e7e9a4564.png)
这是目前的解决办法

**Comment by zhw2590582** [comment]
主要是这个"center"太少用到，暂时不打算添加这个配置

**Comment by Vanisper** [comment]
> 

嗯嗯  感谢回复😊
我已经自己拉取项目修改源码了

**Comment by Vanisper** [comment]
> 主要是这个"center"太少用到，暂时不打算添加这个配置

嗯嗯 感谢回复😊
我已经自己拉取项目  修改源码了
