### ISSUE TITLE
能否支持杜比视界的视频播放呢？

### ISSUE THREAD

**Issue by cheneylaw** [zhw2590582/ArtPlayer#466]
期待能支持杜比视界，谢谢

**Comment by zhw2590582** [comment]
什么是杜比视界的视频？有没有可供测试的视频地址？

**Comment by cheneylaw** [comment]
4K 杜比视界（30集全）
https://www.aliyundrive.com/s/xBaERcojzjz

这个是杜比视界的《三体》电视剧的阿里云盘资源，你可以试试看，网页端播放会偏色，不知道网页端的播放器将来能否支持解码杜比视界的视频呢





***@***.***



&nbsp;

**Comment by zhw2590582** [comment]
这其实取决于浏览器支不支持，而不是播放器支不支持，因为播放器不参与音视频解码的过程
