### ISSUE TITLE
video info提供更详细的视频信息

### ISSUE THREAD

**Issue by sceraser** [zhw2590582/ArtPlayer#467]
ArtPlayer视频信息
![](https://user-images.githubusercontent.com/42718757/218046515-7c526087-1746-48e1-87db-88c42ad44b8f.png)
B站视频信息
![](https://user-images.githubusercontent.com/42718757/218046641-4a03333e-4b63-42e5-9132-51b9c936e2d1.png)

希望能提供视频的音视频码率、编码格式、帧率、网速等详细信息

**Comment by zhw2590582** [comment]
你可能误会了，播放器只是对原生的`video`元素进行封装，原生的api并没有提供这些东西，但假如你是使用hls.js的话就有
