### ISSUE TITLE
Add quality select option for artplayerPluginHlsQuality on phone.

### ISSUE THREAD

**Issue by huy232** [zhw2590582/ArtPlayer#468]
I'm currently using `artplayerPluginHlsQuality ` to stream the m3u8 video type.

If I'm on PC, it'll display the quality control in settings. But if I'm using my phone (IOS - iPhone 7), there was no quality selection.

This is how I set up my Artplayer:

```

function playM3u8(video, url, art) {
				if (Hls.isSupported()) {
					const hls = new Hls()
					hls.loadSource(url)
					hls.attachMedia(video)

					// optional
					art.hls = hls
					art.once("url", () => hls.destroy())
					art.once("destroy", () => hls.destroy())
				} else if (video.canPlayType("application/vnd.apple.mpegurl")) {
					video.src = url
				} else {
					art.notice.show = "Unsupported playback format: m3u8"
				}
			}

const art = new Artplayer({
				...option,
				url: "myVideoSource",
				plugins: [
					artplayerPluginHlsQuality({
						setting: true,
						title: "Quality",
						auto: "Auto",
					}),
					artplayerPluginControl(),
				],
				type: "m3u8",
				customType: {
					m3u8: playM3u8,
				},
			return () => {
				if (art && art.destroy) {
					art.destroy(false)
				}
			}
		}
```

Has quality selection on PC:
![image](https://user-images.githubusercontent.com/59156109/218174113-31a0cbae-b499-4afd-b0e8-a4e9c1caed6f.png)

No quality selection when using a phone:
![329569498_540091447937791_362062958569580816_n](https://user-images.githubusercontent.com/59156109/218174479-8dfa6d53-ce5a-4faa-a956-003a8ef8d63b.jpg)

Is this because HLS is having problems with IOS - iPhone, or is it because due to my fault that it doesn't display quality in settings on my phone? Please let me know 😸

**Comment by zhw2590582** [comment]
See this one: https://github.com/zhw2590582/ArtPlayer/issues/440#issuecomment-1369776189
