### ISSUE TITLE
ASS subtitles sometimes appear late

### ISSUE THREAD

**Issue by flixmu** [zhw2590582/ArtPlayer#471]
how do we tell the audience if the subtitles will be displayed, sometimes the audience thinks there are no subtitles in the video, even though they only show up late.

for example displays "Loading Subtitle..." or "Subtitle is currently displayed"

**Comment by zhw2590582** [comment]
Like this ? [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20subtitle%3A%20%7B%0A%20%20%20%20%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.srt%27%2C%0A%20%20%20%20%7D%2C%0A%09layers%3A%20%5B%0A%09%09%7B%0A%09%09%09name%3A%20%27subtitle%27%2C%0A%09%09%09html%3A%20%27Loading%20Subtitle...%27%2C%0A%09%09%09style%3A%20%7B%0A%09%09%09%09textAlign%3A%20%27center%27%2C%0A%09%09%09%09paddingTop%3A%20%2710px%27%0A%09%09%09%7D%0A%09%09%7D%0A%09%5D%0A%7D)%3B%0A%0Aart.once(%27subtitleUpdate%27%2C%20()%20%3D%3E%20%7B%0A%09art.layers.subtitle.style.display%20%3D%20%27none%27%3B%0A%7D))

**Comment by zhw2590582** [comment]
[JavascriptSubtitlesOctopus](https://github.com/libass/JavascriptSubtitlesOctopus) ？I'm not very familiar with ASS subtitle plugin, this can't help you for now
