### ISSUE TITLE
Can I get some help and example on creating custom button on screen.

### ISSUE THREAD

**Issue by huy232** [zhw2590582/ArtPlayer#472]
I have a video and it has the `start` and `end` duration info of an intro already, I want to create a button that appears near the right of the screen (inside the video player range), if the `currentTime` of the video passes the `end`, it'll disappear and won't appear again.

Can you help me with a small example where the part about creating the custom button, I think I can handle the logic part above so I don't want to bother you too much, I just really don't know how to implement the button inside the screen of the video player and work together with the video player.

**Comment by zhw2590582** [comment]
You mean, display a button on the video during a certain time period of the video?

**Comment by huy232** [comment]
> You mean, display a button on the video during a certain time period of the video?

Yes, but I don't know how to create a button inside the video player, I just only know how to add something into the bottom controls through the docs 😃 , can you help me with a little example, thanks.

**Comment by zhw2590582** [comment]
Like this ? [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09layers%3A%20%5B%0A%09%09%7B%0A%09%09%09name%3A%20%27button%27%2C%0A%09%09%09html%3A%20%27%3Cbutton%20type%3D%22button%22%3EClick%20me%20!!%3C%2Fbutton%3E%27%2C%0A%09%09%09style%3A%20%7B%0A%09%09%09%09display%3A%20%27none%27%2C%0A%09%09%09%09position%3A%20%27absolute%27%2C%0A%09%09%09%09right%3A%20%2720px%27%2C%0A%09%09%09%09top%3A%20%2720px%27%2C%0A%09%09%09%7D%2C%0A%09%09%09click()%20%7B%0A%09%09%09%09console.info(%27Click%20me%20!!%27)%3B%0A%09%09%09%7D%2C%0A%09%09%09mounted(button)%20%7B%0A%09%09%09%09this.on(%27video%3Atimeupdate%27%2C%20()%20%3D%3E%20%7B%0A%09%09%09%09%09if%20(this.currentTime%20%3E%205%20%26%26%20this.currentTime%20%3C%2010)%20%7B%0A%09%09%09%09%09%09button.style.display%20%3D%20%27block%27%3B%0A%09%09%09%09%09%7D%20else%20%7B%0A%09%09%09%09%09%09button.style.display%20%3D%20%27none%27%3B%0A%09%09%09%09%09%7D%0A%09%09%09%09%7D)%3B%0A%09%09%09%7D%0A%09%09%7D%0A%09%5D%0A%7D)%3B)

The button will show up between 5 seconds and 10 seconds

https://artplayer.org/document/en/start/component.html#layers

**Comment by huy232** [comment]
> Like this ? [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09layers%3A%20%5B%0A%09%09%7B%0A%09%09%09name%3A%20%27button%27%2C%0A%09%09%09html%3A%20%27%3Cbutton%20type%3D%22button%22%3EClick%20me%20!!%3C%2Fbutton%3E%27%2C%0A%09%09%09style%3A%20%7B%0A%09%09%09%09display%3A%20%27none%27%2C%0A%09%09%09%09position%3A%20%27absolute%27%2C%0A%09%09%09%09right%3A%20%2720px%27%2C%0A%09%09%09%09top%3A%20%2720px%27%2C%0A%09%09%09%7D%2C%0A%09%09%09click()%20%7B%0A%09%09%09%09console.info(%27Click%20me%20!!%27)%3B%0A%09%09%09%7D%2C%0A%09%09%09mounted(button)%20%7B%0A%09%09%09%09this.on(%27video%3Atimeupdate%27%2C%20()%20%3D%3E%20%7B%0A%09%09%09%09%09if%20(this.currentTime%20%3E%205%20%26%26%20this.currentTime%20%3C%2010)%20%7B%0A%09%09%09%09%09%09button.style.display%20%3D%20%27block%27%3B%0A%09%09%09%09%09%7D%20else%20%7B%0A%09%09%09%09%09%09button.style.display%20%3D%20%27none%27%3B%0A%09%09%09%09%09%7D%0A%09%09%09%09%7D)%3B%0A%09%09%09%7D%0A%09%09%7D%0A%09%5D%0A%7D)%3B)
> 
> The button will show up between 5 seconds and 10 seconds
> 
> https://artplayer.org/document/en/start/component.html#layers

YES, that's what I'm looking for, thanks @zhw2590582
