### ISSUE TITLE
Dash Quality Selector

### ISSUE THREAD

**Issue by flixmu** [zhw2590582/ArtPlayer#473]
Hi, Can i add qulaity selector in dash video?

**Comment by zhw2590582** [comment]
Of course, maybe I have to write a plugin for dash, If I finish writing this plugin, I will let you know here

**Comment by zhw2590582** [comment]
`artplayer-plugin-dash-quality@1.0.0` has been released to npm, the usage is the same as `artplayer-plugin-hls-quality`: [demo](https://artplayer.org/?libs=https://cdnjs.cloudflare.com/ajax/libs/dashjs/4.5.2/dash.all.min.js%0A./uncompiled/artplayer-plugin-dash-quality/index.js&example=dash.quality)
