### ISSUE TITLE
Test the webtor plugin 

### ISSUE THREAD

**Issue by metab0** [zhw2590582/ArtPlayer#474]
hello there, can you test webtor sdk in artplayer? Below is the link of sdk please check it out this link https://github.com/webtor-io/embed-sdk-js

**Comment by zhw2590582** [comment]
I checked the source code of this sdk, it uses iframe to play magnet or torrentUrl, so it cannot replace its player with artplayer

But you can try this way: 
https://github.com/webtorrent/webtorrent
https://github.com/zhw2590582/ArtPlayer/issues/456
