### ISSUE TITLE
请问能播放实时流吗

### ISSUE THREAD

**Issue by manyhelp** [zhw2590582/ArtPlayer#475]
websocket接收推过来的H264数据，然后实时播放。

ws.onmessage = (event) => {
    let data = new Uint8Array(event.data)
    //解码然后播放
};

1、视频是H264编码。不是MP4、TS、FLV等文件。
2、请问这种方式延迟高吗？是否考虑用FFmpeg转WASM 解码？

**Comment by manyhelp** [comment]
使用 MSE 进行播放，会有兼容性问题吧？ 手机浏览器好像不支持

**Comment by zhw2590582** [comment]
假如你要考虑手机的话，那目前没有方案了
