### ISSUE TITLE
能否对addListener事件做一下处理

### ISSUE THREAD

**Issue by Vanisper** [zhw2590582/ArtPlayer#476]
能否对这一行代码做一下修改([点击跳转到指定位置](https://github.com/zhw2590582/ArtPlayer/blob/master/packages/artplayer/src/events/index.js#L26))：
```js
proxy(target, name, callback, option = {}) {
// ...
}
```

修改成`proxy(target, name, callback, option = { passive: true }`
原因：
有时会因为这个，浏览器控制台会提示警告`[Violation] Added non-passive event listener to a ...`

**Comment by zhw2590582** [comment]
可以参考这个
https://github.com/zhw2590582/ArtPlayer/issues/385

**Comment by Vanisper** [comment]
> 可以参考这个 #385

哦哦  好的  谢谢大佬
