### ISSUE TITLE
字幕为什么无法显示呢?

### ISSUE THREAD

**Issue by how4ever** [zhw2590582/ArtPlayer#48]
为什么srt字幕无法加载显示呢??
win10下用的chrome浏览器. 显示srt字幕, 看chrome里的警告是 Resource interpreted as TextTrack but transferred with MIME type text/plain: "http://127.0.0.1/Imitationgame/The.Imitation.Game.2014.BluRay.720p.chs_eng.srt"
导入的是artplayer.css和artplayer.js文件.
用下面教程的方法显示的字幕.
var art = new Artplayer({
    container: '.artplayer-app',
    url: url + '/video/one-more-time-one-more-chance-480p.mp4',
    subtitle: {
        url: url + '/subtitle/one-more-time-one-more-chance.srt',
        style: {
            color: '#03A9F4',
        },
    },
});

**Comment by zhw2590582** [comment]
再试试刚刚发的版本`@3.1.17`。

**Comment by how4ever** [comment]
> 再试试刚刚发的版本`@3.1.17`。

试了,还是不行. 奇怪的是在ie等其他浏览器都没问题. 就是chrome78不行. 不知道是不是chrome的什么特殊安全策略导致的字幕文件无法从本地加载.

**Comment by zhw2590582** [comment]
有没有一个我这边可以访问的地址URL？我来试试

**Comment by how4ever** [comment]
> 有没有一个我这边可以访问的地址URL？我来试试
好像是本地资源加载的问题, 可能和服务器的设置有关吧. 不管了, 先关了. 反正我自己用的,不用chrome就完事了.

**Comment by how4ever** [comment]
close
