### ISSUE TITLE
can't play hls m3u8 

### ISSUE THREAD

**Issue by a0937027831** [zhw2590582/ArtPlayer#483]
### Expected behaviour
play m3u8 livestream

### Actual behaviour
Uncaught TypeError: Cannot read properties of undefined (reading 'call')

### Steps to reproduce
1.open cmd
2.input npx nuxi init video_test
3.npm install artplayer、npm install hls、npm install artplayer-plugin-hls-quality

### Environment
-   Browser: chorme
-   Version: 110.0.5481.178
-   Operating System: nuxt
-   Version: 3.2.3

### Console errors (if any)
Uncaught TypeError: Cannot read properties of undefined (reading 'call')

### Link to where the bug is happening

[online editor](https://codesandbox.io/p/github/a0937027831/artplayer/main?file=%2FREADME.md&workspace=%257B%2522activeFileId%2522%253A%2522cleziyos50008g8hs53j1e3ho%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522cleziyrvl0015356iilz4azv7%2522%253A%257B%2522key%2522%253A%2522cleziyrvl0015356iilz4azv7%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clezj57mz007q356iovw8t3vp%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clezj55mp0055356iu54ikuzs%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522cleziyrvl0015356iilz4azv7%2522%252C%2522spacesOrder%2522%253A%255B%2522cleziyrvl0015356iilz4azv7%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)

**Comment by zhw2590582** [comment]
https://github.com/video-dev/hls.js/issues/5146#issuecomment-1375070955

**Comment by a0937027831** [comment]
> [video-dev/hls.js#5146（評論）](https://github.com/video-dev/hls.js/issues/5146#issuecomment-1375070955)

Many thanks for your reply
