### ISSUE TITLE
player buffering not stopped when changing web page

### ISSUE THREAD

**Issue by jedgarf** [zhw2590582/ArtPlayer#488]
how to stop player buffering when page has changed?

**Comment by zhw2590582** [comment]
Is your playback address an ordinary `.mp4` address, or a `.m3u8` address?

**Comment by jedgarf** [comment]
.m3u8

> Is your playback address an ordinary `.mp4` address, or a `.m3u8` address?

**Comment by zhw2590582** [comment]
When the page changes, you need to destroy the instance of hls yourself: `hls.destroy()`

**Comment by jedgarf** [comment]
I'll try this, thanks
