### ISSUE TITLE
How can I set offset subtitle to some specific seconds by default of every video?

### ISSUE THREAD

**Issue by huy232** [zhw2590582/ArtPlayer#489]
Hi, how can I set offset subtitle by default when the video loads?
My video has ads for 5 seconds of every video at the beginning, but the subtitle I have is the subtitle for the video that doesn't contain ads, so now the subtitle has been slower by default for 5 seconds.
Mean, I want the subtitle to be offset by default 5 seconds behind the scene for every video. But in the offset option, I still want the offset option to be set as 0 (not by 5 seconds) so the user can adjust by themselves or for some other cases, too.

I found a case similar and saw this `demo` but it seems outdated:
[Demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09subtitleOffset%3A%20true%2C%0A%20%20%20%20subtitle%3A%20%7B%0A%20%20%20%20%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.srt%27%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%09art.plugins.subtitleOffset.offset(5)%0A%7D)%3B)

Because after I tried `art.plugins.subtitleOffset.offset(5)`, it doesn't work anymore and the error I receive was: 
`Uncaught TypeError: Cannot read properties of undefined (reading 'offset')`

I tried this one from the document:
```
art.on('subtitleOffset', (offset) => {
    console.info('subtitleOffset', offset);
});
```

But it just show the offset changed when I interact with the offset subtitle option.

**Comment by zhw2590582** [comment]
This problem is a bit complicated, and the player does not have this function. The best way is to offset the time of the subtitle before the player loads the subtitle

What format are your subtitles in? srt, ass or vtt?

**Comment by huy232** [comment]
> This problem is a bit complicated, and the player does not have this function. The best way is to offset the time of the subtitle before the player loads the subtitle
> 
> What format are your subtitles in? srt, ass or vtt?

I’m using vtt

**Comment by zhw2590582** [comment]
try this: [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09setting%3A%20true%2C%0A%09subtitleOffset%3A%20true%2C%0A%09subtitle%3A%20%7B%0A%09%09url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.vtt%27%0A%09%7D%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%09art.subtitleOffset%20%3D%205%3B%0A%09art.notice.show%20%3D%20%27%27%3B%0A%7D)%3B)

**Comment by huy232** [comment]
> try this: [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09setting%3A%20true%2C%0A%09subtitleOffset%3A%20true%2C%0A%09subtitle%3A%20%7B%0A%09%09url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.vtt%27%0A%09%7D%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%09art.subtitleOffset%20%3D%205%3B%0A%09art.notice.show%20%3D%20%27%27%3B%0A%7D)%3B)

Thank you so much, it's work for my case now. I'll close issue.
