### ISSUE TITLE
移动版优化，字幕，悬浮提示开关 问题

### ISSUE THREAD

**Issue by kazegh** [zhw2590582/ArtPlayer#491]
移动版长按右键的功能没有了，而且播放图标在正中间没有PC版好看，
PC版界面字体太小了，鼠标悬浮按钮图标时的提示过于多余了。

**Comment by kazegh** [comment]
我的意思是加一个悬浮提示的开关，移动版界面就有PC版的，蛮好看的.

**Comment by kazegh** [comment]
art.subtitle.url可以对初始化未开字幕后再更新字幕，但是字幕偏移开关不起效啊？art.option.subtitleOffset=true

**Comment by kazegh** [comment]
@zhw2590582 配置了双击全屏，每次都会让视频暂停（貌似有点击暂停事件） art.on('dblclick',()=>{art.fullscreen=!art.fullscreen});

**Comment by zhw2590582** [comment]
> art.subtitle.url可以对初始化未开字幕后再更新字幕，但是字幕偏移开关不起效啊？art.option.subtitleOffset=true;而且不支持srt字幕显示（帮助文档却说支持，需要转换vtt） @zhw2590582

其实很多播放的状态是无法带到下一个播放地址的，假如你遇到这个情况，建议可以销毁播放器再重新实例化，而不是切换播放地址

你指的不支持srt是什么意思？播放器是支持的srt和ass的

**Comment by kazegh** [comment]
> > art.subtitle.url可以对初始化未开字幕后再更新字幕，但是字幕偏移开关不起效啊？art.option.subtitleOffset=true;而且不支持srt字幕显示（帮助文档却说支持，需要转换vtt） @zhw2590582
> 
> 其实很多播放的状态是无法带到下一个播放地址的，假如你遇到这个情况，建议可以销毁播放器再重新实例化，而不是切换播放地址
> 
> 你指的不支持srt是什么意思？播放器是支持的srt和ass的
支持srt和ass？是需要插件库支持吧？（帮助文档没有详细说明，上面说的可以直接支持，实际上我测试不行，用磁力链接测试的，先判断有字幕，用sub.getBlob() 转文本，再srt转vtt，再转blobURL，）art.subtitle.url=赋值);https://unpkg.com/artplayer@4.6.2/src/utils/subtitle.js

**Comment by zhw2590582** [comment]
https://artplayer.org/document/start/option.html#subtitle

[srt字幕演示](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20subtitle%3A%20%7B%0A%20%20%20%20%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.srt%27%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B%0A)

[ass字幕演示](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20subtitle%3A%20%7B%0A%20%20%20%20%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.ass%27%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B)

可以把你的字幕链接或者文件发给我吗，我测试一下

**Comment by kazegh** [comment]
> https://artplayer.org/document/start/option.html#subtitle
> 
> [srt字幕演示](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20subtitle%3A%20%7B%0A%20%20%20%20%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.srt%27%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B%0A)
> 
> [ass字幕演示](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20subtitle%3A%20%7B%0A%20%20%20%20%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.ass%27%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B)
> 
> 可以把你的字幕链接或者文件发给我吗，我测试一下
用的磁力链接测试，字幕不是简单的在线网址，
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no,minimal-ui">
<style>.artplayer-app{width:100%}
body,html{width:100%;height:auto;padding:0;margin:0;overflow:hidden}
div.art-progress-indicator{block-size:5px!important}
.art-info{width:472px!important}.art-info-content{width:358px!important}.art-info-content[data-video="src"]{white-space:normal !important;word-break:break-all !important}.art-video-player .art-state,.art-video-player.art-loading-show .art-loading{position:absolute!important;opacity:0.2!important}
</style>
<script src="https://fastly.jsdelivr.net/npm/webtorrent@1.8.26/webtorrent.min.js"></script>
<script src="https://fastly.jsdelivr.net/npm/artplayer/dist/artplayer.js"></script>
</head>
<body>
<div class="artplayer-app"></div>
<script>
//https://cdnjs.cloudflare.com/ajax/libs/hls.js/8.0.0-beta.3/hls.min.js
//https://cdn.jsdelivr.net/npm/webtorrent@2.0.13/index.min.js
var source='magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fsintel.torrent';
var mtype='';if(source.indexOf('magnet:')>-1){mtype='torrent'}else{mtype=source.match(/mp4|ogg|webm|m3u8|flv/)[0]};
var artoption={
  container: '.artplayer-app',
  url: source,
  type: mtype,
  autoplay: true,
  setting: true,
  hotkey: false,
  fullscreen: true,
  playbackRate: true,
  aspectRatio: true,
  lang:'en',
  autoOrientation: true,
  //title: 'video-title',screenshot: true,
  //controls:[{name:'mspeed',position:'right',html:'1',selector:[{html:'<span>0.5</span>'},{html:'<span>0.75</span>'},{default:true,html:'<span>1</span>'},{html:'<span>1.25</span>'},{html:'<span>1.5</span>'},{html:'<span>2</span>'}],onSelect:function(item,$dom){art.playbackRate=Number($dom.innerText);console.info(this);art.controls.mspeed.show = !1;return item.html}}]
};
if(mtype=='torrent'&&source&&window.WebTorrent&&window.WebTorrent.WEBRTC_SUPPORT){
  var announce=["http://1337.abcvg.info:80/announce","http://bt.okmp3.ru:2710/announce","http://bt1.letpo.com:80/announce"];
  artoption.customType={
    "torrent": function(video, url, art) {
      var client = new WebTorrent();
      client.add(url,{announce:announce}, function (torrent) {
        var file = torrent.files.find((file)=>/\.mp4/.test(file.name));
        console.log(torrent.files.map(a=>a.name).join('\n'));
        if(file){
          file.renderTo(video,{autoplay:art.option.autoplay,controls: false},()=>{console.info(art.torrent)});
          art.notice.show=file.name+' '+Math.round(file.length/1048576)+'M';
          var infoAdd=(ahtm)=>{var td=document.createElement("div"); td.className='art-info-item';td.innerHTML=ahtm;document.querySelector('.art-info-panel').appendChild(td)};
          infoAdd('\n        <div class="art-info-title">File:</div>\n        <div class="art-info-content">'+file.name+' '+Math.round(file.length/1048576)+'M</div>');
          infoAdd('\n        <div class="art-info-title">_userAgent: </div>\n        <div class="art-info-content">'+torrent.discovery._userAgent+'</div>');
          infoAdd('\n        <div class="art-info-title">Speed Download: </div>\n        <div class="art-info-content download"></div>');
          var sub=torrent.files.find((file)=>/(zh|en)\.(srt|vtt|ass)/.test(file.name));
          if(sub){
            art.notice.show='字幕: '+sub.name;
            sub.getBlob(function (err, blob) {
              if (err) {
                console.error('getBlobURL err:'+err);
              } else {
                var reader = new FileReader();
                reader.onload = function() {
                  var srtText = reader.result;
                  var subt=sub.name.match(/(srt|vtt|ass)/)[0];
                  var webvtt = subt=='srt'?srtToVtt(srtText):srtText;
                  var vblob = new Blob([webvtt], { type: 'text/vtt' });//vttToBlob(vttText)
                  var suburl = URL.createObjectURL(vblob);console.log(webvtt);
                  art.subtitle.url=suburl;art.subtitle.style({color: 'red',fontSize:'20px',bottom:'40px',color:'#fff'});art.option.subtitleOffset=true;//art.subtitle.encoding='utf-8';escape 转义 html 标签
                  art.controls.add({name:'subtitle',position:'right',html:'Subtitle',selector:[{default:true,html:'<span>'+sub.name+'</span>'}],onSelect:function(item,$dom){console.info(item, $dom);return item.html},click:function(...args){art.subtitle.show=!art.subtitle.show}});
                }
                reader.readAsText(blob);
              }
            })
          }
        }else{art.notice.show=torrent.files.map(a=>a.name).join('\n')};
        torrent.on('download',()=>{if(art.info.show){document.querySelector('.art-info-panel .art-info-content.download').innerText=Math.round(torrent.downloadSpeed/1024)+' kb  '+Math.round(torrent.timeRemaining/60000)+'min  '+(torrent.progress*100).toFixed(1)+'%  '+torrent.numPeers+ 'peer(s)'}});
        torrent.on('error',function(err){console.log('torrent error: '+err.message,300000,0.8)});
        torrent.on('noPeers',function(announceType){console.log('noPeers: '+announceType,3000,0.8)});
      });
      art.torrent = client;
      art.once('url', () => client.destroy());
      art.once('destroy', () => client.destroy());
    }
  }
  function fixSrt(srt){
    return srt.replace(/(\d\d:\d\d:\d\d)[,.](\d+)/g,(_,$1,$2)=>{let ms=$2.slice(0,3);if($2.length===1){ms=$2+'00'}if($2.length===2){ms=$2+'0'}return `${$1},${ms}`})
  }
  function srtToVtt(srtText){
    return'WEBVTT \r\n\r\n'.concat(fixSrt(srtText).replace(/\{\\([ibu])\}/g,'</$1>').replace(/\{\\([ibu])1\}/g,'<$1>').replace(/\{([ibu])\}/g,'<$1>').replace(/\{\/([ibu])\}/g,'</$1>').replace(/(\d\d:\d\d:\d\d),(\d\d\d)/g,'$1.$2').replace(/{[\s\S]*?}/g,'').concat('\r\n\r\n'))
  }
}
var art=new Artplayer(artoption);
art.on('dblclick',()=>{art.fullscreen=!art.fullscreen});
art.on('error',(error,reconnectTime)=>{art.notice.show=error+','+reconnectTime});

//问题 移动版右键；controls点击隐藏；tooltips隐藏
//https://unpkg.com/artplayer@4.6.2/src/utils/subtitle.js
</script>
</body>
</html>

**Comment by zhw2590582** [comment]
你这混乱的代码我看不懂，而且字幕只支持http链接，不支持磁力链接
