### ISSUE TITLE
移动版中心的播放按钮能隐藏吗？

### ISSUE THREAD

**Issue by slash130** [zhw2590582/ArtPlayer#492]
是否能通过配置隐藏中心的播放按钮，这个按钮和继续观看的提示有点重叠了。

**Comment by zhw2590582** [comment]
这可以使用css把它隐藏掉的

**Comment by slash130** [comment]
还有个问题，m3u8的视频在ios端未开始播放之前有个加载的动图一直在转，开始播放之后就没了，安卓上没有出现这问题。

**Comment by zhw2590582** [comment]
在ios上，在播放之前显示加载状态是正常的
