### ISSUE TITLE
hls画质切换bug

### ISSUE THREAD

**Issue by lemontea66** [zhw2590582/ArtPlayer#493]
调用HLS的画质切换有bug，理论上讲应该是切换画质后刷新已加载的ts文件，例如：目前是4K画质，我选择了1080后应该整体变为1080画质，而目前plugin的问题是切换画质后，之前的ts文件还在，就会存在之前几秒的东西始终是4K的这个问题。（可能表述不太清楚，到但是看下图应该能理解到我的意思）
![image](https://user-images.githubusercontent.com/75238397/228737763-1856ad93-0d34-4f32-a0e1-7f1b023e1791.png)

**Comment by zhw2590582** [comment]
在最新版中已修复
