### ISSUE TITLE
不能拦截控制栏按钮双击事件

### ISSUE THREAD

**Issue by xinggsf** [zhw2590582/ArtPlayer#495]
我增加一个快进按钮，想拦截其双击事件，试了多种方法都做不到！！

在mounted和ready事件中都试了，拦截不了。右键菜单事件就能拦截，真是令我困惑

```
const preventEvent = ev => {
	if (!ev.target.closest('.art-control')) return;
	ev.stopPropagation();
	ev.preventDefault();
};
mounted(el) {
	art.template.$controls.addEventListener('contextmenu', preventEvent);
	art.template.$controls.addEventListener('dblclick', preventEvent);
	art.controls.playAndPause.after(el);
	art.proxy(el, 'mousedown', ev => {
		if (art.duration && ev.button > 0)
			art.currentTime += ev.button == 1 ? 1 : 20;
	});
}
```

**Comment by zhw2590582** [comment]
我不理解你的意思，为什么要拦截控制栏按钮双击事件

**Comment by xinggsf** [comment]
> 

有时要快速快进而连按键，但没必要引发双击！

想再问个问题：
怎么用art.icons属性添加按钮的SVG图标？

**Comment by zhw2590582** [comment]
art.icons 都是一些内置的图标，属性都是dom，不过需要实例化之后才能访问到

```js
var art = new Artplayer({
    container: '.artplayer-app',
    url: '/assets/sample/video.mp4',
});

art.controls.add({
    position: 'right',
    html: art.icons.airplay
});
```

**Comment by xinggsf** [comment]
报告BUG:
鼠标还在点击控制栏按钮，控制栏就自动隐藏了！应该设置为悬停于控制栏时、有鼠标动作时，不隐藏

**Comment by xinggsf** [comment]
> art.icons 都是一些内置的图标，属性都是dom，不过需要实例化之后才能访问到

我在 Icons类中看到如下代码：
```
            close,
            airplay,
            ...art.option.icons,
        };
```
是否意味着能在实例化时添加自定义图标？

**Comment by zhw2590582** [comment]
> 报告BUG: 鼠标还在点击控制栏按钮，控制栏就自动隐藏了！应该设置为悬停于控制栏时、有鼠标动作时，不隐藏

这个没遇到过，你有复现的url吗？

**Comment by zhw2590582** [comment]
> > art.icons 都是一些内置的图标，属性都是dom，不过需要实例化之后才能访问到
> 
> 我在 Icons类中看到如下代码：
> 
> ```
>             close,
>             airplay,
>             ...art.option.icons,
>         };
> ```
> 
> 是否意味着能在实例化时添加自定义SVG图标？

是的: https://artplayer.org/document/start/option.html#icons

**Comment by zhw2590582** [comment]
你需要Object.assign(art.option.icons这段代码放到插件的顶部，而不是最后

**Comment by xinggsf** [comment]
> 你需要Object.assign(art.option.icons这段代码放到插件的顶部，而不是最后

大佬，这样并没用啊！！！

**Comment by zhw2590582** [comment]
看看这样行不行：[demo](https://artplayer.org/?libs=&code=function%20artPlus()%20%7B%0A%09return%20art%20%3D%3E%20%7B%0A%09%09art.controls.add(%7B%0A%09%09%09position%3A%20%27right%27%2C%0A%09%09%09html%3A%20art.icons.forward%0A%09%09%7D)%3B%0A%09%09art.controls.add(%7B%0A%09%09%09position%3A%20%27right%27%2C%0A%09%09%09html%3A%20art.icons.rewind%0A%09%09%7D)%3B%0A%09%7D%0A%7D%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09plugins%3A%20%5BartPlus()%5D%2C%0A%09icons%3A%20%7B%0A%09%09forward%3A%20%27%3Csvg%20viewBox%3D%220%200%2018%2018%22%3E%3Cpath%20d%3D%22M7.875%207.171L0%201v16l7.875-6.171V17L18%209%207.875%201z%22%3E%3C%2Fpath%3E%3C%2Fsvg%3E%27%2C%0A%09%09rewind%3A%20%27%3Csvg%20viewBox%3D%220%200%2018%2018%22%3E%3Cpath%20d%3D%22M10.125%201L0%209l10.125%208v-6.171L18%2017V1l-7.875%206.171z%22%3E%3C%2Fpath%3E%3C%2Fsvg%3E%27%2C%0A%09%7D%2C%0A%7D)%3B)

**Comment by xinggsf** [comment]
@zhw2590582
这样就封装不完整为一个插件了

**Comment by zhw2590582** [comment]
那可以这样，其实不用太纠结把icon放在哪里的，[demo](https://artplayer.org/?libs=&code=function%20artPlus()%20%7B%0A%09return%20art%20%3D%3E%20%7B%0A%09%09Object.assign(art.icons%2C%20%7B%0A%09%09%09forward%3A%20%27%3Csvg%20viewBox%3D%220%200%2018%2018%22%3E%3Cpath%20d%3D%22M7.875%207.171L0%201v16l7.875-6.171V17L18%209%207.875%201z%22%3E%3C%2Fpath%3E%3C%2Fsvg%3E%27%2C%0A%09%09%09rewind%3A%20%27%3Csvg%20viewBox%3D%220%200%2018%2018%22%3E%3Cpath%20d%3D%22M10.125%201L0%209l10.125%208v-6.171L18%2017V1l-7.875%206.171z%22%3E%3C%2Fpath%3E%3C%2Fsvg%3E%27%2C%0A%09%09%7D)%0A%09%09art.controls.add(%7B%0A%09%09%09position%3A%20%27right%27%2C%0A%09%09%09html%3A%20art.icons.forward%0A%09%09%7D)%3B%0A%09%09art.controls.add(%7B%0A%09%09%09position%3A%20%27right%27%2C%0A%09%09%09html%3A%20art.icons.rewind%0A%09%09%7D)%3B%0A%09%7D%0A%7D%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09plugins%3A%20%5BartPlus()%5D%2C%0A%7D)%3B)

**Comment by xinggsf** [comment]
> 那可以这样，其实不用太纠结把icon放在哪里的

图标全变黑了，看不清啊

**Comment by xinggsf** [comment]
@zhw2590582
控制栏应该设置为悬停于控制栏时、有鼠标动作时，不隐藏！
你可安装[我的豆瓣脚本](https://raw.github.com/xinggsf/gm/master/gf-459540.user.js)，测试自动隐藏问题

**Comment by zhw2590582** [comment]
加个svg样式就可以了：[demo](https://artplayer.org/?libs=&code=function%20artPlus()%20%7B%0A%09return%20art%20%3D%3E%20%7B%0A%09%09Object.assign(art.icons%2C%20%7B%0A%09%09%09forward%3A%20%27%3Csvg%20fill%3D%22%23fff%22%20viewBox%3D%220%200%2018%2018%22%3E%3Cpath%20d%3D%22M7.875%207.171L0%201v16l7.875-6.171V17L18%209%207.875%201z%22%3E%3C%2Fpath%3E%3C%2Fsvg%3E%27%2C%0A%09%09%09rewind%3A%20%27%3Csvg%20fill%3D%22%23fff%22%20viewBox%3D%220%200%2018%2018%22%3E%3Cpath%20d%3D%22M10.125%201L0%209l10.125%208v-6.171L18%2017V1l-7.875%206.171z%22%3E%3C%2Fpath%3E%3C%2Fsvg%3E%27%2C%0A%09%09%7D)%0A%09%09art.controls.add(%7B%0A%09%09%09position%3A%20%27right%27%2C%0A%09%09%09html%3A%20art.icons.forward%0A%09%09%7D)%3B%0A%09%09art.controls.add(%7B%0A%09%09%09position%3A%20%27right%27%2C%0A%09%09%09html%3A%20art.icons.rewind%0A%09%09%7D)%3B%0A%09%7D%0A%7D%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09plugins%3A%20%5BartPlus()%5D%2C%0A%7D)%3B)

**Comment by zhw2590582** [comment]
> @zhw2590582 控制栏应该设置为悬停于控制栏时、有鼠标动作时，不隐藏！ 你可安装[我的豆瓣脚本](https://raw.github.com/xinggsf/gm/master/gf-459540.user.js)，测试自动隐藏问题

这个在官网复现不了啊，本来就是鼠标经过时不隐藏的

**Comment by xinggsf** [comment]
@zhw2590582 
感谢您的耐心回复
