### ISSUE TITLE
ArtPlayer plugin for multi audio

### ISSUE THREAD

**Issue by SinonCute** [zhw2590582/ArtPlayer#498]
Hi, I'm looking for a solution use multi-audio for ArtPlayer, I heard my friend say, ArtPlayer has a plugin for that.

**Comment by zhw2590582** [comment]
If you don't use a third-party decoding library, it is currently impossible to switch audio: https://caniuse.com/?search=audioTracks

But if you use `hls.js` or `dash.js` it can be done, then you need to refer to their documentation

**Comment by SinonCute** [comment]
I working with dash.js

**Comment by zhw2590582** [comment]
So, your video and audio are two separate files? If this is the case, artplayer can play these two files at the same time, just need to develop such a plug-in separately

**Comment by SinonCute** [comment]
I am stuck at writing a plugin for Artplayer, I'm using reactjs and it didn't come together.  I have 2 separate file dash

**Comment by zhw2590582** [comment]
If both files are dash, then this plugin will be a bit complicated

**Comment by SinonCute** [comment]
I'm not familiar with artplayer plugin (not even done one yet 😢 )

**Comment by zhw2590582** [comment]
The process is like this, create two artplayer players, one plays video, the other plays audio (hidden), and then synchronizes the playback progress of the two players

**Comment by SinonCute** [comment]
I understood the problem but still can't write a plugin, I got stuck when trying to import artplayer as a dependency 😞

**Comment by zhw2590582** [comment]
Do you have the urls for these two dash files? I want to see if I can write this plugin for you

**Comment by zhw2590582** [comment]
Do you have the urls for these two dash files? I want to see if I can write this plugin for you

**Comment by SinonCute** [comment]
Yes, but it will expire soon about 2 hours
Video:
- https://upos-sz-mirrorcosbstar1.bilivideo.com/iupxcodeboss/hh/ef/n230331er18squio9cce2u208uvxefhh-1-261210110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1681535995&gen=playurlv2&os=cosbstar1bv&oi=2883744842&trid=7237a1b2645c4766b525f647131cf1e5i&mid=1674015840&platform=pc&upsig=16148894aa133139cbf4f3cc25f9d99b&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,2&logo=00000000
- https://upos-bstar1-mirrorakam.akamaized.net/iupxcodeboss/hh/ef/n230331er18squio9cce2u208uvxefhh-1-261210110000.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1681535995&gen=playurlv2&os=akam&oi=2883744842&trid=7237a1b2645c4766b525f647131cf1e5i&mid=1674015840&platform=pc&upsig=e05c5493e1e65ae2411f6438c9821e83&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&hdnts=exp=1681535995~hmac=cabe98c119e63d6ab4299d2225161a94cfa139c34a9db2fed82f2a8f6b06cf41&bvc=vod&nettype=0&orderid=1,2&logo=00000000

Audio:
- https://upos-sz-mirrorgcsbstar1.bilivideo.com/iupxcodeboss/hh/ef/n230331er18squio9cce2u208uvxefhh-1-2a1301000023.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1681535995&gen=playurlv2&os=gcsbstar1bv&oi=2883744842&trid=7237a1b2645c4766b525f647131cf1e5i&mid=1674015840&platform=pc&upsig=0752d08fe5364e61c8ac602abf4099de&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&URLPrefix=aHR0cHM6Ly91cG9zLXN6LW1pcnJvcmdjc2JzdGFyMS5iaWxpdmlkZW8uY29tL2l1cHhjb2RlYm9zcy9oaC9lZi9uMjMwMzMxZXIxOHNxdWlvOWNjZTJ1MjA4dXZ4ZWZoaC0xLTJhMTMwMTAwMDAyMy5tNHM=&Expires=1681535995&KeyName=bilibili&Signature=TMpvxwmYlP7M3QXhErxgZQQFfBg=&bvc=vod&nettype=0&orderid=0,2&logo=00000000
- https://upos-sz-mirrorcosbstar1.bilivideo.com/iupxcodeboss/hh/ef/n230331er18squio9cce2u208uvxefhh-1-2a1301000023.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1681535995&gen=playurlv2&os=cosbstar1bv&oi=2883744842&trid=7237a1b2645c4766b525f647131cf1e5i&mid=1674015840&platform=pc&upsig=2e125f4e2b9b680e5d16f9119227903e&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=1,2&logo=00000000

**Comment by SinonCute** [comment]
Let me know if you want me to renew the link.

**Comment by zhw2590582** [comment]
I think this plugin is too complicated and the use case is rare, so I can't write this plugin for you at the moment, sorry

**Comment by SinonCute** [comment]
Ty,
