### ISSUE TITLE
Replacing selector in  control

### ISSUE THREAD

**Issue by gaozhangmin** [zhw2590582/ArtPlayer#499]
How do i remove a control which was added by `artplayer.controls.add`,
Or, How can i replace the selector in control?

**Comment by gaozhangmin** [comment]
Please show me how to hide the old and create new, 
I read the docs, ` art.controls.show = false` seems to take no effect;  @zhw2590582 
```
art.controls.add({
        name: '播放列表',
        index: 10,
        position: 'right',
        style: { padding: '0 10px' },
        html: pageVideo.file_name,
        selector: playList,
        onSelect: (item: { url: string; html: string; quality: { url: string; html: string; default?: boolean }[] }) => {
          art.controls.show = false
          const defaultQ = item.quality[0]
          art.controls.add({
            name: '清晰度',
            index: 10,
            position: 'right',
            style: { textAlign: 'left' },
            html: defaultQ ? defaultQ.html : '',
            selector: item.quality,
            onSelect: (item: { url: string; html: string; default?: boolean }) => {
              art.switchQuality(item.url)
            }
          })
          art.switchUrl(item.url)
          if (appStore.pageVideo) {
            appStore.pageVideo.file_name = item.html
          }
        }
      })
```

**Comment by gaozhangmin** [comment]
@zhw2590582  I made an donation, Please help me .

**Comment by zhw2590582** [comment]
Like this: [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09controls%3A%20%5B%0A%09%09%7B%0A%09%09%09position%3A%20%27right%27%2C%0A%09%09%09name%3A%20%27old%27%2C%0A%09%09%09html%3A%20%27old-selector%27%2C%0A%09%09%09selector%3A%20%5B%0A%09%09%09%09%7B%0A%09%09%09%09%09html%3A%20%27old-item%27%2C%0A%09%09%09%09%7D%0A%09%09%09%5D%0A%09%09%7D%2C%0A%09%5D%2C%0A%7D)%3B%0A%0AsetTimeout(()%20%3D%3E%20%7B%0A%09art.controls%5B%27old%27%5D.style.display%20%3D%20%27none%27%3B%0A%09art.controls.add(%7B%0A%09%09position%3A%20%27right%27%2C%0A%09%09name%3A%20%27new%27%2C%0A%09%09html%3A%20%27new-selector%27%2C%0A%09%09selector%3A%20%5B%0A%09%09%09%7B%0A%09%09%09%09html%3A%20%27new-item%27%2C%0A%09%09%09%7D%0A%09%09%5D%0A%09%7D)%0A%7D%2C%201000)%3B)
