### ISSUE TITLE
移动端的一个显示bug

### ISSUE THREAD

**Issue by aiselp** [zhw2590582/ArtPlayer#505]
https://user-images.githubusercontent.com/76829457/233370233-cb9c41ad-0e75-4ab3-8940-abe3066e027d.mp4

### Actual behaviour
在视频中这个小锁头点击不会变更图标了，其他行为都正常。
本以为是我项目中的css可能有影响到了，后来使用vite创建了一个新的vue项目也还是会出现这样的情况
### Environment

-   Browser:
-   Version:
-   Operating System:
-   Version:"^4.6.2"

### Console errors (if any)
无

**Comment by zhw2590582** [comment]
这个问题已经修复，会在下个版本中发布

**Comment by zhw2590582** [comment]
在最新版中已修复
