### ISSUE TITLE
 更改播放器选项

### ISSUE THREAD

**Issue by eken007** [zhw2590582/ArtPlayer#506]
嗨，它在文档中说直接更改播放器选项不会立即在播放器上看到。那么如何立即在播放器上应用选项的修改 ？？？

**Comment by zhw2590582** [comment]
例如你想动态修改哪些选项呢？

**Comment by zhw2590582** [comment]
我会在下一个版本(5.0.0)中添加动态修改画质的功能，文档也会更新，到时我会在这里通知你的

**Comment by eken007** [comment]
好的，非常感谢你，请问什么时候可以用？

**Comment by zhw2590582** [comment]
Not sure when yet, I think it will take a few days to release

**Comment by zhw2590582** [comment]
If you use the latest version of `Artplayer-Plugin-Hls-Quality@2.0.0`, this problem has been fixed
