### ISSUE TITLE
如何添加多线路源支持？

### ISSUE THREAD

**Issue by xwlcn** [zhw2590582/ArtPlayer#507]
目前只看到有hls、dash的画质源切换功能，像直播平台那种切换播放线路的该怎么实现，线路与画质切换不同，线路是针对同一分辨率的视频切换不同的播放地址，最好能够支持同时添加mp4与hls混合的多个线路地址。

**Comment by zhw2590582** [comment]
播放器本身不关注播放线路的，这是业务问题，播放器只关心播放地址能不能播放，以及如何播放。
