### ISSUE TITLE
新版本5.00问题

### ISSUE THREAD

**Issue by kazegh** [zhw2590582/ArtPlayer#511]
1.新建控制按钮出现了滑块（例：移动版右侧按钮速度调节，4.6.2没有）
controls:[{name:'mspeed',position:'right',html:'1',selector:[{html:'<span>0.5</span>'},{html:'<span>0.75</span>'},{default:true,html:'<span>1</span>'},{html:'<span>1.25</span>'},{html:'<span>1.5</span>'},{html:'<span>2</span>'}],onSelect:function(item,$dom){art.playbackRate=Number($dom.innerText);art.controls.mspeed.show=!1;return item.html}}]
2.移动版还是没有长按右键啊

**Comment by zhw2590582** [comment]
1.新建控制按钮出现了滑块
这个滑块是不是只纵向的滚动条？因为控制器有一个最大的高度，在移动端默认值是180px，你可以修改一下: [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20controls%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20name%3A%20%27mspeed%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20position%3A%20%27right%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%271%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20selector%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%20html%3A%20%270.5%27%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%20html%3A%20%270.75%27%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%20default%3A%20true%2C%20html%3A%20%271%27%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%20html%3A%20%271.25%27%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%20html%3A%20%271.5%27%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%20html%3A%20%272%27%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20onSelect%3A%20function%20(item%2C%20%24dom)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20art.playbackRate%20%3D%20Number(%24dom.innerText)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20art.controls.mspeed.show%20%3D%20!1%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20item.html%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%5D%2C%0A%09cssVar%3A%20%7B%0A%09%09%27--art-selector-max-height%27%3A%20%27200px%27%0A%09%7D%0A%7D)%3B)

2.本来移动端就是没有长按右键的功能的

**Comment by kazegh** [comment]
多谢，1.我是（建议在style标签里面直接设置，plyr播放器就是的）在artplayer还必须!important参数
<style>.art-video-player{--art-state-opacity:0.2!important;--art-indicator-size:5px!important;--art-selector-max-height:200px!important}</style>
2.我的的意思是移动版可不可以加上长按右键面板

**Comment by zhw2590582** [comment]
1. 只是css优先级问题，无需使用important，`.artplayer-app .art-video-player {};`
2. 移动版从来都没有右键菜单，目前也不打算开启这个功能
