### ISSUE TITLE
option.quality

### ISSUE THREAD

**Issue by eken007** [zhw2590582/ArtPlayer#512]
你好，谢谢你的更新。
但我的问题一直没有得到解决。可能是我的一个错误。下面是我想做的事情：
- 我有一个剧集的清单，每一集都有链接来识别其不同的品质。
- 当加载第一集时，我执行以下指令来加载其质量： 

              this.option.url = data.data[i].video
               this.option.quality.push({
                  default: true、
                  html: data.data[i].quality、
                    url: data.data[i].video
                  },
              ) 
- 当我切换到下一个视频时，我使用同样的指令，但质量没有变化：
              this.art.option.quality.push({
                  default: true、
                  html: data.data[i].quality、
                    url: data.data[i].video
                  },
                )
谢谢你对我的帮助

通过www.DeepL.com/Translator（免费版）翻译

**Comment by zhw2590582** [comment]
Just like this: [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%7D)%3B%0A%0A%2F%2F%20Old%20quality%0Aart.controls.add(%7B%0A%09name%3A%20%27quality%27%2C%0A%09index%3A%2010%2C%0A%09position%3A%20%27right%27%2C%0A%09html%3A%20%27Old%20quality%27%2C%0A%09selector%3A%20%5B%0A%09%09%7B%0A%09%09%09default%3A%20true%2C%0A%09%09%09html%3A%20%271080P%27%2C%0A%09%09%7D%2C%0A%09%09%7B%0A%09%09%09html%3A%20%27720P%27%2C%0A%09%09%7D%2C%0A%09%5D%2C%0A%7D)%3B%0A%0AsetTimeout(()%20%3D%3E%20%7B%0A%09%2F%2F%20New%20quality%0A%09art.controls.update(%7B%0A%09%09name%3A%20%27quality%27%2C%0A%09%09index%3A%2010%2C%0A%09%09position%3A%20%27right%27%2C%0A%09%09html%3A%20%27New%20quality%27%2C%0A%09%09selector%3A%20%5B%0A%09%09%09%7B%0A%09%09%09%09default%3A%20true%2C%0A%09%09%09%09html%3A%20%27720P%27%2C%0A%09%09%09%7D%2C%0A%09%09%09%7B%0A%09%09%09%09html%3A%20%27360P%27%2C%0A%09%09%09%7D%2C%0A%09%09%5D%2C%0A%09%7D)%3B%0A%7D%2C%203000)%3B)
