### ISSUE TITLE
更新5.0版本后底部控件问题

### ISSUE THREAD

**Issue by a2803401120** [zhw2590582/ArtPlayer#514]
![Screenshot_20230424_013746](https://user-images.githubusercontent.com/54971249/233855990-71047be7-aa9f-4a42-b5ff-fd73afe42654.jpg)
如图 底部控件位置变成顶部了

**Comment by zhw2590582** [comment]
你这个有没有网址？这次更新的代码比较多

**Comment by a2803401120** [comment]
没有 直接复制文档上的也有问题

貌似是浏览器兼容问题 换个浏览器就正常了

**Comment by zhw2590582** [comment]
你试试`5.0.2`版本
