### ISSUE TITLE
5.0.1搜狗浏览器兼容问题

### ISSUE THREAD

**Issue by xwlcn** [zhw2590582/ArtPlayer#515]
问题：
1. 控制条到顶部去了
2. 不支持`aspect-ratio: 16/9;`
3. 还是网页全屏问题，不兼容

参考解决方案：
1. `.art-video-player .art-bottom`的`justify-content: end;`改为`justify-content: flex-end;`
2. 这个问题比较麻烦，`aspect-ratio: 16/9;`可用`height: 0;padding-bottom: 56.25% !important;`代替，但`.art-video-player`的`position: relative;`会导致播放器没有高度，即高度为父容器的`0`，改为`absolute`即可正确显示，但此时父容器必须设置`postion:relative`。希望能提供修改`.art-video-player`的`position`属性的接口，或者现有接口也行我找了下没有找到，只找到个`art.template.$player.style = 'position:absolute'`的方法，但这种方法会导致网页全屏的`poosition:fixed`失效，因为`style`会将`css 选择器`的`poosition:fixed`覆盖掉。
3. `.art-fullscreen-web`增加`top:0;left:0`属性。

**Comment by zhw2590582** [comment]
1. 刚刚发布了5.0.2版本修复了这个问题
2. aspect-ratio 这个属于可选的样式，只能通过其它方法解决了
3. 网页全屏问题不兼容是什么意思，是播放器无法突破容器吗？可以使用下面这个办法

```js
Artplayer.FULLSCREEN_WEB_IN_BODY = true;
var art = new Artplayer({
    container: '.artplayer-app',
    url: '/assets/sample/video.mp4',
    fullscreenWeb: true,
});
```

**Comment by xwlcn** [comment]
> 

网页全屏不兼容：相对位置的问题，在某些浏览器下面，没加`left:0;top:0`的话，位置会错乱。

![alt](https://pic3.58cdn.com.cn/nowater/webim/big/n_v2e69c4e05e57945c4a097b9c28091a9c1.png)

**Comment by zhw2590582** [comment]
https://artplayer.org/document/#%E5%8F%A4%E8%80%81%E7%9A%84%E6%B5%8F%E8%A7%88%E5%99%A8
