### ISSUE TITLE
关于移动端 Safari 快进快退建议

### ISSUE THREAD

**Issue by orangejx** [zhw2590582/ArtPlayer#517]
hi 开发大大, 

我在使用移动端(iPad Pro 11寸)Safari 浏览器时, 全屏播放器并不能像移动端(iPhone)Safari 浏览器上一样完全全屏, 还会有播放器控件显示出来, 这时并不能使用滑动屏幕快进或后退, 只能使用通过点击进度条调整进度, 但由于是移动端, 所以手指并不像在 PC 端上一样精准. 但这个问题在同样的设备上的 Chrome 上是正常的. 

浏览器: Safari
移动设备: iPad Pro 2
设备尺寸: 11 寸

![IMG3382](https://user-images.githubusercontent.com/19427231/234412824-605aacca-04f4-4477-a36e-8ad91326a7aa.png)

**Comment by zhw2590582** [comment]
在iPhone里的全屏只是视频元素的全屏，但在iPad的全屏却是整个播放器的全屏。
不能滑动屏幕来改变进度，可能是因为播放器把iPad判断成电脑了，但我现在没有你这个型号的iPad，也不好处理。
你看看能不能把你的iPad的userAgent发给我

```js
console.log(Artplayer.utils.userAgent)
```

**Comment by orangejx** [comment]
> 在iPhone里的全屏只是视频元素的全屏，但在iPad的全屏却是整个播放器的全屏。 不能滑动屏幕来改变进度，可能是因为播放器把iPad判断成电脑了，但我现在没有你这个型号的iPad，也不好处理。 你看看能不能把你的iPad的userAgent发给我
> 
> ```js
> console.log(Artplayer.utils.userAgent)
> ```

首先感谢老板的回复. 我发现 iPad 的 Safari 浏览器上似乎会**默认访问 PC 版**网页. 然后两个 UAG 是这样的:
PC版: 
`HTTP/2.0＂ 200 7816＂Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15＂`
移动版:
`HTTP/2.0＂ 200 7816 ＂Mozilla/5.0 (iPad; CPU OS 16_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Mobile/15E148 Safari/604.1＂`

在移动版网页上 ArtPlayer 也是以播放器全屏的模式出现的, 但调整进度的功能是正常的. 而在 iPad 上以 **PC** 版网页全屏也是以**播放器全屏的模式**出现的, 但**调整进度的功能失效**了. 
以及最后 iPad OS 的版本是 16.3

**Comment by zhw2590582** [comment]
这个PC的UA信息，怎么看都不知道原来是ipad的，这就尴尬了

**Comment by orangejx** [comment]
> 这个PC的UA信息，怎么看都不知道原来是ipad的，这就尴尬了
> 
> https://developer.apple.com/forums/thread/119186?page=2

我在这篇帖子底下找到了一个回答, 我用手头上的 iPad 和 Mac 上的 Safari 测了下, 都是能识别出来的. 以及回答链接, [https://developer.apple.com/forums/thread/119186?answerId=705140022#705140022](https://developer.apple.com/forums/thread/119186?answerId=705140022#705140022) 还是得辛苦老板您看看这个能不能用, 如果可以的话, 那应该还是蛮不错的
```
function iOS() {
  return [
    'iPad Simulator',
    'iPhone Simulator',
    'iPod Simulator',
    'iPad',
    'iPhone',
    'iPod'
  ].includes(navigator.platform)
  // iPad on iOS 13 detection
  || (navigator.userAgent.includes("Mac") && "ontouchend" in document)
}
```
以及我自己测试的截图. 
iPad Safari:
![WechatIMG3501](https://user-images.githubusercontent.com/19427231/235276736-adc89e69-544a-48ea-aed7-416286c37fb2.jpeg)
![WechatIMG3500](https://user-images.githubusercontent.com/19427231/235276739-356414fa-db53-4fc3-bd47-af9848eb4949.jpeg)
Mac Safari:
<img width="198" alt="PC" src="https://user-images.githubusercontent.com/19427231/235276759-775b7902-05d8-4d61-9166-eeaa7f75e591.png">

**Comment by zhw2590582** [comment]
多谢建议，下个版本修复这个问题
