### ISSUE TITLE
Long controls cutoff

### ISSUE THREAD

**Issue by WeidiDeng** [zhw2590582/ArtPlayer#518]
### Problems

If controls selectors are too many (like a playlist or quality selector), top of the options can't be scrolled to.

### Environment

-   Browser: Latest Chrome
-   Version: 5.0.3
-   Operating System:
-   Version:

### Link to where the bug is happening

https://artplayer.org/?libs=https://cdnjs.cloudflare.com/ajax/libs/dashjs/4.5.2/dash.all.min.js%0A./uncompiled/artplayer-plugin-dash-quality/index.js&example=dash.quality

![image](https://user-images.githubusercontent.com/28780594/234730390-519d902e-8caf-4686-9ba6-7e6cc369e283.png)

The top most 180p can't be fully viewed. For longer controls it become more problematic.

**Comment by zhw2590582** [comment]
Default: `--art-selector-max-height: 300px`
But you can set a value that suits you:  [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09controls%3A%20%5B%0A%09%09%7B%0A%09%09%09position%3A%20%27right%27%2C%0A%09%09%09html%3A%20%27Control%27%2C%0A%09%09%09selector%3A%20%5B%0A%09%09%09%09%7B%0A%09%09%09%09%09html%3A%20%271%27%0A%09%09%09%09%7D%2C%0A%09%09%09%09%7B%0A%09%09%09%09%09html%3A%20%271%27%0A%09%09%09%09%7D%2C%0A%09%09%09%09%7B%0A%09%09%09%09%09html%3A%20%271%27%0A%09%09%09%09%7D%2C%0A%09%09%09%09%7B%0A%09%09%09%09%09html%3A%20%271%27%0A%09%09%09%09%7D%2C%0A%09%09%09%09%7B%0A%09%09%09%09%09html%3A%20%271%27%0A%09%09%09%09%7D%2C%0A%09%09%09%09%7B%0A%09%09%09%09%09html%3A%20%271%27%0A%09%09%09%09%7D%2C%0A%09%09%09%09%7B%0A%09%09%09%09%09html%3A%20%271%27%0A%09%09%09%09%7D%2C%0A%09%09%09%09%7B%0A%09%09%09%09%09html%3A%20%271%27%0A%09%09%09%09%7D%2C%0A%09%09%09%09%7B%0A%09%09%09%09%09html%3A%20%271%27%0A%09%09%09%09%7D%0A%09%09%09%5D%0A%09%09%7D%2C%0A%09%5D%2C%0A%09cssVar%3A%20%7B%0A%09%09%27--art-selector-max-height%27%3A%20%27200px%27%0A%09%7D%0A%7D)%3B)

**Comment by WeidiDeng** [comment]
It won't work for truly long controls (as in a playlist with 20 or more videos). 

Base on this [demo](https://artplayer.org/document/component/controls.html#%E5%88%9B%E5%BB%BA) and copy selectors for many times and set `'--art-selector-max-height': '999px'`.

![image](https://user-images.githubusercontent.com/28780594/234734873-cac43f34-5d52-430f-80e6-4a30ec4292e2.png)

**Comment by zhw2590582** [comment]
I mean make --art-selector-max-height smaller, not bigger

**Comment by WeidiDeng** [comment]
![image](https://user-images.githubusercontent.com/28780594/234740174-2b2a71ba-56e2-45cb-a566-56136758012e.png)

It became nearly unselectable

**Comment by zhw2590582** [comment]
What does your code look like?

**Comment by WeidiDeng** [comment]
```
var urls = []; // list of video urls.
var art = new Artplayer({
    container: '.artplayer-app',
});

var list = {
            name: 'list',
            position: 'right',
            html: 'list',
            selector: [
            ],
            onSelect: function (item, $dom) {
                art.url = urls[$dom.dataset.index]
                return item.html;
            },
        },
// create selector from urls;
//list.selector.push();
art.controls.add(list)
```

**Comment by zhw2590582** [comment]
Yes, this is a style bug, I will fix it in the next version, thanks for the feedback: [demo](https://artplayer.org/?libs=&code=var%20urls%20%3D%20%5B%0A%09%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09%27%2Fassets%2Fsample%2Fvideo.mp4%27%0A%5D%3B%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09cssVar%3A%20%7B%0A%09%09%27--art-selector-max-height%27%3A%20%27200px%27%0A%09%7D%0A%7D)%3B%0A%0Avar%20list%20%3D%20%7B%0A%09name%3A%20%27list%27%2C%0A%09position%3A%20%27right%27%2C%0A%09html%3A%20%27list%27%2C%0A%09selector%3A%20urls.map((url%2C%20index)%20%3D%3E%20%7B%0A%09%09return%20%7B%0A%09%09%09url%3A%20url%2C%0A%09%09%09html%3A%20%27Url-%27%20%2B%20index%2C%0A%09%09%7D%0A%09%7D)%2C%0A%09onSelect%3A%20function%20(item)%20%7B%0A%09%09art.url%20%3D%20item.url%0A%09%09return%20item.html%3B%0A%09%7D%2C%0A%7D%0A%0Aart.controls.add(list))

**Comment by zhw2590582** [comment]
发布了`5.0.4`版本了

**Comment by WeidiDeng** [comment]
Thanks for the quick fix
