### ISSUE TITLE
弹幕发送功能

### ISSUE THREAD

**Issue by MonoLogueChi** [zhw2590582/ArtPlayer#52]
我在弹幕插件中没有找到弹幕发送的功能，请问有这方面的计划吗？

我写了一个Dplayer的弹幕服务器，想适配给ArtPlayer，但是并没有找到弹幕发送接口，现在不知道接口应该设计哪些参数，目前Bilibili弹幕代理已经完成了，目前可以返回xml格式的弹幕给ArtPlayer，但是不知道怎么接收从ArtPlayer发送的弹幕

**Comment by MonoLogueChi** [comment]
[https://github.com/MonoLogueChi/Dplayer.Danmaku#artplayer弹幕](https://github.com/MonoLogueChi/Dplayer.Danmaku#artplayer弹幕)

**Comment by zhw2590582** [comment]
使用说明：

https://github.com/zhw2590582/ArtPlayer/tree/master/packages/artplayer-plugin-danmuku#usage

发送弹幕：
```js
art.plugins.artplayerPluginDanmuku.emit({
    text: '666', // 文本
    time: 5, // 所在时间，单位秒
    color: '#fff', // 颜色
    size: 25, // 尺寸
    border: false, // 是否有描边
    mode: 'scroll', // 模式: 滚动 scroll 或者静止 static
});
```

**Comment by MonoLogueChi** [comment]
最终使用了类似 Dplayer 的接口

[https://dandoc.u2sb.top/danmaku/api.html#artplayer-弹幕接口](https://dandoc.u2sb.top/danmaku/api.html#artplayer-弹幕接口)
