### ISSUE TITLE
Can't play mainfest dash file

### ISSUE THREAD

**Issue by SinonCute** [zhw2590582/ArtPlayer#520]
### Expected behaviour
- It should play the video through manifest (XML) 
### Actual behaviour
- Can't play
### Steps to reproduce
- use the link to provide a dash manifest
- paste that to URL variable
### Environment

-   Browser: Chrome
-   Version: Version 112.0.5615.137 (Official Build) (x86_64)
-   Operating System: Mac/Win
-   Version: 

### Console errors (if any)
no
### Link to where the bug is happening
That link is my API link

**Comment by zhw2590582** [comment]
can you give me the link I'll test it

**Comment by SinonCute** [comment]
https://api-2.karyl.live/stream-bilibili?id=11$12811420

**Comment by zhw2590582** [comment]
This is not a problem with the player. You can’t play your link even if you use the official dash demo.

http://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html

**Comment by SinonCute** [comment]
![image](https://user-images.githubusercontent.com/81401485/235313682-f4f3320b-f007-4924-827d-4f9272d7b42d.png)
something weird

**Comment by SinonCute** [comment]
https://api-2.karyl.live/stream-bilibili?id=11$12785653
you can try again, I tested it a lot of times on the official dash demo.

**Comment by SinonCute** [comment]
https://api-2.karyl.live/stream-bilibili?id=11$12785653
if you do not mind, you can try again. I tested it a lot of times on the official dash demo

**Comment by zhw2590582** [comment]
This works: [demo](https://artplayer.org/?libs=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fdashjs%2F4.5.2%2Fdash.all.min.js&code=function%20playMpd(video%2C%20url%2C%20art)%20%7B%0A%20%20%20%20if%20(dashjs.supportsMediaSource())%20%7B%0A%20%20%20%20%20%20%20%20if%20(art.dash)%20art.dash.destroy()%3B%0A%20%20%20%20%20%20%20%20const%20dash%20%3D%20dashjs.MediaPlayer().create()%3B%0A%20%20%20%20%20%20%20%20dash.initialize(video%2C%20url%2C%20art.option.autoplay)%3B%0A%20%20%20%20%20%20%20%20art.dash%20%3D%20dash%3B%20%0A%20%20%20%20%20%20%20%20art.on(%27destroy%27%2C%20()%20%3D%3E%20dash.destroy())%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20art.notice.show%20%3D%20%27Unsupported%20playback%20format%3A%20mpd%27%3B%0A%20%20%20%20%7D%0A%7D%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fapi-2.karyl.live%2Fstream-bilibili%3Fid%3D11%2412785653%27%2C%0A%20%20%20%20type%3A%20%27mpd%27%2C%0A%20%20%20%20customType%3A%20%7B%0A%20%20%20%20%20%20%20%20mpd%3A%20playMpd%0A%20%20%20%20%7D%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20console.info(art.dash)%3B%0A%7D)%3B)

**Comment by SinonCute** [comment]
Yes, it works but how can I implement it to dash quality control?

**Comment by zhw2590582** [comment]
Like this: [demo](https://artplayer.org/?libs=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fdashjs%2F4.5.2%2Fdash.all.min.js%0A.%2Funcompiled%2Fartplayer-plugin-dash-quality%2Findex.js&code=function%20playMpd(video%2C%20url%2C%20art)%20%7B%0A%09if%20(dashjs.supportsMediaSource())%20%7B%0A%09%09if%20(art.dash)%20art.dash.destroy()%3B%0A%09%09const%20dash%20%3D%20dashjs.MediaPlayer().create()%3B%0A%09%09dash.initialize(video%2C%20url%2C%20art.option.autoplay)%3B%0A%09%09art.dash%20%3D%20dash%3B%0A%09%09art.on(%27destroy%27%2C%20()%20%3D%3E%20dash.destroy())%3B%0A%09%7D%20else%20%7B%0A%09%09art.notice.show%20%3D%20%27Unsupported%20playback%20format%3A%20mpd%27%3B%0A%09%7D%0A%7D%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27https%3A%2F%2Fapi-2.karyl.live%2Fstream-bilibili%3Fid%3D11%2412785653%27%2C%0A%09type%3A%20%27mpd%27%2C%0A%09setting%3A%20true%2C%0A%09customType%3A%20%7B%0A%09%09mpd%3A%20playMpd%0A%09%7D%2C%0A%09plugins%3A%20%5B%0A%09%09artplayerPluginDashQuality(%7B%0A%09%09%09control%3A%20true%2C%0A%09%09%09setting%3A%20true%2C%0A%09%09%09getResolution%3A%20(level)%20%3D%3E%20level.height%20%2B%20%27P%27%2C%0A%09%09%09title%3A%20%27Quality%27%2C%0A%09%09%09auto%3A%20%27Auto%27%2C%0A%09%09%7D)%2C%0A%09%5D%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%09console.info(art.dash)%3B%0A%7D)%3B)

**Comment by SinonCute** [comment]
thank you
