### ISSUE TITLE
Dash quality

### ISSUE THREAD

**Issue by eken007** [zhw2590582/ArtPlayer#521]
你好，我希望你一切都好。 我已经在一个Vuejs项目中集成了你的播放器，现在我想使用Dash质量插件。 我已经按照文档的要求做了：
- 我运行了命令 ( npm install artplayer-plugin-dash-quality )
- 然后我导入了 ( import artplayerPluginDashQuality from "artplayer-plugin-dash-quality" )
- 我将artplayerPluginDashQuality添加到我的播放器插件中：
插件: [...
        artplayerPluginDashQuality({
            // 在控制中显示质量
            control: true、

            // 在设置中显示质量
            setting: true、

            //从级别中获取分辨率文本
			getResolution: (level) => level.height + 'P'、
    // I18n
            title: '质量'、
            auto: 'Auto'、
        }),
    ].

我的第一个问题是关于customType的，当我使用演示的例子时，我得到的回报是dashjs没有定义。

我不确定Dash插件是否支持Mp4和其他视频格式。

谢谢你的答复。

**Comment by zhw2590582** [comment]
You need to install Dash.js yourself
```js
import dashjs from 'dashjs';
```

**Comment by eken007** [comment]
我们能否用另一种视频格式来代替mpd格式？

**Comment by zhw2590582** [comment]
I don't understand what you mean, what does `another video format` mean

**Comment by eken007** [comment]
在Dash插件的例子中，我们使用一个.mpd文件，我想知道是否有办法使用mp4文件？谢谢

**Comment by zhw2590582** [comment]
Yes, you can delete the line `type: 'mpd'`:  [demo](https://artplayer.org/?libs=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fdashjs%2F4.5.2%2Fdash.all.min.js&code=function%20playMpd(video%2C%20url%2C%20art)%20%7B%0A%20%20%20%20if%20(dashjs.supportsMediaSource())%20%7B%0A%20%20%20%20%20%20%20%20if%20(art.dash)%20art.dash.destroy()%3B%0A%20%20%20%20%20%20%20%20const%20dash%20%3D%20dashjs.MediaPlayer().create()%3B%0A%20%20%20%20%20%20%20%20dash.initialize(video%2C%20url%2C%20art.option.autoplay)%3B%0A%20%20%20%20%20%20%20%20art.dash%20%3D%20dash%3B%20%0A%20%20%20%20%20%20%20%20art.on(%27destroy%27%2C%20()%20%3D%3E%20dash.destroy())%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20art.notice.show%20%3D%20%27Unsupported%20playback%20format%3A%20mpd%27%3B%0A%20%20%20%20%7D%0A%7D%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fdash.akamaized.net%2Fakamai%2Fbbb_30fps%2Fbbb_30fps.mpd%27%2C%0A%20%20%20%20%2F%2F%20type%3A%20%27mpd%27%2C%0A%20%20%20%20customType%3A%20%7B%0A%20%20%20%20%20%20%20%20mpd%3A%20playMpd%0A%20%20%20%20%7D%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20console.info(art.dash)%3B%0A%0A%09setTimeout(()%20%3D%3E%20%7B%0A%09%09art.dash.destroy()%3B%0A%09%09art.url%20%3D%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%3B%0A%09%7D%2C%203000)%3B%0A%7D)%3B)
