### ISSUE TITLE
弹幕开关记忆功能

### ISSUE THREAD

**Issue by xwlcn** [zhw2590582/ArtPlayer#522]
目前弹幕插件好像是没有记忆功能的，默认是开启的，自己手动加了下，发现`art.plugins.artplayerPluginDanmuku.hide();`用代码关闭弹幕，下面控制条上的图标不能跟随改变。文档上的那个`isHide Demo`即可重现问题。

希望增加弹幕开关记忆，以及修复默认控制图标代码切换时显示的问题。

**Comment by zhw2590582** [comment]
这个有待修复

**Comment by zhw2590582** [comment]
在`artplayer-plugin-danmuku@5.0.1`中已修复
