### ISSUE TITLE
[Feature] 进度条上显示弹幕热度图

### ISSUE THREAD

**Issue by kira1928** [zhw2590582/ArtPlayer#523]
像b站的类似功能一样，可以方便快速定位长视频中的精彩片段。

**Comment by kira1928** [comment]
![image](https://user-images.githubusercontent.com/2352900/235420257-e14ed761-56f7-4e4b-880b-a1e993196026.png)
就是这个东西

**Comment by zhw2590582** [comment]
热度图不是问题，问题是怎么生成热度图的数据，只要不是大站，这个东西都形如虚设，因为普通的视频站没有足够的弹幕样本

**Comment by kira1928** [comment]
我是在直播录播项目中使用 artplayer 的，会同时录制视频和弹幕。
热度比较高的主播有精彩镜头的时候会有比较明显的弹幕爆发趋势，有弹幕热度图的话可以很轻易地找到精彩的镜头。
以LPL比赛的弹幕来说，一晚上的弹幕量用b站录播姬保存成xml格式的话大概是500MB左右，是足以生成热图的分量了。

**Comment by zhw2590582** [comment]
在`artplayer-plugin-danmuku@5.0.1`中已实现
