### ISSUE TITLE
字幕偏移拖动条从0开始

### ISSUE THREAD

**Issue by 1871847400** [zhw2590582/ArtPlayer#524]
"artplayer": "5.0.4"

![image](https://user-images.githubusercontent.com/46037361/235556743-dc780465-0ef4-46da-9176-2284800a23af.png)

如图所示，字幕偏移只能从0开始到最高10。

只发生在动态加入字幕设置时：player.setting.add(subtitlesSetting)

还有在player.switchUrl()后，实际偏移不准确

**Comment by zhw2590582** [comment]
很多状态是无法带到下一个视频的，例如播放进度，视频长宽比，字幕偏移等等，这个情况下，你可以销毁播放器然后再实例化就可以了: [demo](https://artplayer.org/?libs=&code=var%20option%20%3D%20%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%7D%0A%0Avar%20art%20%3D%20new%20Artplayer(option)%3B%0A%0AsetTimeout(()%20%3D%3E%20%7B%0A%09%2F%2F%20%E5%88%87%E6%8D%A2%E5%9C%B0%E5%9D%80%E6%97%B6%EF%BC%8C%E9%94%80%E6%AF%81%E6%97%A7%E7%9A%84%E6%92%AD%E6%94%BE%E5%99%A8%EF%BC%8C%E7%84%B6%E5%90%8E%E9%87%8D%E6%96%B0%E5%AE%9E%E4%BE%8B%E5%8C%96%E6%92%AD%E6%94%BE%E5%99%A8%0A%09option.url%20%3D%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%3B%0A%09art.destroy()%3B%0A%09art%20%3D%20new%20Artplayer(option)%3B%0A%7D%2C%205000)%3B)
