### ISSUE TITLE
word wrapping for subtitles

### ISSUE THREAD

**Issue by montagao** [zhw2590582/ArtPlayer#527]
Hi, thank for your hard work and for putting out such a great library. I was just wondering if there is any word wrapping feature for english subtitles. 

![pic-selected-230502-1809-47](https://user-images.githubusercontent.com/9814181/235797168-45a684b0-ee33-4e2d-90a0-5a816dd30f77.png)

For example in the above picture, the word "Neural" is cut as "Neur" and "al", when I'd expect it to wrap in a way so that the words are preserved and kept together.  

Desired result:
![mpv-shot0002](https://user-images.githubusercontent.com/9814181/235797923-34dabc1b-5675-4d41-aba9-d7ddf5146390.jpg)

**Comment by zhw2590582** [comment]
Thank you for your feedback, I will fix this problem in the next version

**Comment by zhw2590582** [comment]
Fixed in `artplayer@5.0.5`
