### ISSUE TITLE
谷歌浏览器暂停播放异常

### ISSUE THREAD

**Issue by dsyscms** [zhw2590582/ArtPlayer#528]
我的网站参与度：chrome://media-engagement/

Origin | Sessions | Sessions with playback | Last Playback | Is High | Score
-- | -- | -- | -- | -- | --
http://localhost:3000 | 18 | 14 | 2023-05-04T02:59:31.333Z | Yes | 0.70

当`Is High`为Yes且设置`autoplay:true`意味着浏览器第一次打开url可以实现视频自动播放,但是当点击暂停视频的时候，视频界面暂停了 ，但是我居然听到了视频继续播放的声音，经过多次调试发现页面加载了两次视频而且是同时播放，点击暂停只是暂停了其中一个，我需要手动点击下面图片的地方才能暂停播放。
如果第一次进页面不能自动播放，则一切正常。

![iP0uE5.png](https://i.328888.xyz/2023/05/04/iP0uE5.png)

**Comment by zhw2590582** [comment]
`加载了两次视频而且是同时播放`，但art播放器只实例化一次的话，怎么会有两个播放器呢？另外一个播放器明显不是art的啊

**Comment by dsyscms** [comment]
> 你可以提供个demo地址吗

使用下面这个项目测试发现异常，经过排查，执行npm run build以后直接运行静态html正常，执行npm run start测试异常，测试视频为m3u8且开启自动播放。

`https://github.com/zhw2590582/ArtPlayer/tree/master/packages/artplayer-template/react.js`

为了测试自动播放异常，可以使用firefox浏览器开启允许自动播放权限

使用下面项目测试一切正常，那应该就是react.js项目引起的异常，和artplayer代码无关
`https://github.com/zhw2590582/ArtPlayer/tree/master/packages/artplayer-template/next.js`

**Comment by zhw2590582** [comment]
据说是因为react的严格模式下引起的, 可以试试关闭严格模式
