### ISSUE TITLE
一个ArtPlayer可以用的弹幕服务器

### ISSUE THREAD

**Issue by MonoLogueChi** [zhw2590582/ArtPlayer#53]
我写了一个弹幕服务器，在前一段时间适配了ArtPlayer的弹幕系统，可以加入到ArtPlayer的生态吗？

相关API[文档](https://dandoc.u2sb.top/danmaku/api.html#artplayer-%E5%BC%B9%E5%B9%95%E6%8E%A5%E5%8F%A3)

**Comment by zhw2590582** [comment]
可以，等我改写下发送弹幕的接口，兼容Dplayer

**Comment by zhw2590582** [comment]
你这个假如向`/api/dplayer/v1/`POST了一个`Dplayer`的弹幕对象后，接口会返回一个兼容`Artplayer`的弹幕对象吗？还是说要重新封装？

Dplayer弹幕对象：
```js
{
  id: "C6CC6218F1FB8770",
  text: "弹幕啊", 
  time: 23.359518,
  color: 16777215,
  type: 0,
  author: "DIYgod"
}
```

Artplayer弹幕对象：
```js
{
    text: '666',
    time: 5,
    color: '#fff',
    size: 25,
    border: false,
    mode: 0,
}
```

**Comment by MonoLogueChi** [comment]
目前用的是bilibili的xml格式，比如POST请求 `https://danmaku.xwhite.studio/api/artplayer/v1`，提交弹幕
```json
{
  id: "C6CC6218F1FB8770",
  text: "弹幕啊", 
  time: 23.359518,
  color: 16777215,
  type: 0,
  author: "DIYgod"
}
```
可以从接口 `https://danmaku.xwhite.studio/api/artplayer/v1?id=C6CC6218F1FB8770` 获取xml格式的弹幕

因为数据库最开始是为Dplayer设计的，所以某些字段现在还没有办法存储

目前做的只是兼容适配，以后会想一个更完善的v2接口

**Comment by zhw2590582** [comment]
不是这个意思，例如正常逻辑是，我发送一个弹幕对象，首先通过接口走到服务器，服务器处理完(验证或者储存等等)就会回调处理结果，我再根据结果把刚刚的弹幕对象展示在播放器上。但按你的说我每次发送完一个弹幕，都要重新请求一个xml吗？

**Comment by MonoLogueChi** [comment]
我理解的正常逻辑是，发送一个弹幕，直接渲染到屏幕上，同时向服务器提交弹幕数据。

因为只有在打开视频的时候才会从服务器上请求一个文件，里面的内容是当前视频所有已保存的弹幕，在视频播放中间并不会再向服务器请求弹幕。

比如我打开一个id为 `C6CC6218F1FB8770` ，打开视频时会从服务器加载弹幕，在观看过程中发送弹幕只需要向服务器提交，下次再打开视频时弹幕列表会包含本次发送的弹幕。


在发送弹幕到服务器以后会返回结果，格式是 `{ code : 0 , data : null }`，如果需要从客户端检验是否已保存，可以检查结果中的code，code为0时表示成功，其他值表示错误。

**Comment by nikolamakin** [comment]
我觉得我可以用socket 来展示实时的弹幕
期待你们的作品
