### ISSUE TITLE
控制方面的问题

### ISSUE THREAD

**Issue by eken007** [zhw2590582/ArtPlayer#532]
我希望你一切顺利。 我在播放器上遇到了一个问题。我在我的播放器上创建了一个新的控制选择器，列出了一个季节的所有剧集。 问题是，列表的一部分被隐藏了，就像下面的图片一样

https://drive.google.com/file/d/1KQF2-U_Dy9PTo8sfFx1aKvr3bjxH5o3Y/view?usp=sharing

你会看到第1至5集被隐藏了。
请帮助我

**Comment by zhw2590582** [comment]
Please update to the latest version `5.0.6`

**Comment by eken007** [comment]
我还有一个问题，我在加载播放器时，长宽比设置为16:9，但每次我改变视频的质量时，长宽比又默认为4:3。

**Comment by zhw2590582** [comment]
This will be fixed in the next version

**Comment by zhw2590582** [comment]
Fixed in `artplayer@5.0.7`

**Comment by zhw2590582** [comment]
Then I added a new property that dynamically updates the quality
https://artplayer.org/document/en/advanced/property.html#quality
