### ISSUE TITLE
为什么实例包含了一个X对象，和文档对不上了

### ISSUE THREAD

**Issue by meesii** [zhw2590582/ArtPlayer#537]
### Environment

-   Browser:
-   Version:5.0.9
-   Operating System:
-   Version:

![image](https://github.com/zhw2590582/ArtPlayer/assets/1815046/b68f8c8c-d9d0-407e-b71e-08b0d1730aa0)

不管是Artplayer.instances获取，还是直接获取new出来的实例，都包含一个X对象，和官网文档完全不一样了

**Comment by zhw2590582** [comment]
这个`X`应该是代码被压缩后的实例缩写，就是`art`的本身，但这个并不重要，你用不上这个的，例如你想网页全屏：

https://artplayer.org/document/advanced/property.html#fullscreenweb

```js
var art = new Artplayer({
    container: '.artplayer-app',
    url: '/assets/sample/video.mp4',
});

art.on('ready', () => {
    art.fullscreenWeb = true;
})
```
