### ISSUE TITLE
使用第三方hls库播放m3u8文件时.如果m3u8文件加载失败不会触发artplayer带得error事件

### ISSUE THREAD

**Issue by hktrace** [zhw2590582/ArtPlayer#538]
我在文件中已经写了
art.on('error', (error, reconnectTime) => {
    console.info(error, reconnectTime);
});
但是m3u8如果加载失败时不会触发到这个事件.
比如m3u8网页状态码为404.就不会触发

**Comment by zhw2590582** [comment]
因为这是两回事，使用`hls.js`的时候，`artplayer`接受的视频地址已经是`Blob Url`了，`Blob Url`不存在`404`的情况，只是`hls.js`会通过自己的`ajax`去拉取视频数据，这个过程才会发生`404`，所以你应该去监听`hls.js`的错误事件。

https://github.com/video-dev/hls.js/blob/master/docs/API.md#network-errors
