### ISSUE TITLE
How do I set up responsive subtitles font-size, right now its just staying constant across all screen sizes.

### ISSUE THREAD

**Issue by Brav3Trav3l3r** [zhw2590582/ArtPlayer#539]
PLEASE USE OUR SPECIFIC ISSUE TEMPLATES for bug reports, features and improvement suggestions.

**Comment by zhw2590582** [comment]
You can use media queries to set different font sizes.
Or you can dynamically set the font size by the height of the player: [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09fullscreenWeb%3A%20true%2C%0A%20%20%20%20subtitle%3A%20%7B%0A%20%20%20%20%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.srt%27%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B%0A%0Aart.on(%27resize%27%2C%20()%20%3D%3E%20%7B%0A%09art.subtitle.style(%7B%0A%09%09fontSize%3A%20art.height%20*%200.05%20%2B%20%27px%27%0A%09%7D)%0A%7D)%3B)
