### ISSUE TITLE
Multiple Thumbnnails

### ISSUE THREAD

**Issue by namdevel** [zhw2590582/ArtPlayer#543]
hello i need requests new feature

```javascript
thumbnails: {
        url: ['/assets/sample/thumbnails.png', '/assets/sample/thumbnails-2.png'],
        x_col: 10,
        y_col: 10,
        x_number:160,
       y_number: 90,
    },
```

**Comment by zhw2590582** [comment]
https://github.com/zhw2590582/ArtPlayer/issues/234#issuecomment-1058762370

**Comment by namdevel** [comment]
not work use plugins

**Comment by zhw2590582** [comment]
Can you give me more information? otherwise i can't help you

**Comment by namdevel** [comment]
![Screenshot_81](https://github.com/zhw2590582/ArtPlayer/assets/62225978/3cf40a67-5a21-47ac-bcfa-1e6362431a57)

**Comment by zhw2590582** [comment]
You have multiple large thumbnails. I thought it was multiple small thumbnails. This is a special case for you. There is no solution at present.
