### ISSUE TITLE
displaying image when hover video progressbar

### ISSUE THREAD

**Issue by jedgarf** [zhw2590582/ArtPlayer#544]
how to display image in artplayer progressbar?
![image](https://github.com/zhw2590582/ArtPlayer/assets/40312999/6c7c39b8-e92b-4ca9-aedb-b8f6c7aa5db1)

**Comment by zhw2590582** [comment]
https://www.artplayer.org/document/en/start/option.html#thumbnails

**Comment by jedgarf** [comment]
thanks
