### ISSUE TITLE
播放失败再使用switchUrl切换视频 不会重置art状态

### ISSUE THREAD

**Issue by xifangczy** [zhw2590582/ArtPlayer#548]
播放一个错误链接或假视频 UI中间出现错误图标，使用switchUrl切换视频地址，UI仍然无法使用，所有控件都无法点击，无法暂停，错误图标也不会消失。

只能使用 art.destroy() 销毁后再重新 new Artplayer

### Environment
-   Browser: Chrome
-   Version: 113.0.5672.127

**Comment by zhw2590582** [comment]
播放地址错误确实不应该播放器，下个版本改一下

**Comment by dylanZk1** [comment]
貌似是video:canplay事件响应问题，视频播放的时候没有先触发canplay，导致出了问题

**Comment by z836454898** [comment]
同样有这个问题

**Comment by zhw2590582** [comment]
下个版本中修复
