### ISSUE TITLE
引用hls 播放插件的时候不能自动播放

### ISSUE THREAD

**Issue by nikolamakin** [zhw2590582/ArtPlayer#55]
您好，
-   Browser:
google
-   Version:
3.4.2
-   Operating System:
mac os
-   Version:
这是我的代码片段：
`customType: {
            m3u8: function(video, url) {
                var hls = new Hls();
                hls.loadSource(url);
                hls.attachMedia(video);
            },
        },
autoplay: true, //自动播放`

autoplay: true 失效；我不知道这是一个BUG还是在hls 里配置？如果是在HLS 里，请提供相应的属性给我，非常感谢。

**Comment by zhw2590582** [comment]
自动播放是有条件限制的：[https://developers.google.com/web/updates/2017/09/autoplay-policy-changes](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes)，目前只有默认静音可以解决。

```js
var art = new Artplayer({
    container: '.artplayer-app',
    autoplay: true,
    muted: true, // 默认静音即可
    url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    customType: {
        m3u8: function(video, url) {
            var hls = new Hls();
            hls.loadSource(url);
            hls.attachMedia(video);
        },
    },
});
```

**Comment by nikolamakin** [comment]
明白了，非常感谢

**Comment by sunshineLixun** [comment]
非常感谢您，开源这么好的播放器。 hls 在这里也顺利解决了。

**Comment by accountunavaible** [comment]
为啥还是自动播放不了啊。 

      const art = new Artplayer({
        ...option,
        fullscreen: false,
        fullscreenWeb: false,
        muted: true,
        autoplay: true,
        lang: 'zh-cn',
        container: artRef.current,
        type: 'm3u8',
        customType: {
          m3u8: playM3u8,
        },
      });


所有的配置都设置好了
