### ISSUE TITLE
The playback rate display is abnormal

### ISSUE THREAD

**Issue by dsyscms** [zhw2590582/ArtPlayer#550]
artplayer version: 5.0.9

setting:
``` js
Artplayer.PLAYBACK_RATE = [0.5, 0.75, 1, 1.25, 1.5, 1.75, 2];

```

show:

```
0.5 0.8 1 1.3 1.5 1.8 2
```

**Comment by zhw2590582** [comment]
yes, it is a bug, wil be fixed in next vision, thanks

**Comment by zhw2590582** [comment]
This is because the numbers have been processed by `.toFixed(1)`, but I think these values ​​​​should not be accurate to two decimal places.
