### ISSUE TITLE
播放器嵌套在iframe下弹幕显示的问题

### ISSUE THREAD

**Issue by yangtuyun** [zhw2590582/ArtPlayer#551]
### Expected behaviour
在弹幕开启的情况下，弹幕字体设置为百分比，iframe 宽高 width:1265px;height:712px; 弹幕字体显示正常，在全屏模式下应该重新计算弹幕字体大小，来适应新的宽度对应的字体大小
### Actual behaviour
iframe 宽高 width:1265px;height:712px; 弹幕字体显示正常，在全屏状态下，弹幕字体大小没有重新计算，还是保持在原有宽高计算的弹幕字体大小
### Steps to reproduce
iframe 宽高 width:1265px;height:712px，开启弹幕弹幕字体为百分比，然后打开全屏字体没有变化，此时调整弹幕字体大小，退出全屏，弹幕字体大小保持在全屏状态下的大小
### Environment

-   Browser: Microsoft Edge
-   Version: 113.0.1774.57
-   Operating System: windows
-   Version: 11

**Comment by zhw2590582** [comment]
目前字幕字号的百分比只计算一次，但你可以自己去动态设置它
https://github.com/zhw2590582/ArtPlayer/issues/539#issuecomment-1550799340

**Comment by zhw2590582** [comment]
差不多意思:[demo](https://www.artplayer.org/?libs=.%2Funcompiled%2Fartplayer-plugin-danmuku%2Findex.js&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20fullscreenWeb%3A%20true%2C%0A%20%20%20%20plugins%3A%20%5B%0A%20%20%20%20%20%20%20%20artplayerPluginDanmuku(%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20danmuku%3A%20%27https%3A%2F%2Fd.artplayer.org%3Fid%3DBV1ks411W7r5%27%2C%0A%20%20%20%20%20%20%20%20%7D)%2C%0A%20%20%20%20%5D%2C%0A%7D)%3B%0A%0Aart.on(%27resize%27%2C%20()%20%3D%3E%20%7B%0A%09art.plugins.artplayerPluginDanmuku.config(%7B%0A%09%09fontSize%3A%20%275%25%27%0A%09%7D)%0A%7D)%3B)
