### ISSUE TITLE
iphone  safari play hls video subtitle not show

### ISSUE THREAD

**Issue by dsyscms** [zhw2590582/ArtPlayer#552]
由于没有iphone手机，于是使用xcode内置的 iphone 14 pro max模拟器，发现播放hls视频字幕始终不显示，需要全屏以后点击safari浏览器自带的字幕按钮选择对应的字幕再退出全屏，播放器才会显示字幕，播放mp4视频字幕可以正常显示，另外safari退出全屏，播放器全屏图标显示成退出全屏的图标。

**Comment by dsyscms** [comment]
今天突然发现使用第三方m3u8可以正常加载字幕
```
https://test-streams.mux.dev/x36xhzz/url_6/193039199_mp4_h264_aac_hq_7.m3u8
```

但是使用我自己的m3u8文件却不能正常加载字幕，因为我的m3u8文件是采用视频音频分离，有空帮忙看一下为啥下面的链接不能正常显示字幕
```
https://pub-7d5128ce0c5344e9aceb920c7884f76a.r2.dev/mpd/index.m3u8
```

**Comment by zhw2590582** [comment]
这是视频里的软字幕吗？测试了两个url，我都是看不到字幕
