### ISSUE TITLE
全屏播放视频导致屏幕闪屏

### ISSUE THREAD

**Issue by dsyscms** [zhw2590582/ArtPlayer#553]
经过测试，播放hls和dash视频，发现如下问题，mp4一切正常

mac chrome 开启硬件加速测试异常，关闭硬件加速，一切正常
1. 播放hls和dash视频全屏观看视频，当播放器控制器隐藏，当字幕显示的时候，会导致严重的闪屏，严重影响观看（miniProgressBar开启也会导致闪屏，即使没有字幕的情况）
2. 只要播放器控制器显示，即使字幕显示也不会导致闪屏
3. win10 chrome 开启硬件加速测试正常

问题总结：
引起的具体原因我没搞明白，不过经历两天的测试，我解决了这个闪屏问题，只要全屏状态下播放器界面始终显示内容就可以解决这个问题，为了不影响体验，我加了一个空字符串div覆盖在播放器上方。

``` js           
 //fix screen flash when  hardware accelerate open
 const videoContainer = document.querySelector('.art-video-player');
 const child = document.createElement('div');
 child.innerHTML = '&nbsp;';
 videoContainer.appendChild(child);
```
[请看录屏](https://pub-7d5128ce0c5344e9aceb920c7884f76a.r2.dev/35_1685832809.mp4)

**Comment by zhw2590582** [comment]
这么奇怪，不过这更像是原生video的问题，而不是播放器的问题，你试试这个链接，看看全屏的时候会不会闪屏：[demo](https://www.artplayer.org/?libs=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fhls.js%2F8.0.0-beta.3%2Fhls.min.js&code=const%20%24video%20%3D%20document.createElement(%27video%27)%3B%0Aconst%20%24player%20%3D%20document.querySelector(%27.artplayer-app%27)%3B%0A%24player.appendChild(%24video)%3B%0A%24video.style.width%20%3D%20%27100%25%27%3B%0A%24video.style.height%20%3D%20%27100%25%27%3B%0A%24video.controls%20%3D%20true%3B%0A%0Aconst%20url%20%3D%20%27https%3A%2F%2Ftest-streams.mux.dev%2Fx36xhzz%2Fx36xhzz.m3u8%27%3B%0Aconst%20hls%20%3D%20new%20Hls()%3B%0Ahls.loadSource(url)%3B%0Ahls.attachMedia(%24video)%3B)

**Comment by dsyscms** [comment]
原生video控制器显示以后再隐藏也会导致闪屏，后期还是建议播放器优化一下,b站和youtube开启字幕要是也是闪屏我就不提问了
[demo](https://pub-7d5128ce0c5344e9aceb920c7884f76a.r2.dev/37_1686401792.mp4)

**Comment by zhw2590582** [comment]
假如是原生video的与浏览器的问题，我更偏向于等待浏览器来优化这个问题
