### ISSUE TITLE
建议弹幕设置里面增加热力图开关

### ISSUE THREAD

**Issue by KNaiFen** [zhw2590582/ArtPlayer#554]
这个目前是只能在源码里面设置吧，然后开了，有的人不喜欢看也没法关掉

**Comment by zhw2590582** [comment]
可以添加个自定义开关: [demo](https://www.artplayer.org/?libs=.%2Funcompiled%2Fartplayer-plugin-danmuku%2Findex.js&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09setting%3A%20true%2C%0A%09plugins%3A%20%5B%0A%09%09artplayerPluginDanmuku(%7B%0A%09%09%09danmuku%3A%20%27https%3A%2F%2Fd.artplayer.org%3Fid%3DBV1ks411W7r5%27%2C%0A%09%09%09heatmap%3A%20true%2C%0A%09%09%7D)%2C%0A%09%5D%2C%0A%09settings%3A%20%5B%0A%09%09%7B%0A%09%09%09name%3A%20%27heatmap%27%2C%0A%09%09%09html%3A%20%27%E7%83%AD%E5%8A%9B%E5%9B%BE%27%2C%0A%09%09%09switch%3A%20true%2C%0A%09%09%09tooltip%3A%20%27%E5%BC%80%27%2C%0A%09%09%09onSwitch(item)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20const%20nextState%20%3D%20!item.switch%3B%0A%09%09%09%09const%20%24heatmap%20%3D%20art.controls%5B%27heatmap%27%5D%3B%0A%09%09%09%09%24heatmap.style.display%20%3D%20nextState%20%3F%20%27%27%20%3A%20%27none%27%3B%0A%09%09%09%09item.tooltip%20%3D%20nextState%20%3F%20%27%E5%BC%80%27%20%3A%20%27%E5%85%B3%27%3B%0A%09%09%09%09return%20nextState%3B%0A%09%09%09%7D%0A%09%09%7D%0A%09%5D%0A%7D)%3B)
