### ISSUE TITLE
Support multi types media

### ISSUE THREAD

**Issue by achekra** [zhw2590582/ArtPlayer#556]
Hi,
It will be nice if the player supports mp4 and webm in same time, it depends on support like html5 player 

Regards

**Comment by zhw2590582** [comment]
I don't quite understand what you mean, the player originally supports mp4 and webm

**Comment by achekra** [comment]
I'm asking if the library supports multi-source dependencies for device support on Android/iOS, like this:
<video width="320" height="240" controls>
  <source src="movie.mp4" type="video/mp4">
  <source src="movie.ogg" type="video/ogg">
  Your browser does not support the video tag.
</video>

**Comment by zhw2590582** [comment]
I understand what you mean, but the current architecture of the player does not support this way of writing
