### ISSUE TITLE
Uncaught ArtPlayerError: The width and height of the container cannot be 0

### ISSUE THREAD

**Issue by trompx** [zhw2590582/ArtPlayer#56]
### Actual behaviour
Uncaught ArtPlayerError: The width and height of the container cannot be 0

### Steps to reproduce
Tried with the basic setup and html markup.

### Environment
-   Browser: chrome
-   Version: 80.0.3987.132
-   Operating System: windows
-   Version: 8.1

### Console errors (if any)
Uncaught ArtPlayerError: The width and height of the container cannot be 0

**Comment by zhw2590582** [comment]
You should give the container an initial size, like:

[document#container](https://artplayer.org/document/#/?id=container)

```css
.artplayer-app {
    width: 400px;
    height: 300px;
}
```

**Comment by trompx** [comment]
Hey @zhw2590582,
I already had width and height in css.
I tried inline css too without success: `style="width: 500px; height: 500px"`

Other idea ?
Other video players like plyr/medialement.js have options to stretch videos to fit/cover parent container. It would be best to not have to hardcode the width and height and make it auto adjust to parent size.

**Comment by trompx** [comment]
Found the problem, which is not related to artplayer.js.

I tried to include artplayer in a website that has both a main.js file handling dynamic routing and modular components that load their own js. I created a video component and its js code was loaded before the main file would display the page.

The page had display: none thus artplayer couldn't get the width and height of the player.
