### ISSUE TITLE
fetch subtitle 500 internal server error

### ISSUE THREAD

**Issue by namdevel** [zhw2590582/ArtPlayer#561]
![Screenshot_104](https://github.com/zhw2590582/ArtPlayer/assets/62225978/cb0a03ec-5f24-44ad-8db8-b17cf2f799bc)

**Comment by namdevel** [comment]
error on 5.0.9

but when i use 5.0.6 version that error not showing

**Comment by zhw2590582** [comment]
This is a server error with your subtitle file, the player cannot resolve this

**Comment by namdevel** [comment]
v5.0.6 work fine
v5.0.9 error

my subtitle fine

**Comment by zhw2590582** [comment]
Can you send me the link to your subtitle file? Or send it to my email

**Comment by namdevel** [comment]
I has been fix it by add extension in subtitle 
The first is my subtitle link like this

localhost:3000/api/subtitle/{video_id}
I fix it by change the routing like this

localhost:3000/api/subtitle/{video_id}.vtt

**Comment by zhw2590582** [comment]
https://www.artplayer.org/document/en/start/option.html#subtitle

Or you can do this:

```js
var art = new Artplayer({
    container: '.artplayer-app',
    url: '/assets/sample/video.mp4',
    subtitle: {
        url: 'localhost:3000/api/subtitle/{video_id}',
        type: 'vtt',
    },
});
```
