### ISSUE TITLE
When clicking on the mute icon, the volumeChange event does not work correctly

### ISSUE THREAD

**Issue by radislaw** [zhw2590582/ArtPlayer#564]
### Expected behaviour
When clicking on the mute icon, the volumeChange event should trigger with event.target.volume === 0

### Actual behaviour
When clicking on the mute icon, the volumeChange event returns event.target.volume === 1

### Steps to reproduce
Click on the mute icon, use video:volumechange event

### Environment

-   Browser: Chrome
-   Version:  114
-   Operating System: MacOs
-   Version: 14
-   ArtPlayer Version:  ^5.0.9

**Comment by zhw2590582** [comment]
In fact, this is the default property of `vide` dom object, the change of `mute` will not affect the value of `volume`

[demo](https://www.artplayer.org/?libs=&code=const%20%24app%20%3D%20document.querySelector(%27.artplayer-app%27)%3B%0Aconst%20%24video%20%3D%20document.createElement(%27video%27)%3B%0A%24video.style.width%20%3D%20%27100%25%27%3B%0A%24video.style.height%20%3D%20%27100%25%27%3B%0A%24video.controls%20%3D%20true%3B%0A%24video.src%20%3D%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%3B%0A%24app.appendChild(%24video)%3B%0A%0A%24video.addEventListener(%27volumechange%27%2C%20()%20%3D%3E%20%7B%0A%09console.info(%27muted%20--%3E%27%2C%20%24video.muted)%3B%0A%09console.info(%27volume%20--%3E%27%2C%20%24video.volume)%3B%0A%7D)%3B%0A%0A%24video.addEventListener(%27canplay%27%2C%20()%20%3D%3E%20%7B%0A%09%24video.muted%20%3D%20true%3B%0A%7D%2C%20%7B%0A%09once%3A%20true%0A%7D)%3B)

**Comment by zhw2590582** [comment]
In the next version, I will add a custom `muted` event to listen to `muted` changes

```js
var art = new Artplayer({
    container: '.artplayer-app',
    url: '/assets/sample/video.mp4',
});

art.on('muted', (state) => {
    console.log(state);
});
```
