### ISSUE TITLE
同一个页面多个实例，播放一个的时候，另外的会暂停。

### ISSUE THREAD

**Issue by hu2014** [zhw2590582/ArtPlayer#566]
我想要实现多个视频一起播放怎么搞，现在播放一个，另外的视频就会自动暂停

**Comment by zhw2590582** [comment]
https://www.artplayer.org/document/start/option.html#mutex

**Comment by hu2014** [comment]
想要隐藏控制栏好像设置seeting:false 不行

**Comment by zhw2590582** [comment]
隐藏底部的控制栏？默认是没有永久隐藏的，或者可以通过样式把它隐藏掉

**Comment by hu2014** [comment]
好的。
