### ISSUE TITLE
能否增加顶部控制栏？

### ISSUE THREAD

**Issue by cqsn558** [zhw2590582/ArtPlayer#567]
希望能在顶部增加一个控制栏，左边可以显示视频名称其他自定义信息，右边可以自定义一些按钮，特别是在手机版，因为屏幕较小，自定义按钮较多时无法增加，顶部控制栏随底部控制栏显示或隐藏，这样也不影响自定义的layers业务层，像muiplayer那样感觉很好。
[[https://muiplayer.js.org/zh/demo/](url)](https://muiplayer.js.org/zh/demo/)
![1](https://github.com/zhw2590582/ArtPlayer/assets/39335744/3eea5908-4447-4f84-a989-4d7ba31dfc38)

**Comment by zhw2590582** [comment]
这个属于自定义了，有的人不喜欢在视频里添加太多元素，但你可以自己添加一些层进去：[demo](https://www.artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09layers%3A%20%5B%0A%09%09%7B%0A%09%09%09html%3A%20%27%E8%A7%86%E9%A2%91%E6%A0%87%E9%A2%98%27%2C%0A%09%09%09style%3A%20%7B%0A%09%09%09%09position%3A%20%27absolute%27%2C%0A%09%09%09%09top%3A%20%2720px%27%2C%0A%09%09%09%09right%3A%20%2720px%27%2C%0A%09%09%09%7D%2C%0A%09%09%09click()%20%7B%0A%09%09%09%09console.log(%27%E7%82%B9%E5%87%BB%E4%BA%86%E6%A0%87%E9%A2%98%27)%3B%0A%09%09%09%7D%2C%0A%09%09%09mounted(el)%20%7B%0A%09%09%09%09this.on(%27control%27%2C%20state%20%3D%3E%20%7B%0A%09%09%09%09%09el.style.opacity%20%3D%20state%20%3F%201%20%3A%200%3B%0A%09%09%09%09%7D)%3B%0A%09%09%09%7D%0A%09%09%7D%2C%0A%09%5D%2C%0A%7D)%3B)
