### ISSUE TITLE
iPhone上一直连接视频

### ISSUE THREAD

**Issue by byDuming** [zhw2590582/ArtPlayer#568]
### Expected behaviour
正常播放
### Actual behaviour
一直连接视频
### Environment

-   Browser:safari，夸克，谷歌，均为iPhone移动端版本
-   Version:
-   Operating System:IOS
-   Version:16.4.1

**Comment by zhw2590582** [comment]
可以提供一个demo地址，或者视频的地址吗

**Comment by byDuming** [comment]
> 可以提供一个demo地址，或者视频的地址吗

当然可以！顺便一提，我是使用苹果cms超级播放器里的atrplayer，视频地址：https://cooing.cc/vodplay/331-1-1/
请尝试在iPhone移动端上进行播放

**Comment by byDuming** [comment]
> 可以提供一个demo地址，或者视频的地址吗

我推测可能是没把资源返回过来，因为夸克的视频嗅探没有自动获取并到夸克播放器里播放

**Comment by zhw2590582** [comment]
你用手机打开这个网站，我这边ios是可以播放的

手机：[demo](https://www.artplayer.org/mobile.html?libs=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fhls.js%2F8.0.0-beta.3%2Fhls.min.js&code=function%20playM3u8(video%2C%20url%2C%20art)%20%7B%0A%20%20%20%20if%20(Hls.isSupported())%20%7B%0A%20%20%20%20%20%20%20%20if%20(art.hls)%20art.hls.destroy()%3B%0A%20%20%20%20%20%20%20%20const%20hls%20%3D%20new%20Hls()%3B%0A%20%20%20%20%20%20%20%20hls.loadSource(url)%3B%0A%20%20%20%20%20%20%20%20hls.attachMedia(video)%3B%0A%20%20%20%20%20%20%20%20art.hls%20%3D%20hls%3B%0A%20%20%20%20%20%20%20%20art.on(%27destroy%27%2C%20()%20%3D%3E%20hls.destroy())%3B%0A%20%20%20%20%7D%20else%20if%20(video.canPlayType(%27application%2Fvnd.apple.mpegurl%27))%20%7B%0A%20%20%20%20%20%20%20%20video.src%20%3D%20url%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20art.notice.show%20%3D%20%27Unsupported%20playback%20format%3A%20m3u8%27%3B%0A%20%20%20%20%7D%0A%7D%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fs6.bfzycdn.com%2Fvideo%2Fguimiezhirenduandaocunpian%2F%E7%AC%AC01%E9%9B%86%2Findex.m3u8%27%2C%0A%20%20%20%20type%3A%20%27m3u8%27%2C%0A%20%20%20%20customType%3A%20%7B%0A%20%20%20%20%20%20%20%20m3u8%3A%20playM3u8%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20console.info(art.hls)%3B%0A%7D)%3B)

代码：[demo](https://www.artplayer.org/?libs=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fhls.js%2F8.0.0-beta.3%2Fhls.min.js&code=function%20playM3u8(video%2C%20url%2C%20art)%20%7B%0A%20%20%20%20if%20(Hls.isSupported())%20%7B%0A%20%20%20%20%20%20%20%20if%20(art.hls)%20art.hls.destroy()%3B%0A%20%20%20%20%20%20%20%20const%20hls%20%3D%20new%20Hls()%3B%0A%20%20%20%20%20%20%20%20hls.loadSource(url)%3B%0A%20%20%20%20%20%20%20%20hls.attachMedia(video)%3B%0A%20%20%20%20%20%20%20%20art.hls%20%3D%20hls%3B%0A%20%20%20%20%20%20%20%20art.on(%27destroy%27%2C%20()%20%3D%3E%20hls.destroy())%3B%0A%20%20%20%20%7D%20else%20if%20(video.canPlayType(%27application%2Fvnd.apple.mpegurl%27))%20%7B%0A%20%20%20%20%20%20%20%20video.src%20%3D%20url%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20art.notice.show%20%3D%20%27Unsupported%20playback%20format%3A%20m3u8%27%3B%0A%20%20%20%20%7D%0A%7D%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fs6.bfzycdn.com%2Fvideo%2Fguimiezhirenduandaocunpian%2F%E7%AC%AC01%E9%9B%86%2Findex.m3u8%27%2C%0A%20%20%20%20type%3A%20%27m3u8%27%2C%0A%20%20%20%20customType%3A%20%7B%0A%20%20%20%20%20%20%20%20m3u8%3A%20playM3u8%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20console.info(art.hls)%3B%0A%7D)%3B)

**Comment by byDuming** [comment]
> 你用手机打开这个网站，我这边ios是可以播放的
> 
> 手机：[demo](https://www.artplayer.org/mobile.html?libs=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fhls.js%2F8.0.0-beta.3%2Fhls.min.js&code=function%20playM3u8(video%2C%20url%2C%20art)%20%7B%0A%20%20%20%20if%20(Hls.isSupported())%20%7B%0A%20%20%20%20%20%20%20%20if%20(art.hls)%20art.hls.destroy()%3B%0A%20%20%20%20%20%20%20%20const%20hls%20%3D%20new%20Hls()%3B%0A%20%20%20%20%20%20%20%20hls.loadSource(url)%3B%0A%20%20%20%20%20%20%20%20hls.attachMedia(video)%3B%0A%20%20%20%20%20%20%20%20art.hls%20%3D%20hls%3B%0A%20%20%20%20%20%20%20%20art.on(%27destroy%27%2C%20()%20%3D%3E%20hls.destroy())%3B%0A%20%20%20%20%7D%20else%20if%20(video.canPlayType(%27application%2Fvnd.apple.mpegurl%27))%20%7B%0A%20%20%20%20%20%20%20%20video.src%20%3D%20url%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20art.notice.show%20%3D%20%27Unsupported%20playback%20format%3A%20m3u8%27%3B%0A%20%20%20%20%7D%0A%7D%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fs6.bfzycdn.com%2Fvideo%2Fguimiezhirenduandaocunpian%2F%E7%AC%AC01%E9%9B%86%2Findex.m3u8%27%2C%0A%20%20%20%20type%3A%20%27m3u8%27%2C%0A%20%20%20%20customType%3A%20%7B%0A%20%20%20%20%20%20%20%20m3u8%3A%20playM3u8%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20console.info(art.hls)%3B%0A%7D)%3B)
> 
> 代码：[demo](https://www.artplayer.org/?libs=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fhls.js%2F8.0.0-beta.3%2Fhls.min.js&code=function%20playM3u8(video%2C%20url%2C%20art)%20%7B%0A%20%20%20%20if%20(Hls.isSupported())%20%7B%0A%20%20%20%20%20%20%20%20if%20(art.hls)%20art.hls.destroy()%3B%0A%20%20%20%20%20%20%20%20const%20hls%20%3D%20new%20Hls()%3B%0A%20%20%20%20%20%20%20%20hls.loadSource(url)%3B%0A%20%20%20%20%20%20%20%20hls.attachMedia(video)%3B%0A%20%20%20%20%20%20%20%20art.hls%20%3D%20hls%3B%0A%20%20%20%20%20%20%20%20art.on(%27destroy%27%2C%20()%20%3D%3E%20hls.destroy())%3B%0A%20%20%20%20%7D%20else%20if%20(video.canPlayType(%27application%2Fvnd.apple.mpegurl%27))%20%7B%0A%20%20%20%20%20%20%20%20video.src%20%3D%20url%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20art.notice.show%20%3D%20%27Unsupported%20playback%20format%3A%20m3u8%27%3B%0A%20%20%20%20%7D%0A%7D%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fs6.bfzycdn.com%2Fvideo%2Fguimiezhirenduandaocunpian%2F%E7%AC%AC01%E9%9B%86%2Findex.m3u8%27%2C%0A%20%20%20%20type%3A%20%27m3u8%27%2C%0A%20%20%20%20customType%3A%20%7B%0A%20%20%20%20%20%20%20%20m3u8%3A%20playM3u8%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20console.info(art.hls)%3B%0A%7D)%3B)

在我提供的视频链接中，你是否也无法播放？我已将其更新到5.0.9，不知为何不行

**Comment by zhw2590582** [comment]
你提供的网址里，我这边也是播放不了，但这个不确定是什么问题，而且也调试不了，但这个问题和播放器无关的

你试试嵌入下面这个调试代码，我再帮你看看

```html
<script src="https://unpkg.com/vconsole@latest/dist/vconsole.min.js"></script>
<script>var vConsole = new VConsole();</script>
```

**Comment by byDuming** [comment]
> 

我已嵌入，就麻烦你帮我看看了，再次感谢！！！

**Comment by zhw2590582** [comment]
应该是你的代码问题，iframe 并没有加载，所以还没有到达播放器

![微信图片_20230630105049](https://github.com/zhw2590582/ArtPlayer/assets/5907357/887f07f1-8360-4903-a60d-31b8e31c52ff)

**Comment by byDuming** [comment]
> 应该是你的代码问题，iframe 并没有加载，所以还没有到达播放器
> 
> ![Snipaste_2023-06-30_10-51-09](https://user-images.githubusercontent.com/5907357/249980447-1e4d59d6-ef08-4eb5-b485-7341850a34da.png)

MacPlayer.Html = '<iframe border="0" src="https://cooing.cc/addons/dp/player/index.php?key=0&id='+MacPlayer.Id+'&url='+MacPlayer.PlayUrl+'" width="100%" height="100%" marginWidth="0" frameSpacing="0" marginHeight="0" frameBorder="0" scrolling="no" vspale="0" noResize sandbox="allow-popups"></iframe>';
MacPlayer.Show();

这是我的播放器代码，你看看有什么问题？

**Comment by zhw2590582** [comment]
这个我无法调试的，而且和播放器无关，你需要一步一步的调试找出原因才行

**Comment by byDuming** [comment]
> 这个我无法调试的，而且和播放器无关，你需要一步一步的调试找出原因才行

并且我发现这问题只出现在移动端上，pc端是可以正常加载出 iframe 的

**Comment by zhw2590582** [comment]
最直接的方法，你直接在网页里添加下面这个代码，看能不能播放：

```html
<iframe width="100%" height="100%" src="https://cooing.cc/addons/dp/player/index.php?key=0&amp;url=https://s6.bfzycdn.com/video/guimiezhirenduandaocunpian/第01集/index.m3u8" frameborder="0" border="0" marginwidth="0" marginheight="0" scrolling="no" allowfullscreen="allowfullscreen" mozallowfullscreen="mozallowfullscreen" msallowfullscreen="msallowfullscreen" oallowfullscreen="oallowfullscreen" webkitallowfullscreen="webkitallowfullscreen" security="restricted" sandbox="allow-same-origin allow-forms allow-scripts"></iframe>
```

**Comment by byDuming** [comment]
> 最直接的方法，你直接在网页里添加下面这个代码，看能不能播放：
> 
> ```
> <iframe width="100%" height="100%" src="https://cooing.cc/addons/dp/player/index.php?key=0&amp;url=https://s6.bfzycdn.com/video/guimiezhirenduandaocunpian/第01集/index.m3u8" frameborder="0" border="0" marginwidth="0" marginheight="0" scrolling="no" allowfullscreen="allowfullscreen" mozallowfullscreen="mozallowfullscreen" msallowfullscreen="msallowfullscreen" oallowfullscreen="oallowfullscreen" webkitallowfullscreen="webkitallowfullscreen" security="restricted" sandbox="allow-same-origin allow-forms allow-scripts"></iframe>
> ```

不行，还是一直等待连接中...

**Comment by byDuming** [comment]
> 最直接的方法，你直接在网页里添加下面这个代码，看能不能播放：
> 
> ```
> <iframe width="100%" height="100%" src="https://cooing.cc/addons/dp/player/index.php?key=0&amp;url=https://s6.bfzycdn.com/video/guimiezhirenduandaocunpian/第01集/index.m3u8" frameborder="0" border="0" marginwidth="0" marginheight="0" scrolling="no" allowfullscreen="allowfullscreen" mozallowfullscreen="mozallowfullscreen" msallowfullscreen="msallowfullscreen" oallowfullscreen="oallowfullscreen" webkitallowfullscreen="webkitallowfullscreen" security="restricted" sandbox="allow-same-origin allow-forms allow-scripts"></iframe>
> ```

![图片](https://github.com/zhw2590582/ArtPlayer/assets/49818466/660d451e-4e7b-47c8-a26f-18906a051664)
我是这样使用artpalyer播放器的，不知道是否正确？

**Comment by zhw2590582** [comment]
我也不清楚这个

**Comment by zhw2590582** [comment]
你手机打开，也是可以播放的

手机：[demo](https://www.artplayer.org/mobile.html?libs=&code=const%20%24app%20%3D%20document.querySelector(%27.artplayer-app%27)%3B%0A%24app.innerHTML%20%3D%20%60%3Ciframe%20width%3D%22100%25%22%20height%3D%22100%25%22%20src%3D%22https%3A%2F%2Fcooing.cc%2Faddons%2Fdp%2Fplayer%2Findex.php%3Fkey%3D0%26amp%3Burl%3Dhttps%3A%2F%2Fs6.bfzycdn.com%2Fvideo%2Fguimiezhirenduandaocunpian%2F%E7%AC%AC01%E9%9B%86%2Findex.m3u8%22%20frameborder%3D%220%22%20border%3D%220%22%20marginwidth%3D%220%22%20marginheight%3D%220%22%20scrolling%3D%22no%22%20allowfullscreen%3D%22allowfullscreen%22%20mozallowfullscreen%3D%22mozallowfullscreen%22%20msallowfullscreen%3D%22msallowfullscreen%22%20oallowfullscreen%3D%22oallowfullscreen%22%20webkitallowfullscreen%3D%22webkitallowfullscreen%22%20security%3D%22restricted%22%20sandbox%3D%22allow-same-origin%20allow-forms%20allow-scripts%22%3E%3C%2Fiframe%3E%60)

代码：[demo](https://www.artplayer.org/?libs=&code=const%20%24app%20%3D%20document.querySelector(%27.artplayer-app%27)%3B%0A%24app.innerHTML%20%3D%20%60%3Ciframe%20width%3D%22100%25%22%20height%3D%22100%25%22%20src%3D%22https%3A%2F%2Fcooing.cc%2Faddons%2Fdp%2Fplayer%2Findex.php%3Fkey%3D0%26amp%3Burl%3Dhttps%3A%2F%2Fs6.bfzycdn.com%2Fvideo%2Fguimiezhirenduandaocunpian%2F%E7%AC%AC01%E9%9B%86%2Findex.m3u8%22%20frameborder%3D%220%22%20border%3D%220%22%20marginwidth%3D%220%22%20marginheight%3D%220%22%20scrolling%3D%22no%22%20allowfullscreen%3D%22allowfullscreen%22%20mozallowfullscreen%3D%22mozallowfullscreen%22%20msallowfullscreen%3D%22msallowfullscreen%22%20oallowfullscreen%3D%22oallowfullscreen%22%20webkitallowfullscreen%3D%22webkitallowfullscreen%22%20security%3D%22restricted%22%20sandbox%3D%22allow-same-origin%20allow-forms%20allow-scripts%22%3E%3C%2Fiframe%3E%60)
