### ISSUE TITLE
Player styling - hide controls, customize buttons

### ISSUE THREAD

**Issue by trompx** [zhw2590582/ArtPlayer#57]
I've gone through the documentation and couldn't find a way to **hide all controls**.

I'd like to have a muted/autoplay video that I can still pause.
On pause, only the big play button should show, then disappear when I click again.
Is there a way to do that in artplayer or should I directly hide controls via css ?

Is there a **recommended way to override artplayer styles/icons** ?
I'd like to modify the play button (and maybe other part of the player) which is rendered as `art-icon art-icon-state` and has a harcoded svg in artplayer.js.

Otherwise thanks for making artplayer, I'm loving the modular code structure and easy install in an es6/webpack project!

**Comment by zhw2590582** [comment]
Hide all [controls](https://artplayer.org/document/#/?id=controls-1) : 
`art.controls.show = false`;

But do you want to hide controls permanently，can be achieved by css : 
`.art-bottom: none`;

All [icons](https://artplayer.org/document/#/?id=icons) are replaceable：
```js
var art = new Artplayer({
    container: '.artplayer-app',
    url: 'path/to/video.mp4',
    icons: {
        state: 'Your svg or other image format url',
    },
});
```

**Comment by trompx** [comment]
Ok, yes I want them disabled permanently, but not the state icon which is perfect as it is not linked to controls.

I thought I could do:
```
    var art = new Artplayer({
        container: '.artplayer-app',
        loop: true,
        controls: {
          show: false,
        }
        ...
    });
```
But I was getting : `artplayer.js:8 Uncaught Error: [Type Error]: 'option.controls' require 'array' type, but got 'object'`

Anyway with:
```
    var art = new Artplayer({
        container: '.artplayer-app',
        loop: true,
        ...
    });
    art.controls.show = false;
```
It is doing nothing, the video starts with all the controls visible. When the video first end, controls disappear (until you hover the video again).

Really cool to be able to override the icons, even with html tags!

**Comment by zhw2590582** [comment]
It can be hidden permanently like this:
```css
.art-bottom {
    display:none;
}
```

**Comment by trompx** [comment]
I had to do:
```
    art.on('ready', function() {
        art.controls.show = false;
    });
```
for the controls to not show on video start (inspired from [loading](https://artplayer.org/document/#/?id=loading)). Maybe a little documentation update could help.

But it still appear on mouse hover. I'll go the css route to hide it permanently, but it may be a good idea to provide that through the art player instanciation, like:
```
    var art = new Artplayer({
        container: '.artplayer-app',
        controls: {
             hidePermantly: true, // hide even on mouse interaction
        }
    });
```
What do you think?

**Comment by zhw2590582** [comment]
I think, as a player library, a controls is necessary. If you don't need a controls, it can be more convenient to use the native video tag directly.

**Comment by trompx** [comment]
I know but I provide an interface for my clients to control what they want to display. So I need to make it as customizable as it can be. But I can totally customize it by css.
