### ISSUE TITLE
请问有什么办法可以支持远程json弹幕？

### ISSUE THREAD

**Issue by cqsn558** [zhw2590582/ArtPlayer#573]
我建了一个弹幕数据库，可以远程返回json数据，但弹幕插件好像只支持远程返回的xml格式，有什么办法可以支持远程返回json格式？

**Comment by zhw2590582** [comment]
支持的，使用Promise返回就可以了

https://www.artplayer.org/document/plugin/danmuku.html#%E4%BD%BF%E7%94%A8%E5%BC%82%E6%AD%A5%E8%B0%83%E7%94%A8
