### ISSUE TITLE
当页面没有变化失焦后，进度条的宽度就突然变为整个屏幕的高度，获取焦点后就恢复

### ISSUE THREAD

**Issue by dylanZk1** [zhw2590582/ArtPlayer#579]
### Environment

-   Browser:
-   Version:
-   Operating System:
-   Version:

**Comment by zhw2590582** [comment]
有没有演示的链接?

**Comment by dylanZk1** [comment]
https://dwa-1300208283.cos.ap-nanjing.myqcloud.com/error.mp4

**Comment by dylanZk1** [comment]
还有一个，进度条的预览图除了sprite图，可以添加wasm方法吗？我这里是想试着动态读取帧图像

**Comment by zhw2590582** [comment]
你可以给我一个演示的链接，而不是一个演示的视频，我才能调试。
假如视频已经全部加载完，那无需用到wasm，可以直接截图生成sprite，参考：
https://artplayer.org/?libs=./uncompiled/artplayer-tool-thumbnail/index.js&example=thumbnail

**Comment by dylanZk1** [comment]
https://drobot-1300208283.cos.accelerate.myqcloud.com/artplayer.html

**Comment by zhw2590582** [comment]
可能编译环境不一样，或者依赖的版本不一样，导致编译出来的样式的优先级有差异

**Comment by dylanZk1** [comment]
那大佬您的编译环境可以说下吗？我好调整下

**Comment by dylanZk1** [comment]
我的node版本为18.16.0，npm版本为9.5.0，其他的依赖版本和源码一样

**Comment by zhw2590582** [comment]
系统@mac node@v18.14.2 npm@9.5.0
这其实也不好排查原因，有点难搞

**Comment by dylanZk1** [comment]
https://dylan-1300208283.cos.ap-nanjing.myqcloud.com/test_art-layer-mini-progress-bar.mp4
我调试了一下，发现 .art-video-player .art-layer-mini-progress-bar样式中定义的--art-mini-progress-height变量失效了，转而height自动转为了100%，你看一下哪里出了问题呢？

**Comment by dylanZk1** [comment]
我的改动方案是，在.art_full样式中添加一个参数@height，然后将-art-mini-progress-height赋值过去，这个改动也还算小，目前测试没有问题。链接：https://drobot-1300208283.cos.accelerate.myqcloud.com/artplayer.html

**Comment by w1217358955** [comment]
我也遇到了同样的问题
系统@macM1 node@v18.14.2 npm@9.5.0
命令
npm run build

结果出现此问题 后续查看编译文件 发现art-layer-mini-progress-bar 多出一些属性

.art-layer-mini-progress-bar{
z-index:0;
height:var(--art-mini-progress-height);
background-color:var(--art-theme);
width:100%;
height:100%;
display:flex;
position:absolute;
top:auto;
bottom:0;
left:0;
right:0
}
应该是多出来的属性 把原本的height覆盖了

**Comment by w1217358955** [comment]
暂时通过引入外部css 解决问题 期待后续修复

.art-layers > .art-layer-mini-progress-bar {
  height:var(--art-mini-progress-height);
}

**Comment by zhw2590582** [comment]
下个版本中修复
