### ISSUE TITLE
Theme color not used

### ISSUE THREAD

**Issue by trompx** [zhw2590582/ArtPlayer#58]
I was trying to change the default background color which is initially black: 
```
.art-video-player .art-video {
    background-color: #000;
}
```
I can of course override it with css but is there a recommended way to do it, maybe the theme option was intended to do this?
The doc doesn't stipulate what part of the player it affects. Besides the css var --theme is not used anywhere.

**Comment by zhw2590582** [comment]
The video is opaque. It is not necessary to set the background color of the video as the theme color, and no one will notice this color.

**Comment by trompx** [comment]
For some layouts (in my case I want my video to have a specific height : 56.25% for 16/9). According to video width, as there is no cover mode, the video does not cover the whole width, and I want a background color different of my page background so I need to modify it.
But css is fine. I'm closing this if not a lot of people have the same requirements.
