### ISSUE TITLE
播放hls，缺失的.ts 文件会导致一直卡住，点击进度跳转不播放

### ISSUE THREAD

**Issue by ghost** [zhw2590582/ArtPlayer#580]
## 概述

ffmpeg HLS 切割 ts流  一共10份

故意把1.ts 、2.ts 文件删除，ArtPlayer 播放开头会 loading，但点击进度跳转 还是会 loading 状态，不会加载存在的 ts流 （例如：7.ts、8.ts）

![image](https://github.com/zhw2590582/ArtPlayer/assets/140519127/08a1c2ed-423c-4fa9-9fdb-5e687d05cd1c)

## 预期行为

在 dplayer 配合 hls.js 在上述场景中，1.ts、 2.ts 文件缺失，会自动跳转播放至3.ts流 。播放交互正常

**Comment by zhw2590582** [comment]
有没有m3u8链接，我试试

**Comment by zhw2590582** [comment]
这个切片加载完全是hls.js的行为，artplayer是没有做任何干预的，或者你可以看看hls.js的配置，当第一个切片404的时候，它一直重连这个切片，文档里看看能不能跳过错误的切片，或者换个hls.js的版本，例如你上面说的那个配和aplayer的那个hls的版本：[demo](https://artplayer.org/?libs=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fhls.js%2F8.0.0-beta.3%2Fhls.min.js&code=const%20%24container%20%3D%20document.querySelector(%27.artplayer-app%27)%3B%0Aconst%20%24video%20%3D%20document.createElement(%27video%27)%3B%0A%24video.style.width%20%3D%20%27100%25%27%3B%0A%24video.style.height%20%3D%20%27100%25%27%3B%0A%24video.controls%20%3D%20true%3B%0A%24container.appendChild(%24video)%3B%0A%0Aconst%20hls%20%3D%20new%20Hls()%3B%0Ahls.loadSource(%27https%3A%2F%2Ftest-video-xi.vercel.app%2Fplaylist.m3u8%27)%3B%0Ahls.attachMedia(%24video)%3B)
