### ISSUE TITLE
支持音频和视频作为分离资源进行播放

### ISSUE THREAD

**Issue by Sualiu** [zhw2590582/ArtPlayer#581]
我在使用时遇到一个问题，就是 ArtPlayer 目前似乎不支持音频和视频作为分离资源进行播放的模式。但是在一些场景下，音频和视频文件是分离保存的，这时就无法直接使用 ArtPlayer 来播放。

增加相关的支持，会让 ArtPlayer 适用于更多的场景。感谢您的贡献。

**Comment by zhw2590582** [comment]
默认的网页播放器肯定不知道这种复杂的模式，你见过那个播放器自带这个功能的，你这种属于定制化场景，需要单独定制开发才行

**Comment by Sualiu** [comment]
感谢您的回复，我完全理解您的观点。我提出的需求属于定制化功能，受众很少，不太适合直接集成到 ArtPlayer 的主要代码中。

如果我确实需要这个功能，可以在本地 fork ArtPlayer 后进行二次开发，或者利用现有接口做自定义控制逻辑。

非常感谢您的专业建议。我理解这个功能的实现会增加代码的复杂性。

谢谢您的帮助。
