### ISSUE TITLE
支持内封字幕

### ISSUE THREAD

**Issue by mastersamasama** [zhw2590582/ArtPlayer#582]
请问播放器支持内封字幕吗?或者是否有方法获取内封字幕轨的信息?

**Comment by zhw2590582** [comment]
不支持的，播放器本身不做任何解码的事情，可以认为播放器只是对原生的video元素换了一个皮肤而已

**Comment by dylanZk1** [comment]
如果在electron中倒是可以实现，在主进程中调用c++字幕提取工具，并返回数据

**Comment by dylanZk1** [comment]
只不过需要在本地建个node服务才行

**Comment by mastersamasama** [comment]
已解决
用ffmpeg.wasm在前端提取了字幕的Uint8Array
