### ISSUE TITLE
Video quality not same

### ISSUE THREAD

**Issue by x3inspire** [zhw2590582/ArtPlayer#584]
Hi, i noticed the video quality is not same.

![image](https://github.com/zhw2590582/ArtPlayer/assets/4635825/8fdfecee-a93c-4dea-ac0d-f0880572c27f)

On quality setting selected as Auto, but at the left it show 720. When i selected 1080, quality setting still show as auto.

![image](https://github.com/zhw2590582/ArtPlayer/assets/4635825/89cfd82a-740b-4041-af1c-12446d2c8283)

When i choose 1080 from the setting, also at the left side still show 720. Seem like both not sync?

**Comment by zhw2590582** [comment]
Yes, there is no sync yet, because usually two "Video quality" are not used at the same time, do you need two "Video quality"？

**Comment by x3inspire** [comment]
> Yes, there is no sync yet, because usually two "Video quality" are not used at the same time, do you need two "Video quality"？

Only one, but i like both because at left side as shortcut. So both are same function even it not synced?

**Comment by zhw2590582** [comment]
Fixed in artplayer-plugin-hls-control
