### ISSUE TITLE
请问electron框架可以兼容吗

### ISSUE THREAD

**Issue by dylanZk1** [zhw2590582/ArtPlayer#585]
最近在做一个electron应用，想问下，electron调用会有影响吗？

**Comment by zhw2590582** [comment]
目前没听说过electron相关的issues，你可以试试

**Comment by dylanZk1** [comment]
现在我遇到一个问题，就是fullscreen，浏览器的安全策略导致必须要点击后才能全屏。但我设置了全屏的快捷键F11，逻辑是，当一开始进入的时候，按F11应该进入全屏。但这时没有交互，所以无法触发webkitScreenFull。我想重写全屏的逻辑，当触发全屏时，调用electron的mainwindow.setFullScreen函数，包括全屏判断也改为isFullScreen，但我对源码不太熟悉，请问是否只要修改FullScreenMix.js就行了呢？

**Comment by zhw2590582** [comment]
你按F11后，调用electron的mainwindow.setFullScreen函数后，可以再调用art.fullScreen = true
