### ISSUE TITLE
字幕新增 ass 和 lrc 渲染组件

### ISSUE THREAD

**Issue by dylanZk1** [zhw2590582/ArtPlayer#592]
我发现 vtt 针对 ass 和 lrc 的渲染效果并不好，只是单单提取文字而已。我想新增 ass 渲染组件，自己实现或者调用ass.js。这个必须修改源码，可我从源码中找不到字幕直接渲染的代码，想问一下修改哪里较为合适？

**Comment by dylanZk1** [comment]
我试了下，发现ass.js和artplayer有冲突，一旦引入就会报错，我也不知道是编译指令的问题，还是其他冲突

**Comment by cong71925** [comment]
> 我发现 vtt 针对 ass 和 lrc 的渲染效果并不好，只是单单提取文字而已。我想新增 ass 渲染组件，自己实现或者调用ass.js。这个必须修改源码，可我从源码中找不到字幕直接渲染的代码，想问一下修改哪里较为合适？

https://github.com/libass/JavascriptSubtitlesOctopus
可以试试这个
