### ISSUE TITLE
切换视频后，初次点击控制条，无法正常跳转，回到最初

### ISSUE THREAD

**Issue by dylanZk1** [zhw2590582/ArtPlayer#594]
### Expected behaviour
切换视频后点击控制条可以正常跳转

### Actual behaviour
切换视频后，初次点击控制条，无法正常跳转，回到最初，然后正常
### Environment

-   Browser: electron
-   Version: 25.1.0
-   Operating System: Windows/Mac
-   Version: 11/BigSur

**Comment by dylanZk1** [comment]
我好像发现问题出在哪里了，视频刚播放的时候没有触发video:canplay，导致video标签信息没有同步。当点击控制条时，canplay事件被触发了，而此时currentTime还是0，所以就从头播放了

**Comment by zhw2590582** [comment]
视频元信息加载完之前，是无法设置播放时间的
