### ISSUE TITLE
Show "Auto" in quality menu (artplayerPluginHlsQuality)

### ISSUE THREAD

**Issue by icewyvrn** [zhw2590582/ArtPlayer#595]
How to add the auto quality in the menu when using artplayerPluginHlsQuality?

i see that there is an option for changing the auto text?
![image](https://github.com/zhw2590582/ArtPlayer/assets/41411360/0b736b6e-72fc-4358-8d93-ee1661a67a3b)

**Comment by zhw2590582** [comment]
I'm not sure about the function you want, but you can modify the source code yourself, this plugin is very simple

https://github.com/zhw2590582/ArtPlayer/blob/master/packages/artplayer-plugin-hls-quality/src/index.js

**Comment by icewyvrn** [comment]
thanks

**Comment by icewyvrn** [comment]
@zhw2590582 how to make the player remember the selected quality?
