### ISSUE TITLE
字幕和弹幕没有进行编码处理，只能正常显示utf8编码的

### ISSUE THREAD

**Issue by dylanZk1** [zhw2590582/ArtPlayer#596]
### Expected behaviour
涉及文本的部分可以通过外部程序转为正常编码后显示，或直接使用矢量图渲染(最理想的解决办法)
### Actual behaviour
字幕和弹幕没有进行编码处理，只能正常显示utf8编码的
### Steps to reproduce
pass
### Environment

-   Browser: electron
-   Version: 25.1.0
-   Operating System: windows/Mac
-   Version:11/BigSur

**Comment by zhw2590582** [comment]
字幕有encoding选项，不过弹幕还没有，弹幕文件可以fetch后单独处理，再把弹幕数组传到选项里

https://artplayer.org/document/start/option.html#subtitle

**Comment by zhw2590582** [comment]
所以这个只能在播放器以外进行处理了
