### ISSUE TITLE
Remove pause before video:ended

### ISSUE THREAD

**Issue by wpplumber** [zhw2590582/ArtPlayer#597]
Welcome, I want to toggle a prop when user plays a video which works ok, but the conflict with `video:pause` which works fine too when pausing **manually** but the current version seems firing `video:pause` before `video:ended`!

Is there a solution before getting this fixed in other release?

**Comment by zhw2590582** [comment]
In fact, this is the behavior of the browser's native video element and cannot be changed

**Comment by wpplumber** [comment]
Thank you, @zhw2590582

I used the following:

```
art.on('pause', (...args) => {

});
```
