### ISSUE TITLE
可以支持视频列表播放吗？

### ISSUE THREAD

**Issue by dylanZk1** [zhw2590582/ArtPlayer#599]
你好，我在做一个electron本地播放器，在读取目录时会获取到目录下多个媒体文件，我想集合在一个列表中播放。之后目录有变动也可以动态更新。如果是手动添加视频，也可以直接加入列表。列表最好是右侧单击弹出那种。

逻辑方面我可以自己实现，可是界面实现方面，我没啥把握，而且我觉得这个也是比较实际有用的功能，所以作者可以考虑实现下这个功能的UI嘛？不是通过layer层的方式。

**Comment by dylanZk1** [comment]
我反正这里先尝试自己实现一个，如果作者有更好的实现方案，我就改回来

**Comment by zhw2590582** [comment]
你是说播放器列表的UI，样式还是你自己写好一些，不一定要用layer，可以在播放器外面实现，你甚至可以用vue或者react来实现
