### ISSUE TITLE
vue如何监听各个事件

### ISSUE THREAD

**Issue by UmeusYoung** [zhw2590582/ArtPlayer#60]
您好，这个demo过于简单，我想知道怎么去监听播放器事件呢？

**Comment by zhw2590582** [comment]
自定义事件：[https://artplayer.org/document/#/?id=event](https://artplayer.org/document/#/?id=event)

video原生事件: [https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Media_events](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Media_events)

```js
const art = new Artplayer({
// ...
});

// 自定义事件
art.on('ready', () => {
// ...
});

// 原生事件
art.on('video:canplay', () => {
// ...
})
```

**Comment by UmeusYoung** [comment]
实例是挂载到vue上去了~，没有定义art，我怎么去监听呢？抱歉，我vue也是初涉不深~

**Comment by zhw2590582** [comment]
vue的话，可以用这个: [artplayer-vue](https://github.com/zhw2590582/ArtPlayer/tree/master/packages/artplayer-vue)
这里有个例子：[https://codesandbox.io/s/6z76lm109n](https://codesandbox.io/s/6z76lm109n)
第49行可以获取art实例

**Comment by UmeusYoung** [comment]
抱歉，我没表述清楚~我就是看了这个例子，然后不知道怎么去监听事件了~在创建播放器的时候就调取了getInstance这个方法，获得了实例，但是怎么写接下来的监听事件呢，类似于组件上自定义一个事件"pause":
<ArtplayerComponent
      :option="option"
      @pause="pause"
      @getInstance="getInstance"
      :style="{
        width: '600px',
        height: '400px',
        margin: '0 auto'
      }"
    />
有没有更深一点的vue demo，能让我知道在vue中怎么监听artplayer的各种事件？

**Comment by zhw2590582** [comment]
上面那个例子，假如要监听`pause`的话，修改一下就可以了：

```js
    getInstance(ins) {
      ins.on('pause', () => {
        // ...
      });
    }
```

**Comment by UmeusYoung** [comment]
非常感谢，已经解决！我以为getInstance就调用一次，不可以监听呢（主要是我把返回的实例又挂载到vue的data中，外部调用就报错）~这个播放器很好用，自定义最好！您应该多推广一下，比我用的其他的播放器要好看还实用！尤其是自定义这块，无与伦比啊！有没有学习交流群，也可以推荐一个，谢谢！

**Comment by zhw2590582** [comment]
简介下面有QQ群二维码
