### ISSUE TITLE
同页面存储多个播放视频的播放记录

### ISSUE THREAD

**Issue by dylanZk1** [zhw2590582/ArtPlayer#602]
若同一个Artplayer播放了不止一个视频，存储播放记录的时候可以根据url, md5（本地文件）等关键字段存储吗？源码只是根据Artplayer对象本身播放的时长存储的，并未依据视频信息存储

**Comment by zhw2590582** [comment]
默认播放器记录的储存是共享的，不同的art都是使用同一个localStorage，播放记录的默认依据是url，但你可以给选项传一个id值，以id为依据

https://artplayer.org/document/start/option.html#id

假如你希望不同的art使用不同的localStorage，也是可以的
https://artplayer.org/document/advanced/built-in.html#storage
