### ISSUE TITLE
插件可以添加移除的函数吗？

### ISSUE THREAD

**Issue by dylanZk1** [zhw2590582/ArtPlayer#603]
源码里实现了插件动态加载的函数，可没有实现动态移除的函数。请问可以在未来实现吗？

**Comment by dylanZk1** [comment]
源码里针对plugin.name不存在的情况，如果只是单纯的赋值一个数值，这样就很难控制创建的plugin了，最好是可以维护一个plugin列表，将plugin体和name进行绑定，这样修改也好，删除也好，操作至少可控

**Comment by zhw2590582** [comment]
插件可以通过 `art.plugins['yourPluginName']` 访问到，没有直接动态移除的插件，是因为插件里可以创建dom或者绑定事件，art是不知道这些边效应的，所以也不能直接移除，但你可以为插件自定义一个移除方法来移除插件的边效应

```js
function yourPlugin(art) {
    return {
        name: 'yourPlugin',
        destroy: function () {
            console.info('destroy');
        },
    };
}
```

```js
art.plugins['yourPlugin'].destroy();
```

**Comment by dylanZk1** [comment]
感谢！
