### ISSUE TITLE
art.switchUrl后没有触发autoPlayBack

### ISSUE THREAD

**Issue by dylanZk1** [zhw2590582/ArtPlayer#611]
art.switchUrl后没有触发autoPlayBack。通过源码分析，可知，autoPlayBack只有在artplayer初始化完成后才会触发，若切换了url，autoPlayBack不会触发。

**Comment by zhw2590582** [comment]
这个需要优化一下，事实上很多播放状态是没有带到下一个播放地址的，最后办法还是销毁播放器然后重新构建
