### ISSUE TITLE
artplayer模块中style的index.less导入自定义less后无法被js识别

### ISSUE THREAD

**Issue by dylanZk1** [zhw2590582/ArtPlayer#613]
artplayer模块中style的index.less导入自定义less后无法被js识别。但如果单独引入的话，就可以识别了。

**Comment by dylanZk1** [comment]
通过测试，好像是 !!document.getElementById('artplayer-style') 为 true，具体原因还在排查中

**Comment by zhw2590582** [comment]
你需要的是样式热更新吧？假如修改源码的话是不支持的，默认都是刷新才生效，假如修改频繁的话，建议还是单独引入额外的样式
