### ISSUE TITLE
弹幕设置和开关持久化

### ISSUE THREAD

**Issue by colorthoro** [zhw2590582/ArtPlayer#614]
页面刷新之后保留上次的弹幕设置。
自己简单做了缓存，使用config方法恢复弹幕设置，但是控制栏里的弹幕设置在config恢复后不会同步选中项。

**Comment by zhw2590582** [comment]
在`artplayer-plugin-danmuku@5.1.0`已经支持该功能：[demo](https://artplayer.org/?libs=.%2Funcompiled%2Fartplayer-plugin-danmuku%2Findex.js&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09plugins%3A%20%5B%0A%09%09artplayerPluginDanmuku(%7B%0A%09%09%09...JSON.parse(localStorage.getItem(%27danmuku%27)%20%7C%7C%20%27%7B%7D%27)%2C%0A%09%09%09danmuku%3A%20%27%2Fassets%2Fsample%2Fdanmuku.xml%27%2C%0A%09%09%7D)%2C%0A%09%5D%2C%0A%7D)%3B%0A%0Aart.on(%27artplayerPluginDanmuku%3Aconfig%27%2C%20(option)%20%3D%3E%20%7B%0A%09%2F%2F%20%E6%8E%92%E9%99%A4%E4%B8%8D%E5%BF%85%E8%A6%81%E7%9A%84%E9%80%89%E9%A1%B9%EF%BC%8C%E5%A6%82mount%0A%09const%20%7B%20mount%2C%20...rest%20%7D%20%3D%20option%3B%0A%0A%09%2F%2F%20%E4%BF%9D%E5%AD%98%E5%88%B0localStorage%0A%09localStorage.setItem(%27danmuku%27%2C%20JSON.stringify(rest))%3B%0A%7D)%3B)
