### ISSUE TITLE
可以添加媒体文件编码检测吗？

### ISSUE THREAD

**Issue by dylanZk1** [zhw2590582/ArtPlayer#615]
可以添加媒体文件的编编码检测吗？主要的应用场景，就是做本地媒体播放时，就播放格式，我这儿主要是以后缀名为参考(单纯的本地播放，不存在接口之类的)。但存在恶意文件，后缀满足但编编码不满足。导致应用或页面卡住不动。

目前的方案是接入mediainfo.js，但性能开销较大。也试着接入ffmpeg.wasm，但问题也差不多。我这儿现在也没有其他更合适的方案

**Comment by zhw2590582** [comment]
编码检测是个复杂的功能，这不应该是播放器的工作，需要在播放前处理
