### ISSUE TITLE
希望支持点击隐藏工具栏

### ISSUE THREAD

**Issue by viocha** [zhw2590582/ArtPlayer#622]
每次点击播放器就是将工具栏显示，照理说再次点击应该将工具栏隐藏，但是没有实现该功能，希望能改进一下

**Comment by zhw2590582** [comment]
没理解你的意思，YouTube和B站都不是这样的逻辑的，什么场景下是需要点击播放器隐藏工具栏的？

**Comment by viocha** [comment]
> 没理解你的意思，YouTube和B站都不是这样的逻辑的，什么场景下是需要点击播放器隐藏工具栏的？

https://github.com/zhw2590582/ArtPlayer/assets/66580331/1270f271-3d3c-4a57-a60b-dc08e07d671e

https://github.com/zhw2590582/ArtPlayer/assets/66580331/7ee13e2a-bfea-4720-9cde-e49ca9b94ca7

YouTube和B站都支持

**Comment by zhw2590582** [comment]
原来你是指移动端的，那确实需要改进一下

**Comment by CF-JS** [comment]
支持，目前移动端主流播放器都支持点击关闭工具栏，这个播放器只能点击显示，隐藏只能等自动消失有点不好用，还有就是快进的时候会出现工具栏

**Comment by CF-JS** [comment]
> 原来你是指移动端的，那确实需要改进一下

希望大佬有空可以考虑弄一下

**Comment by zhw2590582** [comment]
下个版本中修复该问题
