### ISSUE TITLE
倍速功能在safari中不生效

### ISSUE THREAD

**Issue by dengshenkk** [zhw2590582/ArtPlayer#624]
### Expected behaviour
能够按照设定的倍速进行播放
### Actual behaviour
没有反应, 控制台没有报错和输出
### Steps to reproduce
1. 使用safari打开这个页面测试 (测试视频)[https://www.artplayer.org/?libs=&code=Artplayer.PLAYBACK_RATE%20%3D%20%5B0.5%2C%201%2C%201.5%2C%202%2C%203%2C%204%5D%3B%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09setting%3A%20true%2C%0A%09playbackRate%3A%20true%2C%0A%7D)%3B%0A]
### Environment

-   Browser: safari
-   Version: 16.4 (18615.1.26.110.1)
-   Operating System: MacOS
-   Version: 13.3.1 (a) (22E772610a)

**Comment by zhw2590582** [comment]
我这边测试没有任务，等我升级一下MacOS再看看
Safari：15.3 (17612.4.9.1.8)
MacOS: 12.2.1 (21D62)

**Comment by zhw2590582** [comment]
升级过后，亲测没有问题，只是Safari的倍速播放器没有Chrome那么流畅

**Comment by dengshenkk** [comment]
> 升级过后，亲测没有问题，只是Safari的倍速播放器没有Chrome那么流畅

你是Ventura吗? 我测试了bigsur的safari也没问题, 只有Ventura的safari有问题

**Comment by dengshenkk** [comment]
> 升级过后，亲测没有问题，只是Safari的倍速播放器没有Chrome那么流畅

你是Ventura吗? 我测试了bigsur的safari也没问题, 只有Ventura的safari有问题

**Comment by zhw2590582** [comment]
问题似乎与播放器无关，而是和原生的video有关，播放器也只是调用`video.playbackRate = 1`这样的接口，
