### ISSUE TITLE
can't embed youtube video

### ISSUE THREAD

**Issue by cobraprojects** [zhw2590582/ArtPlayer#626]
[(https://www.artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fwww.youtube.com%2Fembed%2F3_3VNqD4Sr8%3Fsi%3D7Y9B5z0wVI53Lhx3%27%0A%7D)%3B)
](https://www.artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fwww.youtube.com%2Fembed%2F3_3VNqD4Sr8%3Fsi%3D7Y9B5z0wVI53Lhx3%27%0A%7D)%3B)](https://www.artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fwww.youtube.com%2Fembed%2F3_3VNqD4Sr8%3Fsi%3D7Y9B5z0wVI53Lhx3%27%0A%7D)%3B)

**Comment by zhw2590582** [comment]
This feature is not currently supported
