### ISSUE TITLE
Add safari support?

### ISSUE THREAD

**Issue by owen800q** [zhw2590582/ArtPlayer#64]
Look like the artplayer not working on and IOS. Keep loading all the time.

**Comment by owen800q** [comment]
@zhw2590582

**Comment by owen800q** [comment]
Also not working safari on Mac 

<img width="1341" alt="Screenshot 2020-04-10 at 5 06 16 PM" src="https://user-images.githubusercontent.com/19252045/78979106-bbb32700-7b4d-11ea-98b2-39b7304d04d6.png">

**Comment by zhw2590582** [comment]
Now it has been fixed, but it has not been released to npm. You can find the latest artplayer.js in the dist directory. 

This seems to be a compatibility difference between safari and chrome.

When the `preload` attribute of the video element is `auto`, posters can not be displayed in chrome. 

When the `preload` attribute is `metadata`, posters can be displayed in chrome but video data cannot be loaded in safari.

**Comment by owen800q** [comment]
Thanks bro, it saves a lot of efforts, solving by wrapping player initialisation inside a condition to check if browser is safari and configure preload as auto otherwise metadata.👍
