### ISSUE TITLE
Subtitle background with padding.

### ISSUE THREAD

**Issue by huy232** [zhw2590582/ArtPlayer#641]
Hi, is there a way for me to padding my background for the subtitles? I have success in doing it but it has a weird padding when there's no text at all, which is not like what I was expecting.

Here's the link to my CSS:
[Subtitle with background and padding](https://www.artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20art.subtitle.url%20%3D%20%27https%3A%2F%2Fccb.megaresources.co%2F33%2F5f%2F335f444d3f2712421782b4bfe8e1b746%2Feng-2.vtt%27%0A%20%20%20%20art.subtitle.style(%7B%0A%09%09%22background-color%22%20%3A%20%22rgba(0%2C%200%2C%200%2C%200.65)%22%2C%0A%09%09width%3A%20%22fit-content%22%2C%0A%09%09left%3A%20%2250%25%22%2C%0A%09%09transform%3A%20%22translateX(-50%25)%22%2C%0A%09%09padding%3A%20%2210px%22%2C%0A%09%09%22border-radius%22%3A%20%226px%22%0A%20%20%20%20%7D)%3B%0A%09art.subtitle.escape%20%3D%20false%0A%7D)%3B)

Padding still lasts when there's no text:
![Untitled](https://github.com/zhw2590582/ArtPlayer/assets/59156109/163f6b09-d7d6-4b0f-81a8-8824526378a2)

CSS in case you can't direct the URL:
```
var art = new Artplayer({
    container: '.artplayer-app',
    url: '/assets/sample/video.mp4',
});

art.on('ready', () => {
    art.subtitle.url = 'https://ccb.megaresources.co/33/5f/335f444d3f2712421782b4bfe8e1b746/eng-2.vtt'
    art.subtitle.style({
		"background-color" : "rgba(0, 0, 0, 0.65)",
		width: "fit-content",
		left: "50%",
		transform: "translateX(-50%)",
		padding: "10px",
		"border-radius": "6px"
    });
	art.subtitle.escape = false
});
```

**Comment by zhw2590582** [comment]
https://codesandbox.io/s/eager-glade-5n5r43?file=/src/index.mjs

Or you can try adding styles to the subtitle lines：

```css
.art-subtitle p {
  background: rgb(0 0 0 / 50%);
}
```

**Comment by huy232** [comment]
For the subtitles I have, I must add escape HTML for it to work, so it only contains <div/> that has text inside. It's something like this:
`<div class="art-subtitle" style="my-style-inside-here;">The escape HTML subtitle inside here, no p tag...</div>`

**Comment by zhw2590582** [comment]
In this case, you need to add your own tags to the subtitle file:

```
WEBVTT

1
00:00:00.306 --> 00:00:00.844
<p>那一天</p>
<p>あの日</p>
```

**Comment by huy232** [comment]
I can't modify the subtitles, I'm receiving them from the source provider of mine.
You can see the subtitle itself here: [The subtitle](https://ccb.megaresources.co/33/5f/335f444d3f2712421782b4bfe8e1b746/eng-2.vtt)

Some of the subtitles will have tag like this: 
`<i>Because the Lawless City...</i>`
But some just plain text like:
`Not him, either.`

**Comment by zhw2590582** [comment]
Or you can dynamically modify the subtitle style:

```js
art.on('subtitleUpdate', text => {
  if (text.trim()) {
    art.subtitle.style('background-color', 'rgba(0, 0, 0, 0.65)');
  } else {
    art.subtitle.style('background-color', 'rgba(0, 0, 0, 0)');
  }
})
```
