### ISSUE TITLE
IOS系统safari中初始化加载需要较长时间

### ISSUE THREAD

**Issue by JiangJunChengGitHub** [zhw2590582/ArtPlayer#642]
### Expected behaviour
与MAC端初始化时间相近

### Actual behaviour
IOS系统端，初始化加载需要教程时间，可以看到视频在缓存加载比较长的一段时间后才开始播放，因为网络传输速度不够快所以导致手机端打开视频后，需要很长的时间（加载视频）才开始播放，是否可以在缓存一点以后立马开始播放？

感谢，期待您的回复。

### Steps to reproduce
手机safari浏览器使用

### Environment

-   Browser:  Safari
-   Version: Mozilla/5.0 (iPhone; CPU iPhone OS 17_0_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0.1 Mobile/15E148 Safari/604.1
-   Operating System: IOS
-   Version: 17.0.3

**Comment by JiangJunChengGitHub** [comment]
补充：在MAC端播放是没有那么长的缓存时间的

**Comment by zhw2590582** [comment]
这个很可能与播放器无关，而是和手机浏览器有关，播放器是监听视频的"canplay"事件来判断视频是否可以播放。

你可以同时准备两个视频测试一下，一个使用artplayer，一个使用原生的video，对比一下是否一样的加载时间，假如是一样就说明和播放器无关
