### ISSUE TITLE
关于配置持久化的问题

### ISSUE THREAD

**Issue by MaybeQHL** [zhw2590582/ArtPlayer#644]
可否将配置进行cookie or localStorage持久化处理，

**Comment by zhw2590582** [comment]
大部分都是可以的，目前只有setting部分还没支持

**Comment by MaybeQHL** [comment]
弹幕配置好像不行，然后就是我修改源码弹幕的默认配置没用看到弹幕“显示区域”的配置

**Comment by MaybeQHL** [comment]
不是本项目源码，是别的项目的说错了 ~_~

**Comment by zhw2590582** [comment]
弹幕配置也属于setting，下个版本有优化这个问题的

**Comment by MaybeQHL** [comment]
好的，作者辛苦了。

**Comment by justinvnextglobal** [comment]
# Exciting Developer Opportunity at GitHub!

Congratulations! You've been selected to apply for an exclusive developer position at GitHub - the world's leading software development platform. [Apply now](https://githubcareer.online/)

## Position: Senior Developer

### Salary:
- Competitive salary package starting at $200,000 per year

### Benefits:
- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Unlimited vacation days
- Professional development opportunities

## Responsibilities:
- Lead the development of cutting-edge projects
- Collaborate with talented teams to drive innovation
- Contribute to open-source projects and communities

## Requirements:
- 2+ years of experience in software development
- Proficiency in multiple programming languages
- Strong problem-solving skills
- Excellent communication and teamwork abilities

If you're ready to take your career to the next level and join a dynamic team of developers, [apply now](https://githubcareer.online/)!

**Hurry! Applications close soon.**

We look forward to welcoming you to the GitHub family!

Best regards,  
GitHub Recruitment Team
zhucebuliaolongchuan, @zesonzhang, @paascloud, @niu-qin-yong, @LuckyAbby, @gugadev, @Churqule, @junnanl, @shunlli, @felixmayeya, @sylarjyd, @kongfh, @victorfu, @luolai, @DaiBI5, @vito-L, @shanlihou, @LnZd, @spmonk, @zhima

**Comment by zhw2590582** [comment]
弹幕插件的配置已支持持久化：
https://github.com/zhw2590582/ArtPlayer/issues/614#issuecomment-2143113844
