### ISSUE TITLE
请问第三方库flv.js什么时候可以替换成mpegts.js

### ISSUE THREAD

**Issue by Smecta** [zhw2590582/ArtPlayer#645]
mpegts.js这个支持H265格式了，而且还是flv.js的延续

**Comment by zhw2590582** [comment]
你直接换就可以了:  [mpegts.js demo](https://www.artplayer.org/?libs=https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fmpegts.js%401.7.3%2Fdist%2Fmpegts.min.js&code=function%20playFlv(video%2C%20url%2C%20art)%20%7B%0A%09if%20(mpegts.isSupported())%20%7B%0A%09%09if%20(art.flv)%20art.flv.destroy()%3B%0A%0A%09%09const%20flv%20%3D%20mpegts.createPlayer(%7B%0A%09%09%09type%3A%20%27flv%27%2C%0A%09%09%09url%3A%20url%0A%09%09%7D)%3B%0A%09%09flv.attachMediaElement(video)%3B%0A%09%09flv.load()%3B%0A%09%09flv.play()%3B%0A%0A%09%09art.flv%20%3D%20flv%3B%0A%09%09art.on(%27destroy%27%2C%20()%20%3D%3E%20flv.destroy())%3B%0A%09%7D%20else%20%7B%0A%09%09art.notice.show%20%3D%20%27Unsupported%20playback%20format%3A%20flv%27%3B%0A%09%7D%0A%7D%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.flv%27%2C%0A%09type%3A%20%27flv%27%2C%0A%09customType%3A%20%7B%0A%09%09flv%3A%20playFlv%2C%0A%09%7D%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%09console.info(art.flv)%3B%0A%7D)%3B)
