### ISSUE TITLE
引用js在h5加载不显示是什么原因

### ISSUE THREAD

**Issue by ange8506** [zhw2590582/ArtPlayer#65]
<script src="https://cdn.jsdelivr.net/npm/artplayer/dist/artplayer.js"></script>
<div class="artplayer-app"></div>
<script>
var art = new Artplayer({
    container: '.artplayer-app',
    url: '略',
});
</script>

虽然是这么写了但是页面只有空白

**Comment by zhw2590582** [comment]
你要给容易一个初始化的大小，宽度和高度不能为空。
