### ISSUE TITLE
[feature] 实现音轨切换

### ISSUE THREAD

**Issue by Corezcy** [zhw2590582/ArtPlayer#653]
目前有时在线播放，会有音轨切换的需求，尤其是双语电影。

希望万能的开发者后续忙里抽闲小完善一下呗。

目前我是通过ffmpeg删除音轨的方式后台改的。

多谢！！！

**Comment by zhw2590582** [comment]
播放器本身不做解码和音频处理，假如浏览器都不支持这个音轨切换的功能，播放器也是做不到的，除非找第三发的解码库

**Comment by li-guohao** [comment]
我们也有切换音轨的需求，只需要切换文件内置的音轨就行

情况是这样的：我们[ikaros](https://ikaros.run/)管理的视频需要支持多种场景的播放，
其中一种场景就是：有的视频文件是带多个音轨的，副音轨一般是staff的杂谈，比如VCB压制的k-on(可以看这个其它端播放的[演示视频](https://www.bilibili.com/video/BV1ku411E7Dw)，一般情况下主音轨就是正常的，但也有某些多音轨的视频资源主音轨默认是staff音轨，这个情况下需要播放器支持音轨切换。

web端我们想引入 artplayer ，不知道有没有合适支持切换文件内音轨的方案？

**Comment by zhw2590582** [comment]
对于非标准格式或者特殊情况，可能需要使用其他库或API来实现更复杂的功能，比如使用MPEG-DASH或HLS流时的音轨切换。

假如是是普通的mp4链接，可以通过`art.video.audioTracks`获取到音轨列表，通过设置音轨的 enabled 属性来实现的切换音轨，不过目前这个浏览器支持情况不太好

**Comment by li-guohao** [comment]
> 对于非标准格式或者特殊情况，可能需要使用其他库或API来实现更复杂的功能，比如使用MPEG-DASH或HLS流时的音轨切换。
> 
> 
> 
> 假如是是普通的mp4链接，可以通过`art.video.audioTracks`获取到音轨列表，通过设置音轨的 enabled 属性来实现的切换音轨，不过目前这个浏览器支持情况不太好

感谢回答，
我之后会尝试下后面这种的方式
根据我的观察，大部分视频都是基于h265 acc mkv格式封装的，
特殊情况web实在播放不了的，后续应该会在后端做实时转码给web端播放。

**Comment by li-guohao** [comment]
> > 对于非标准格式或者特殊情况，可能需要使用其他库或API来实现更复杂的功能，比如使用MPEG-DASH或HLS流时的音轨切换。
> > 假如是是普通的mp4链接，可以通过`art.video.audioTracks`获取到音轨列表，通过设置音轨的 enabled 属性来实现的切换音轨，不过目前这个浏览器支持情况不太好
> 
> 感谢回答， 我之后会尝试下后面这种的方式 根据我的观察，大部分视频都是基于h265 acc mkv格式封装的， 特殊情况web实在播放不了的，后续应该会在后端做实时转码给web端播放。

尝试了下，行不通，网上也没找到啥合适的方案，放弃了，
我打算把这个功能放后端和实时转码一起做了：[ikaros-dev/ikaros#522](https://github.com/ikaros-dev/ikaros/issues/522)，
基本上就是后端通过一个接口，暴露视频元数据信息，其中包括音轨信息，音轨信息展示在播放器自定义设置里，用户在播放器上切换音轨，走ffmpeg操作逻辑，返回临时URL。
