### ISSUE TITLE
Subtitle display many option on mobile

### ISSUE THREAD

**Issue by x3inspire** [zhw2590582/ArtPlayer#662]
May i know why on smartphone the subtitle option display many option?

![image](https://github.com/zhw2590582/ArtPlayer/assets/4635825/1dd74c62-e0d0-4c7d-836d-e5efb6e8bcfe)

**Comment by zhw2590582** [comment]
This UI comes from the functions that come with the iPhone, not from artplayer.

**Comment by x3inspire** [comment]
> This UI comes from the functions that come with the iPhone, not from artplayer.

Hi, i wonder wht when i play using full screen the sub not display. I had to choose Off option, then choose Auto. After that it will display, if not it will not display ever.
