### ISSUE TITLE
按住ctrl或command键时不触发设置的快捷键

### ISSUE THREAD

**Issue by WeidiDeng** [zhw2590582/ArtPlayer#667]
用hotkeys设置了按`w`键切换网页视频全屏，但焦点在播放器时，mac上面无法通过command+w关闭标签页了。同理，设置了0-9跳至视频的不同播放进度，也与浏览器的标签页切换起冲突。

**Comment by zhw2590582** [comment]
你可以使用 https://www.artplayer.org 生成一个demo链接吗，我这边复现不了你的情况

**Comment by WeidiDeng** [comment]
[这里](https://www.artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%7D)%3B%0A%0Afunction%20hotkeyEvent(event)%20%7B%0A%20%20%20%20console.info(%27click%27%2C%20event)%3B%0A%09console.info(event.ctrlKey%2C%20event.metaKey)%3B%0A%7D%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20art.hotkey.add(70%2C%20hotkeyEvent)%3B%0A%7D)%3B)，焦点在播放器时无法使用command/ctrl + f进行搜索，事件管理里面可以看到command键按下了，但是这个时候事件已经preventDefault了，无法使用默认的事件处理了。
