### ISSUE TITLE
请问没有关闭弹幕显示的功能吗

### ISSUE THREAD

**Issue by fans2333** [zhw2590582/ArtPlayer#67]
文档与实例里好像都没有写关闭弹幕显示

**Comment by zhw2590582** [comment]
可以的，只是要自己去自定义触发

说明：[artplayer-plugin-danmuku#usage](https://github.com/zhw2590582/ArtPlayer/tree/master/packages/artplayer-plugin-danmuku#usage)

演示：[demo](https://artplayer.org/?libs=.%2Funcompiled%2Fartplayer-plugin-danmuku.js&code=var%20url%20%3D%20%27https%3A%2F%2Fzhw2590582.github.io%2Fassets-cdn%27%3B%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20url%20%2B%20%27%2Fvideo%2Fyour-name.mp4%27%2C%0A%20%20%20%20autoSize%3A%20true%2C%0A%20%20%20%20setting%3A%20true%2C%0A%20%20%20%20playbackRate%3A%20true%2C%0A%20%20%20%20fullscreenWeb%3A%20true%2C%0A%20%20%20%20plugins%3A%20%5BartplayerPluginDanmuku(%7B%0A%20%20%20%20%20%20%20%20danmuku%3A%20url%20%2B%20%27%2Fdanmuku%2Fyour-name.xml%27%2C%0A%20%20%20%20%20%20%20%20speed%3A%205%2C%0A%20%20%20%20%20%20%20%20maxlength%3A%2050%2C%0A%20%20%20%20%20%20%20%20margin%3A%20%5B10%2C%20100%5D%2C%0A%20%20%20%20%20%20%20%20opacity%3A%201%2C%0A%20%20%20%20%20%20%20%20fontSize%3A%2025%2C%0A%20%20%20%20%20%20%20%20synchronousPlayback%3A%20false%2C%0A%20%20%20%20%7D)%5D%2C%0A%20%20%20%20%20controls%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20position%3A%20%27right%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%27%E5%85%B3%E9%97%AD%E5%BC%B9%E5%B9%95%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20click%3A%20function()%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20art.plugins.artplayerPluginDanmuku.hide()%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20position%3A%20%27right%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%27%E6%98%BE%E7%A4%BA%E5%BC%B9%E5%B9%95%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20click%3A%20function()%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20art.plugins.artplayerPluginDanmuku.show()%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%5D%2C%0A%7D)%3B)

**Comment by fans2333** [comment]
> 可以的，只是要自己去自定义触发
> 
> 说明：[图播放器-插件-danmuku#用法](https://github.com/zhw2590582/ArtPlayer/tree/master/packages/artplayer-plugin-danmuku#usage)
> 
> 演示：[演示](https://artplayer.org/?libs=.%2Funcompiled%2Fartplayer-plugin-danmuku.js&example=danmuku)

想再请教下有没有让弹幕不重叠的功能呢

**Comment by zhw2590582** [comment]
可以做到，但没必要，假如真是大量弹幕出现，重不重叠都没差别
