### ISSUE TITLE
Difficulty Implementing ArtPlayer with VTT Thumbnails in Next.js Project

### ISSUE THREAD

**Issue by OrkhanGG** [zhw2590582/ArtPlayer#673]
I am encountering challenges while attempting to integrate ArtPlayer into my Next.js project, particularly when trying to incorporate VTT thumbnails. Despite my efforts, I have not been successful in achieving the desired functionality.

**Comment by zhw2590582** [comment]
You can refer to the following link：

https://github.com/zhw2590582/ArtPlayer/tree/master/packages/artplayer-template/next.js

https://artplayer.org/?libs=./uncompiled/artplayer-plugin-vtt-thumbnail/index.js&example=vtt.thumbnail

**Comment by OrkhanGG** [comment]
How do we install npm dependencies of 'vtt thumbnail'? I tried `npm install artplayer-plugin-vtt-thumbnail` but it did not work.

**Comment by zhw2590582** [comment]
artplayer-plugin-vtt-thumbnail has not been released to npm, but you can directly use the files in the dist directory.
