### ISSUE TITLE
Use multiple instances

### ISSUE THREAD

**Issue by pozdnyakov-ds** [zhw2590582/ArtPlayer#675]
The Vue3+Next project uses a component with Artplayer.

The component is connected several times on the page like this:
<Playlist :playlist="region.media.id" :key="region.id"/>

Every component changes the video at certain intervals.
1) If there is only one component on the page, then everything works well.

2) If there are two or more, then he swears that there cannot be two identical components in the DOM.
Unique classes are made for this purpose. The error disappears.

3) But still different instances of the component behave as with common variables.
This is manifested in the fact that when you change the url in one playlist, the video in the next one is paused.

Nothing can be overcome.
Working with Artplayer.instances as an array does not help.

Simplified working code on Codesandbox:
[https://codesandbox.io/p/sandbox/youthful-mirzakhani-f3fxn4?file=%2Fsrc%2FApp.vue]

Part of the code:

```
<div v-show="currentItem.type.includes('video')"
   :class="ar.class + ' media'">
</div>

const ar = reactive({
        id: null,
        player: null,
        class: 'artplayer_' + randomId(4)
})

function mediaPlay(item) {
        if (ar.id == null) {
            ar.player = new Artplayer({
                container: '.' + ar.class,
                url: `...`,
                type: item.type,
                autoSize: true,
                autoplay: true,
                muted: true,
                loop: true,
                miniProgressBar: false,
                autoPlayback: true,
                isLive: true,
                mini: true
            })
            ar.id = Artplayer.instances.length - 1

            Artplayer.instances[ar.id].on('ready', () => {
                console.log("Player ready to play [", ar.id, "]", Artplayer.instances[ar.id])
                Artplayer.instances[ar.id].play()
            })

        } else {
            console.log("Change video [", ar.id, "]", Artplayer.instances[ar.id])
            Artplayer.instances[ar.id].switchUrl(`...`)
            Artplayer.instances[ar.id].type = item.type
            Artplayer.instances[ar.id].play()
        }
    }
```

**Comment by zhw2590582** [comment]
I don't quite understand what you mean. Can you provide a demo?

**Comment by pozdnyakov-ds** [comment]
Hello! Here a link to Codesand:
[https://codesandbox.io/p/sandbox/youthful-mirzakhani-f3fxn4?file=%2Fsrc%2FApp.vue]

**Comment by zhw2590582** [comment]
So you want each player's play and pause to not affect other players?

**Comment by pozdnyakov-ds** [comment]
Of course I want to. And I don't understand how this can be fixed. The code was originally written without using Artplayer.instances. Even using the Art player.instances array did not help to separate the players.
Is this even possible with this library?

**Comment by zhw2590582** [comment]
Use this
https://artplayer.org/document/en/start/option.html#mutex
