### ISSUE TITLE
添加视频列表组件，包含当前播放列表和历史播放记录

### ISSUE THREAD

**Issue by dylanZk1** [zhw2590582/ArtPlayer#677]
我这个是一个本地视频+网络视频的播放器，需要显示当前播放列表和历史播放列表。

当前播放列表的话，如果是本地视频，则显示对应目录下的所有视频文件；如果是网络视频，则根据列表API返回的JSON对象来

历史播放记录的话，本地视频调用electron或者本地数据库缓存的列表，如果是网络视频，同样有对应的API。

数据方面我可以自己操作，但前端 UI 部分建议可以添加一下

**Comment by dylanZk1** [comment]
样式的话，我给个参考：

可以使用侧边栏的形式，侧边栏弹出的界面又可以分为左右可滑动的两个tab，一个播放列表，一个历史记录。列表单个元素的话，两个tab都需要给出缩略图，视频标题和视频时长，历史记录需要多一个播放到的时刻，类似aa::bb::cc/dd::ee::ff 这种。

**Comment by dylanZk1** [comment]
如果可以的话，播放列表那里可以加个导入列表按钮，不方便的话可以不加

**Comment by zhw2590582** [comment]
播放列表的定制化太广泛，其实也只是一个简单的列表，但样式难以适应不同的环境，建议还是自己添加它，你甚至可以使用vue和react做列表

**Comment by 1229984599** [comment]
> 播放列表的定制化太广泛，其实也只是一个简单的列表，但样式难以适应不同的环境，建议还是自己添加它，你甚至可以使用vue和react做列表

大佬，这个是不是不支持jsx呀，我测试半天都不行，可不可以给个使用示例呀

**Comment by zhw2590582** [comment]
```jsx
import { useState } from "react";
import ReactDOM from "react-dom";
import Artplayer from "./Artplayer.tsx";

function List({ target }) {
  return ReactDOM.createPortal(<div>这是通过Portal渲染的组件</div>, target);
}

function App() {
  const [art, setArt] = useState(null);
  return (
    <div>
      <Artplayer
        option={{
          url: "https://artplayer.org/assets/sample/video.mp4",
          layers: [
            {
              name: "list",
              html: "",
            },
          ],
        }}
        style={{
          width: "600px",
          height: "400px",
          margin: "60px auto 0",
        }}
        getInstance={(instance) => {
          setArt(instance);
        }}
      />
      {art ? <List target={art.layers.list} /> : null}
    </div>
  );
}

export default App;

```

**Comment by 1229984599** [comment]
> @1229984599
> 
> ```js
> import { useState } from "react";
> import ReactDOM from "react-dom";
> import Artplayer from "./Artplayer.tsx";
> 
> function List({ target }) {
>   return ReactDOM.createPortal(<div>这是通过Portal渲染的组件</div>, target);
> }
> 
> function App() {
>   const [art, setArt] = useState(null);
>   return (
>     <div>
>       <Artplayer
>         option={{
>           url: "https://artplayer.org/assets/sample/video.mp4",
>           layers: [
>             {
>               name: "list",
>               html: "",
>             },
>           ],
>         }}
>         style={{
>           width: "600px",
>           height: "400px",
>           margin: "60px auto 0",
>         }}
>         getInstance={(instance) => {
>           setArt(instance);
>         }}
>       />
>       {art ? <List target={art.layers.list} /> : null}
>     </div>
>   );
> }
> 
> export default App;
> ```

感谢大佬的解答，不过我是想在具体的html等属性上使用jsx，大致是下面这种效果
```javascript
art.setting.add({
      name: "skip-end",
      html: "片尾",
      range: [playerStore.playerConfig.skipEnd, 0, 6 * 60, 1],
      tooltip: () => {
        return (
          <span class="skip-end-tooltip">
            {formatTime(playerStore.playerConfig.skipEnd)}
          </span>
        );
      },
      onChange(item) {
        playerStore.playerConfig.skipEnd = item.range;
        return formatTime(item.range);
      },
    });
```
