### ISSUE TITLE
请问 我使用 websocket，静音情况下，当软件最小化或者被其他应用挡住，播放器就自动暂停了，打开后是延续播放而不是播放最新的，请问怎么解决呢

### ISSUE THREAD

**Issue by RayCssjmt** [zhw2590582/ArtPlayer#678]
请问 我使用 websocket，当软件最小化或者被其他应用挡住，播放器就自动暂停了，打开后是延续播放而不是播放最新的，请问怎么解决呢
### Expected behaviour
继续播放或者播放实时
### Actual behaviour
暂停播放了，打开后还是延续播放 不是跳转到实时
### Steps to reproduce
将其他英语窗口最大化，把该应用挡住或 最小化

-   Browser: Electron
-   Version:
-   Operating System: Window
-   Version:10

**Comment by zhw2590582** [comment]
这似乎与播放器的行为无关，而是在于你怎么拉取最新的流然后跳转到最新的位置，我不知道你的实际拉取的流的情况，所以也无法提供更多的建议

**Comment by RayCssjmt** [comment]
> 这似乎与播放器的行为无关，而是在于你怎么拉取最新的流然后跳转到最新的位置，我不知道你的实际拉取的流的情况，所以也无法提供更多的建议

我这边是通过 node ffmpeg 将 rtsp 转成 mpegts 的 ws ，是不停的 通讯，只是 前端播放器，只要音量为静音 缩小或者被挡住就会遇到 自动暂停的情况，音量为1就不会了，现在想 解决自动暂停 或者 ，自动播放 重新加载最新的 流进行播放
