### ISSUE TITLE
Unsupport M3U8 file / 不支持M3U8播放QAQ

### ISSUE THREAD

**Issue by Dos7t3r** [zhw2590582/ArtPlayer#679]
无法解析m3u8文件。。。官方文档的案例代码也运行失败QAQ

**Comment by zhw2590582** [comment]
你可以把你的M3U8地址贴出来吗，否则我也无法解答

**Comment by Dos7t3r** [comment]
> 你可以把你的M3U8地址贴出来吗，否则我也无法解答

这是一个示例M3U8 
https://v8.suonizy-youku.com/202401/25/sVeZ3vmLeW1/video/index.m3u8
您可以试试

**Comment by zhw2590582** [comment]
可以播放的，但你的地址有一定概率会出现502：[demo](https://artplayer.org/?libs=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fhls.js%2F8.0.0-beta.3%2Fhls.min.js&code=function%20playM3u8(video%2C%20url%2C%20art)%20%7B%0A%20%20%20%20if%20(Hls.isSupported())%20%7B%0A%20%20%20%20%20%20%20%20if%20(art.hls)%20art.hls.destroy()%3B%0A%20%20%20%20%20%20%20%20const%20hls%20%3D%20new%20Hls()%3B%0A%20%20%20%20%20%20%20%20hls.loadSource(url)%3B%0A%20%20%20%20%20%20%20%20hls.attachMedia(video)%3B%0A%20%20%20%20%20%20%20%20art.hls%20%3D%20hls%3B%0A%20%20%20%20%20%20%20%20art.on(%27destroy%27%2C%20()%20%3D%3E%20hls.destroy())%3B%0A%20%20%20%20%7D%20else%20if%20(video.canPlayType(%27application%2Fvnd.apple.mpegurl%27))%20%7B%0A%20%20%20%20%20%20%20%20video.src%20%3D%20url%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20art.notice.show%20%3D%20%27Unsupported%20playback%20format%3A%20m3u8%27%3B%0A%20%20%20%20%7D%0A%7D%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fv8.suonizy-youku.com%2F202401%2F25%2FsVeZ3vmLeW1%2Fvideo%2Findex.m3u8%27%2C%0A%20%20%20%20type%3A%20%27m3u8%27%2C%0A%20%20%20%20customType%3A%20%7B%0A%20%20%20%20%20%20%20%20m3u8%3A%20playM3u8%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20console.info(art.hls)%3B%0A%7D)%3B)

![Snipaste_2024-02-01_16-08-57](https://github.com/zhw2590582/ArtPlayer/assets/5907357/667bb354-a729-4f29-aaa8-44fbad70df9f)

**Comment by Dos7t3r** [comment]
> 可以播放的，但你的地址有一定概率会出现502：[demo](https://artplayer.org/?libs=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fhls.js%2F8.0.0-beta.3%2Fhls.min.js&code=function%20playM3u8(video%2C%20url%2C%20art)%20%7B%0A%20%20%20%20if%20(Hls.isSupported())%20%7B%0A%20%20%20%20%20%20%20%20if%20(art.hls)%20art.hls.destroy()%3B%0A%20%20%20%20%20%20%20%20const%20hls%20%3D%20new%20Hls()%3B%0A%20%20%20%20%20%20%20%20hls.loadSource(url)%3B%0A%20%20%20%20%20%20%20%20hls.attachMedia(video)%3B%0A%20%20%20%20%20%20%20%20art.hls%20%3D%20hls%3B%0A%20%20%20%20%20%20%20%20art.on(%27destroy%27%2C%20()%20%3D%3E%20hls.destroy())%3B%0A%20%20%20%20%7D%20else%20if%20(video.canPlayType(%27application%2Fvnd.apple.mpegurl%27))%20%7B%0A%20%20%20%20%20%20%20%20video.src%20%3D%20url%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20art.notice.show%20%3D%20%27Unsupported%20playback%20format%3A%20m3u8%27%3B%0A%20%20%20%20%7D%0A%7D%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fv8.suonizy-youku.com%2F202401%2F25%2FsVeZ3vmLeW1%2Fvideo%2Findex.m3u8%27%2C%0A%20%20%20%20type%3A%20%27m3u8%27%2C%0A%20%20%20%20customType%3A%20%7B%0A%20%20%20%20%20%20%20%20m3u8%3A%20playM3u8%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20console.info(art.hls)%3B%0A%7D)%3B)
> 
> ![Snipaste_2024-02-01_16-08-57](https://private-user-images.githubusercontent.com/5907357/301430751-667bb354-a729-4f29-aaa8-44fbad70df9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMTc1MzEsIm5iZiI6MTcwNzExNzIzMSwicGF0aCI6Ii81OTA3MzU3LzMwMTQzMDc1MS02NjdiYjM1NC1hNzI5LTRmMjktYWFhOC00NGZiYWQ3MGRmOWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDVUMDcxMzUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmRmZjVjOTViNDAwYTljNjk2NWU2ZmI4ZmQ1ZjU0MWQ1ZjhjYjI1Mjg2MjU0NjNmNTI4YWMyZTAzMTI1NTkxYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gIW0y-WuGE_4aJZ9j0ZhL7ILfi9UjxxdB_6oBRuVPNY)

好的 感谢解答~
