### ISSUE TITLE
Mobile Player

### ISSUE THREAD

**Issue by kulvir97** [zhw2590582/ArtPlayer#68]
Hello,

How can I show ArtPlayer on Mobile rather than the native player?

Thanks

**Comment by zhw2590582** [comment]
You can configure the phone whitelist to enable ArtPlayer：

https://artplayer.org/document/#/?id=whitelist

**Comment by kulvir97** [comment]
Hello,

Thanks for your reply. I'm wondering how I missed this in the documentation.

Thanks again.
