### ISSUE TITLE
关于播放速度数值显示异常的问题

### ISSUE THREAD

**Issue by moonmusicstone** [zhw2590582/ArtPlayer#685]
在ArtPlayer  5.1.0版本中，播放速度显示数值被四舍五入了，点击切换后左上角会显示正确的速率，但在设置菜单中显示异常。

### Environment

-   Browser:Chrome
-   Version:120.0.6099.131
-   Operating System: Windows 11
-   Version:22631.2861

**Comment by cxw620** [comment]
感觉像是 playbackRate.js 那儿改 i18n 改出问题了()

**Comment by zhw2590582** [comment]
不过，实际使用场景下，播放速度真的需要精确到小数点后两位吗

**Comment by moonmusicstone** [comment]
> 实际使用场景下，播放速度真的需要精确到小数据点吗？

emm,至少对我来说更习惯显示完全，以及目前貌似只是倍速显示错误，但实际会调整成设置值，在使用上会有些不好

**Comment by moonmusicstone** [comment]
> 感觉像是 playbackRate.js 那儿改 i18n 改出问题了() 速度不是 1.0 的时候就是 toFix(1) 了导致四舍五入. 你可以自己改 toFix(2), 或者直接保留原来的值?
> 
> https://github.com/zhw2590582/ArtPlayer/blob/434aa3d57dc18053170eaf8c69274d173bdf8e23/packages/artplayer/src/setting/playbackRate.js#L11-L11
> 
> 如果测试下来没问题你可以发 PR 给作者看看

收到，我试试
