### ISSUE TITLE
注册了ended事件，但是当进度条走到最后没有触发

### ISSUE THREAD

**Issue by thshu** [zhw2590582/ArtPlayer#687]
### Expected behaviour
预期为触发事件在控制台输出 视频播放完毕

### Actual behaviour
没有任何事件被触发

### Steps to reproduce
相关代码：
```javascript
art.on('ended', () => {
    console.log("视频播放完毕");
    speed.value++
});
```

### Environment

-   Browser: 谷歌浏览器
-   Version: 120.0.6099.200
-   Operating System: Windows
-   Version: win10

**Comment by zhw2590582** [comment]
原生的video事件需要使用`video:ended`
https://artplayer.org/document/advanced/event.html

```js
art.on('video:ended', () => {
    console.log("视频播放完毕");
});
```
