### ISSUE TITLE
playsinline support?

### ISSUE THREAD

**Issue by mobistor** [zhw2590582/ArtPlayer#69]
when I run artplayer web page in iOS, I found it always plays in fullscreen mode. If its possible to support playsinline mode?

**Comment by zhw2590582** [comment]
This custom attribute can be implemented in the following ways:

```js
var art = new Artplayer({
    moreVideoAttr: {
        'webkit-playsinline': true,
        playsinline: true,
    },
});
```

**Comment by mobistor** [comment]
Thank for your amazing quick response.

I have tried your above method by the npm artplayer 3.5.4 version , and also downloading the latest source to build one, but still FAIL in iPhone 6S and iOS version is 13.3.1.

However, if I directly modifies the <video> tag in the artplayer/src/template.js file by adding playsinline tag, like this <video class="art-video" playsinline></video> in mobile(){} function, it WORKS!!  under iOS, no going to fullscreen. 

I don't know why the moreVideoAttr method does not work for me, but Always thanks your great project and quick response again.

**Comment by zhw2590582** [comment]
Thanks for your feedback, I know why this is caused, and I will fix it in the next version.

**Comment by mobistor** [comment]
Ya! It works. Thank a lot.

**Comment by dantart** [comment]
Yes, it works, but it disable the fullscreen button feature :-(
is there anyway to disable the auto-fullscreen in iPhone but without disabling the fullscreen button feature ?
I mean, not to go fullscreen automatically, but allow user to go fullscreen if he clicks the fullscreen icon

**Comment by zhw2590582** [comment]
@dantart It's a good question and I'll try to solve it for a while

**Comment by dantart** [comment]
Works perfectly! THANK YOU !
