### ISSUE TITLE
支持 dash 等流媒体格式

### ISSUE THREAD

**Issue by BTMuli** [zhw2590582/ArtPlayer#691]
rt，对于 [B站视频返回](https://socialsisteryi.github.io/bilibili-API-collect/docs/video/videostream_url.html#dash%E6%A0%BC%E5%BC%8F) 的 dash 格式的数据，希望提供支持

**Comment by zhw2590582** [comment]
https://artplayer.org/?libs=https://cdnjs.cloudflare.com/ajax/libs/dashjs/4.5.2/dash.all.min.js&example=dash
