### ISSUE TITLE
部分视频播放没有声音

### ISSUE THREAD

**Issue by thshu** [zhw2590582/ArtPlayer#693]
具体规律还没有找到，但是确实有这种问题，原来以为是我代码的问题，但是发现alist内也会有相同的问题，播放视频没有声音
![image](https://github.com/zhw2590582/ArtPlayer/assets/58914330/73f18a78-1b06-4ded-a40b-352bdc666b8e)
使用本地的播放器是有声音的

**Comment by zhw2590582** [comment]
很正常，因为浏览器没有对应格式的音频解码器，你本地播放器一般都是有大部分音频解码器
你直接把视频拖放到浏览器里播放，也是没声音的，和art播放器无关的

**Comment by thshu** [comment]
> 很正常，因为浏览器没有对应格式的音频解码器，你本地播放器一般都是有大部分音频解码器 你直接把视频拖放到浏览器里播放，也是没声音的，和art播放器无关的

感谢回复，我刚找了一下历史的issue，发现应该是因为我的这个视频音频编码为E-AC-3，所以没办法播放
