### ISSUE TITLE
丰富弹幕插件功能

### ISSUE THREAD

**Issue by xiaofengorz** [zhw2590582/ArtPlayer#698]
ArtPlayer的弹幕目前仅区分滚动和静止弹幕。而市面上主流的弹幕视频网站（Bilibili、Niconico、AcFun等）至少有滚动、顶部、底部三种区分。还有更复杂的弹幕形式，如高级弹幕等，构成了“弹幕文化”。能否对支持的弹幕形式进行丰富？

此外，希望用户端可以有简单的弹幕过滤功能。如过滤超长/超短弹幕、正则匹配、过滤指定关键词、过滤特定发送UUID的弹幕等。希望通过这些个性功能，从而丰富用户的使用体验。

另推介一个较完善的弹幕解析库[jabbany/CommentCoreLibrary](https://github.com/jabbany/CommentCoreLibrary)。这个库似乎涵盖了上述的一些功能，但是也已经比较老了。可能可以作为参考。

**Comment by zhw2590582** [comment]
复杂的弹幕功能属于吃力不讨好，这都是很定制化的功能，和业务深度绑定，复杂意味着配置也复杂，数据结构也复杂，后端也复杂，真正能用上的人非常少
