### ISSUE TITLE
hls format doesnt work on IOS 

### ISSUE THREAD

**Issue by magicknight** [zhw2590582/ArtPlayer#7]
### Expected behaviour
在 iphone X 上用 safari 来播放m3u8格式，也引入了hls.js，但并不能播放，桌面端可以。
手机段 console 没有任何出错信息。
如果通过whitelist允许用复杂界面，出现 “vt.on is not a function" 这个错误
### Environment

- Browser:
safari
- Version:
- Operating System:
IOS 
- Version:
12
### Console errors (if any)
vt.on is not a function

**Comment by zhw2590582** [comment]
hls.js 上面有一个兼容性的说明：https://github.com/video-dev/hls.js/#compatibility
同时也说了iOS Safari上虽然不支持hls.js，但能直接支持m3u8作为地址，所以你可能要做下兼容处理

https://artplayer.org/issues/7.html
https://artplayer.org/issues/7.html?whitelist=iPhone

```js
var art = new Artplayer({
    container: '.artplayer-app',
    url: 'https://video-dev.github.io/streams/x36xhzz/x36xhzz.m3u8',
    customType: {
        m3u8: function(video, url) {
            var hls = new Hls();
            hls.loadSource(url);
            hls.attachMedia(video);
            if (!video.src) {
                video.src = url;
            }
        },
    },
});
```

**Comment by magicknight** [comment]
Got it, thanks.
