### ISSUE TITLE
在移动端全屏播放视频时，打开设置菜单中的播放速度上下滑动时会意外调整音量

### ISSUE THREAD

**Issue by fbotp** [zhw2590582/ArtPlayer#701]
### Expected behaviour
在全屏下修改视频倍速时，不会改变音量
### Actual behaviour
滑动倍速列表的同时，音量也随之变化
### Steps to reproduce
https://artplayer.org/mobile.html
全屏播放并滑动播放速度列表时，音量就会随之改变
### Environment

-   Browser: Via
-   Operating System: Android

### Link to where the bug is happening
复现视频（观看时注意调低音量）
https://github.com/zhw2590582/ArtPlayer/assets/46618620/9feaa428-7f5c-40c0-820d-61cabd7ea057

**Comment by fbotp** [comment]
我看了代码感觉是修改`art-settings`对应的滑动事件阻止冒泡，但是具体应该修改哪个文件没有找到，可以说下吗？我可以提一个PR

**Comment by zhw2590582** [comment]
应该是在这里插入，不过我没安卓手机可以测试，你可以试试

https://github.com/zhw2590582/ArtPlayer/blob/83ab3419e0456891a69d3172f69fe3044a3da824/packages/artplayer/src/setting/index.js#L39

```js
art.proxy($setting, 'scroll', event => {
    event.stopPropagation();
})
```

**Comment by fbotp** [comment]
好的谢谢

**Comment by fbotp** [comment]
经测试发现，音量调节功能是via中的“启用视频播放器手势”功能，ArtPlayer并无滑动视频调节音量的功能，关闭via中的设置后正常。感谢您的耐心回复
