### ISSUE TITLE
setting.add方法添加滑块范围时第一个添加的滑块默认值会被重置

### ISSUE THREAD

**Issue by 1229984599** [zhw2590582/ArtPlayer#705]
### Expected behaviour
setting.add方法能够正常使用
### Actual behaviour
![image](https://github.com/zhw2590582/ArtPlayer/assets/34052312/74fc88c8-d055-4312-9edc-08553925eb3e)

### Environment

-   Browser:`edge`
-   Version:`121.0.2277.128`
-   Operating System:`win11`
-   Version:

**Comment by zhw2590582** [comment]
Fixed in artplayer@5.2.1
