### ISSUE TITLE
Multiple audio track supported??

### ISSUE THREAD

**Issue by jdkcoder** [zhw2590582/ArtPlayer#713]
I tried to search on the document & google but cannot find how to config the options for mutiple audio track (with Hls.js)

**Comment by zhw2590582** [comment]
This is a function of hls.js. The player does not support mutiple audio track because it does not have a decoding function, but artplayer.js + hls.js should be able to

**Comment by jdkcoder** [comment]
> This is a function of hls.js. The player does not support mutiple audio track because it does not have a decoding function, but artplayer.js + hls.js should be able to

thanks, how about 10-bit HDR video, I have 10-bit HDR m3u8 file but when I put the link into src, the video couldn't be played, is it also a function of  hls.js?

**Comment by zhw2590582** [comment]
Yes, you can test your m3u8 url:https://hlsjs.video-dev.org/demo/
