### ISSUE TITLE
Pinch to zoom

### ISSUE THREAD

**Issue by Pantyhose-X** [zhw2590582/ArtPlayer#714]
Pinch to zoom, Drag and Drop Video
It's like a win10 Magnifier.

**Comment by zhw2590582** [comment]
I don't quite understand what you mean. Can you describe it in detail?

**Comment by Pantyhose-X** [comment]
> I don't quite understand what you mean. Can you describe it in detail?

Like the video says. https://www.youtube.com/watch?v=-o81n-heK-A

**Comment by zhw2590582** [comment]
This is currently too complex for web players and is not a necessary function, so we do not plan to add this function for the time being.
