### ISSUE TITLE
如何设置播放器在手机全屏时自动旋转屏幕？ 多谢

### ISSUE THREAD

**Issue by kodoku-san** [zhw2590582/ArtPlayer#716]
正如标题所说，谢谢

**Comment by zhw2590582** [comment]
假如是视频全屏的话，播放器没有权限做旋转，假如是播放器全屏的话，可以试试下面这个
https://artplayer.org/document/start/option.html#autoorientation

**Comment by kodoku-san** [comment]
谢谢
