### ISSUE TITLE
How to override default language on setting panel?

### ISSUE THREAD

**Issue by owen800q** [zhw2590582/ArtPlayer#72]
Beside changing source code directly, is a way to override setting name shown in english to another language?

**Comment by owen800q** [comment]
@zhw2590582

**Comment by zhw2590582** [comment]
Yes, it can be done in most cases：[demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20lang%3A%20%27jp%27%2C%0A%7D)%3B%0A%0Aart.i18n.update(%7B%0A%20%20%20%20jp%3A%20%7B%0A%20%20%20%20%20%20%20%20Play%3A%20%27%E6%97%A5%E6%96%87%E6%92%AD%E6%94%BE%27%2C%0A%20%20%20%20%20%20%20%20Pause%3A%20%27%E6%97%A5%E6%96%87%E6%9A%82%E5%81%9C%27%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B)

**Comment by owen800q** [comment]
@zhw2590582  Awesome

> Yes, it can be done in most cases：[demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20lang%3A%20%27jp%27%2C%0A%7D)%3B%0A%0Aart.i18n.update(%7B%0A%20%20%20%20jp%3A%20%7B%0A%20%20%20%20%20%20%20%20Play%3A%20%27%E6%97%A5%E6%96%87%E6%92%AD%E6%94%BE%27%2C%0A%20%20%20%20%20%20%20%20Pause%3A%20%27%E6%97%A5%E6%96%87%E6%9A%82%E5%81%9C%27%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B)

awesome
