### ISSUE TITLE
webm 格式的支持

### ISSUE THREAD

**Issue by change41** [zhw2590582/ArtPlayer#722]
看文档说默认支持 webm 格式，但实际使用中 webm 无法播放，不知道是哪里的问题
请求大佬给个使用说明
https://dt.shuobude.top:5245/d/DefaultDownload/Windows-screen0.webm  测试用的文件

**Comment by zhw2590582** [comment]
似乎preload默认值有点问题，你可以这样做，[demo](http://localhost:8082/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27https%3A%2F%2Fdt.shuobude.top%3A5245%2Fd%2FDefaultDownload%2FWindows-screen0.webm%27%2C%0A%09moreVideoAttr%3A%20%7B%0A%09%09preload%3A%20%27auto%27%0A%09%7D%0A%7D)%3B)

```js
var art = new Artplayer({
	container: '.artplayer-app',
	url: 'https://dt.shuobude.top:5245/d/DefaultDownload/Windows-screen0.webm',
	moreVideoAttr: {
		preload: 'auto'
	}
});
```
