### ISSUE TITLE
Getting ArtPlayerError: The width and height of the container cannot be 0

### ISSUE THREAD

**Issue by l-u-k-a** [zhw2590582/ArtPlayer#73]
### Expected behaviour
Should render the player
### Actual behaviour
Throws error
`The width and height of the container cannot be 0`
### Steps to reproduce
use `<ArtplayerComponent /> in a React component in a condition like:
(even if wrapping into a container with defined fixed width and height)
```
function Wrapper() {
  if (someThin) return <div>other thing</div>
  return (
    <ArtplayerComponent
        option={{
            url: editingAsset.asset.attributes.url,
            theme: '#acadee',
            volume: 0.5,
            muted: false,
            autoplay: false,
            setting: true,
        }}
    />
  )
}
```
### Environment
Mac OS Catalina 10.15.5
-   Browser: Google Chrome
-   Version: 83
-   Operating System: Mac OS
-   Version: Catalina 10.15.5

### Package versions
* "react": "^16.13.1",
* "react-dom": "^16.13.1",

### Console errors (if any)
`artplayer-react.js:8 Uncaught ArtPlayerError: The width and height of the container cannot be 0`

**Comment by zhw2590582** [comment]
You should specify a fixed size for ArtplayerComponent, for example:
[demo](https://codesandbox.io/s/n74859y9rl)

Or you can use a percentage: `width:100%; height:100%`, and then give the parent element of ArtplayerComponent a fixed size

**Comment by l-u-k-a** [comment]
aha, I see, ok thanks
