### ISSUE TITLE
Auto full-screen on video start

### ISSUE THREAD

**Issue by jedgarf** [zhw2590582/ArtPlayer#730]
how to auto full-screen when the video is ready

**Comment by zhw2590582** [comment]
Due to the browser security mechanism, there must be interaction on the page (for example, the user has clicked on the page) before triggering the window to go full screen.

```js
var art = new Artplayer({
    container: '.artplayer-app',
    url: '/assets/sample/video.mp4',
});

art.on('ready', () => {
	art.fullscreen = true;
	// art.fullscreenWeb = true;
})
```

**Comment by jedgarf** [comment]
thank you
