### ISSUE TITLE
Documentation or usage examples with hls for next.js or react

### ISSUE THREAD

**Issue by timomedia** [zhw2590582/ArtPlayer#732]
Hello
I'm using your library for next.js and react, but when I read your documentation, I'm not sure how to use it. I tried using your library with the hls playback and HLS Quality options but it didn't work the way I wanted. Can you further update your library usage with react and next.js?
Thank you very much!

**Comment by zhw2590582** [comment]
Like this?

https://github.com/zhw2590582/ArtPlayer/tree/master/packages/artplayer-template

**Comment by timomedia** [comment]
> Like this?
> 
> https://github.com/zhw2590582/ArtPlayer/tree/master/packages/artplayer-template

Thank you, but I use it with typescript and next.js 14. I have customized my code and it works with your library.
Thanks for your library!
