### ISSUE TITLE
Autoplay as a choice option

### ISSUE THREAD

**Issue by Tescan-group** [zhw2590582/ArtPlayer#735]
Hey there, I have two queries if you could help me out;

1- could you help me to find a way to make a checkbox to let the user decide if autoplay true or false? I plan to implement it as local storage to remember on my site.

2- Also, I have been using the plugin you did here which is great. However, how could I implement end time as art.duration? So the start time for example is 50s but end time is until the video ends.
Here is the plugin I mentioned;
https://github.com/zhw2590582/ArtPlayer/issues/394

**Comment by zhw2590582** [comment]
Like this?

[autoplay](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09muted%3A%20true%2C%0A%09controls%3A%20%5B%0A%09%09%7B%0A%09%09%09name%3A%20%27autoplay%27%2C%0A%09%09%09position%3A%20%27right%27%2C%0A%09%09%09html%3A%20%60ON%60%2C%0A%09%09%09click(_%2C%20%7B%20target%20%7D)%20%7B%0A%09%09%09%09const%20checked%20%3D%20localStorage.getItem(%27autoplay%27)%20%3D%3D%3D%20%27true%27%3B%0A%09%09%09%09target.textContent%20%3D%20checked%20%3F%20%27OFF%27%20%3A%20%27ON%27%3B%0A%09%09%09%09localStorage.setItem(%27autoplay%27%2C%20!checked)%3B%0A%09%09%09%7D%2C%0A%09%09%09mounted(target)%20%7B%0A%09%09%09%09const%20checked%20%3D%20localStorage.getItem(%27autoplay%27)%20%3D%3D%3D%20%27true%27%3B%0A%09%09%09%09target.textContent%20%3D%20checked%20%3F%20%27ON%27%20%3A%20%27OFF%27%3B%0A%09%09%09%09this.video.autoplay%20%3D%20checked%3B%0A%09%09%09%7D%2C%0A%09%09%7D%0A%09%5D%0A%7D)%3B)

[artplayerPluginHighlight](https://artplayer.org/?libs=&code=function%20artplayerPluginHighlight(option)%20%7B%0A%09return%20(art)%20%3D%3E%20%7B%0A%09%09const%20%24highlight%20%3D%20art.query(%27.art-progress-highlight%27)%3B%0A%09%09const%20%7B%20append%2C%20createElement%2C%20setStyles%20%7D%20%3D%20art.constructor.utils%3B%0A%09%09art.on(%27video%3Aloadedmetadata%27%2C%20()%20%3D%3E%20%7B%0A%09%09%09for%20(let%20index%20%3D%200%3B%20index%20%3C%20option.length%3B%20index%2B%2B)%20%7B%0A%09%09%09%09const%20item%20%3D%20option%5Bindex%5D%3B%0A%09%09%09%09const%20left%20%3D%20item.start%20%2F%20art.duration%20*%20100%3B%0A%09%09%09%09const%20width%20%3D%20(item.end%20-%20item.start)%20%2F%20art.duration%20*%20100%3B%0A%09%09%09%09const%20%24item%20%3D%20createElement(%27div%27)%3B%0A%09%09%09%09%24item.dataset.text%20%3D%20item.text%3B%0A%09%09%09%09setStyles(%24item%2C%20%7B%0A%09%09%09%09%09position%3A%20%27absolute%27%2C%0A%09%09%09%09%09left%3A%20left%20%2B%20%27%25%27%2C%0A%09%09%09%09%09width%3A%20width%20%2B%20%27%25%27%2C%0A%09%09%09%09%09height%3A%20%27100%25%27%2C%0A%09%09%09%09%09background%3A%20%27%2300ff96%27%2C%0A%09%09%09%09%7D)%3B%0A%09%09%09%09append(%24highlight%2C%20%24item)%3B%0A%09%09%09%7D%0A%09%09%7D)%0A%09%7D%0A%7D%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09plugins%3A%20%5B%0A%09%09artplayerPluginHighlight(%5B%0A%09%09%09%7B%0A%09%09%09%09start%3A%2010%2C%0A%09%09%09%09end%3A%2020%2C%0A%09%09%09%09text%3A%20%27some%20text%2001%27%2C%0A%09%09%09%7D%2C%0A%09%09%09%7B%0A%09%09%09%09start%3A%2030%2C%0A%09%09%09%09end%3A%2050%2C%0A%09%09%09%09text%3A%20%27some%20text%2002%27%2C%0A%09%09%09%7D%2C%0A%09%09%5D)%0A%09%5D%0A%7D)%3B)

**Comment by Tescan-group** [comment]
Thanks, for autoplay is it possible to do it inside settings as a toggle? I played around a bit but couldn't make it work.

Basically what I am trying to do is like the PiP button on this demo;
[PiP Button Demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09muted%3A%20true%2C%0A%09setting%3A%20true%2C%0A%09settings%3A%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%27PIP%20Mode%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20tooltip%3A%20%27Close%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20icon%3A%20%27%3Cimg%20width%3D%2222%22%20heigth%3D%2222%22%20src%3D%22https%3A%2F%2Fartplayer.org%2Fassets%2Fimg%2Fstate.svg%22%3E%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20switch%3A%20false%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20onSwitch%3A%20function%20(item%2C%20%24dom%2C%20event)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20console.info(item%2C%20%24dom%2C%20event)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20const%20nextState%20%3D%20!item.switch%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20art.pip%20%3D%20nextState%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20item.tooltip%20%3D%20nextState%20%3F%20%27Open%27%20%3A%20%27Close%27%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20nextState%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%5D%2C%0A%7D)%3B)

But I would like to add the autoplay option you made and one more option to toggle "Auto Next" so if toggled and the player reaches a specific time, it will do a `window.location.href = nextUrl;`

**Comment by Tescan-group** [comment]
Have managed to get through by going through your samples, thank you. Will close the issue.
