### ISSUE TITLE
在全屏（或页面全屏）和非全屏状态切换时setting组件漂移问题

### ISSUE THREAD

**Issue by fbotp** [zhw2590582/ArtPlayer#737]
### Expected behaviour
setting组件正常显示
### Actual behaviour
https://github.com/zhw2590582/ArtPlayer/assets/46618620/2494f67f-8438-4064-a855-62553170885c

### Steps to reproduce
- 从非全屏到全屏：
在[https://artplayer.org/](https://artplayer.org/)中，点击setting按钮两次，使其显示后再关闭，随后点击页面全屏或全屏按钮，再次单击setting按钮，setting从左方漂移到了正确位置
- 从全屏到非全屏：
操作类似，先在全屏状态点击两次setting按钮，再退回非全屏状态，点击setting按钮，setting从右方漂移到了正确位置
### Environment

-   Browser: Chrome
-   Version: 123.0.6312.106
-   Operating System: Windows Pro
-   Version: 22H2(19045.4239)

### Link to where the bug is happening
[https://artplayer.org/](https://artplayer.org/)

**Comment by zhw2590582** [comment]
因为设置按钮的位置是不确定的，设置面板和设置按钮也是不关联的，所以点击设置按钮的时候会计算一次它的位置，再设置面板的位置，在加上动画的延迟就会感觉面板偏移了，确实效果不太好，有待优化

**Comment by zhw2590582** [comment]
Fixed in artplayer@5.2.1

**Comment by fbotp** [comment]
🥳🥳🥳
