### ISSUE TITLE
Safari can't fire playing event after seeked

### ISSUE THREAD

**Issue by amowu** [zhw2590582/ArtPlayer#74]
### Expected behaviour

如下图，当 Chrome 视频处于播放状态，`seeked` 事件之后，**可以**触发 `playing` 事件：

![2020-06-16 16 52 09](https://user-images.githubusercontent.com/559351/84753736-f58f2680-aff1-11ea-89fc-89e98cb323d9.gif)

### Actual behaviour

如下图，当 Safari 视频处于播放状态，`seeked` 事件之后，**无法**触发 `playing` 事件：

![2020-06-16 16 51 38](https://user-images.githubusercontent.com/559351/84753706-ec05be80-aff1-11ea-960f-bca89711ae77.gif)

### Steps to reproduce

1. 打开 Safari 前往 https://artplayer.org
2. 播放视频
3. 拖曳时间轴
4. 确认 Console 的 `video: seeked` 事件之后，应该出现 `video: playing` 事件

### Environment

-   Browser: Safari
-   Version: 13.1
-   Operating System: macOS
-   Version: 10.15.4

### Link to where the bug is happening

https://artplayer.org

如下图，原先以为是 Safari 对视频事件的实作有问题，但是试了一下，原先的 Safari video 在 `seeked` 之后，**可以**触发 `playing` 事件：

![2020-06-16 16 50 50](https://user-images.githubusercontent.com/559351/84754369-e197f480-aff2-11ea-8100-c562762446d8.gif)

**Comment by zhw2590582** [comment]
这个差异得要研究一番，不过目前应该也没对播放器的逻辑造成什么影响。
