### ISSUE TITLE
Video auto pause when clicking another tab chrome

### ISSUE THREAD

**Issue by son-bh** [zhw2590582/ArtPlayer#742]
### Expected behaviour
I stream straight from a `.flv` link using `Artplayer`. However, the player is instantly stopped by the player when I click to another Chrome tab. Even if I switch to a different tab, I still want the player to play.

### My config:
```
function playFlv(video, url, art) {
  if (FlvJs.isSupported()) {
    if (art.flv) art.flv.destroy()
    const flv = FlvJs.createPlayer({ type: 'flv', url })
    flv.attachMediaElement(video)
    flv.load()
    art.flv = flv
    art.on('destroy', () => flv.destroy())
  } else {
    art.notice.show = 'Unsupported playback format: flv'
  }
}

 const art = new Artplayer({
      ...option,
      autoplay:true,
      muted: true,
      playbackRate: true,
      aspectRatio: true,
      fullscreen: true,
      fullscreenWeb: true,
      playsInline: true,
      setting: true,
      container: artRef.current,
      customType: {
          flv: playFlv 
      },
    })
```

**Comment by zhw2590582** [comment]
https://artplayer.org/?libs=https://cdnjs.cloudflare.com/ajax/libs/flv.js/1.6.2/flv.min.js&example=flv

My test here did not reproduce the situation you mentioned.

**Comment by son-bh** [comment]
I use link `.flv` from https request. 
Link example: https://pull06.scstream.net/live/stream-9911957_lhd.flv

**Comment by zhw2590582** [comment]
I can't access your flv link, can you give me the demo address?

**Comment by son-bh** [comment]
You can try https://pull06.scstream.net/live/stream-9912052_lhd.flv?auth_key=1713930551-0-0-edc0fb05169987e38434fe67bd8386c1. The link will expire after 90 minutes and you can't use it.

**Comment by zhw2590582** [comment]
I tested it here and there is no problem: [demo](https://artplayer.org/?libs=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fflv.js%2F1.6.2%2Fflv.min.js&code=function%20playFlv(video%2C%20url%2C%20art)%20%7B%0A%20%20%20%20if%20(flvjs.isSupported())%20%7B%0A%20%20%20%20%20%20%20%20if%20(art.flv)%20art.flv.destroy()%3B%0A%20%20%20%20%20%20%20%20const%20flv%20%3D%20flvjs.createPlayer(%7B%20type%3A%20%27flv%27%2C%20url%20%7D)%3B%0A%20%20%20%20%20%20%20%20flv.attachMediaElement(video)%3B%0A%20%20%20%20%20%20%20%20flv.load()%3B%0A%20%20%20%20%20%20%20%20art.flv%20%3D%20flv%3B%20%0A%20%20%20%20%20%20%20%20art.on(%27destroy%27%2C%20()%20%3D%3E%20flv.destroy())%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20art.notice.show%20%3D%20%27Unsupported%20playback%20format%3A%20flv%27%3B%0A%20%20%20%20%7D%0A%7D%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fpull06.scstream.net%2Flive%2Fstream-9912052_lhd.flv%3Fauth_key%3D1713930551-0-0-edc0fb05169987e38434fe67bd8386c1%27%2C%0A%20%20%20%20type%3A%20%27flv%27%2C%0A%09isLive%3A%20true%2C%0A%20%20%20%20customType%3A%20%7B%0A%20%20%20%20%20%20%20%20flv%3A%20playFlv%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20console.info(art.flv)%3B%0A%7D)%3B)

**Comment by son-bh** [comment]
Can you try config `autoplay: true, muted: true,`?

**Comment by zhw2590582** [comment]
This is a problem with flv.js, you can refer to this solution: https://github.com/bilibili/flv.js/issues/259#issuecomment-555852246

**Comment by son-bh** [comment]
Oh. Let me check. I will close issue. Thank for you help.
