### ISSUE TITLE
display poster image at the end of the video

### ISSUE THREAD

**Issue by jedgarf** [zhw2590582/ArtPlayer#747]
how to display poster image at the end of the video

I tried this but not working:

art.on('video:ended', () => {
   art.poster = 'https://artworks.thetvdb.com/banners/v4/series/81797/backgrounds/65a14ba386293.jpg';
});

**Comment by zhw2590582** [comment]
```js
var art = new Artplayer({
	container: '.artplayer-app',
	url: '/assets/sample/video.mp4',
	poster: '/assets/sample/poster.jpg',
});

art.on('video:ended', () => {
	art.template.$poster.style.display = '';
});
```
