### ISSUE TITLE
Screenshot button not working in react version

### ISSUE THREAD

**Issue by abdellani** [zhw2590582/ArtPlayer#75]
### Expected behaviour
A window shows up to select where the file should be saved. 
### Actual behaviour
Nothing happens on the demo page.
On a personal project, I can the following message in the top :
![screenshot_3](https://user-images.githubusercontent.com/16113997/85005762-220d8480-b151-11ea-8ca9-37f4e716cfc3.png)
### Steps to reproduce
Open demo page using chrome: https://codesandbox.io/s/n74859y9rl?file=/src/index.js
Click on the screenshot button.

This button works under firefox.
### Environment

-   Browser: Google Chrome 
-   Version: Version 83.0.4103.61 (Official Build) (64-bit)
-   Operating System: Ubuntu 
-   Version: 18.04

**Comment by zhw2590582** [comment]
It seems that this is chrome's private strategy and cannot download files under iframe
