### ISSUE TITLE
restart事件不会被触发

### ISSUE THREAD

**Issue by zijiren233** [zhw2590582/ArtPlayer#751]
```js
var art = new Artplayer({
    container: '.artplayer-app',
    url: '/assets/sample/video.mp4',
});

art.on('ready', () => {
    art.url = '/assets/sample/video.mp4'
	console.log("ready")
});

art.on('restart', (url) => {
    console.info('restart', url);
});
```

在[在线编辑器](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20art.url%20%3D%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%0A%09console.log(%22ready%22)%0A%7D)%3B%0A%0Aart.on(%27restart%27%2C%20(url)%20%3D%3E%20%7B%0A%20%20%20%20console.info(%27restart%27%2C%20url)%3B%0A%7D)%3B)中发现只会打印ready，而没有restart

**Comment by zhw2590582** [comment]
文档写漏了，触发restart的还有一个前提是，前后两个url是不一样的：[demo](http://localhost:8082/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%09console.log(%27ready%27)%0A%20%20%20%20art.url%20%3D%20%27%2Fassets%2Fsample%2Fvideo.mp4%3Ft%3D1%27%0A%7D)%3B%0A%0Aart.on(%27restart%27%2C%20(url)%20%3D%3E%20%7B%0A%20%20%20%20console.info(%27restart%27%2C%20url)%3B%0A%7D)%3B)
