### ISSUE TITLE
How to add subtitle setting dynamically?

### ISSUE THREAD

**Issue by Tescan-group** [zhw2590582/ArtPlayer#752]
Hey there, could you help me out on how to add a subtitle menu like you have in the player at artplayer.org settings dynamically?

I want to add it in this JS code without having to create a new player if possible;

```
document.getElementById("ChangeServerButton").addEventListener("click", function() {
                art.switchUrl('<?php echo $videoUrl; ?>');
                art.quality = [];
                <?php if(isset($subtitles['English'])) : ?>
                    art.subtitle.url = '<?php echo $subtitles['English']; ?>';
                    art.subtitle.style({
                        color: '#fe9200',
                        fontSize: '25px',
                    });
                <?php endif; ?>
                
            	
            });
```

I basically want to add the subtitle option on the screenshot below without re-building the player;
<img width="261" alt="image" src="https://github.com/zhw2590582/ArtPlayer/assets/73188081/c80b9d2d-4196-4085-bf97-903f6cf5a6a4">

**Comment by zhw2590582** [comment]
You can update settings:

https://artplayer.org/document/en/component/setting.html#updates
