### ISSUE TITLE
add a cast functionality on player

### ISSUE THREAD

**Issue by ScripterSaurav** [zhw2590582/ArtPlayer#754]
Make to display a cast icon on player. So user can cast that video from player on a big screen.

**Comment by zhw2590582** [comment]
https://github.com/zhw2590582/ArtPlayer/tree/master/packages/artplayer-plugin-chromecast

You can try this: [demo](https://artplayer.org/?libs=./uncompiled/artplayer-plugin-chromecast/index.js&example=chromecast)
