### ISSUE TITLE
字幕条裁剪

### ISSUE THREAD

**Issue by LGTMXD** [zhw2590582/ArtPlayer#76]
语音识别后的字幕一行字数太多，需要能功能是：可以在轨道上把字幕条裁开一分为二。

**Comment by zhw2590582** [comment]
裁开的意思是把单个时间块过长的字幕，拆分成多个时间块？那不是字幕本身的问题吗？

**Comment by LGTMXD** [comment]
对，在字幕文本框里按回车键可以把字幕块一拆为二，然后时间线上手动调准位置，YouTube后台字幕编辑器有这个功能.


字幕用autosub讯飞api自动生成的，裁剪不太智能，有时候字幕一行字数太多.

**Comment by zhw2590582** [comment]
那只能在字幕文件处理，播放器是不对字幕文件做额外切割的。
