### ISSUE TITLE
弹幕可以无缝刷新吗

### ISSUE THREAD

**Issue by wuhen8** [zhw2590582/ArtPlayer#764]
现在更换弹幕只能重载，会把弹幕全部清除重新加载，可以不清除续上吗，想实现腾讯那种弹幕效果，一页一页加载

**Comment by zhw2590582** [comment]
不太明白，不清空原来旧的弹幕，然后加上新的弹幕？那么原来旧的还没发送的弹幕不就和新弹幕混在一起了吗

**Comment by wuhen8** [comment]
就是弹幕有很多页，一页一页加载，art.plugins.artplayerPluginDanmuku.emit()这个可以加载弹幕 XML吗，我用这个
{
            position: 'right',
            html: '切换弹幕',
            click: function () {
                art.plugins.artplayerPluginDanmuku.config({
                    danmuku: '/assets/sample/danmuku-v2.xml',
                });
                art.plugins.artplayerPluginDanmuku.load();
            },
        },
弹幕会中断，不想让他中断，想这一页弹幕加载完了，下一页续上，不要清空更自然一点

**Comment by zhw2590582** [comment]
目前还没有动态加载xml的功能，下个版本加上

**Comment by zhw2590582** [comment]
可以更新到artplayer-plugin-danmuku@5.1.2
https://artplayer.org/document/plugin/danmuku.html#load
