### ISSUE TITLE
Play at a special time in loop pattern

### ISSUE THREAD

**Issue by tomtomtomtony** [zhw2590582/ArtPlayer#766]
is it possible to Play a video at a special time in loop pattern? the play() function can pass three params {starttime,endtime,loopCount}

**Comment by zhw2590582** [comment]
Yes, I wrote an artplayerPluginLoop to see if it works for you：[demo](https://artplayer.org/?libs=&code=function%20artplayerPluginLoop(option)%20%7B%0A%09return%20(art)%20%3D%3E%20%7B%0A%09%09let%20enable%20%3D%20false%3B%0A%09%09let%20count%20%3D%200%3B%0A%09%09let%20startTime%20%3D%200%3B%0A%09%09let%20endTime%20%3D%200%3B%0A%09%09let%20loopCount%20%3D%200%3B%0A%0A%09%09function%20play(option)%20%7B%0A%09%09%09enable%20%3D%20true%3B%0A%09%09%09count%20%3D%200%3B%0A%09%09%09startTime%20%3D%20option.startTime%3B%0A%09%09%09endTime%20%3D%20option.endTime%3B%0A%09%09%09loopCount%20%3D%20option.loopCount%3B%0A%0A%09%09%09art.once(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%09%09%09%09art.currentTime%20%3D%20startTime%3B%0A%09%09%09%7D)%3B%0A%09%09%7D%0A%0A%09%09art.on(%27video%3Atimeupdate%27%2C%20()%20%3D%3E%20%7B%0A%09%09%09if%20(!enable)%20return%3B%0A%0A%09%09%09if%20(count%20%3E%3D%20loopCount)%20%7B%0A%09%09%09%09enable%20%3D%20false%3B%0A%09%09%09%09art.notice.show%20%3D%20%27Loop%20end%27%3B%0A%09%09%09%09return%3B%0A%09%09%09%7D%0A%0A%09%09%09if%20(art.currentTime%20%3C%20startTime)%20%7B%0A%09%09%09%09art.currentTime%20%3D%20startTime%3B%0A%09%09%09%7D%0A%0A%09%09%09if%20(art.currentTime%20%3E%20endTime)%20%7B%0A%09%09%09%09art.currentTime%20%3D%20startTime%3B%0A%09%09%09%09count%20%2B%3D%201%3B%0A%09%09%09%09art.notice.show%20%3D%20%27Loop%3A%20%27%20%2B%20count%3B%0A%09%09%09%7D%0A%09%09%7D)%3B%0A%0A%09%09if%20(option)%20play(option)%0A%09%09return%20%7B%0A%09%09%09name%3A%20%27loop%27%2C%0A%09%09%09play%3A%20play%2C%0A%09%09%09set%20enable(state)%20%7B%0A%09%09%09%09enable%20%3D%20state%3B%0A%09%09%09%7D%2C%0A%09%09%09get%20enable()%20%7B%0A%09%09%09%09return%20enable%3B%0A%09%09%09%7D%0A%09%09%7D%0A%09%7D%0A%7D%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09plugins%3A%20%5BartplayerPluginLoop()%5D%0A%7D)%3B%0A%0Aart.plugins.loop.play(%7B%0A%09startTime%3A%2010%2C%0A%09endTime%3A%2020%2C%0A%09loopCount%3A%203%2C%0A%7D))
