### ISSUE TITLE
缩略图插件不支持移动浏览器

### ISSUE THREAD

**Issue by vaseala** [zhw2590582/ArtPlayer#767]
### Expected behaviour
希望缩略图插件（https://github.com/zhw2590582/ArtPlayer/blob/master/packages/artplayer-plugin-vtt-thumbnail/src/index.js）能支持移动浏览器
我能排查到是因为移动浏览器上不能用mousemove事件，改成 touchmove 事件之后，貌似获取不到拖动的进度。
希望官方能兼容移动浏览器

**Comment by zhw2590582** [comment]
已修复，更新到 `artplayer-plugin-vtt-thumbnail@1.0.1`
