### ISSUE TITLE
How do I make the video automatically switch to full-screen mode when I rotate the screen on a mobile device?

### ISSUE THREAD

**Issue by timomedia** [zhw2590582/ArtPlayer#769]
Hello!
I have searched through your documentation; however, everything doesn't quite work as I want it to. What I need is that when users access a page with a video on their phone, if they rotate the screen, the video will automatically go full screen. I noticed in your documentation that due to the browser's security mechanism, it requires interaction with the browser to intervene in fullscreen mode. However, even when I swipe the screen (without clicking), the video doesn't go fullscreen. If I understand correctly, swiping or rotating the screen should inherently be an interaction with the browser. Because it either changes the browser's size or interacts with the browser's scroll bar. Please guide me on how to achieve this. 
Thank you very much!

**Comment by zhw2590582** [comment]
Do you want the video to go into full screen and rotate when you rotate the screen? like: 
![1](https://github.com/zhw2590582/ArtPlayer/assets/5907357/eba95135-7a62-483c-b1f7-b67f30fb1aff)

**Comment by timomedia** [comment]
> Do you want the video to go into full screen and rotate when you rotate the screen? like: ![1](https://private-user-images.githubusercontent.com/5907357/337864423-eba95135-7a62-483c-b1f7-b67f30fb1aff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NjYwNzcsIm5iZiI6MTcxNzg2NTc3NywicGF0aCI6Ii81OTA3MzU3LzMzNzg2NDQyMy1lYmE5NTEzNS03YTYyLTQ4M2MtYjFmNy1iNjdmMzBmYjFhZmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDhUMTY1NjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTgxZTMxMjc2NmMxZDZkZDcwYWM5OWM3NWQ5ODE1MDU0M2IyNmM5YWEzMmIzYTJmMjA0N2Q2NDRhODVhM2VkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8wwJICP7Xlzbt73TStD_YdFs4SNyDSIhv9XZ9h5fvoI)

Yes! Like youtube or vimeo. Pls help me! Thank you

**Comment by zhw2590582** [comment]
Like this? [demo](https://artplayer.org/mobile.html?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09autoOrientation%3A%20true%2C%0A%09fullscreenWeb%3A%20true%2C%0A%09fullscreen%3A%20true%2C%0A%7D)%3B%0A%0Aart.on(%27resize%27%2C%20async%20()%20%3D%3E%20%7B%0A%09if%20(!Artplayer.utils.isMobile)%20return%3B%0A%09if%20(art.state%20!%3D%3D%20%27standard%27)%20return%3B%0A%09if%20(window.innerWidth%20%3E%20window.innerHeight)%20%7B%0A%09%09art.fullscreenWeb%20%3D%20true%3B%0A%09%7D%0A%7D))

**Comment by zhw2590582** [comment]
Like this? [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09autoOrientation%3A%20true%2C%0A%09fullscreenWeb%3A%20true%2C%0A%09fullscreen%3A%20true%2C%0A%7D)%3B%0A%0Aasync%20function%20checkOrientation()%20%7B%0A%09if%20(!Artplayer.utils.isMobile)%20return%3B%0A%09if%20(window.innerWidth%20%3E%20window.innerHeight)%20%7B%0A%09%09art.fullscreenWeb%20%3D%20false%3B%0A%09%09await%20Artplayer.utils.sleep(1000)%3B%0A%09%09art.fullscreenWeb%20%3D%20true%3B%0A%09%7D%20else%20%7B%0A%09%09%2F%2F%0A%09%7D%0A%7D%0A%0AcheckOrientation()%3B%0Awindow.addEventListener(%27resize%27%2C%20checkOrientation)%3B)

**Comment by zhw2590582** [comment]
Cannot use fullscreen directly

**Comment by timomedia** [comment]
Thank you very much!
