### ISSUE TITLE
seeking is not working under Safari browser.

### ISSUE THREAD

**Issue by abdellani** [zhw2590582/ArtPlayer#77]
### Expected behaviour
Once the user clicks on the play button, I programmatically move the cursor to make the video playing from a predefined time.
### Actual behaviour
Under Safari, the code part responsible for moving the cursor doesn't work.
The same code works under Firefox and Chrome.
### Steps to reproduce
I'm actually using the following code
```javascript
        <ArtplayerComponent
          key={url}
          option={option}
          style={{
            width: `${width}px`,
            height: `${height}px`,
          }}
          getInstance={instance => {
            if (!!t)
              instance.seek = t
            instance.on('pause', () => onSeekOrPause(instance.currentTime))
            instance.on('seek', () => onSeekOrPause(instance.currentTime))
            instance.on('ready', () => onReady(instance))
          }}
        />
```
The following part is responsible for moving the cursor. `t` is the time from which the video should start.
`
            if (!!t)
              instance.seek = t
`
### Environment

-   Browser: Safari
-   Operating System: Mac Os

### Console errors (if any)
N/A
### Link to where the bug is happening
N/A

**Comment by zhw2590582** [comment]
I have tested on my side that Safari on mac is working properly. Maybe your instance is not ready so you cannot see the effect of seek immediately, or you can do this:

```jsx
<ArtplayerComponent
  key={url}
  option={option}
  style={{
    width: `${width}px`,
    height: `${height}px`,
  }}
  getInstance={(instance) => {
    instance.on("pause", () => onSeekOrPause(instance.currentTime));

    instance.on("seek", () => onSeekOrPause(instance.currentTime));
    // or
    instance.on("video:seeking", () => onSeekOrPause(instance.currentTime));

    instance.on("ready", () => {
      if (!!t) instance.seek = t;
    });
  }}
/>;

```

**Comment by abdellani** [comment]
Hi
Thank you very much for your reply.
I'll try that change and I'll share the results soon.

**Comment by abdellani** [comment]
It works perfectly now.
Thank you again.
