### ISSUE TITLE
从5.1.2版本后手机浏览器全屏不会横屏

### ISSUE THREAD

**Issue by kkl2** [zhw2590582/ArtPlayer#770]
### Environment

-   Browser:kiwi Browser和edge Browser 手机版
-   Version:最新版
-   Operating System:安卓
-   Version:13

### Link to where the bug is happening

alist使用的是5.0.9版本可以横屏，地址https://al.nn.ci/desktop.mp4

**Comment by zhw2590582** [comment]
已修复，更新到 `artplayer@5.1.6`
