### ISSUE TITLE
如果有20个字幕，多重字幕如何随意多选

### ISSUE THREAD

**Issue by qwer130140190** [zhw2590582/ArtPlayer#771]
我看文档demo里只有2个字幕，double是写死的，如何实现随意多选2个

**Comment by zhw2590582** [comment]
例如这样：[demo](https://artplayer.org/?libs=.%2Funcompiled%2Fartplayer-plugin-multiple-subtitles%2Findex.js&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20async%20()%20%3D%3E%20%7B%0A%09%2F%2F%20%E5%AE%9A%E4%B9%89%E6%89%80%E6%9C%89%E5%AD%97%E5%B9%95%0A%09const%20subtitles%20%3D%20%5B%0A%09%09%7B%0A%09%09%09name%3A%20%27chinese%27%2C%0A%09%09%09url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.cn.srt%27%2C%0A%09%09%7D%2C%0A%09%09%7B%0A%09%09%09name%3A%20%27japanese%27%2C%0A%09%09%09url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.jp.srt%27%2C%0A%09%09%7D%2C%0A%09%09%7B%0A%09%09%09name%3A%20%27english%27%2C%0A%09%09%09url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.jp.srt%27%2C%0A%09%09%7D%2C%0A%09%09%7B%0A%09%09%09name%3A%20%27german%27%2C%0A%09%09%09url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.jp.srt%27%2C%0A%09%09%7D%0A%09%5D%3B%0A%0A%09const%20plugin%20%3D%20artplayerPluginMultipleSubtitles(%7B%20subtitles%20%7D)%3B%0A%09await%20art.plugins.add(plugin)%3B%0A%0A%09%2F%2F%20%E5%88%87%E6%8D%A2%E4%BB%BB%E6%84%8F%E4%B8%A4%E4%B8%AA%E5%AD%97%E5%B9%95%0A%09art.plugins.multipleSubtitles.tracks(%5B%27chinese%27%2C%20%27japanese%27%5D)%3B%0A%7D))

**Comment by qwer130140190** [comment]
> 例如这样：[demo](https://artplayer.org/?libs=.%2Funcompiled%2Fartplayer-plugin-multiple-subtitles%2Findex.js&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20async%20()%20%3D%3E%20%7B%0A%09%2F%2F%20%E5%AE%9A%E4%B9%89%E6%89%80%E6%9C%89%E5%AD%97%E5%B9%95%0A%09const%20subtitles%20%3D%20%5B%0A%09%09%7B%0A%09%09%09name%3A%20%27chinese%27%2C%0A%09%09%09url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.cn.srt%27%2C%0A%09%09%7D%2C%0A%09%09%7B%0A%09%09%09name%3A%20%27japanese%27%2C%0A%09%09%09url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.jp.srt%27%2C%0A%09%09%7D%2C%0A%09%09%7B%0A%09%09%09name%3A%20%27english%27%2C%0A%09%09%09url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.jp.srt%27%2C%0A%09%09%7D%2C%0A%09%09%7B%0A%09%09%09name%3A%20%27german%27%2C%0A%09%09%09url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.jp.srt%27%2C%0A%09%09%7D%0A%09%5D%3B%0A%0A%09const%20plugin%20%3D%20artplayerPluginMultipleSubtitles(%7B%20subtitles%20%7D)%3B%0A%09await%20art.plugins.add(plugin)%3B%0A%0A%09%2F%2F%20%E5%88%87%E6%8D%A2%E4%BB%BB%E6%84%8F%E4%B8%A4%E4%B8%AA%E5%AD%97%E5%B9%95%0A%09art.plugins.multipleSubtitles.tracks(%5B%27chinese%27%2C%20%27japanese%27%5D)%3B%0A%7D))

界面上应该如何支持呢，支持多选

**Comment by zhw2590582** [comment]
播放器不支持你这种20选2的自定义UI，你可以把这个功能在播放器外面
