### ISSUE TITLE
动态修改thumbnails无效

### ISSUE THREAD

**Issue by qwer130140190** [zhw2590582/ArtPlayer#772]
art = new Artplayer(options);
art.thumbnails.column = 10;
art.thumbnails.number = 123;
art.thumbnails.url = 'aaa.webp';
修改了没有显示，如果放到options初始化是显示的

**Comment by zhw2590582** [comment]
目前不支持动态修改thumbnails

**Comment by qwer130140190** [comment]
> 目前不支持动态修改thumbnails

目前想要实现的是，先初始化一个播放器loading占位，然后去后端获取视频的各种信息，这个期间不会白屏，然后再动态的修改覆盖各个配置，subtitle，quality，url等都没问题，如果thumbnails目前不支持，是否有办法能让整个播放器重新刷新一下options

**Comment by zhw2590582** [comment]
那不如直接销毁占位的播放器，重新new一个新播放器就行

**Comment by qwer130140190** [comment]
> 那不如直接销毁占位的播放器，重新new一个新播放器就行

这个思路没毛病，这样重新渲染，页面上可能会删一下，loading的动画也会中断不连续

**Comment by zhw2590582** [comment]
是的，不过目前这是最好的办法

**Comment by qwer130140190** [comment]
> 是的，不过目前这是最好的办法

好的，希望后续能支持动态修改
