### ISSUE TITLE
为什么我的字幕偏移是0-10，而不是-5到5

### ISSUE THREAD

**Issue by qwer130140190** [zhw2590582/ArtPlayer#775]
<img width="431" alt="image" src="https://github.com/zhw2590582/ArtPlayer/assets/29937512/efe8f22c-a190-4f30-bb9c-9f02bd456e27">
另外这个偏移的范围能不能自定义

**Comment by qwer130140190** [comment]
经测试是使用setting.add后会导致此问题

**Comment by rzmic** [comment]
i have same problem, how to resolve it?

**Comment by zhw2590582** [comment]
Fixed in artplayer@5.2.1
