### ISSUE TITLE
Unable to pause and mute when using HLS.

### ISSUE THREAD

**Issue by mattivndev** [zhw2590582/ArtPlayer#780]
I'm using your library with some customizations to fit my project that runs HLS videos. However, when I click the Pause button or the Mute button, the media player continues to run in the background (I can still hear the audio from the media player even though it appears to be paused).
My project using NextJS 13 (JSX) and HLS library from here https://www.npmjs.com/package/hls.js?activeTab=readme
`import { useEffect, useRef } from 'react';
import Artplayer from 'artplayer';
import Hls from "hls.js";

export default function Player({ option, getInstance, ...rest }) {
    const artRef = useRef();

    function playM3u8(video, url, art) {
      if (Hls.isSupported()) {
        if (art.hls) art.hls.destroy();
        const hls = new Hls();
        hls.loadSource(url);
        hls.attachMedia(video);
        art.hls = hls;
        art.on("destroy", () => hls.destroy());
      } else if (video.canPlayType("application/vnd.apple.mpegurl")) {
        video.src = url;
      } else {
        art.notice.show = "Unsupported playback format: m3u8";
      }
    }

    useEffect(() => {
        const art = new Artplayer({
            ...option,
            container: artRef.current,
            type: "m3u8",
            customType: {
              m3u8: playM3u8,
            },
        });

        if (getInstance && typeof getInstance === 'function') {
            getInstance(art);
        }

        return () => {
            if (art && art.destroy) {
                art.destroy(false);
            }
        };
    }, []);

    return <div ref={artRef} {...rest}></div>;
}`

**Comment by zhw2590582** [comment]
Can you give me a URL? I need to see it to know what's going on
