### ISSUE TITLE
希望像hls quality插件那样，提供一个hls 多音频切换的plugin

### ISSUE THREAD

**Issue by qwer130140190** [zhw2590582/ArtPlayer#786]
理论上hls.js是可以的，应该也不难

**Comment by zhw2590582** [comment]
这和换画质差不多，你可以参考换画质的插件，自己实现一下，主要是找到相关的hls的api既可

**Comment by qwer130140190** [comment]
> 这和换画质差不多，你可以参考换画质的插件，自己实现一下，主要是找到相关的hls的api既可

已经照着画质插件写好了，默认svg图标是从iconfont找的吗
