### ISSUE TITLE
[feat] 增加一个新插件以支持没有 WebVTT 的缩略图

### ISSUE THREAD

**Issue by kslr** [zhw2590582/ArtPlayer#788]
在插件中指定参数宽、高、间隔后自动计算在图中位置并显示，如果接受这个想法，我来实现这个功能

**Comment by zhw2590582** [comment]
不是很理解你具体要实现什么，你是指这个插件吗？ [artplayer-plugin-vtt-thumbnail](https://artplayer.org/?libs=./uncompiled/artplayer-plugin-vtt-thumbnail/index.js&example=vtt.thumbnail)

**Comment by kslr** [comment]
> 不是很理解你具体要实现什么，你是指这个插件吗？ [artplayer-plugin-vtt-thumbnail](https://artplayer.org/?libs=./uncompiled/artplayer-plugin-vtt-thumbnail/index.js&example=vtt.thumbnail)

类似 videojs的 https://github.com/cadenzah/videojs-thumbnail-sprite

**Comment by zhw2590582** [comment]
这不是自带的功能吗
https://artplayer.org/document/start/option.html#thumbnails
