### ISSUE TITLE
请问能实现同时播放HLS和FLV视频吗

### ISSUE THREAD

**Issue by wxhbts** [zhw2590582/ArtPlayer#795]
有具体实现的代码吗

**Comment by wxhbts** [comment]
那怎么通过 quality 切换来实现呢
`var qualitys = [
        {
            default: true,
            html: 'flv',
	    url: 'https://artplayer.org/assets/sample/video.flv',
        },
        {
            html: 'm3u8',
            url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
        },
    ];`

**Comment by zhw2590582** [comment]
这样：[demo](https://artplayer.org/?libs=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fhls.js%2F8.0.0-beta.3%2Fhls.min.js%0Ahttps%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fflv.js%2F1.6.2%2Fflv.min.js&code=%2F%2F%20npm%20i%20hls.js%0A%2F%2F%20npm%20i%20flv.js%0A%0A%2F%2F%20import%20Hls%20from%20%27hls.js%27%3B%0A%2F%2F%20import%20flvjs%20from%20%27flv.js%27%3B%0A%0Afunction%20playM3u8(video%2C%20url%2C%20art)%20%7B%0A%09if%20(Hls.isSupported())%20%7B%0A%09%09if%20(art.hls)%20art.hls.destroy()%3B%0A%09%09const%20hls%20%3D%20new%20Hls()%3B%0A%09%09hls.loadSource(url)%3B%0A%09%09hls.attachMedia(video)%3B%0A%09%09art.hls%20%3D%20hls%3B%0A%09%09art.on(%27destroy%27%2C%20()%20%3D%3E%20hls.destroy())%3B%0A%09%7D%20else%20if%20(video.canPlayType(%27application%2Fvnd.apple.mpegurl%27))%20%7B%0A%09%09video.src%20%3D%20url%3B%0A%09%7D%20else%20%7B%0A%09%09art.notice.show%20%3D%20%27Unsupported%20playback%20format%3A%20m3u8%27%3B%0A%09%7D%0A%7D%0A%0Afunction%20playFlv(video%2C%20url%2C%20art)%20%7B%0A%09if%20(flvjs.isSupported())%20%7B%0A%09%09if%20(art.flv)%20art.flv.destroy()%3B%0A%09%09const%20flv%20%3D%20flvjs.createPlayer(%7B%20type%3A%20%27flv%27%2C%20url%20%7D)%3B%0A%09%09flv.attachMediaElement(video)%3B%0A%09%09flv.load()%3B%0A%09%09art.flv%20%3D%20flv%3B%0A%09%09art.on(%27destroy%27%2C%20()%20%3D%3E%20flv.destroy())%3B%0A%09%7D%20else%20%7B%0A%09%09art.notice.show%20%3D%20%27Unsupported%20playback%20format%3A%20flv%27%3B%0A%09%7D%0A%7D%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%09url%3A%20%27%27%2C%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09customType%3A%20%7B%0A%09%09m3u8%3A%20playM3u8%2C%0A%09%09flv%3A%20playFlv%2C%0A%09%7D%2C%0A%09controls%3A%20%5B%0A%09%09%7B%0A%09%09%09name%3A%20%27quality%27%2C%0A%09%09%09position%3A%20%27right%27%2C%0A%09%09%09html%3A%20%27%E5%88%87%E6%8D%A2%27%2C%0A%09%09%09selector%3A%20%5B%0A%09%09%09%09%7B%0A%09%09%09%09%09type%3A%20%27m3u8%27%2C%0A%09%09%09%09%09url%3A%20%27https%3A%2F%2Ftest-streams.mux.dev%2Fx36xhzz%2Fx36xhzz.m3u8%27%2C%0A%09%09%09%09%09html%3A%20%27HLS%27%2C%0A%09%09%09%09%7D%2C%0A%09%09%09%09%7B%0A%09%09%09%09%09type%3A%20%27flv%27%2C%0A%09%09%09%09%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.flv%27%2C%0A%09%09%09%09%09html%3A%20%27FLV%27%2C%0A%09%09%09%09%7D%2C%0A%09%09%09%5D%2C%0A%09%09%09onSelect%3A%20function%20(item)%20%7B%0A%09%09%09%09art.type%20%3D%20item.type%3B%0A%09%09%09%09art.url%20%3D%20item.url%3B%0A%09%09%09%09return%20item.html%3B%0A%09%09%09%7D%2C%0A%09%09%7D%2C%0A%09%5D%0A%7D)%3B)

**Comment by wxhbts** [comment]
可以使用 感谢您

**Comment by wxhbts** [comment]
发现一个BUG 切换直播源的时候 不会自动终止 比如从FLV的直播源切换到M3U8的直播源 不会自动中断FLV源 浏览器会一直加载

**Comment by zhw2590582** [comment]
这样：[demo](https://artplayer.org/?libs=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fhls.js%2F8.0.0-beta.3%2Fhls.min.js%0Ahttps%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fflv.js%2F1.6.2%2Fflv.min.js&code=%2F%2F%20npm%20i%20hls.js%0A%2F%2F%20npm%20i%20flv.js%0A%0A%2F%2F%20import%20Hls%20from%20%27hls.js%27%3B%0A%2F%2F%20import%20flvjs%20from%20%27flv.js%27%3B%0A%0Afunction%20playM3u8(video%2C%20url%2C%20art)%20%7B%0A%09%2F%2F%20%E9%94%80%E6%AF%81flv%0A%09if%20(art.flv)%20art.flv.destroy()%3B%0A%0A%09if%20(Hls.isSupported())%20%7B%0A%09%09if%20(art.hls)%20art.hls.destroy()%3B%0A%09%09const%20hls%20%3D%20new%20Hls()%3B%0A%09%09hls.loadSource(url)%3B%0A%09%09hls.attachMedia(video)%3B%0A%09%09art.hls%20%3D%20hls%3B%0A%09%09art.on(%27destroy%27%2C%20()%20%3D%3E%20hls.destroy())%3B%0A%09%7D%20else%20if%20(video.canPlayType(%27application%2Fvnd.apple.mpegurl%27))%20%7B%0A%09%09video.src%20%3D%20url%3B%0A%09%7D%20else%20%7B%0A%09%09art.notice.show%20%3D%20%27Unsupported%20playback%20format%3A%20m3u8%27%3B%0A%09%7D%0A%7D%0A%0Afunction%20playFlv(video%2C%20url%2C%20art)%20%7B%0A%09%2F%2F%20%E9%94%80%E6%AF%81hls%0A%09if%20(art.hls)%20art.hls.destroy()%3B%0A%0A%09if%20(flvjs.isSupported())%20%7B%0A%09%09if%20(art.flv)%20art.flv.destroy()%3B%0A%09%09const%20flv%20%3D%20flvjs.createPlayer(%7B%20type%3A%20%27flv%27%2C%20url%20%7D)%3B%0A%09%09flv.attachMediaElement(video)%3B%0A%09%09flv.load()%3B%0A%09%09art.flv%20%3D%20flv%3B%0A%09%09art.on(%27destroy%27%2C%20()%20%3D%3E%20flv.destroy())%3B%0A%09%7D%20else%20%7B%0A%09%09art.notice.show%20%3D%20%27Unsupported%20playback%20format%3A%20flv%27%3B%0A%09%7D%0A%7D%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%09url%3A%20%27%27%2C%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09customType%3A%20%7B%0A%09%09m3u8%3A%20playM3u8%2C%0A%09%09flv%3A%20playFlv%2C%0A%09%7D%2C%0A%09controls%3A%20%5B%0A%09%09%7B%0A%09%09%09name%3A%20%27quality%27%2C%0A%09%09%09position%3A%20%27right%27%2C%0A%09%09%09html%3A%20%27%E5%88%87%E6%8D%A2%27%2C%0A%09%09%09selector%3A%20%5B%0A%09%09%09%09%7B%0A%09%09%09%09%09type%3A%20%27m3u8%27%2C%0A%09%09%09%09%09url%3A%20%27https%3A%2F%2Ftest-streams.mux.dev%2Fx36xhzz%2Fx36xhzz.m3u8%27%2C%0A%09%09%09%09%09html%3A%20%27HLS%27%2C%0A%09%09%09%09%7D%2C%0A%09%09%09%09%7B%0A%09%09%09%09%09type%3A%20%27flv%27%2C%0A%09%09%09%09%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.flv%27%2C%0A%09%09%09%09%09html%3A%20%27FLV%27%2C%0A%09%09%09%09%7D%2C%0A%09%09%09%5D%2C%0A%09%09%09onSelect%3A%20function%20(item)%20%7B%0A%09%09%09%09art.type%20%3D%20item.type%3B%0A%09%09%09%09art.url%20%3D%20item.url%3B%0A%09%09%09%09return%20item.html%3B%0A%09%09%09%7D%2C%0A%09%09%7D%2C%0A%09%5D%0A%7D)%3B)
