### ISSUE TITLE
关于artplayer-plugin-hls-quality分辨率插件改进建议

### ISSUE THREAD

**Issue by iamithunk** [zhw2590582/ArtPlayer#798]
播放m3u8视频文件时候，如果采用artplayer-plugin-hls-quality插件的话，可否实现如下改进：
1.分辨率插件能否可以从高分辨率到到低分辨率排序？目前分辨率菜单从上到下是从低分辨率到高分辨率排序，和主流播放器不同，不适应用户习惯。
2.可否实现分辨率自定义显示：比如很多视频并不是标准的1080p的分辨率，视频经常是1072p或其他分辨率，可以将这些分辨率统一自定义显示为1080p或者FHD分辨率，这样多视频网站播放时分辨率数字不至于太乱。同理，720p分辨率即其他分辨率也如此。
3.在显示各个具体分辨率的时候，是否可以选择将“自适应”选项专门显示出来，增强用户体验。

现在插件的样式：![image](https://github.com/user-attachments/assets/e480f0af-f2a5-4606-998f-5e51ce6b3409)

建议优化后的样式：![image](https://github.com/user-attachments/assets/abd0a8ce-29ee-498e-a5dd-60ab14a6e0fc)

**Comment by zhw2590582** [comment]
建议不错，下个版本加上

**Comment by iamithunk** [comment]
谢谢，真棒

**Comment by zhw2590582** [comment]
Now you can try the new plugin: [demo](https://artplayer.org/?libs=https://cdnjs.cloudflare.com/ajax/libs/hls.js/8.0.0-beta.3/hls.min.js%0A./uncompiled/artplayer-plugin-hls-control/index.js&example=hls.control)

**Comment by iamithunk** [comment]
太棒了。请教下，如果想自定义显示分辨率应该怎么写代码呢？比如程序自动获取的分辨率为714p，710p等，我想菜单统一显示为720P或者HD，应该如何配置代码？菜单能否通过配置默认就显示为auto？现在好像默认显示的是第一个分辨率

**Comment by zhw2590582** [comment]
可以的，只要getName方法返回多个同名的，也只会显示一个，例如返回了两个720p，显示的只有一个720p

**Comment by iamithunk** [comment]
如果getName方法得到的是1072p，714p，355p，但是想让菜单显示为1080p,720p,360p呢？可否实现？即是否可以自定义菜单显示，比如分辨率为 1068-1072p之间的视频，都统一显示为1080p。 因为很多视频流清晰度并不是标准的720p，1080p，设定范围后，很多不规范的视频流，都统一显示为720p，1080p等，这样比较统一整洁。特别适合用在影视网站中。

**Comment by zhw2590582** [comment]
怎么办level.height的721,722,725统一格式化成720P，这要你自己实现getName的返回值了，不难的
