### ISSUE TITLE
Add support for screenshot working on cross-origin domain vide source.

### ISSUE THREAD

**Issue by owen800q** [zhw2590582/ArtPlayer#80]
if the Vue app hosted example.com, and video source from another domain name streaming.example.com.

In this case screenshot will throw exceptions
<img width="797" alt="Screenshot 2020-07-24 at 11 52 01 PM" src="https://user-images.githubusercontent.com/19252045/88410266-b9c55900-ce08-11ea-8691-9dfac9f7524e.png">

This can be solved by adding crossorigin attribute with value of anonymous

```
<video class="art-video" crossorigin="anonymous" preload="auto" src="https://streaming.example.com/video/0"><track default="" kind="metadata"></video>
```

**Comment by zhw2590582** [comment]
You only need to add additional `video` attributes via `moreVideoAttr`:

```js
var art = new Artplayer({
    container: '.artplayer-app',
    url: 'streaming.example.com/video.mp4',
    screenshot: true,

    // Optional
    moreVideoAttr: {
        crossOrigin: 'anonymous',
    },
});
```

**Comment by owen800q** [comment]
Got it, thanks
