### ISSUE TITLE
artplayer-plugin-vtt-thumbnail plugin throwing error

### ISSUE THREAD

**Issue by divyam234** [zhw2590582/ArtPlayer#800]
artplayer-plugin-vtt-thumbnail is throwing error on 5.1.7

``Uncaught (in promise) ArtPlayerError: Can't add an existing [thumbnails] to the [control]
    at errorHandle (error.js:13:15)
    at Control.add (component.js:54:19)
    at Control.add (index.js:205:15)
    at Artplayer.<anonymous> (index.js:29:22)
``
![image](https://github.com/user-attachments/assets/eef28fd1-b80d-48b1-86ae-2e16695d29a9)

**Comment by zhw2590582** [comment]
已修复：`artplayer-plugin-vtt-thumbnail@1.0.2`
