### ISSUE TITLE
Visitor to add his own subtitles

### ISSUE THREAD

**Issue by Tescan-group** [zhw2590582/ArtPlayer#801]
Hey there!

Is it possible to edit the player so that a user can upload his own subtitle file? 

But uploaded locally for visitor's browser only, without uploading to server.

**Comment by zhw2590582** [comment]
You can add an upload button where you want it, then:

```js
function onUpload(file) {
	const url = URL.createObjectURL(file);
	art.subtitle.switch(url, {
		type: 'srt'
	});
}
```

**Comment by Tescan-group** [comment]
@zhw2590582 sorry for the ping again, would it be possible to show a demo of this with the player?

**Comment by Tescan-group** [comment]
@zhw2590582 sorry to ping, can you show a demo on this on a player perhaps?

**Comment by Tescan-group** [comment]
My bad, managed to do. Thanks again!
