### ISSUE TITLE
截图时候可以把字幕也截进去吗？

### ISSUE THREAD

**Issue by chengfengfengwang** [zhw2590582/ArtPlayer#802]
个人希望截图能够截上台词，但是不知道是不是大家的需要，酌情处理哈

**Comment by zhw2590582** [comment]
也是可以的: [demo](https://artplayer.org/?libs=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fhtml2canvas%2F1.4.1%2Fhtml2canvas.min.js&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09subtitle%3A%20%7B%0A%09%09url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.srt%27%2C%0A%09%09style%3A%20%7B%0A%09%09%09color%3A%20%27%23fe9200%27%2C%0A%09%09%09fontSize%3A%20%2720px%27%2C%0A%09%09%7D%2C%0A%09%7D%2C%0A%09controls%3A%20%5B%0A%09%09%7B%0A%09%09%09position%3A%20%27right%27%2C%0A%09%09%09html%3A%20%27%E6%88%AA%E5%9B%BE%27%2C%0A%09%09%09async%20click()%20%7B%0A%09%09%09%09const%20%7B%20%24player%20%7D%20%3D%20art.template%3B%0A%09%09%09%09const%20%7B%20download%20%7D%20%3D%20Artplayer.utils%3B%0A%0A%09%09%09%09const%20canvas%20%3D%20await%20html2canvas(%24player%2C%20%7B%0A%09%09%09%09%09ignoreElements(element)%20%7B%0A%09%09%09%09%09%09return%20%5B%0A%09%09%09%09%09%09%09%27art-bottom%27%2C%0A%09%09%09%09%09%09%09%27art-notice%27%2C%0A%09%09%09%09%09%09%09%27art-mask%27%2C%0A%09%09%09%09%09%09%09%27art-loading%27%2C%0A%09%09%09%09%09%09%09%27art-info%27%2C%0A%09%09%09%09%09%09%09%27art-contextmenus%27%2C%0A%09%09%09%09%09%09%5D.includes(element.className)%3B%0A%09%09%09%09%09%7D%2C%0A%09%09%09%09%7D)%3B%0A%0A%09%09%09%09canvas.toBlob((blob)%20%3D%3E%20%7B%0A%09%09%09%09%09const%20downloadUrl%20%3D%20URL.createObjectURL(blob)%3B%0A%09%09%09%09%09download(downloadUrl%2C%20%60%24%7BDate.now()%7D.png%60)%3B%0A%09%09%09%09%7D)%3B%0A%09%09%09%7D%2C%0A%09%09%7D%2C%0A%09%5D%2C%0A%7D)%3B)
