### ISSUE TITLE
VUE版，更新弹幕一直报错  'artplayerPluginDanmuku' is a read-only 

### ISSUE THREAD

**Issue by hunnchong** [zhw2590582/ArtPlayer#804]
art.plugins.artplayerPluginDanmuku.load();

错误信息， Uncaught (in promise) TypeError: 'get' on proxy: property 'artplayerPluginDanmuku' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '#<Object>' but got '#<Object>')
大佬知道啥问题吗

**Comment by zhw2590582** [comment]
不用把art赋予到ref里，使用shallowRef
