### ISSUE TITLE
官方文档中部分说明内容缺失的问题

### ISSUE THREAD

**Issue by superlovelace** [zhw2590582/ArtPlayer#805]
### 问题描述：
官方文档中很多只有示例代码，没有代码说明，▶ Run Code 也不见了
### 官方文档中的内容：
![PixPin_2024-09-07_10-19-00](https://github.com/user-attachments/assets/75d36bd9-39d1-438c-85bd-db3920c41aea)
### github中的页面：
![PixPin_2024-09-07_10-19-18](https://github.com/user-attachments/assets/43632895-d2c5-4d17-a14f-de302e277453)

**Comment by zhw2590582** [comment]
已修复，谢谢提醒
