### ISSUE TITLE
Google Drive Video

### ISSUE THREAD

**Issue by poinime** [zhw2590582/ArtPlayer#81]
Can i open video from google drive in ArtPlayer.js?

**Comment by zhw2590582** [comment]
As long as the video file can be accessed correctly, it is the same no matter where the file is saved

**Comment by poinime** [comment]
Sory, I put this link video from google drive (https://drive.google.com/uc?export=download&id=0B0JMGMGgxp9WMEdWb1hyQUhlOWs) but video not load, why?

**Comment by poinime** [comment]
This link too not support https://drive.google.com/file/d/0B0JMGMGgxp9WMEdWb1hyQUhlOWs/edit

**Comment by zhw2590582** [comment]
Because this is not a video address, but a web page address, but there is a video on this web page. What you really need is to get the real video address

**Comment by poinime** [comment]
How can I get the address of a video to play in artplayer?

**Comment by poinime** [comment]
![Screenshot_2020-08-24-21-04-52-87](https://user-images.githubusercontent.com/69905953/91053743-7fd8b400-e64d-11ea-9fb8-3b856c8d9719.png)

I can't access this link address
