### ISSUE TITLE
如果一个字幕，本身和视频时间对不上，能否在不修改全局偏移时间情况下，仅针对当前字幕设置延迟时间

### ISSUE THREAD

**Issue by qwer130140190** [zhw2590582/ArtPlayer#814]
多个字幕，每个字幕本身和视频时间延迟都不一样，能否在不修改全局偏移时间情况下，仅针对当前字幕设置延迟时间，subtitle对象里支持配置吗，我试过在onselect的时候art.subtitleOffset = 1;但是无效，因为字幕加载是异步的，加载完后延迟就无效了，好像要加载完成以后再设置才可以，但是subtitleLoad事件，只有url，不好操作

**Comment by zhw2590582** [comment]
还有一个`subtitleSwitch`事件，在字幕加载完后触发的

**Comment by qwer130140190** [comment]
> 还有一个`subtitleSwitch`事件，在字幕加载完后触发的

但是回调只有url参数，如果有subtitle对象就好饿了

**Comment by zhw2590582** [comment]
可以的：[demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09subtitle%3A%20%7B%0A%09%09url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.srt%27%2C%0A%09%7D%2C%0A%7D)%3B%0A%0Aart.on(%27subtitleSwitch%27%2C%20async%20()%20%3D%3E%20%7B%0A%09const%20%7B%20sleep%20%7D%20%3D%20Artplayer.utils%3B%0A%09await%20sleep(100)%3B%0A%09const%20cues%20%3D%20%5B...art.template.%24track.track.cues%5D%3B%0A%09for%20(let%20index%20%3D%200%3B%20index%20%3C%20cues.length%3B%20index%2B%2B)%20%7B%0A%09%09const%20cue%20%3D%20cues%5Bindex%5D%3B%0A%09%09cue.startTime%20%2B%3D%201%3B%0A%09%09cue.endTime%20%2B%3D%201%3B%0A%09%7D%0A%7D)%3B)

**Comment by qwer130140190** [comment]
> 可以的：[demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09subtitle%3A%20%7B%0A%09%09url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.srt%27%2C%0A%09%7D%2C%0A%7D)%3B%0A%0Aart.on(%27subtitleSwitch%27%2C%20async%20()%20%3D%3E%20%7B%0A%09const%20%7B%20sleep%20%7D%20%3D%20Artplayer.utils%3B%0A%09await%20sleep(100)%3B%0A%09const%20cues%20%3D%20%5B...art.template.%24track.track.cues%5D%3B%0A%09for%20(let%20index%20%3D%200%3B%20index%20%3C%20cues.length%3B%20index%2B%2B)%20%7B%0A%09%09const%20cue%20%3D%20cues%5Bindex%5D%3B%0A%09%09cue.startTime%20%2B%3D%201%3B%0A%09%09cue.endTime%20%2B%3D%201%3B%0A%09%7D%0A%7D)%3B)

ok，这个可以，有两个疑问，好像sleep去掉就失效了，还有就是如何获取每个字幕对应的偏移时间，我是放到subtitle对象里的

**Comment by zhw2590582** [comment]
这个偏移时间只能自己记录了

**Comment by qwer130140190** [comment]
> 这个偏移时间只能自己记录了

好的，那如何获取字幕的索引，url等，async (url) => {}，这个url也不知字幕真实的链接

**Comment by zhw2590582** [comment]
字幕的索引指的是什么

**Comment by qwer130140190** [comment]
> 字幕的索引指的是什么

就是settings菜单中配置的subtitles的index，也就是第几个字幕，主要是现在async (url) => {}无法得知是哪一个字幕

**Comment by qwer130140190** [comment]
> > 字幕的索引指的是什么
> 
> 就是settings菜单中配置的subtitles的index，也就是第几个字幕，主要是现在async (url) => {}无法得知是哪一个字幕，字幕的偏移是放到和url同级的，现在不知如何获取

**Comment by qwer130140190** [comment]
暂时先用一个变量解决

**Comment by zhw2590582** [comment]
确实是个问题，下个版本我更新一下

**Comment by zhw2590582** [comment]
这样应该可以修复你的问题： [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09setting%3A%20true%2C%0A%09subtitleOffset%3A%20true%2C%0A%09subtitle%3A%20%7B%0A%20%20%20%20%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.srt%27%2C%0A%20%20%20%20%7D%2C%0A%09settings%3A%20%5B%0A%09%09%7B%0A%09%09%09width%3A%20200%2C%0A%09%09%09html%3A%20%27Subtitle%27%2C%0A%09%09%09tooltip%3A%20%27Bilingual%27%2C%0A%09%09%09selector%3A%20%5B%0A%09%09%09%09%7B%0A%09%09%09%09%09default%3A%20true%2C%0A%09%09%09%09%09html%3A%20%27Bilingual%27%2C%0A%09%09%09%09%09url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.srt%27%2C%0A%09%09%09%09%7D%2C%0A%09%09%09%09%7B%0A%09%09%09%09%09html%3A%20%27Chinese%27%2C%0A%09%09%09%09%09url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.cn.srt%27%2C%0A%09%09%09%09%7D%2C%0A%09%09%09%09%7B%0A%09%09%09%09%09html%3A%20%27Japanese%27%2C%0A%09%09%09%09%09url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.jp.srt%27%2C%0A%09%09%09%09%7D%2C%0A%09%09%09%5D%2C%0A%09%09%09onSelect%3A%20function%20(item)%20%7B%0A%09%09%09%09art.subtitle.switch(item.url%2C%20%7B%0A%09%09%09%09%09name%3A%20item.html%2C%0A%09%09%09%09%7D)%3B%0A%0A%09%09%09%09return%20item.html%3B%0A%09%09%09%7D%2C%0A%09%09%7D%2C%0A%09%5D%2C%0A%7D)%3B%0A%0Aart.on(%27subtitleLoad%27%2C%20(cues%2C%20option)%20%3D%3E%20%7B%0A%09%2F%2F%20%E5%BD%93%E5%89%8D%E5%AD%97%E5%B9%95%E9%85%8D%E7%BD%AE%0A%09console.log(option)%3B%0A%0A%09%2F%2F%20%E5%8A%A8%E6%80%81%E8%B0%83%E6%95%B4%E5%AD%97%E5%B9%95%E5%81%8F%E7%A7%BB%E8%AE%BE%E7%BD%AE%0A%09art.setting.update(%7B%0A%09%09name%3A%20%27subtitle-offset%27%2C%0A%09%09range%3A%20%5B0%2C%20-10%2C%2010%2C%200.1%5D%2C%0A%09%09tooltip%3A%20%270s%27%2C%0A%09%7D)%3B%0A%0A%09%2F%2F%20%E5%88%9D%E5%A7%8B%E5%8C%96%E8%B0%83%E6%95%B4%E5%AD%97%E5%B9%95%E5%81%8F%E7%A7%BB%E5%80%BC%0A%09art.subtitleOffset%20%3D%200%3B%0A%7D)%3B)
