### ISSUE TITLE
播放器初始化完成后，如何自动获取焦点

### ISSUE THREAD

**Issue by qwer130140190** [zhw2590582/ArtPlayer#815]
目前页面就一个播放器，铺满页面，渲染后空格并不能触发播放暂停，需要再点一下播放器！

**Comment by zhw2590582** [comment]
可以这样: [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09muted%3A%20true%2C%0A%7D)%3B%0A%0Aart.isFocus%20%3D%20true%3B)
