### ISSUE TITLE
字幕时间重叠的时候，不能同时显示多个段

### ISSUE THREAD

**Issue by qwer130140190** [zhw2590582/ArtPlayer#817]
WEBVTT
1
00:00:00.000 --> 00:01:00.000
云飞杨 作品

2
00:00:01.000 --> 00:00:06.000
[ 梦工厂]

比如这个，6s到60s的时候，应该两条同时显示的，现在是0-60s只能显示片段1，试过vtt和ass希望能够支持同时显示

另外我发现字幕格式是ssa时，subtitle的type不支持ssa，我使用ass也是可以正常播放的，希望type支持一下ssa

**Comment by zhw2590582** [comment]
下个版本修复这个问题

**Comment by zhw2590582** [comment]
在`5.2.0`修复了字幕多行问题，不过暂不打算支持ssa
