### ISSUE TITLE
can i include more than one subtitles?

### ISSUE THREAD

**Issue by poinime** [zhw2590582/ArtPlayer#82]
can i include more than one subtitles?

**Comment by zhw2590582** [comment]
You cannot load multiple subtitles at the same time, but you can switch subtitles dynamically.

https://artplayer.org/document/#/properties?id=subtitle

**Comment by poinime** [comment]
thank you i can understand easily It is even better if the subtitle switch style is made like a quality switch style.

**Comment by zhw2590582** [comment]
Coincidentally, this feature is under development

**Comment by poinime** [comment]
Oke thanks, i waiting you, thanks very much..

**Comment by zhw2590582** [comment]
You can use this function through the following introduction, but it is still in the testing stage, so I have not published to `npm`, you can get the latest `artplayer.js` through the `dist` directory

https://artplayer.org/document/#/question?id=create-selector-in-the-controls
