### ISSUE TITLE
Multiple Audio support for a single HLS media

### ISSUE THREAD

**Issue by dev-AshishRanjan** [zhw2590582/ArtPlayer#824]
Add support for multi-audio/multi-lang media.

media url (hls) : `https://ab.matham.ws/07_30_24/07/30/18/QJXBQL2P/XGEQ7NNT.mp4/master.m3u8?h2=4f0dee68559f9f46dc8317bbbd9bf724a5d620fb799e8fb02abc998cea7b2bb50e7c51b8700bdeb502845a4bfbc35cf28abe3ba1c545cb4e52877d615230e5be56306dc4dcc0cd8504fe65600f5a3c31ca1b0402a2eae0df232bc8295abc30a7c8ed4dcba2424a15246e6f9ae494606690f4e0cc391d1ce1763cd7e9d3eee957955123e2b92dcdd473149e6ddc0effdccdec85b500db8586e7ded3d7cac62823bff9177459b1b1607ca64982`

If we play this media using the hls support in Artplayer, we don't get option for language selection, though this media is for multiple languages. 

The feature is already available in Oplayer.  
If you use the above media url here : https://oplayer.vercel.app/player/
You will get an additional option for languages in player's settings

It will be nice to have this feature in ArtPlayer

**Comment by zhw2590582** [comment]
Now you can try the new plugin: [demo](https://artplayer.org/?libs=https://cdnjs.cloudflare.com/ajax/libs/hls.js/8.0.0-beta.3/hls.min.js%0A./uncompiled/artplayer-plugin-hls-control/index.js&example=hls.control)
