### ISSUE TITLE
Better subtitle rendering

### ISSUE THREAD

**Issue by dev-AshishRanjan** [zhw2590582/ArtPlayer#825]
Just wanted to ask and suggest about Subtitle rendering in ArtPlayer

I am getting html tags in my subtitles(subtitles are from opensubtitles), subtitles are in `srt` format
When  subtitles are rendered, they are being treated as simple text, but can be treated as html.
Is there any way to render them as html?
My code implementation for subtitles
```jsx
subtitle: {
        type: "srt",
        encoding: "utf-8",
      },
```
```jsx
{
          html: "OpenSubtitle",
          width: 250,
          tooltip: "",
          icon: '<img width="22" heigth="22" src="https://artplayer.org/assets/img/subtitle.svg">',
          selector: [
            {
              html: "Display",
              tooltip: "Show",
              switch: true,
              onSwitch: function (item) {
                item.tooltip = item.switch ? "Hide" : "Show";
                art.subtitle.show = !item.switch;
                return !item.switch;
              },
            },
            ...OnlineSubs,
          ],
          onSelect: function (item) {
            art.subtitle.url = item?.url;
            art.subtitle.type = item?.type;
            art.subtitle.encoding = "utf-8";
            return item?.html;
          },
        },
```

## screenshot
![image](https://github.com/user-attachments/assets/1d16a738-0158-4bcd-b87e-bc12d43b3f6e)

## Link to issue
[Rive](https://rivestream.live/watch?type=movie&id=533535)
choose any subtitles in OpenSubtiles from players settings 

## Proposed Solution:
In react 
1. Rendered as text 
```jsx
<p>{data?.overview}</p>
```

2. Rendered as HTML
```jsx
<p dangerouslySetInnerHTML={{ __html: data?.overview }}></p>
```

If you want to keep the current rendering process, then You can add this as a new option to Artplayer.

```jsx
const art: any = new Artplayer({
      setting: true,
      fullscreen: true,
      .
      .
      .
      setSubtilesDangerously: true,
      ...
  });
```

**Comment by nabajit-cpu** [comment]
We can render subtitles as HTML in ArtPlayer by modifying the subtitle rendering logic to support dangerouslySetInnerHTML. Simply by adding a setSubtitlesDangerously flag to toggle between safe text and HTML rendering for flexibility.
