### ISSUE TITLE
在移动端音量调节滑块无法使用

### ISSUE THREAD

**Issue by lhlyu** [zhw2590582/ArtPlayer#826]
在移动端是无法触发hover事件去弹出音量调节滑块。
点击音量按钮，会切换禁音
我想让它在移动端的时候点击音量按钮会弹出上下滑块

**Comment by zhw2590582** [comment]
因为ios系统是不支持调节音量的，所以目前统一为不弹出音量调节滑块

**Comment by lhlyu** [comment]
> 因为ios系统是不支持调节音量的，所以目前统一为不弹出音量调节滑块

那可以设置隐藏音量按钮吗？

我现在是想把这个播放器内嵌到flutter webview里，我想在html实现右侧上下滑动调节音量，左侧上下滑动调节亮度，然后发送事件到flutter去调接口修改系统的值，现在基于这库有办法可以实现这些功能吗？
如果不行，我只能在播放器上面加个mask去处理了。

**Comment by zhw2590582** [comment]
上下滑动的逻辑可以自己实现，或者找一下手势库，是可以做到的

**Comment by lhlyu** [comment]
> 上下滑动的逻辑可以自己实现，或者找一下手势库，是可以做到的

嗯，我现在自己实现，但是音量按钮可以隐藏吗，如果移动端不支持上下滑动调整，那这个音量按钮很鸡肋

**Comment by zhw2590582** [comment]
可以用css隐藏它

**Comment by zhw2590582** [comment]
需求太罕见，暂不支持
