### ISSUE TITLE
ArtPlayer React not support in Nextjs

### ISSUE THREAD

**Issue by gilang-as** [zhw2590582/ArtPlayer#83]
![Screenshot (33)](https://user-images.githubusercontent.com/47550176/92300221-7b809500-ef83-11ea-8cd8-27feb8cbbbe4.png)
This is a very attractive player, but still not supported in NextJs. I'm still confused to solve it

**NextJS** : Latest
**ArtPlayer** : 3.5.14

how to solve this?
Should I use a third party package?
Thanks

**Comment by zhw2590582** [comment]
Nextjs runs on the server, and artplayer needs to run in the browser. I'm not very familiar with nextjs. You can try to search relevant documents or articles

**Comment by gilang-as** [comment]
Okay, fixed. just disable the ssr feature in the player component.
![Screenshot (38)](https://user-images.githubusercontent.com/47550176/92393736-8cc7ce00-f14a-11ea-83a6-1bd26d621e82.png)
Thanks
