### ISSUE TITLE
[Feature Request] modify this.option.poster to update video poster

### ISSUE THREAD

**Issue by YunYouJun** [zhw2590582/ArtPlayer#84]
I want to change the cover after the video loads by artplayer-vue.

I try `this.option.poster = "xxx"` or `this.art.option.poster = 'xxx'`, but failed.
But i can use `this.art.player.url = "xxx"` to change video src.

I check the source code, it seems that poster is not treated like [urlMix](https://github.com/zhw2590582/ArtPlayer/blob/8daf69e7bf3124255f68f3d33e1b34c7215e72ed/packages/artplayer/src/player/urlMix.js).

Can you add this feature?

Then we can just use `this.option.poster` to change video poster.

**Comment by YunYouJun** [comment]
By the way, i use `document.querySelector('.art-video').poster = 'xxx'` as a temp solution.

**Comment by zhw2590582** [comment]
Or something like this: `art.template.$video.poster = 'xxx'`

**Comment by YunYouJun** [comment]
Yeah, thanks.
But is it a better solution to keep `art.option.poster` and `art.template.$video.poster` the same?

**Comment by zhw2590582** [comment]
I haven't encountered a case that needs to modify the poster dynamically, so I will not consider your proposal for the time being
