### ISSUE TITLE
highlighting specific portion of chapters

### ISSUE THREAD

**Issue by itzzzme** [zhw2590582/ArtPlayer#845]
Is therey any option to give specific chapter portion in progressive bar some color to highlight

**Comment by zhw2590582** [comment]
This is not a common style, but you can modify this style yourself

**Comment by itzzzme** [comment]
I was trying to add styling update in layers on player ready but can't we add smooth transition

```
layers: [
                {
                    name: website_name,
                    html: logo,
                    tooltip: website_name,
                    style: {
                        opacity: 0,
                        position: 'absolute',
                        top: '5px',
                        right: '5px',
                        transition: 'opacity 0.5s ease-out',
                    },
                },
            ],
```

```
setTimeout(() => {
                art.layers.update({
                    name: website_name,
                    html: logo,
                    style: {
                        position: 'absolute',
                        top: '5px',
                        right: '5px',
                        transition: 'opacity 2s ease-out',
                        opacity: 1,
                    }
                });
            }, 2000);
```

the transition is not working. i have to reapply all styles while updating because it seems on update instead of appending styling it overwrites the style of layer. can I do anything to fix that

**Comment by itzzzme** [comment]
> This is not a common style, but you can modify this style yourself

many website uses it btw

![Screenshot 2024-10-22 153509-mh](https://github.com/user-attachments/assets/89106a76-3477-4a02-b5e1-86b714be9c6e)

like this

**Comment by zhw2590582** [comment]
> I was trying to add styling update in layers on player ready but can't we add smooth transition
> 
> **_Initializing the layer_**
> 
> ```
> layers: [
>                 {
>                     name: website_name,
>                     html: logo,
>                     tooltip: website_name,
>                     style: {
>                         opacity: 0,
>                         position: 'absolute',
>                         top: '5px',
>                         right: '5px',
>                         transition: 'opacity 0.5s ease-out',
>                     },
>                 },
>             ],
> ```
> 
> **_Updaing the layer_**
> 
> ```
> setTimeout(() => {
>                 art.layers.update({
>                     name: website_name,
>                     html: logo,
>                     style: {
>                         position: 'absolute',
>                         top: '5px',
>                         right: '5px',
>                         transition: 'opacity 2s ease-out',
>                         opacity: 1,
>                     }
>                 });
>             }, 2000);
> ```
> 
> the transition is not working. i have to reapply all styles while updating because it seems on update instead of appending styling it overwrites the style of layer. can I do anything to fix that

If you use CSS effects on the same layer, you should not use update the layer, but use ordinary js or CSS

**Comment by itzzzme** [comment]
can you tell me an example where I can add the smooth transition in a layer

**Comment by zhw2590582** [comment]
like this: [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20layers%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%09%09%09name%3A%20%27some-name%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%27%3Cimg%20width%3D%22100%22%20src%3D%22%2Fassets%2Fsample%2Flayer.png%22%3E%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20style%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20position%3A%20%27absolute%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20top%3A%20%2720px%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20right%3A%20%2720px%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20opacity%3A%20%270%27%2C%0A%09%09%09%09transition%3A%20%27opacity%200.5s%20ease-out%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%5D%2C%0A%7D)%3B%0A%0AsetTimeout(()%20%3D%3E%20%7B%0A%09art.layers%5B%27some-name%27%5D.style.opacity%20%3D%201%3B%0A%7D%2C%201000)%3B)
