### ISSUE TITLE
Fix: Fixing small font-size problem of subtitle while tacking with <i> tag

### ISSUE THREAD

**Issue by itzzzme** [zhw2590582/ArtPlayer#846]
**PROBLEM: Often the font-size gets automatically small when there is any special tag (i.e: `<i>` tag) or any other possible tags which causes the same problem**

![Screenshot 2024-10-21 212537-mh](https://github.com/user-attachments/assets/312fe424-1b29-4781-9acc-0a3c07ce8c1f)

**FIX**

**step 1:**  set styling as per your preference in subtitle

e.g:
```
subtitle: {
                style: {
                    "font-weight": "400",
                    "font-size": "1rem",        // you can set it as per you preference
                    color: "white",
                },
                escape: false,          // **this line is important. Keep it false to see the effect of those special tags**
            },
```

**step 2:** Now create a **style.css** file

**step 3:** Put this lines in the css file

```
.art-subtitle-line {
  font-size: inherit !important;
}

.art-subtitle-line * {
  font-size: inherit !important;
}
```
**Explanation:** The font-size you set on subtitle will get inherited by this classes which are attached to the subtitle lines

**step 4:** Simply import the css file in your js,jsx,ts,tsx (etc) file

_**Hope it is solved!!**_

![Screenshot 2024-10-21 213802-mh](https://github.com/user-attachments/assets/a9843e14-28e1-4459-af08-f12abcbeee2f)

**Comment by zhw2590582** [comment]
This is more like because global style affects the <i> tag, you can define the style yourself
