### ISSUE TITLE
作者能开发出暂停弹窗广告吗

### ISSUE THREAD

**Issue by taohualang** [zhw2590582/ArtPlayer#848]
点击暂停会弹出广告
类似这种：
![Snipaste_2024-10-23_10-09-46](https://github.com/user-attachments/assets/33f1b775-cf52-4c6d-b248-7be0e116601d)

**Comment by zhw2590582** [comment]
这种吗？直接写一个层，然后监听事件就可以了：[demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20layers%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%09%09%09name%3A%20%27some-name%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%27%3Cimg%20width%3D%22100%22%20src%3D%22%2Fassets%2Fsample%2Flayer.png%22%3E%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20style%3A%20%7B%0A%09%09%09%09display%3A%20%27none%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20position%3A%20%27absolute%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20left%3A%20%2750px%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20top%3A%20%2750px%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%5D%2C%0A%7D)%3B%0A%0Aart.on(%27pause%27%2C%20()%20%3D%3E%20%7B%0A%09art.layers%5B%27some-name%27%5D.style.display%20%3D%20%27%27%3B%0A%7D)%3B%0A%0Aart.on(%27play%27%2C%20()%20%3D%3E%20%7B%0A%09art.layers%5B%27some-name%27%5D.style.display%20%3D%20%27none%27%3B%0A%7D)%3B)
