### ISSUE TITLE
视频广告能设置展示的时机吗

### ISSUE THREAD

**Issue by taohualang** [zhw2590582/ArtPlayer#849]
现在的视频广告是点击播放就弹出广告，我想可以设置多少秒后自己弹出广告或者可以设置开头/中间/结尾弹出广告吗。

**Comment by zhw2590582** [comment]
这样：[demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20layers%3A%20%5B%0A%20%20%20%20%20%20%20%20%7B%0A%09%09%09name%3A%20%27some-name%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20html%3A%20%27%3Cimg%20width%3D%22100%22%20src%3D%22%2Fassets%2Fsample%2Flayer.png%22%3E%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20style%3A%20%7B%0A%09%09%09%09display%3A%20%27none%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20position%3A%20%27absolute%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20left%3A%20%2750px%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20top%3A%20%2750px%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%5D%2C%0A%7D)%3B%0A%0A%2F%2F%20%E6%97%B6%E9%97%B4%E5%B9%BF%E5%91%8A%0Aart.on(%27video%3Atimeupdate%27%2C%20()%20%3D%3E%20%7B%0A%09if%20(art.currentTime%20%3C%201)%20%7B%0A%09%09%2F%2F%20%E5%BC%80%E5%A7%8B%E5%88%B01%E7%A7%92%0A%09%09art.layers%5B%27some-name%27%5D.style.display%20%3D%20%27%27%3B%0A%09%7D%20else%20if%20(art.currentTime%20%3E%205%20%26%26%20art.currentTime%20%3C%2010)%20%7B%0A%09%09%2F%2F%205%E5%88%B010%E7%A7%92%0A%09%09art.layers%5B%27some-name%27%5D.style.display%20%3D%20%27%27%3B%0A%09%7D%20else%20%7B%0A%09%09art.layers%5B%27some-name%27%5D.style.display%20%3D%20%27none%27%3B%0A%09%7D%0A%7D)%3B%0A%0A%2F%2F%20%E6%9A%82%E5%81%9C%E5%B9%BF%E5%91%8A%0Aart.on(%27pause%27%2C%20async%20()%20%3D%3E%20%7B%0A%09await%20Artplayer.utils.sleep(100)%0A%09art.layers%5B%27some-name%27%5D.style.display%20%3D%20%27%27%3B%0A%7D)%3B%0A%0A%2F%2F%20%E5%AE%8C%E7%BB%93%E5%B9%BF%E5%91%8A%0Aart.on(%27video%3Aended%27%2C%20async%20()%20%3D%3E%20%7B%0A%09await%20Artplayer.utils.sleep(100)%0A%09art.layers%5B%27some-name%27%5D.style.display%20%3D%20%27%27%3B%0A%7D)%0A%0A%2F%2F%20%E6%92%AD%E6%94%BE%E6%97%B6%E5%8F%96%E6%B6%88%0Aart.on(%27play%27%2C%20()%20%3D%3E%20%7B%0A%09art.layers%5B%27some-name%27%5D.style.display%20%3D%20%27none%27%3B%0A%7D)%3B)
