### ISSUE TITLE
AV1 manifest file do not play in Artplayer with Artplayer-HLS-Control

### ISSUE THREAD

**Issue by Feierkuula** [zhw2590582/ArtPlayer#854]
### Expected behaviour
AV1 video codec should play fine in the Player. Known to work in JWPlayer so far.

### Actual behaviour
The browser did not recognize the AV1 codec inside m3u8 file and only the supported Audio codecs play.

### Steps to reproduce
encode any video to AV1 codec with Vod HLS and fMP4 files to m3u8 file, i.e. with ffmpeg

### Environment

-   Browser: Firefox and Chromium so far.
-   Version: Latest
-   Operating System: Arch Linux
-   Version: Latest

### Console errors (if any)
could not play mp4;codec=unknown

if i replace inside the m3u8 file the CODEC="av01.0.31M.08" with typical x264 codec, it still works in Firefox only. So it is an codec identifer issue.

### Link to where the bug is happening
https://artplayer.org/?libs=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fhls.js%2F8.0.0-beta.3%2Fhls.min.js%0A.%2Funcompiled%2Fartplayer-plugin-hls-control%2Findex.js&code=%2F%2F%20npm%20i%20hls.js%0A%2F%2F%20npm%20i%20artplayer-plugin-hls-control%0A%0A%2F%2F%20import%20Hls%20from%20%27hls.js%27%3B%0A%2F%2F%20import%20artplayerPluginHlsControl%20from%20%27artplayer-plugin-hls-control%27%3B%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fwww.bitporno.com%2Fm3u8%2F455df5f5098fdf1c5e0735a6eee763b8%2FHV4TKBSCK6%2Fplaylist.m3u8%27%2C%0A%20%20%20%20setting%3A%20true%2C%0A%20%20%20%20plugins%3A%20%5B%0A%20%20%20%20%20%20%20%20artplayerPluginHlsControl(%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20quality%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20Show%20qualitys%20in%20control%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20control%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20Show%20qualitys%20in%20setting%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20setting%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20Get%20the%20quality%20name%20from%20level%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20getName%3A%20(level)%20%3D%3E%20level.height%20%2B%20%27P%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20I18n%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20title%3A%20%27Quality%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20auto%3A%20%27Auto%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20audio%3A%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20Show%20audios%20in%20control%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20control%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20Show%20audios%20in%20setting%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20setting%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20Get%20the%20audio%20name%20from%20track%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20getName%3A%20(track)%20%3D%3E%20track.name%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20I18n%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20title%3A%20%27Audio%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20auto%3A%20%27Auto%27%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D)%2C%0A%20%20%20%20%5D%2C%0A%20%20%20%20customType%3A%20%7B%0A%20%20%20%20%20%20%20%20m3u8%3A%20function%20playM3u8(video%2C%20url%2C%20art)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20if%20(Hls.isSupported())%20%7B%0A%09%09%09%09if%20(art.hls)%20art.hls.destroy()%3B%0A%09%09%09%09const%20hls%20%3D%20new%20Hls()%3B%0A%09%09%09%09hls.loadSource(url)%3B%0A%09%09%09%09hls.attachMedia(video)%3B%0A%09%09%09%09art.hls%20%3D%20hls%3B%0A%09%09%09%09art.on(%27destroy%27%2C%20()%20%3D%3E%20hls.destroy())%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%20else%20if%20(video.canPlayType(%27application%2Fvnd.apple.mpegurl%27))%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20video.src%20%3D%20url%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20art.notice.show%20%3D%20%27Unsupported%20playback%20format%3A%20m3u8%27%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%2C%0A%7D)%3B

**Comment by zhw2590582** [comment]
I tried using video-dev.org and it couldn't play your m3u8 url either
https://hlsjs.video-dev.org/demo/

**Comment by Feierkuula** [comment]
my apologies, its because of allow-origin settings, here the new m3u8 link for you to testing (safe for work):

https://www.bitporno.com/m3u8/a0440c0b8a2cfce5fd1d26ebd78dabfa/HV7BQN89FB/playlist.m3u8

**Comment by zhw2590582** [comment]
<img width="1113" alt="image" src="https://github.com/user-attachments/assets/38ccf860-13da-45b3-84d8-6197065ab807">

Still can't play

**Comment by Feierkuula** [comment]
Well on my end, it works. I think it has to do with the firewall in China. I will upload it into my server.

**Comment by zhw2590582** [comment]
try this: [demo](https://artplayer.org/?libs=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Fhls.js%2F1.5.17%2Fhls.min.js&code=%2F%2F%20npm%20i%20hls.js%0A%2F%2F%20import%20Hls%20from%20%27hls.js%27%3B%0A%0Afunction%20playM3u8(video%2C%20url%2C%20art)%20%7B%0A%20%20%20%20if%20(Hls.isSupported())%20%7B%0A%20%20%20%20%20%20%20%20if%20(art.hls)%20art.hls.destroy()%3B%0A%20%20%20%20%20%20%20%20const%20hls%20%3D%20new%20Hls()%3B%0A%20%20%20%20%20%20%20%20hls.loadSource(url)%3B%0A%20%20%20%20%20%20%20%20hls.attachMedia(video)%3B%0A%20%20%20%20%20%20%20%20art.hls%20%3D%20hls%3B%0A%20%20%20%20%20%20%20%20art.on(%27destroy%27%2C%20()%20%3D%3E%20hls.destroy())%3B%0A%20%20%20%20%7D%20else%20if%20(video.canPlayType(%27application%2Fvnd.apple.mpegurl%27))%20%7B%0A%20%20%20%20%20%20%20%20video.src%20%3D%20url%3B%0A%20%20%20%20%7D%20else%20%7B%0A%20%20%20%20%20%20%20%20art.notice.show%20%3D%20%27Unsupported%20playback%20format%3A%20m3u8%27%3B%0A%20%20%20%20%7D%0A%7D%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fwww.bitporno.com%2Fm3u8%2Fa0440c0b8a2cfce5fd1d26ebd78dabfa%2FHV7BQN89FB%2Fplaylist.m3u8%27%2C%0A%20%20%20%20type%3A%20%27m3u8%27%2C%0A%20%20%20%20customType%3A%20%7B%0A%20%20%20%20%20%20%20%20m3u8%3A%20playM3u8%2C%0A%20%20%20%20%7D%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%20%20%20%20console.info(art.hls)%3B%0A%7D)%3B)

**Comment by Feierkuula** [comment]
In this configuration, it works.
