### ISSUE TITLE
Skipping forward or backward on double click on left or right side of the player

### ISSUE THREAD

**Issue by itzzzme** [zhw2590582/ArtPlayer#857]
I had something in mind something like this

```
{
 html: "",
 style: {
            position: "absolute",
            left: 0,
            top: 0,
            width: "40%",
            height: "100%",
  },
  disable: !Artplayer.utils.isMobile,
   dblclick: function () {
            art.currentTime = Math.max(0, art.currentTime - 10);
   }
},
```
Since `dblclick` is not a thing in layers so I can't do that
But if you have any existing code written on artplayer's IDE then it would be appreciated if you can share that . Because I couldn't find something like this in available docs

**Comment by zhw2590582** [comment]
Like this? [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%09layers%3A%20%5B%0A%09%09%7B%0A%09%09%09name%3A%20%22left%22%2C%0A%09%09%09html%3A%20%27%27%2C%0A%09%09%09style%3A%20%7B%0A%09%09%09%09position%3A%20%22absolute%22%2C%0A%09%09%09%09left%3A%200%2C%0A%09%09%09%09top%3A%200%2C%0A%09%09%09%09width%3A%20%2240%25%22%2C%0A%09%09%09%09height%3A%20%22100%25%22%2C%0A%09%09%09%09backgroundColor%3A%20%27red%27%0A%09%09%09%7D%2C%0A%09%09%7D%0A%09%5D%2C%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%09const%20%24left%20%3D%20art.layers%5B%27left%27%5D%0A%09art.proxy(%24left%2C%20%27dblclick%27%2C%20()%20%3D%3E%20%7B%0A%09%09art.notice.show%20%3D%20%27-10s%27%3B%0A%09%09art.currentTime%20%3D%20Math.max(0%2C%20art.currentTime%20-%2010)%3B%0A%09%7D)%0A%7D))

**Comment by itzzzme** [comment]
yes it's perfect but how to hide it in mobile

if i use this line

`disable: !Artplayer.utils.isMobile,`

then will it be disable since you are using proxy so will the disable get affected

**Comment by itzzzme** [comment]
I am countering one problem when I tried to add those layers subtitles got disable in my setting

**Comment by zhw2590582** [comment]
You can check the console for any error messages
