### ISSUE TITLE
html/label of quality is not changing on changing quality

### ISSUE THREAD

**Issue by itzzzme** [zhw2590582/ArtPlayer#859]
I am using artplayer-plugin-hls-control but when i switch quality the html/label of selector doesn't change and shows an error in console

### problem of label not changing:
https://github.com/user-attachments/assets/c0723b72-057f-4a5e-8d9c-d31a753c6b71

### the error showing in console
![Screenshot 2024-11-02 194253](https://github.com/user-attachments/assets/9f4b671b-2c50-4597-823f-4a6f840241b5)

Here is the code:
```
plugins: [
        artplayerPluginHlsControl({
          quality: {
            setting: true,
            getName: (level) => level.height + "P",
            title: "Quality",
            auto: "Auto",
          },
        }),
]
```

**Comment by zhw2590582** [comment]
Please make sure you are using the latest version of artplayer

**Comment by itzzzme** [comment]
> Please make sure you are using the latest version of artplayer

I am using 5.2.0
