### ISSUE TITLE
请问可以根据网速动态切换视频画质吗？

### ISSUE THREAD

**Issue by nanqic** [zhw2590582/ArtPlayer#868]
非常感谢有这么棒的player！
不知道有没有内置自动切换画质的feature?
如果没有，可以在切换画质后持久化配置吗？

我的配置是这样的，在切换视频画质后再播放其他视频又变成默认画质了。
``` javascript
  quality: [
              {
                  html: '疾速',
                  url: `${alistSrc}/360p/${no}.mp4`
              },
              {
                  default: true,
                  html: '标准',
                  url: buildSrc('480'),
           }，
           ...
]
   ```

**Comment by zhw2590582** [comment]
hls有这个自动画质的功能，普通的mp4链接的话，要你自己去判断网速的大小才行

**Comment by nanqic** [comment]
很开心这么快得到回复，请问配置quality数组对象没办法持久存储吗？是不是要添加自定义按钮并创建自定义方法才可以实现

**Comment by zhw2590582** [comment]
给你写了个demo, 可以参考以下： [demo](https://artplayer.org/?libs=&code=const%20qualitys%20%3D%20%5B%0A%09%7B%0A%09%09default%3A%20true%2C%0A%09%09html%3A%20%27480P%27%2C%0A%09%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%3Fq%3D480%27%2C%0A%09%7D%2C%0A%09%7B%0A%09%09html%3A%20%27720P%27%2C%0A%09%09url%3A%20%27%2Fassets%2Fsample%2Fvideo.mp4%3Fq%3D720%27%2C%0A%09%7D%2C%0A%5D%0A%0Avar%20art%20%3D%20new%20Artplayer(%7B%0A%09container%3A%20%27.artplayer-app%27%2C%0A%09controls%3A%20%5B%0A%09%09%7B%0A%09%09%09name%3A%20%27quality%27%2C%0A%09%09%09position%3A%20%27right%27%2C%0A%09%09%09html%3A%20%27480P%27%2C%0A%09%09%09selector%3A%20qualitys%2C%0A%09%09%09async%20onSelect(item)%20%7B%0A%09%09%09%09await%20art.switchQuality(item.url)%3B%0A%09%09%09%09art.storage.set(%27quality%27%2C%20item.html)%3B%0A%09%09%09%09return%20item.html%3B%0A%09%09%09%7D%2C%0A%09%09%09async%20mounted()%20%7B%0A%09%09%09%09await%20Artplayer.utils.sleep(100)%3B%0A%09%09%09%09const%20quality%20%3D%20this.storage.get(%27quality%27)%3B%0A%09%09%09%09const%20priority%20%3D%20qualitys.find(item%20%3D%3E%20item.html%20%3D%3D%3D%20quality)%20%7C%7C%20qualitys.find(item%20%3D%3E%20item.default)%20%7C%7C%20qualitys%5B0%5D%3B%0A%09%09%09%09this.switchQuality(priority.url)%3B%0A%09%09%09%09this.controls.check(priority)%0A%09%09%09%7D%0A%09%09%7D%0A%09%5D%0A%7D)%3B)

**Comment by nanqic** [comment]
非常非常感谢！
