### ISSUE TITLE
Loads the URL although the video is not played

### ISSUE THREAD

**Issue by dantart** [zhw2590582/ArtPlayer#87]
Hi!
I use ArtPlayer to show 10 videos on page, all of them with the "poster" variable.
But I see each time I load the page, it requests to the server the 10 poster url's AND ALSO the 10 mp4 files.
So that's a lot of data transfer consuming, because the user probably will see just 1 or 2 videos.
Is there any option to disable this, so ArtPlayer request the mp4 video mp4 just if user plays it ?

**Comment by zhw2590582** [comment]
If you don’t want to load the video by default, you can add a preload="metadata", for example

var art = new Artplayer({
    moreVideoAttr: {
        preload: "metadata",
    },
});

**Comment by dantart** [comment]
I have it that way, but still loading all mp4 files from server (according to Apache logs)

**Comment by zhw2590582** [comment]
Of course, the general approach is to fake a screenshot of the player, and then initialize the player when the user clicks on the screenshot

**Comment by zhw2590582** [comment]
Or you can use lazy loading

**Comment by dantart** [comment]
Well, you could create a parameter for that working together with poster. For example: poster_lazyload = true
... and when user clicks on video, poster disappears and the attribute src for the video element is set then.

**Comment by zhw2590582** [comment]
You have a good idea, but I think it's a specific business scenario and can't be part of the player's functionality.
