### ISSUE TITLE
restart事件回调时视频未加载成功

### ISSUE THREAD

**Issue by ruilingshan** [zhw2590582/ArtPlayer#872]
想要达到的效果是，切换了url后利用restart回调事件，开始自动播放新一段视频，但偶而播放时会报错The play() request was interrupted by a call to pause()，应该是此时新的视频还没加载好就开始播放了。请问这个情况要用哪个钩子，还是说是bug？

const playerSwitchUrl = async ({ videoUrl, autoPlay, seekTime }) => {
  art.value.url = videoUrl;
  seekTime &&
    art.value.on('restart', () => {
      art.value.seek = seekTime;
    });
  autoPlay &&
    art.value.on('restart', () => {
      art.value.play();
    });
};

**Comment by zhw2590582** [comment]
试试这样
```js
const playerSwitchUrl = async ({ videoUrl, autoPlay, seekTime }) => {
  art.value.once('video:canplay', () => {
    if (seekTime) {
      art.value.seek = seekTime;
    }
    if (autoPlay) {
      art.value.play();
    }
  });
  art.value.url = videoUrl;
};

```
