### ISSUE TITLE
请问如何不销毁播放器重新加载新的弹幕库

### ISSUE THREAD

**Issue by DirectLinkSs** [zhw2590582/ArtPlayer#88]
我在不销毁播放器的情况下切换视频地址，需要同时切换弹幕库。
请问如何切换。
我尝试使用
```
art.plugins.artplayerPluginDanmuku.config({
            danmuku: '/assets/sample/danmuku.xml',
            speed: 5,
            maxlength: 50,
            margin: [10, 100],
            opacity: 1,
            fontSize: 25,
            synchronousPlayback: false,
        });
```

来切换，danmuku似乎不起作用，其他参数可以被改变。

另外我想询问关于控件单个按钮隐藏的具体用法，以实现播放器窗口较小的情况下隐藏部分按钮。

**Comment by zhw2590582** [comment]
好想法，之前我没考虑到可以动态切换弹幕库，现在最新版本支持了，添加了`load`方法用于加载最新的`danmuku `选项

```js
art.plugins.artplayerPluginDanmuku.config({
    danmuku: '/assets/sample/danmuku.xml',
    speed: 5,
    maxlength: 50,
}).load();
```

另外，每个控件都是对应不同的类名的，建议通过css的媒体查询来控制显示隐藏

**Comment by DirectLinkSs** [comment]
感谢，另外控件可以动态添加，如何动态删除呢。
比如我添加了一个选择框用来选集（这不太合适，太多的选择项会导致溢出），在加载播放器地址后需要删除这个控件重新添加。
```
    controls: [
        {
            position: 'right',
            html: 'Subtitle 01',
            selector: [
                {
                    name: 'Subtitle 01',
                    url: '/assets/sample/subtitle.srt?id=1',
                },
                {
                    name: 'Subtitle 02',
                    url: '/assets/sample/subtitle.srt?id=2',
                },
            ],
            onSelect: function (item) {
                art.subtitle.switch(item.url, {
                    name: item.name
                });
            },
        },
    ],
```

还有一个建议，右键菜单严格限制在画面内部生效。在右键点击控制栏跟设置栏的时候恢复默认右键菜单。
方便在设置栏中插入的输入框可以正常操作。
这也许能通过 `art.events.proxy()`自定义实现，希望能成为播放器默认状态。

**Comment by DirectLinkSs** [comment]
> 好想法，之前我没考虑到可以动态切换弹幕库，现在最新版本支持了，添加了`load`方法用于加载最新的`danmuku `选项
> 
> ```js
> 艺术。插件。artplayerPluginDanmuku 。config （{ 
>     danmuku：' / assets/sample/danmuku.xml ' ，
>     速度：5 ，
>     maxlength：50 ，
> } ）。负载（）;
> ```
> 
> 另外，每个控件都是对应不同的类名的，建议通过css的媒体查询来控制显示隐藏







感谢，另外控件可以动态添加，如何动态删除呢。
有时我添加了一个选择框用来选择集（这不太合适，太多的选择项会导致重叠），在加载播放器地址后需要删除这个控件重新添加。

    controls: [
        {
            position: 'right',
            html: 'Subtitle 01',
            selector: [
                {
                    name: 'Subtitle 01',
                    url: '/assets/sample/subtitle.srt?id=1',
                },
                {
                    name: 'Subtitle 02',
                    url: '/assets/sample/subtitle.srt?id=2',
                },
            ],
            onSelect: function (item) {
                art.subtitle.switch(item.url, {
                    name: item.name
                });
            },
        },
    ],
还有一个建议，快捷菜单严格限制在画面内部增强。在快捷点击控制栏跟设置栏的时候恢复重置菜单。
方便在设置位置插入的输入框可以正常操作。
这也许能通过art.events.proxy()自定义实现，希望能成为播放器预设状态。

**Comment by DirectLinkSs** [comment]
感谢，另外控件可以动态添加，如何动态删除呢。
有时我添加了一个选择框用来选择集（这不太合适，太多的选择项会导致重叠），在加载播放器地址后需要删除这个控件重新添加。

    controls: [
        {
            position: 'right',
            html: 'Subtitle 01',
            selector: [
                {
                    name: 'Subtitle 01',
                    url: '/assets/sample/subtitle.srt?id=1',
                },
                {
                    name: 'Subtitle 02',
                    url: '/assets/sample/subtitle.srt?id=2',
                },
            ],
            onSelect: function (item) {
                art.subtitle.switch(item.url, {
                    name: item.name
                });
            },
        },
    ],
还有一个建议，快捷菜单严格限制在画面内部增强。在快捷点击控制栏跟设置栏的时候恢复重置菜单。
方便在设置位置插入的输入框可以正常操作。
这也许能通过art.events.proxy()自定义实现，希望能成为播放器预设状态。

**Comment by DirectLinkSs** [comment]
> 好想法，之前我没考虑到可以动态切换弹幕库，现在最新版本支持了，添加了`load`方法用于加载最新的`danmuku `选项
> 
> ```js
> art.plugins.artplayerPluginDanmuku.config({
>     danmuku: '/assets/sample/danmuku.xml',
>     speed: 5,
>     maxlength: 50,
> }).load();
> ```
> 
> 另外，每个控件都是对应不同的类名的，建议通过css的媒体查询来控制显示隐藏

感谢，另外控件可以动态添加，如何动态删除呢。
有时我添加了一个选择框用来选择集（这不太合适，太多的选择项会导致重叠），在加载播放器地址后需要删除这个控件重新添加。

    controls: [
        {
            position: 'right',
            html: 'Subtitle 01',
            selector: [
                {
                    name: 'Subtitle 01',
                    url: '/assets/sample/subtitle.srt?id=1',
                },
                {
                    name: 'Subtitle 02',
                    url: '/assets/sample/subtitle.srt?id=2',
                },
            ],
            onSelect: function (item) {
                art.subtitle.switch(item.url, {
                    name: item.name
                });
            },
        },
    ],
还有一个建议，快捷菜单严格限制在画面内部增强。在快捷点击控制栏跟设置栏的时候恢复重置菜单。
方便在设置位置插入的输入框可以正常操作。
这也许能通过art.events.proxy()自定义实现，希望能成为播放器预设状态。

**Comment by zhw2590582** [comment]
目前不支持动态删除控件，因为要动态解绑事件会改动很多代码，当时也没考虑这一点，建议做隐藏就好。
但你的另外一个建议，我不是很理解你的意思

**Comment by DirectLinkSs** [comment]
![image](https://user-images.githubusercontent.com/17827407/99866326-67941900-2beb-11eb-940f-22630407c09d.png)
我插入了一个输入框，但是不能右键进行粘贴，会弹出播放器的右键菜单。

**Comment by zhw2590582** [comment]
或者考虑把输入框放外面，你是不是要做弹幕输入框，像B站那样的输入框也是在播放器外面的

**Comment by DirectLinkSs** [comment]
好的，了解了。
