### ISSUE TITLE
Problems with the webtorrent in the own Artplayer demo

### ISSUE THREAD

**Issue by 1pipinto** [zhw2590582/ArtPlayer#881]
So i was testing the webtorrent with a movie torrent, 720p, mp4 and the torrent dont play, the code is the default one, the only thing i changed is the magnet lol, it just infinite load and thats it, sometimes when i reload the page the default torrent for demo plays, sometimes not, and i got this error...
![Screenshot_3](https://github.com/user-attachments/assets/449dea06-c9a7-4eff-9206-640f12a7083c)

**Comment by zhw2590582** [comment]
This is a question you should ask webtorrent：https://github.com/webtorrent/webtorrent
