### ISSUE TITLE
试图同时支持flv与dash格式的播放失败。

### ISSUE THREAD

**Issue by DirectLinkSs** [zhw2590582/ArtPlayer#89]
我试图让播放器在不销毁的情况下同时支持dash与flv，通过修改type来实现无效。是否能支持切换呢。

另外
文档中的 art.url 和 art.switchUrl 有什么区别呢。

**Comment by zhw2590582** [comment]
切换前，指明类型就可以了
```js
const flvUrl = 'xxx'
const dashUrl = `xxx`;

art.option.type = 'flv';
art.url = flvUrl;

// 切换
art.option.type = 'dash';
art.url = dashUrl;
```
art.url 是只修改video的src, 不会做其他事情
https://github.com/zhw2590582/ArtPlayer/blob/master/packages/artplayer/src/player/urlMix.js

art.switchUrl 是修改了video的src，而且会做一些适配事情，例如调整尺寸，播放时间归零，推荐用这个
https://github.com/zhw2590582/ArtPlayer/blob/master/packages/artplayer/src/player/switchMix.js

**Comment by DirectLinkSs** [comment]
谢谢，想问下如何清空弹幕。用  
```
			art.plugins.artplayerPluginDanmuku.config({
				danmuku: 'xx'
			}).load();
```
加载新的弹幕库不会清空旧的弹幕库。

**Comment by zhw2590582** [comment]
修复了，你试试最新版本`3.5.22`

**Comment by DirectLinkSs** [comment]
> 修复了，你试试最新版本`3.5.22`

使用新版，已经加载在画面上的不会被清空，而且会永远留在画面上。
![image](https://user-images.githubusercontent.com/17827407/99966568-763c2500-2dd1-11eb-8d54-9e2fd1be13b8.png)
圈中的是新切换的弹幕，正常滚动，其他弹幕是旧的会留在画面上。

**Comment by zhw2590582** [comment]
好吧，我明天再看看

**Comment by zhw2590582** [comment]
可以了，再试试

**Comment by DirectLinkSs** [comment]
> 可以了，再试试

动态滚动弹幕可以了，静态弹幕还是会一直留在画面上。

**Comment by zhw2590582** [comment]
你要安装最新版本

**Comment by DirectLinkSs** [comment]
我 使用的 版本为3.5.23  。
![演示](https://user-images.githubusercontent.com/17827407/100041269-f602d780-2e43-11eb-9623-4970b4a3fc6b.gif)
并且切换弹幕后调整播放器尺寸，会暴露尚未出现的旧弹幕。

**Comment by DirectLinkSs** [comment]
> 你要安装最新版本

感谢，忘记切换了，测试正常。
