### ISSUE TITLE
请问如何更改清晰度里的地址。

### ISSUE THREAD

**Issue by DirectLinkSs** [zhw2590582/ArtPlayer#93]
我在创建播放器后添加了一个清晰度选项，然后尝试在切换url以后通过 art.option.quality 更新清晰度选项。
清晰度列表依然是原视频的地址。

**Comment by zhw2590582** [comment]
底部的控制栏选项不是动态的，你这个情况可以销毁实例重新实例化

**Comment by DirectLinkSs** [comment]
好的。
