### ISSUE TITLE
弹幕库为空时，加载出错。

### ISSUE THREAD

**Issue by DirectLinkSs** [zhw2590582/ArtPlayer#94]
### Environment

-   Browser:
-   Version:
-   Operating System:
-   Version:

### Link to where the bug is happening
![QQ截图20201214201413](https://user-images.githubusercontent.com/17827407/102080228-11f90800-3e49-11eb-8849-9786f4df1411.png)
加载B站弹幕库，没有弹幕的时候，控制台报错。
不影响使用，建议增加判断。

**Comment by zhw2590582** [comment]
多谢反馈，我知道哪里出报的错了，下个小版本会修复的

**Comment by DirectLinkSs** [comment]
另一个小BUG。
`art.on('ready', function (args) {
    console.info('The player can play');
});`
上面这段代码在移动端会输出两次（使用自定义解码库的时候，比如 flv.js）。

**Comment by zhw2590582** [comment]
这个我要查一下，你这边可以用`art.once('ready');`，保证运行一次

**Comment by DirectLinkSs** [comment]
👌，谢谢。

`art.on('resize', function (args) { console.info(args); });`
当播放器改变大小的时候 返回参数一直是 undefined 。

**Comment by DirectLinkSs** [comment]
`art.on('control', function (args) { console.info(args); });`
显示控件时，返回的是 是否显示，说明文档里写返回配置。

**Comment by zhw2590582** [comment]
文档有些地方还没更新过来，有时候也忘了更新
`resize`事件不会返回参数了，你可以通过例如`art.height`，或者（`'bottom', 'height', 'left', 'right', 'top', 'width'`）获取尺寸和坐标
`control`事件返回的是`是否显示`
