### ISSUE TITLE
How to include subtitles but start the video with them disabled?

### ISSUE THREAD

**Issue by dantart** [zhw2590582/ArtPlayer#95]
I have subtitles successfully setup, but I need to disable them as default, so if user wants it, (s)he has to click in the subtitle icon.

How can I do it?
Thank you !

**Comment by zhw2590582** [comment]
This is simple: [Demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fartplayer.org%2Fassets%2Fsample%2Fvideo.mp4%27%2C%0A%20%20%20%20subtitle%3A%20%7B%0A%20%20%20%20%20%20%20%20url%3A%20%27%2Fassets%2Fsample%2Fsubtitle.srt%27%2C%0A%20%20%20%20%7D%0A%7D)%3B%0A%0Aart.on(%27ready%27%2C%20()%20%3D%3E%20%7B%0A%09art.subtitle.show%20%3D%20false%3B%0A%7D))

**Comment by dantart** [comment]
Thank you, I didn't see it
