### ISSUE TITLE
WebVtt format is supported but ArtPlayer writes the "-" in the beginning of each line

### ISSUE THREAD

**Issue by dantart** [zhw2590582/ArtPlayer#96]
As you can see here
https://developer.mozilla.org/en/docs/Web/API/WebVTT_API

WebVtt format writes a new line starting with "-"

This dash should not be printed in subtitles.

**Comment by zhw2590582** [comment]
But if you use the following native code directly, you will also see "-" at the beginning of the subtitle. I want to keep the effect consistent with it.

subtitles.vtt
```
WEBVTT - This file has cues.

1
00:00:01.000 --> 00:00:10.000
- What?
- Where are we now?
```

```html
<video src="./video.mp4" controls>
    <track src="./subtitles.vtt" default>
</video>
```

**Comment by dantart** [comment]
I appreciate your response and your consistency ;-)
It make sense.
Them I will modify the vtt by my side.
THANK YOU !
