### ISSUE TITLE
请问我如何使用js控制播放器

### ISSUE THREAD

**Issue by TingzhouJia** [zhw2590582/ArtPlayer#97]
我在使用React，但是ref拿到的instance没有原生的`pasue()`以及`play()`，只能使用原生的js进行控制，请问是否有解决办法呢？谢谢

**Comment by zhw2590582** [comment]
ArtPlayer大部分功能都是getter/setter，所以你要的方法就是：

```js
art.pasue = true;
art.play = true;
```
其它属性可以参考文档：[https://artplayer.org/document/#/properties?id=player](https://artplayer.org/document/#/properties?id=player)

**Comment by TingzhouJia** [comment]
非常感谢
