### ISSUE TITLE
您好，我的播放器经常会降级为原生播放器请问会是什么原因呢？

### ISSUE THREAD

**Issue by TingzhouJia** [zhw2590582/ArtPlayer#98]
<img width="453" alt="截屏2021-01-02 上午10 20 23" src="https://user-images.githubusercontent.com/44245347/103460457-4d6a5200-4ce4-11eb-8f82-ad1539129d2b.png">

**Comment by zhw2590582** [comment]
因为不同的手机上，兼容性会导致功能上有差异，所以要设置白名单：[https://artplayer.org/document/#/options?id=whitelist](https://artplayer.org/document/#/options?id=whitelist)

假如你想图省事，可以像下面这样就可以了
```js
var art = new Artplayer({
    container: '.artplayer-app',
    url: '/assets/sample/video.mp4',
    whitelist: ['*'],
});
```

**Comment by TingzhouJia** [comment]
非常感谢🙏
