### ISSUE TITLE
Sometimes video load fails and poster is not printed

### ISSUE THREAD

**Issue by dantart** [zhw2590582/ArtPlayer#99]
Hi:

1) It's not happening always but sometimes I see the "Reconnect: 1" in the top left, and then the video is loaded (because the label dissapears). When this happens, the poster is not loaded correctly. The viewport stays black until you play the video.

2) Sometimes the Reconnect goes up to 5 ... and the video is not even loaded... I have the refresh the page (with SHIFT pressed, so maybe it's something about cache), in order to have the player working properly.
Maybe is some debug information I can get to help ... maybe it's when there's some fail loading the mp4, I don't know.

**Comment by zhw2590582** [comment]
When reconnect occurs, it must be a video address loading error. You can open the chrome console and see the specific error, such as 404

**Comment by dantart** [comment]
Yes, I agree about that ... but the bug tells about what happens when the resource is loaded successfully.
As I explained, I see a "Reconnect: 1", but NO "Reconnect: 2" ... so when your library tries more attempt and loads the resource successfully, the POSTER is not shown.

**Comment by zhw2590582** [comment]
I can't reproduce what you said. If the video address is wrong, the poster will still appear: [demo](https://artplayer.org/?libs=&code=var%20art%20%3D%20new%20Artplayer(%7B%0A%20%20%20%20container%3A%20%27.artplayer-app%27%2C%0A%20%20%20%20url%3A%20%27https%3A%2F%2Fnone.mp4%27%2C%0A%20%20%20%20poster%3A%20%27%2Fassets%2Fsample%2Fposter.jpg%27%2C%0A%7D)%3B)

**Comment by dantart** [comment]
Believe me... but I'm going to tell you probably the weirdest bug ...

I have a page with tons of links to a page where one video player is shown. It's like a Youtube page with a lot of video links, then you click, and go to the page with the video. Unfortunately, this is a backoffice, I can give you the link to test.

When I click and go to the video page, the art player is loaded, with the poster.
If I click in the play, after 2 seconds, the video stopped and appears: "Reconnect: 1", and stays there.

So I thought to see what's happening in the Web inspector.
But when I do the same operation with the "Web inspector" opened, the video plays perfectly.

So, it's impossible for me to see/check what's happening when (in the first example) the video stops after 2 seconds and Reconnect label appears.

Any help?

**Comment by dantart** [comment]
I'm storing objects in cloud storage from OVH:

After reading this:
https://docs.openstack.org/swift/latest/cors.html
https://github.com/GoogleChrome/workbox/issues/2632

and MORE IMPORTANT this: https://frantzroulet.com/blog/jekyll/update/2020/09/21/how_to_make_cross-origin_cors_requests_on_an_ovh_object_storage_bucket.html

I wonder if there's change to use CORS headers when you request the objects.

Can I have a "non-minified" version of the final .js so I can try it for you ? ;-)

**Comment by zhw2590582** [comment]
This is "non-minified" version: [https://github.com/zhw2590582/ArtPlayer/blob/master/docs/uncompiled/artplayer.js](https://github.com/zhw2590582/ArtPlayer/blob/master/docs/uncompiled/artplayer.js)

**Comment by dantart** [comment]
I can't find where the video/poster is loaded ... can you just point me the "area"? ;-)

**Comment by zhw2590582** [comment]
Believe me, the code logic is very simple. You can even use the following code directly. If it still fails to play, it means that the video URL is wrong:

```html
<video src="http://your-video.mp4" poster="http://your-poster.jpg"></video>
```

**Comment by dantart** [comment]
Believe, but it's not !
Before doing what you suggested, please notice that I wrote that the video loads, you see "1 second", and then it appears the "Reconnect", and when I RELOAD the page, it works perfectly.
Obviously, if I load the URL in a new tab, it's working.

Now, your test... it's working perfectly.

**Comment by zhw2590582** [comment]
It's really strange that you have the video address and poster address that can be accessed through the Internet. I'll test the following

**Comment by dantart** [comment]
I'm doing more tests and I think it's happening what here is explained: https://frantzroulet.com/blog/jekyll/update/2020/09/21/how_to_make_cross-origin_cors_requests_on_an_ovh_object_storage_bucket.html

"I was making two requests for the same object, one from HTML, one from XHR. The second one fails, because Chrome uses the cached response from the first request, which has no Access-Control-Allow-Origin response header."

Maybe your script is doing two calls (206 partial content requests), and when the object is storaged in a  hosting that needs CORS requests, it fails.

That's the reason why it works when I press reload with the shift key (to avoid cache).

Can you test your library with a video hosted in a CORS needed hosting?

I think adding the "X-Container-Meta-Access-Control-Allow-Origin" as an option would be perfect for these cases.

**Comment by zhw2590582** [comment]
But Arplayer doesn't use XHR or fetch to load video and post.

**Comment by dantart** [comment]
Please, I beg you, can you just point me out in where lines you load the video and the poster ? (in the unminified version)
https://github.com/zhw2590582/ArtPlayer/issues/99#issuecomment-764453825

And please, just try ArtPlayer with a video hosted in a CORS hosting, and you will see

**Comment by evidence-sharenet** [comment]
Hi @dantart. Did you manage to resolve the cors issue? I'm currently facing a similar issue. Our web server has some strict cors rules.

**Comment by evidence-sharenet** [comment]
Hi @zhw2590582. Is it possible to edit or configure "Access-Control-Allow-Origin" parameter for the video component? 

I'm trying to access videos that require the "Access-Control-Allow-Origin" parameter to be present in the request

**Comment by zhw2590582** [comment]
CORS Issue can only solve by the server, and the front end cannot control CORS

**Comment by dantart** [comment]
> 

moreVideoAttr: {               
                // crossOrigin: 'anonymous',
                preload: 'none', // metadata
                playsInline: true,
            },

This is what it worked for me ...
apart from creating the "Headers" with CORS

**Comment by evidence-sharenet** [comment]
> > 
> 
> moreVideoAttr: { // crossOrigin: 'anonymous', preload: 'none', // metadata playsInline: true, },
> 
> This is what it worked for me ... apart from creating the "Headers" with CORS

Hi @dantart 

If you don't mind me asking, How did you create the Headers with Cors? Where exactly would you place that code because I'm only passing the video url to Artplayer as shown below?

`<template>
  <artplayer
      :option="playerOptions"
      @get-instance="getInstance"
  />
</template>`

**Comment by zhw2590582** [comment]
@evidence-sharenet 

use this: `moreVideoAttr`, but I'm not sure if this can solve the Cors problem, you can test it

```js
const playerOptions = {
    container: '.artplayer-app',
    url: 'https://artplayer.org/assets/sample/video.mp4',
    moreVideoAttr: {
      // crossOrigin: 'anonymous',
      preload: 'none', // metadata
      playsInline: true,
    },
}
```

Copy from https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attributes
# crossorigin
This enumerated attribute indicates whether to use CORS to fetch the related video. CORS-enabled resources can be reused in the <canvas> element without being tainted. The allowed values are:

### anonymous
Sends a cross-origin request without a credential. In other words, it sends the Origin: HTTP header without a cookie, X.509 certificate, or performing HTTP Basic authentication. If the server does not give credentials to the origin site (by not setting the Access-Control-Allow-Origin: HTTP header), the image will be tainted, and its usage restricted.

### use-credentials
Sends a cross-origin request with a credential. In other words, it sends the Origin: HTTP header with a cookie, a certificate, or performing HTTP Basic authentication. If the server does not give credentials to the origin site (through Access-Control-Allow-Credentials: HTTP header), the image will be tainted and its usage restricted.

When not present, the resource is fetched without a CORS request (i.e. without sending the Origin: HTTP header), preventing its non-tainted used in <canvas> elements. If invalid, it is handled as if the enumerated keyword anonymous was used. See CORS settings attributes for additional information.

**Comment by evidence-sharenet** [comment]
Thanks @zhw2590582 . Let me try out that solution and I will let you know how it goes.

**Comment by evidence-sharenet** [comment]
Thanks @zhw2590582 and @dantart. Your solution worked!!
